### ISSUE TITLE
App Crashes while trying to set Main Picture on a new channel

### ISSUE THREAD

**Issue by terzisspy** [TelegramMessenger/Telegram-iOS#1001]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
While I was trying to create a new channel, when I was trying to add a channel picture from my gallery, the telegram app would crash.

### Expected Behavior
The picture to be set as channel's main picture.

### Actual Behavior
App crashes.

### Steps to Reproduce
1. go to create channel
2. press the button to change the photo
3. Select any photo from your galley

### Screenshots and Videos 

https://user-images.githubusercontent.com/74301392/218279464-ebd60f80-b94f-4e54-9900-824bc4624cfb.mp4

### Environment
**Device:** `iPhone`

**iOS version**: `16.2`

**App version:** `9.4.1`

**Comment by laktyushin** [comment]
Fixed in 9.4.3
