### ISSUE TITLE
[Feature Request] Scheduled day and night mode change

### ISSUE THREAD

**Issue by creyD** [TelegramMessenger/Telegram-iOS#101]
I think it would be pretty unique and practical if you could schedule a color theme (i.e. "Day") for a specific time. That way you could have the dark mode at night and the light mode in the daylight.

**Comment by laktyushin** [comment]
Settings > Appearance > Select Classic or Day Theme > Auto-Night Mode > Scheduled.

**Comment by creyD** [comment]
Im sorry. I didn’t select the classic or day theme and therefore didn’t see the feature. Thanks for pointing it out!
