### ISSUE TITLE
In PeerInfoScreen's infoItems(), how can I obtain the current user's ID?

### ISSUE THREAD

**Issue by shivanraptor** [TelegramMessenger/Telegram-iOS#1010]
In `PeerInfoScreen`'s `infoItems()`, how can I obtain the current user's ID?

Near Line 964 at:
https://github.com/TelegramMessenger/Telegram-iOS/blob/master/submodules/TelegramUI/Sources/PeerInfo/PeerInfoScreen.swift

Also, what is the difference between the `peer` and `chatPeer` in `PeerInfoScreenData`? 

Thanks.

p.s. using `release-9.4.1` tag.

**Comment by ali-fareed** [comment]
The account holder's id is available at `context.account.peerId` throughout the app. The id (and the actual data) of the user/chat that corresponds to the info screen can be accessed at `data.peer?.id`.

`peer` and `chatPeer` are usually equal, except when looking at a secret chat info. In that case, `peer` contains the user info, `chatPeer` contains the secret chat info.
