### ISSUE TITLE
Can't generate project

### ISSUE THREAD

**Issue by anvar0522** [TelegramMessenger/Telegram-iOS#1015]
First, complete the checklist by replacing the empty checkboxes [] with checked ones [x]. -->

### Checklist
- [x ] I am reporting an issue in existing functionality that does not work as intended
- [ x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
Can't generate project

### Expected Behavior
Should generate project

### Actual Behavior
{
    "app": "9.4.1",
    "bazel": "5.3.1",
    "xcode": "14.2"
}

python3 build-system/Make/Make.py \
    --bazel="$HOME/bazel-dist/bazel" \
    --cacheDir="$HOME/telegram-bazel-cache" \
    generateProject \
    --configurationPath="$HOME/telegram-configuration" \
    --disableExtensions \
    --disableProvisioningProfiles

<img width="1302" alt="Screenshot 2023-02-15 at 17 45 36" src="https://user-images.githubusercontent.com/89182155/219030380-927b93d6-4066-4178-a52f-e816e56e0fac.png">

subprocess.CalledProcessError: Command '['/Users/anvar/bazel-dist/bazel', 'build', '//:tulsi', '--macos_cpus=arm64', '--xcode_version=14.2', '--use_top_level_targets_for_symlinks', '--verbose_failures']' 

Inside of variables.bzl :
telegram_bundle_id = "ph.telegra.Telegraph"
telegram_api_id = "8"
telegram_api_hash = "7245de8e747a0d6fbe11f7cc14fcc0bb"
telegram_team_id = "C67CF9S4VU"
telegram_app_center_id = "0"
telegram_is_internal_build = "true"
telegram_is_appstore_build = "false"
telegram_appstore_id = "686449807"
telegram_app_specific_url_scheme = "tg"
telegram_aps_environment = "Development"
telegram_enable_siri = True
telegram_enable_icloud = False
telegram_enable_watch = False

<img width="936" alt="Screenshot 2023-02-15 at 17 49 40" src="https://user-images.githubusercontent.com/89182155/219031217-f7254785-f390-4756-95e1-a394344e0c49.png">

Giving this error

**Comment by ali-fareed** [comment]
It seems to be a Tulsi compilation issue. I would suggest following the official Tulsi documentation to check if that works ok first.
