### ISSUE TITLE
Crashing tulsi when generating project

### ISSUE THREAD

**Issue by anvar0522** [TelegramMessenger/Telegram-iOS#1016]
- [x ] I am reporting an issue in existing functionality that does not work as intended
- [ x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
Tulsi is crashing when Im trying to generate project
I have updated tulsi version to 0.20221005.88 in build-system/
I have restarted my Mac around 5-6 times but it is not helping
And it is have true path to iWon-iOS/build-input/gen/project/bazel, like said ali-fareed, but still cannot generate

### Expected Behavior
Should be generated

### Actual Behavior
Crashing Tulsi when trying to generate 

### Screenshots and Videos 
<img width="1432" alt="Screenshot 2023-02-16 at 00 00 11" src="https://user-images.githubusercontent.com/89182155/219126098-37efdcde-51c3-4a15-bfa1-8d25251d7af0.png">

Variables.bzl:
<img width="402" alt="Screenshot 2023-02-16 at 00 03 35" src="https://user-images.githubusercontent.com/89182155/219127024-e52b282b-d9e1-4c3f-bc11-c045a32b4804.png">

### Environment
**Mac:** 13.0.1
**Xcode:** 14:2
**App version:** `9.4.1`
**Bazel**: 5.3.1

**Comment by ali-fareed** [comment]
Is there any particular reason you are passing a custom bazel path to the build command?

**Comment by anvar0522** [comment]
What does it mean custom Bazel path

**Comment by ali-fareed** [comment]
The `--bazel flag`.

**Comment by anvar0522** [comment]
I will describe project, telegram was cloned and added some features by old iOS Developer around 5-6 months ago. And now I have to generate this project, but I don't know what is the telegram version. Where I can find telegram version and can I update telegram version without generating project and losing some features?

Without --bazel flag I can't generate its Make: error: the following arguments are required: --bazel giving this error.

**Comment by ali-fareed** [comment]
The version 9.4.1 that you specified does not require a separate bazel installation.

**Comment by anvar0522** [comment]
So how I can update telegram version without losing some features added before?
It's my fault that's I specify app version, without knowing it, sorry.

**Comment by anvar0522** [comment]
I cloned new version of telegram project and copy and pasted my custom files (features)
<img width="790" alt="Screenshot 2023-02-16 at 22 04 14" src="https://user-images.githubusercontent.com/89182155/219435775-da0a906f-e014-4dac-bedc-248b8b81212e.png">

And now its have 2 targets, but my iWonCore target is just building but not installing to simulator
<img width="1192" alt="Screenshot 2023-02-16 at 22 05 32" src="https://user-images.githubusercontent.com/89182155/219436307-db69fa48-79a7-4e48-9d94-64a09acb0270.png">

**Comment by ali-fareed** [comment]
You should merge your changes with the latest master, resolve conflicts, and try again.
