### ISSUE TITLE
Webrtc recording remote call.

### ISSUE THREAD

**Issue by azamjalali** [TelegramMessenger/Telegram-iOS#1019]
Hi guys, i want to record voice and video call in telgram-ios, I got success in recording local video using AVCaputureSession. Now, in order record remote video, first I need to get remote video frames/buffer from RTCVideoRenderer(i know one method like renderFrame( RTCVideoFrame *)frame in this class, which renders frame, but how to get that frame). Does everyone help in this, how can I get frames from renderer?

Note: In android, they provided VideoSink method so we can get the frames, but no such class in iOS.

**Comment by ali-fareed** [comment]
Group call recording functionality is available out of the box.

**Comment by azamjalali** [comment]
Hi ali, where is group call recording code? Telegram-ios ui doesn't have call recording option!!!

**Comment by ali-fareed** [comment]
A group admin can access the call recording functionality via the three-dot option menu:

<img width="383" alt="image" src="https://user-images.githubusercontent.com/57234349/219890586-ffa50f94-60b6-499b-bc67-de90718a1980.png">

**Comment by azamjalali** [comment]
Dear ali, i need to save call conversations as a file and capture important conversations as call recording files for absent members or archiving call recording files.

**Comment by azamjalali** [comment]
Thanks alot , i finally find it.
