### ISSUE TITLE
Create a normal readme please!

### ISSUE THREAD

**Issue by Gargo** [TelegramMessenger/Telegram-iOS#1021]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
Readme is missing some steps so I don't know even what am I doing wrong. What do you mean in step 3 "Adjust configuration parameters"? Which values should I modify in configuration.json?

### Expected Behavior
No error occurs

### Actual Behavior
Console log:
```
% python3 build-system/Make/Make.py \
    --cacheDir="$HOME/telegram-bazel-cache" \
    build \
    --configurationPath="$HOME/telegram-configuration/configuration.json" \
    --codesigningInformationPath="$HOME/telegram-provisioning" \
    --buildNumber=100001 \
    --configuration=release_universal
Traceback (most recent call last):
  File "/Users/admin/Documents/xcode_projects/Telegram-iOS/build-system/Make/Make.py", line 1035, in <module>
    build(bazel=bazel_path, arguments=args)
  File "/Users/admin/Documents/xcode_projects/Telegram-iOS/build-system/Make/Make.py", line 581, in build
    resolve_configuration(
  File "/Users/admin/Documents/xcode_projects/Telegram-iOS/build-system/Make/Make.py", line 489, in resolve_configuration
    codesigning_data = resolve_codesigning(
  File "/Users/admin/Documents/xcode_projects/Telegram-iOS/build-system/Make/Make.py", line 463, in resolve_codesigning
    profile_source.copy_profiles_to_destination(destination_path=provisioning_profiles_path)
  File "/Users/admin/Documents/xcode_projects/Telegram-iOS/build-system/Make/BuildConfiguration.py", line 305, in copy_profiles_to_destination
    copy_profiles_from_directory(source_path=self.directory_path + '/profiles', destination_path=destination_path, team_id=self.team_id, bundle_id=self.bundle_id)
  File "/Users/admin/Documents/xcode_projects/Telegram-iOS/build-system/Make/BuildConfiguration.py", line 166, in copy_profiles_from_directory
    for file_name in os.listdir(source_path):
FileNotFoundError: [Errno 2] No such file or directory: '/Users/admin/telegram-provisioning/profiles'
```
If I create and move `Telegram.mobileprovision` profile to  '/Users/admin/telegram-provisioning/profiles' I get another error - `Could not find a valid aps-environment entitlement in the provided provisioning profiles`

### Steps to Reproduce
Just repeat steps 1-5 from readme

### Environment
**Device:** MacBook Pro M2 2022

**iOS version**: -

**App version:** Xcode 14.2

**Comment by terzisspy** [comment]
I had similar issues while trying to build the project last week. At the end it worked with the following instructions:

python3 build-system/Make/Make.py \
--bazel="$HOME/bazel-dist/bazel" \
--cacheDIr="$HOME/telegram—bazel-cache" \
generateProject \
--configurationPath="$HOME/telegram-configuration" \
--disableExtensions

**Comment by ali-fareed** [comment]
@Gargo 

1. Examine files at `build-system/fake-codesigning/profiles`. 
2. Create your own provisioning profiles with the same entitlements.
3. Change `bundle_id` and `team_id` in `build-system/appstore-configuration.json`.

**Comment by v4to** [comment]
> @Gargo
> 
> 1. Examine files at `build-system/fake-codesigning/profiles`.
> 2. Create your own provisioning profiles with the same entitlements.
> 3. Change `bundle_id` and `team_id` in `build-system/appstore-configuration.json`.

As I undertsand in order to build and test the app on a physical device even if I don't plan to distribute the app on App Store, I need to have a paid developer account, right?

**Comment by ali-fareed** [comment]
@v4to It may be possible to use a free Xcode provisioning profile to run the app without the extensions, but there is no guide for that yet. The easiest way is to obtain real provisioning profiles, which requires access to an active Apple developer program membership.
