### ISSUE TITLE
Problem with push notifications on iOS

### ISSUE THREAD

**Issue by SixthTR** [TelegramMessenger/Telegram-iOS#1022]
### _Checklist_
_- [☑️] I am reporting an issue in existing functionality that does not work as intended_
_- [☑️] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)_

### Description
Since the release of the iOS 15 beta version, Telegram has stopped receiving push notifications in a timely manner.

The way iOS works is that if the app is completely closed, a push notification comes in about a minute, but if it is open and minimized, the notification comes almost instantly.

However, over the last 2 years, **Telegram has not sent notifications on iOS in a timely manner**, making the user wait for up to a minute (and sometimes not even sending a notification at all), and this is something users with different iPhone models, iOS versions and Telegram clients face. Inside the app, however, notifications are timely.

By comparison, the macOS version of Telegram receives notifications almost instantly, not containing the problem of its iOS counterpart.

**All other apps send push-notifications in a timely manner.**

The problem lives on to this day on the latest current iOS 16.3.

P.S. A user once reported in a group that Pavel Durov had personally pointed out the problem and promised to fix it.
P.P.S. Sometimes the badge counter on iOS updates instantly, but it is not followed by a push notification.

### Expected Behavior
Push-notifications  arrive in a timely manner instantly, like on all apps.

### Actual Behavior
Push-notifications come with a delay of 10-120 seconds or don't come at all.

### Steps to Reproduce
1. Just write to yourself from another account via a web client and calculate
2. Calculate the time it takes you to receive a push notification

### Environment
**Device:** `iPhone 13 Pro`

**iOS version**: `16.3`

**App version:** `9.4.2`

**Comment by SixthTR** [comment]
@laktyushin https://bugs.telegram.org/c/25110 – how about you stop ignoring the bug reports coming in on this and give us some kind of response so we can solve the problem?

**Comment by shivanraptor** [comment]
I do not have such an issue. However, when I use the Telegram Desktop in macOS, the custom build of Telegram fork also receives a notification or two, but when I select the notification, it just opens the App but without any deep linking.

p.s. please try to be polite to the dev team.

**Comment by ali-fareed** [comment]
The push notification delay has been adjusted in 9.5. There are two possible scenarios:

- If you have been online up to 30 seconds ago, incoming notifications are delayed for 30 seconds
- If you have not been online for 30 seconds or more, incoming notifications are not delayed.

**Comment by SixthTR** [comment]
@ali-fareed Couldn't the delay in notifications be waived altogether? After all, it doesn't exist on either macOS or Android. What is the point of this economy? Many people pay for premium and this should compensate for the cost of notifications. On behalf of myself and many users, I urge you to do away with the delay in notifications altogether.

**Comment by ali-fareed** [comment]
Let's start with checking how it works currently to exclude any factors other than the pre-set delay. Could you check that in about 1 minute (to be safe) after navigating to another app, notifications in private chats arrive with no major delay?

**Comment by SixthTR** [comment]
@ali-fareed Thank you for your reply. Yes, indeed, in the time ranges you mentioned, the notifications arrive in a timely manner, but... I wouldn't like to have any delays at all, because, for example, a competitor in the form of WA delivers notifications without any delays: not 30 seconds, not a minute - but instantly. How possible is this? What is the reason for introducing a pause of 30 seconds?

**Comment by SixthTR** [comment]
@ali-fareed 
I was completely confused, but I tried to make a coherent test.

Two situations:
1. I minimized Telegram (didn't close it), waited 30 seconds and wrote a message from another account/client - the push notification came in time instantly.
2. I minimized Telegram (did not close) and immediately wrote a message from another account/client - the push notification came after ~9 seconds (the badge appeared instantly).

There is a question and a request: why is there a delay if I just minimized Telegram? Can't the second example not delay the push as it was implemented in the first example?

**Comment by SixthTR** [comment]
@ali-fareed You didn't give me an answer, but you answer in other reports. Let's deal with the current question first, shall we?

**Comment by SixthTR** [comment]
@ali-fareed ??

**Comment by SixthTR** [comment]
@ali-fareed I will turn off premium if you won't answer me
