### ISSUE TITLE
Login code, a new telegram user is not receiving SMS code, it tells the code are send in the telegram service notification, this bug is only from unofficial apps

### ISSUE THREAD

**Issue by sarmentoliam** [TelegramMessenger/Telegram-iOS#1024]
### Checklist
- [x ] I am reporting an issue in existing functionality that does not work as intended
- [ ] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
Login code bug

### Expected Behavior
a login code must be sent thru SMS not in telegram service notification if the telegram user is new

### Actual Behavior
when a new user tries to register in unofficial apps, the login code is sent by the Telegram Service Notification Chat

### Environment
**Device:** `iOS/android`

**Comment by ali-fareed** [comment]
As this is a service-wide change, the issue should be reported at bugs.telegram.org.
