### ISSUE TITLE
ITMS-90809: Deprecated API Usage - App updates that use UIWebView will no longer be accepted as of December 2020

### ISSUE THREAD

**Issue by jalalimehdi** [TelegramMessenger/Telegram-iOS#1029]
ITMS-90809: Deprecated API Usage - App updates that use UIWebView will no longer be accepted as of December 2020. Instead, use WKWebView for improved security and reliability.

submodules/GalleryUI/Sources/Items/ChatDocumentGalleryItem.swift#L127
change from
```
       let webView = UIWebView()
            webView.scalesPageToFit = true
            self.webView = webView
```
to
```
let _ = registeredURLProtocol
            let webView = WKWebView()
            
            self.webView = webView
```

and line 280 ,281 , 282 remove

remove these lines 
```
else if let webView = strongSelf.webView as? UIWebView {
                            webView.loadRequest(URLRequest(url: URL(fileURLWithPath: data.path)))
                        }
```

**Comment by ali-fareed** [comment]
Right, as we moved to iOS 11 as the minimal supported version, UIWebView-based code can be removed.
