### ISSUE TITLE
Sharing to Telegram in landscape orientation registers taps on wrong UI elements

### ISSUE THREAD

**Issue by levicki** [TelegramMessenger/Telegram-iOS#1040]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
When you try to share something in landscape orientation and you click on Telegram icon, the resulting popup does not register tap position correctly for top left and top right contacts.

For example:
 - Tapping on top left contact (Saved Messages in my case) results in opening search whose icon is above the contact tapped.
 - Tapping on top right contact results in opening the account switch menu whose icon is above the contact tapped.

### Expected Behavior
 - Tap on top left contact (Saved Messages in my case) should select that contact, not open search.
 - Tap on top right contact in list should select that contact, not open account switch menu.

### Actual Behavior
 - Search is opened instead.
 - Account switch menu is opened instead.

### Steps to Reproduce
1. Open Safari on iPhone
2. Visit any website
3. Rotate the phone to landscape orientation
4. Tap the share icon in the browser address bar
5. Tap the Telegram icon
6. Tap the center of the top left contact icon in your contact list
7. Observe how search is open instead of contact being selected
8. Tap the name under the top left contact icon in your contact list
9. Observe how contact is now selected
10. Repeat the process for top right contact and observe the same result

### Screenshots and Videos 
N/A

### Environment
**Device:** `iPhone 13 Pro Max`

**iOS version**: `16.3.1`

**App version:** `9.4.3`

**Comment by levicki** [comment]
@laktyushin 
I just tested this is still reproducible in Telegram 9.5.1.

Please also take a look at #1039 as well when you have time (although for that one I am not sure if the fix is needed on the client or on the server side or both).

**Comment by laktyushin** [comment]
Fixed in 9.5.3

**Comment by levicki** [comment]
> Fixed in 9.5.3

Thank you very much, I can confirm it works properly now.
