### ISSUE TITLE
How to build/Distribute to appstore?

### ISSUE THREAD

**Issue by gregbickford** [TelegramMessenger/Telegram-iOS#1043]
### Checklist
- [Y ] I am reporting an issue in existing functionality that does not work as intended
- [ Similar but no direct answers] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
Telegram seems to be using the entitlement (com.apple.developer.pushkit.unrestricted-voip) however this entitlement is no longer available for developers to add to there identifier or even request. It seems all the other entitlements that are shown in the fake profiles developers are able to add or at least request from apple. 

How are others getting around this? Does this require changes to the telegram client to be able to publish telegram client to the app store?

Also even if you can get the right entitlements do you create an archive after generating Xcode project to submit to the app store or do you follow a different way of creating IPA and uploading that in a different way?

### Expected Behavior
Be able to add entitlement com.apple.developer.pushkit.unrestricted-voip to identifier in apple developer dashboard

### Actual Behavior
Not available to add this or even reqeust this.

### Steps to Reproduce
1. Try to add this entitlement

**Comment by AganCoder** [comment]
Have the same issue,  i even can't build for iPhone device

![Screen Shot 2023-03-06 at 10 07 06](https://user-images.githubusercontent.com/13814641/223003425-7fd28454-2578-4490-a0be-910cb4ccb7c9.png)

**Comment by gregbickford** [comment]
@AganCoder it seems you may be using the provisioning profiles that are already in the repo which may already be expired, I am talking about creating my own profiles and just having the problem with trying to get the entitlement for the (com.apple.developer.pushkit.unrestricted-voip).

I dont think you will be able to use there profiles to build for your device. If you just want to test in the simulator then you can generate the project and add the flag -disable provisioning as shown in the readme and click run.

**Comment by AganCoder** [comment]
@gregbickford  Thanks for your reply, i use fake-codesigning/profiles  to build, it may already be expired

**Comment by AganCoder** [comment]
@gregbickford i use --disableProvisioningProfiles flag to  generate a project shown in readme, i get the error 

![Screen Shot 2023-03-06 at 11 15 26](https://user-images.githubusercontent.com/13814641/223011491-28ab15b9-07aa-44d3-8f7e-25429ec7f6b4.png)

Do you know how to fix it?

**Comment by gregbickford** [comment]
@AganCoder if your goal to to build it to use it on your physical device or submit it using the fake code signing profiles won’t work. 

If you want to just use the simulator then you can get away with the disable provisions flag

**Comment by AganCoder** [comment]
@gregbickford  Thank you, i use the flag `--disableProvisioningProfiles ` generate project which build for simulator ,but it does not work for me, xcode show the OSSpinLock error like [issue1](https://github.com/TelegramMessenger/Telegram-iOS/issues/935)  and [issue2](https://github.com/TelegramMessenger/Telegram-iOS/issues/949) mentioned . By the way，thank you a lot

**Comment by ali-fareed** [comment]
The `unrestricted-voip` entitlement is no longer required and can be safely omitted from your builds.

**Comment by gregbickford** [comment]
> @gregbickford Thank you, i use the flag `--disableProvisioningProfiles ` generate project which build for simulator ,but it does not work for me, xcode show the OSSpinLock error like [issue1](https://github.com/TelegramMessenger/Telegram-iOS/issues/935) and [issue2](https://github.com/TelegramMessenger/Telegram-iOS/issues/949) mentioned . By the way，thank you a lot

Make sure you are using correct version of xcode as I had issues when not using the exact xcode version
