### ISSUE TITLE
Requesting Usernotifications.filtering Entitlement

### ISSUE THREAD

**Issue by gregbickford** [TelegramMessenger/Telegram-iOS#1046]
### Description
Telegram app doesnt operate properly without the Entitlement usernotifications.filtering but I see that you can request this entitlement from apple by answering a few questions. 

I am not familiar with the full codebase of the telegram app and not sure why this is a necessary entitlement or how to properly answer apples questions for them to grant me the entitlement. I have searched everywhere and tried to better understand why this entitlement is needed but I am a bit lost.

Here are the questions that need to be answered in order to request this entitlement. Could someone help guide me in answering these?
Thanks in advance!
![IMG_0528](https://user-images.githubusercontent.com/34595026/223879831-df21605f-db1b-4f1e-92ca-557576515bcf.png)

**Comment by gregbickford** [comment]
@ali-fareed 
Any ideas?

**Comment by ali-fareed** [comment]
Some service events require that they are handled with the same priority as message notifications. That includes "messages read" and "messages deleted" events. At the moment, the notification filtering capability is the only way to handle such events.

**Comment by SixthTR** [comment]
@ali-fareed https://github.com/TelegramMessenger/Telegram-iOS/issues/1022

**Comment by gregbickford** [comment]
Hey @ali-fareed really appreciate your help a lot! I am pretty understanding of this now. 

I still don’t have full understanding of the third question around which other resources it will need?

**Comment by ali-fareed** [comment]
When the extension runs in response to an event that is not displayed to the user (which is the entire scope of this entitlement), it does not perform any network access. The extension uses its local database to update which messages have been read or deleted, and filters previously displayed notifications if necessary.

**Comment by SixthTR** [comment]
@ali-fareed https://github.com/TelegramMessenger/Telegram-iOS/issues/1022#issuecomment-1463986901 ANSWER

**Comment by gregbickford** [comment]
Thanks really appreciate the answers!

**Comment by SixthTR** [comment]
https://github.com/TelegramMessenger/Telegram-iOS/issues/1022#issuecomment-1464925818

**Comment by Majidbaba** [comment]
Hi my friend lm Majid babanejhad or ( mjbaba ) 

When I started, I wanted to have a team that I could learn from and optimize each other's ideas, but I didn't know anything. What I see now does that mean you did this favor and were persistent?  I will be happy to answer me in this matter
My mailbox asanhamrah.sim@gmail.com
