### ISSUE TITLE
Support for apple native login 

### ISSUE THREAD

**Issue by johndpope** [TelegramMessenger/Telegram-iOS#1047]
is this technically doable already? we just need to code it up?
https://ux-news.com/telegram-will-add-sign-in-with-apple-id-and-google/

**Comment by ali-fareed** [comment]
It is supported.

**Comment by SixthTR** [comment]
@ali-fareed https://github.com/TelegramMessenger/Telegram-iOS/issues/1022 ???

**Comment by SixthTR** [comment]
https://github.com/TelegramMessenger/Telegram-iOS/issues/1022#issuecomment-1464925818
