### ISSUE TITLE
The contrast of the buttons is too low,I can't read the text

### ISSUE THREAD

**Issue by ShadowsSide** [TelegramMessenger/Telegram-iOS#1049]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description

All the buttons contrast colors abnormally

### Expected Behavior

It should have just the right contrast. I can't read the text right now

### Actual Behavior

I've been using this theme and it worked until I updated v9.5.1.

### Screenshots and Videos 

![image](https://user-images.githubusercontent.com/61958350/224204772-0405acb2-7a84-412d-a857-5b983ea84251.png)

### Environment
**Device:** `iPhone12 Pro Max`

**iOS version**: `16.3.1`

**App version:** `9.5.1`

**Comment by ali-fareed** [comment]
Should be fixed in 9.5.2.

**Comment by SixthTR** [comment]
https://github.com/TelegramMessenger/Telegram-iOS/issues/1022#issuecomment-1464925818
