### ISSUE TITLE
Canceling share extension is blocking UI(XS)

### ISSUE THREAD

**Issue by Merc1408** [TelegramMessenger/Telegram-iOS#105]
Precondition: iOS - 12.3.1, Iphone XS, telegram - the latest
Steps:
1. Open contact
2. Click Share contact button
3. Choose Telegram
4. Choose any contact(Share screen is opened)
5. Click Cancel
Act result: Contact screen is locked(User is not able to click any button)
Exp result: User is able to click any buttons

Work around: Close screen and open again.

**Comment by laktyushin** [comment]
Fixed in 5.10 release.
