### ISSUE TITLE
Playing a video message on iPhone outputs audio to earpiece

### ISSUE THREAD

**Issue by Yamimono** [TelegramMessenger/Telegram-iOS#1051]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
Describe the issue that you are experiencing
When a video message is played on an iPhone, the audio is played on the earpiece, when "iPhone" is chosen from the audio output menu. Audio can be rerouted to Speakers when it is chosen in the audio output list during video message playback.

### Expected Behavior
Sounds from the video message should be played just like music.

### Actual Behavior
When iPhone is chosen as the current audio output, it is played via an earpiece.

### Steps to Reproduce
1. Choose iPhone from the audio output list.
2. Play a video message, then try listening to it.
3. Check the audio output list now before the video message ends.

### Screenshots and Videos 
Remove, if not applicable

### Environment
**Device:** iPhone 11

**iOS version**: 16.4 beta 2

**App version:** 9.5.2, 9.5.1, does not affect version 9.5 (25353)

**Comment by SixthTR** [comment]
https://github.com/TelegramMessenger/Telegram-iOS/issues/1022#issuecomment-1464925818

**Comment by ali-fareed** [comment]
Should be fixed in 9.5.3.
