### ISSUE TITLE
Black Screen on first start

### ISSUE THREAD

**Issue by SkyKingPX** [TelegramMessenger/Telegram-iOS#1057]
### Checklist
- [x ] I am reporting an issue in existing functionality that does not work as intended
- [x ] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
Black screen on start

### Expected Behavior
I should log in I think?

### Actual Behavior
When I start the app the screen gets black with nothing 

### Steps to Reproduce
1. Install from IPA
2. Open

### Screenshots and Videos 
![55CB94BB-29B7-4524-B35D-2CE1AD83058C](https://user-images.githubusercontent.com/95442431/226115952-0f25a595-50cb-4857-b54c-442c6d6b5414.png)

### Environment
**Device:** `iPhone 11`

**iOS version**: `16.3.1`

**App version:** `9.5.3`

**Comment by SkyKingPX** [comment]
?

**Comment by ali-fareed** [comment]
Which IPA are you trying to run?

**Comment by ali-fareed** [comment]
Did you build it yourself?

**Comment by SkyKingPX** [comment]
What do you mean

**Comment by ali-fareed** [comment]
Did you install the app using the App Store?

**Comment by SkyKingPX** [comment]
No through IPA

**Comment by SkyKingPX** [comment]
I don't know because I don't know how to do this!

**Comment by df1228** [comment]
ipa 9.6.3 too

#1120

**Comment by LSPBoy** [comment]
can you sovle it
