### ISSUE TITLE
ITMS-90683: Missing purpose string in Info.plist

### ISSUE THREAD

**Issue by shivanraptor** [TelegramMessenger/Telegram-iOS#1061]
### Checklist
- [X] I am reporting an issue in existing functionality that does not work as intended
- [X] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
When submitting the IPA to App Store, the following issue appears: `ITMS-90683: Missing purpose string in Info.plist`. This issue does not happen in previous releases (such as `release-9.4`)

### Expected Behavior
This issue does not happen in previous versions. I have checked that the `Info.plist` contains the required `NSLocationAlwaysAndWhenInUseUsageDescription`.

### Actual Behavior
The following warning appears when delivered to the App Store:
```
ITMS-90683: Missing purpose string in Info.plist - Your app’s code references one or more APIs that access sensitive user data, or the app has one or more entitlements that permit such access. The Info.plist file for the “Telegram.app” bundle should contain a NSLocationAlwaysAndWhenInUseUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. If your app supports multiple locales, you’re now required to provide a purpose string value in the Info.plist file in addition to a valid localized string across each of your app’s localization folders. If you’re using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. For details, visit: https://developer.apple.com/documentation/uikit/protecting_the_user_s_privacy/requesting_access_to_protected_resources.
```

### Steps to Reproduce
1. Generated the IPA using tag `release-9.5.3`
2. Upload the IPA to the App Store via the Transporter app.
3. Received an email complaining about the above issues.

### Environment
**App version:** `9.5.3`

**Comment by ali-fareed** [comment]
We have seen no issues when submitting 9.5.x to the App Store. Are you doing any kind of modifications to the code?

**Comment by Zhuzhune** [comment]
Nope

Vào Th 7, 25 thg 3, 2023 lúc 02:54 ali-fareed ***@***.***> đã
viết:

**Comment by shivanraptor** [comment]
No, I did not perform any modifications related to this.

**Comment by shivanraptor** [comment]
This is unresolved, and some others (#1075) have encountered the same issue. @ali-fareed can you please help?

**Comment by xyunsh** [comment]
same issue

**Comment by xyunsh** [comment]
@ali-fareed can you please help?
