### ISSUE TITLE
 I get an error: ... target 'NotificationContent.mobileprovision' not declared in package 'provisioning'...

### ISSUE THREAD

**Issue by rrrad** [TelegramMessenger/Telegram-iOS#1062]
### Description
I'm trying to build a project to run on the device, but errors appear in the process:
no such target '@build_configuration//provisioning:NotificationContent.mobileprovision': target 'NotificationContent.mobileprovision' not declared in package 'provisioning' defined by /private/var/tmp/_bazel_rrad/9d1dfb85d8b94362ed6f7ad3f9b589c8/external/build_configuration/provisioning/BUILD and referenced by '//Telegram:NotificationContentExtension'

errors appear only for targets: Intents, NotificationContent, NotificationService, Share and Widget

what needs to be done to declare targets, and what is done wrong?

### Environment

**Xcode:** `14.2`

**bazel:** `5.3.1`

**App version:** `9.5.3`

**Comment by rrrad** [comment]
This error is due to invalid provisioning files. It is necessary to look inside the fake-provisioning files for how they should be correctly named.

**Comment by Aadarsh805** [comment]
@rrrad yoo how did you resolve this?
