### ISSUE TITLE
[Feature] Private topics in group chat

### ISSUE THREAD

**Issue by taukeM** [TelegramMessenger/Telegram-iOS#1063]
I suggest adding a feature that would allow group admins to create private topics within a group chat. Only members who are added to the private topic by the admin would be able to see and participate in the conversations within that topic.

**Comment by ali-fareed** [comment]
As a platform-wide feature request, this belongs to https://bugs.telegram.org

**Comment by stebansaa** [comment]
I'm looking for a somehow similar feature. Mainly allow only verified users to access topics, otherwise just let them see one group that works for verification.

**Comment by GSTbyMM** [comment]
> As a platform-wide feature request, this belongs to https://bugs.telegram.org

This is not a bug but a feature request and should be implemented in the next update. It has already been requested by a lot of users and is very necessary, Discord already has this.
