### ISSUE TITLE
Cannot build & run in Xcode on iPad (iPadOS 16.4) device

### ISSUE THREAD

**Issue by shivanraptor** [TelegramMessenger/Telegram-iOS#1078]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
Similar to the issue #1067, the `release-9.5.3` cannot be run on a connected iPad Pro (model A1584, iPad OS 16.4), which has the Apple A9X (ARMv8 architecture). Xcode build results in errors:

```
/private/var/tmp/_bazel_adv/41d096bc4f8e052b19e6258c124586e7/external/bazel_tools/platforms/BUILD:89:6: in alias rule @bazel_tools//platforms:windows: Constraints from @bazel_tools//platforms have been removed. Please use constraints from @platforms repository embedded in Bazel, or preferably declare dependency on https://github.com/bazelbuild/platforms. See https://github.com/bazelbuild/bazel/issues/8622 for details.

/private/var/tmp/_bazel_adv/41d096bc4f8e052b19e6258c124586e7/external/bazel_tools/platforms/BUILD:89:6: Analysis of target '@bazel_tools//platforms:windows' failed

/Users/adv/Documents/workspace/Xcode/xCodeProjects/telegram/release-9.5.3/Telegram/BUILD:1967:16: While resolving toolchains for target //Telegram:Telegram: invalid registered toolchain '@bazel_skylib//toolchains/unittest:cmd_toolchain': 

Analysis of target '//Telegram:Telegram' failed; build aborted: 
```

### Expected Behavior
The Telegram app should be able to build and run on an iPad device.

### Actual Behavior
The Telegram app (`release-9.5.3` tag) cannot be built and run.

### Steps to Reproduce
1. Connect the iPad device to iMac (Intel-based, iMac 2020, 27-inch, Retina 5K, macOS 13.2.1)
2. Click Run in Xcode 14.3 (this version is required to support iOS 16.4)
3. Build failed with the errors shown above.

### Screenshots and Videos 
<img width="1351" alt="Screenshot 2023-04-04 at 14 19 53" src="https://user-images.githubusercontent.com/997890/229704868-fe8ea522-23de-402a-a55b-d395748c1f9b.png">

### Environment
**Device:** `iPad Pro (model A1584)`
**iOS version**: `iPad OS 16.4`
**App version:** `9.5.3`

**Comment by ali-fareed** [comment]
Can you try Xcode 14.2?

**Comment by Nabilabouelenin5** [comment]
https://user-images.githubusercontent.com/89806456/229723358-aff93c15-d802-4bbf-8844-03c0c105bc54.MOV

**Comment by shivanraptor** [comment]
> Can you try Xcode 14.2?

I'm afraid all my devices are using iOS / iPadOS 16.4, therefore it requires Xcode 14.3. Can others help? Thanks all.

**Comment by ali-fareed** [comment]
I have updated the code to run on Xcode 14.3. This will be available in the next release.

**Comment by Zhuzhune** [comment]
Pls not me

Vào CN, 9 thg 4, 2023 lúc 14:05 ali-fareed ***@***.***> đã
viết:

**Comment by ali-fareed** [comment]
@shivanraptor please check out the latest commit.
