### ISSUE TITLE
crash when connect to some proxy

### ISSUE THREAD

**Issue by StarsDream00** [TelegramMessenger/Telegram-iOS#1088]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
crash when connect to some proxy(probably because it has adchannel)

### Expected Behavior
running stably

### Actual Behavior
crash on open

### Steps to Reproduce
1. update to version 9.6
2. use the proxy with adchannel

### Environment
**Device:** `iPhone Xs`

**iOS version**: `16.5 (20F5039e)`

**App version:** `9.6`

**Comment by StarsDream00** [comment]
reinstall

**Comment by Amirnlz** [comment]
I also have this issue with 9.6 version.
In my device crash with all proxies but without trying to use proxy that works fine.

running iOS: `16.4.1`
Device: `iPhone X`

**Comment by MrAli001** [comment]
I have exactly the same problem on version 9.6, when I connect to the proxy, the telegram crash and does not run anymore. :(
 
iOS : 16.4.1
Device : iPhone 13

**Comment by MHMRD** [comment]
I have the same problem on version 9.6. I updated the app last night on my iphone and app crashes when I tap on it.
iOS: 15.7.5
Telegram: 9.6
Device : iPhone 7

**Comment by mhmdbina** [comment]
same issueon on IOS 16.4.1!

**Comment by Amirnlz** [comment]
> I also have this issue with 9.6 version. In my device crash with all proxies but without trying to use proxy that works fine.
> 
> running iOS: `16.4.1` Device: `iPhone X`

My problem fixed by re-update telegram again. go to AppStore and pull to refresh updates, if you see telegram press update. now problem fixed and you can use proxy.
i think problem is from apple-side that update not installed fully or something like this, that's out of my knowledge.

**Comment by StarsDream00** [comment]
bug fixed in version 9.6.1
