### ISSUE TITLE
start_param and tgWebAppStartParam are not present in WebApp opened via direct link

### ISSUE THREAD

**Issue by erfanmola** [TelegramMessenger/Telegram-iOS#1091]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
Since the last release of Telegram for iOS and all other platforms, in the version 6.7 of WebApps there is an ability to open WebApps via an start parameter, just as the bots did, when I try opening my bot via this link, it works in TDesktop and TAndroid, but does not work on iOS, and my investigations show that it is because Telegram iOS does not pass the tgWebAppStartParam as the GET parameter

the link example: https://t.me/botusername/appname?startapp=test

### Expected Behavior
the value of startapp param should be passed as tgWebAppStartParam=test

### Actual Behavior
there is no tgWebAppStartParam in the url

### Screenshots and Videos 
![URL Params](https://s8.uupload.ir/files/photo_2023-04-22_18-29-43_lbiy.jpg)

### Environment
**Device:** `iPhone 14 Pro Max`

**iOS version**: `16.4.1`

**App version:** `9.6.1`

**WebApp version:** `6.7`

**Comment by FeiFanLiang** [comment]
When it needs to be added, this bug not only appears on IOS, but also appears in the MAC client

**Comment by erfanmola** [comment]
> When it needs to be added, this bug not only appears on IOS, but also appears in the MAC client

Seems like the guy maintaining iOS & Mac clients was on vacation when the specifications for WebApps 6.7 were introduced :D

**Comment by FeiFanLiang** [comment]
So is anyone looking at this right now?

**Comment by ma21ar** [comment]
This bug is a preventing us from releasing our bot. Please prioritize fixing this.

**Comment by ArtemSushkov** [comment]
> This bug is a preventing us from releasing our bot. Please prioritize fixing this.

Some! Fix it please.

**Comment by erfanmola** [comment]
> This bug is a preventing us from releasing our bot. Please prioritize fixing this.

The sad part is when considering "How many of users will update their Telegram as soon as the fix gets released, an update that has no announcments"

The guy in-charge of Telegram iOS had one freaking job to do for this update, one freaking job

**Comment by evgenijst21** [comment]
Maybe a stupid question, I'm just getting started with development. But where can I get the appname from the link https://t.me/botusername/appname?startapp=test?

**Comment by ibarchenkov** [comment]
> Maybe a stupid question, I'm just getting started with development. But where can I get the appname from the link https://t.me/botusername/appname?startapp=test?

The question is relevant, I also couldn't find it easily.
Send `/myapps` and then `/newapp` commands to [BotFather](https://t.me/BotFather) to list or create a new `appname` and link it to the URL of your server.

**Comment by erfanmola** [comment]
When in the hell would this issue get fixed???

**Comment by FeiFanLiang** [comment]
Today I saw that the version of ios was updated to 9.6.3, unfortunately this problem still exists, so is anyone concerned about this problem? The new features released on the official website are inconsistent in different clients, which is a very serious problem for developers.

**Comment by erfanmola** [comment]
is anyone even bothered with this issue? are you just holding it back to fix it as a christmas suprise for us?

**Comment by AgentBelfort** [comment]
Up, we can't release an update for our bot, please fix it!

**Comment by erfanmola** [comment]
Up! How irresponsible a dev team could be? It's been a month since this bug report, the bug that you were tasked to implement it in the previous update

Telegram iOS has the worst dev team and customer support between all other clients

Just give it a try and report something on TDesktop and TAndroid, the developers would respond to you less than a day

**Comment by milamaja** [comment]
Try using `startApp` in stead of `startapp` in the URL

So: `https://t.me/botusername/appname?startApp=test`

**Comment by hiunkim** [comment]
> Try using `startApp` in stead of `startapp` in the URL
> 
> So: `https://t.me/botusername/appname?startApp=test`
> 
> _to clarify: It seems that in iOS and Android the parameter is case sensitive. To make sure it also works on Android, use both options:_ `https://t.me/botusername/appname?startapp=test&startApp=test`

Confirmed this works on iOS, but still not on macOS client =(

**Comment by erfanmola** [comment]
> Try using `startApp` in stead of `startapp` in the URL
> 
> So: `https://t.me/botusername/appname?startApp=test`
> 
> _to clarify: It seems that in iOS and Android the parameter is case sensitive. To make sure it also works on Android, use both options:_ `https://t.me/botusername/appname?startapp=test&startApp=test`

This looks like a lower-case and camelCase naming Controversy between the developers of different clients

**Comment by HollaG** [comment]
I can confirm that startApp works for both iOS and Android, while startapp only works for Android

**Comment by milamaja** [comment]
> I can confirm that startApp works for both iOS and Android, while startapp only works for Android

With Android v9.6.5 I seem to not get anything with `startApp`.

**Comment by FeiFanLiang** [comment]
So this issue is still not fixed, I am shocked by TG's IOS team

**Comment by milamaja** [comment]
> So this issue is still not fixed, I am shocked by TG's IOS team

On the positive side... There is a work around available

**Comment by india666661** [comment]
Up! I do hope this issue handled by telegram team.

**Comment by india666661** [comment]
It's been two or three months, haven't it been resolved, telegram ios team, please

**Comment by india666661** [comment]
[InlineKeyboardButton("/start",url=f"https://t.me/{context.bot.username}?start=Transaction_")]  ，The / parameter is missing, how can I deal with this bug？ thankyou

**Comment by india666661** [comment]
> startApp 适用于 iOS 和 Android，而 startapp 仅适用于 Android

bro what method

**Comment by india666661** [comment]
> > 需要添加的时候，这个bug不仅在IOS出现，在MAC客户端也会出现
> 
> 当 WebApps 6.7 的规范被引入时，维护 iOS 和 Mac 客户端的人似乎正在度假 :D

My brother, do you have any results for this question now?

**Comment by india666661** [comment]
> 尝试在 URL 中使用`startApp`而不是`startapp`
> 
> 所以：`https://t.me/botusername/appname?startApp=test`
> 
> _澄清一下：似乎在 iOS 和 Android 中参数是区分大小写的。为确保它也适用于 Android，请使用两个选项：_ `https://t.me/botusername/appname?startapp=test&startApp=test`

[InlineKeyboardButton("/start",url=f"https://t.me/{context.bot.username}?start=Transaction_")] ，The / parameter is missing, how can I deal with this bug？ thankyou

**Comment by NormandoHall** [comment]
Seems they are notified and status changed to **Fix comming** 👍 

![image](https://github.com/TelegramMessenger/Telegram-iOS/assets/2943127/5c5831ce-9f71-46e9-8889-f2ecc46f9302)

**Comment by Prooksius** [comment]
Tried to start Mini App though this type of link:

https://t.me/botusername?startapp=test

Documentation claims that it is working. But in fact it works only in desktop telegram application and not working (not passing any startapp data) in android and ios.
