### ISSUE TITLE
Add chat export function

### ISSUE THREAD

**Issue by morags** [TelegramMessenger/Telegram-iOS#1095]
At the moment, only Telegram's desktop client allows **exporting chats**, while competitors like WhatsApp and Signal also have that functionality in their mobile clients. This means that Telegram is both less safe than competitors (because one might have their chats "locked-in", if they don't own or have access to a desktop), and more confusing to use (because one expects a certain level of feature parity between clients and across apps). In addition, such functionality might also be needed to comply with the GDPR Art. 20: Right to data portability.

Usage scenario:
1. Click on "Settings"
2. Click on "Data and Storage"
3. Click on "Export chats"
4. Pick a destination for export or sharing

**Comment by ali-fareed** [comment]
The chat export function is currently out of scope for mobile apps.
