### ISSUE TITLE
XCode archive error: PIFCache doesn't exist

### ISSUE THREAD

**Issue by xyunsh** [TelegramMessenger/Telegram-iOS#1096]
### Description
Archive error
`error: PIFCache (/Users/shen/Library/Developer/Xcode/DerivedData/Telegram-dbuzhcgxpienccbeldbixzcblbwg/Build/Intermediates.noindex/ArchiveIntermediates/Telegram (Simulator, Device) (Release)/IntermediateBuildFilesPath/XCBuildData/PIFCache) doesn't exist. If you manually cleared Derived Data, you need to close and re-open the project for the PIFCache to be created again. Using the "Clean Build Folder" command instead (⇧ ⌘ K) won't trigger this error. If this error still happens after re-opening the project, please file a bug report here: https://github.com/MobileNativeFoundation/rules_xcodeproj/issues/new?template=bug.md`

It seems that the PIFCache doesn't exist and I'm not sure how to resolve this issue. The error message suggests that if I manually cleared Derived Data, I need to close and re-open the project for the PIFCache to be created again. However, I have tried this and the error still occurs.

### Screenshots and Videos 
![98BA7279-B696-435E-B470-EB64E167B2E5](https://user-images.githubusercontent.com/6416648/236593494-708d959a-abbf-4f0d-aa99-b6282232eb49.png)

### Environment
**Device:** `iPhone/iPad X`
**Xcode version**: 14.2

**Comment by ali-fareed** [comment]
Have you tried to reboot your Mac?

**Comment by xyunsh** [comment]
> Have you tried to reboot your Mac?

Yes, I did. but still not work.

**Comment by ali-fareed** [comment]
Just noticed that you are trying to run Archive from Xcode. This is not supported. Refer to https://github.com/TelegramMessenger/Telegram-iOS#ipa on how to build an .ipa file.
