### ISSUE TITLE
iOS Telegram 5.1 for tg://resolve?domain=username now open user info page but not chat view

### ISSUE THREAD

**Issue by Villy21** [TelegramMessenger/Telegram-iOS#11]
From Telegram 5.0 scheme tg://msg?to=tel stop work.
From Telegram 5.1 scheme tg://resolve?domain=username now open user info page. Previously it open chat with user.

Is now any way to start chat with user by url scheme ?

**Comment by whudwl** [comment]
same here.  URL schema "tg://msg?text=Hello&to=+42333" used to open chat + autofill text, now all it does is open telegram.

**Comment by laktyushin** [comment]
Fixed in 5.10 release.

**Comment by Villy21** [comment]
@laktyushin what exactly you fixed in 5.10 ?
I updated to 5.10 and check all scenarios from top.

tg://msg?to=tel - did nothing.
tg://resolve?domain=username - open user info page but not a chat.
