### ISSUE TITLE
How to modify the PresentationStrings.mapping file In version 5.5?

### ISSUE THREAD

**Issue by twisturn** [TelegramMessenger/Telegram-iOS#110]
How to modify the PresentationStrings.mapping file In version 5.5?

**Comment by shivanraptor** [comment]
I noticed you ask this question again (see #96). Why do you specify an old version 5.5?

**Comment by twisturn** [comment]
@shivanraptor Because our server supports up to 5.5

**Comment by laktyushin** [comment]
Edit the **Localization.strings** and then generate PresentationStrings class like this:
`swift tools/GenerateLocalization.swift Telegram-iOS/en.lproj/Localizable.strings submodules/TelegramUI/TelegramUI/PresentationStrings.swift`

**Comment by twisturn** [comment]
@laktyushin I didn't catch your meaning

**Comment by laktyushin** [comment]
Go to the project root directory and run the command I've provided.

**Comment by twisturn** [comment]
![A3F94256-EEBA-41D0-9D17-E3580BD877F8](https://user-images.githubusercontent.com/17715937/62988028-60714d80-be75-11e9-9d16-adf20ab5f549.png)
@laktyushin
