### ISSUE TITLE
How show telegram Tabbar without Authorisation

### ISSUE THREAD

**Issue by anvar0522** [TelegramMessenger/Telegram-iOS#1101]
### Checklist
- [x ] I am reporting an issue in existing functionality that does not work as intended
- [x ] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
I need to add first with my Authorization screens then open telegram tabbar, when people taps to telegram chats tabbar then I need open Telegram auth
Check clip above(it is android app I need like this in iOS)

####  
If it is too long to describe please tell me how I can open telegram tabbar without authorisation

### Screenshots and Videos 

https://github.com/TelegramMessenger/Telegram-iOS/assets/89182155/bc8ee59b-10c6-49ee-aaea-68dd56e69407

### Environment
**Device:** `all iPhones`

**iOS version**: `all`

**App version:** `9.5.3`

**Comment by ali-fareed** [comment]
That would be a fairly large change to the existing codebase. It is recommended that you familiarize yourself with the existing UI first, and then work towards the desired behavior in small steps.
