### ISSUE TITLE
How to enable code send using SMS instead of telegram app

### ISSUE THREAD

**Issue by dilawer** [TelegramMessenger/Telegram-iOS#1105]
I cloned the project and changed it to create a new version out of it.

I want to enable code sending via SMS instead of Telegram app while user tries to login. 

I studied the code and api docs regarding this method https://core.telegram.org/constructor/auth.sentCode takes multiple params including codeSettings as param which can allow app to check and enable option of verification code while login. However, I think I am missing something important because I am not able to understand how can I pass desired codeSettings or maybe I have to look for something else.

Maybe there is a default settings available so that I can change default code sending type.

Please assist.

**Comment by wwpp3399** [comment]
Have you solved this problem？

**Comment by dilawer** [comment]
No, I actually know that telegram will send code through SMS automatically if there is no telegram app active session.

But if we want to keep it with SMS code only, I dont find yet how to do that through app source code. Any help would be appreciated

**Comment by wwpp3399** [comment]
我不认为能通过开源代码，来发送短信验证码以供登录，因为这样会增长不可控成本

**Comment by wwpp3399** [comment]
I don't think it's possible to send an SMS verification code for login through open source code, because that would add uncontrollable costs

**Comment by wwpp3399** [comment]
But after I resigned, telegram still couldn't send an SMS code

**Comment by ali-fareed** [comment]
The server controls whether the code is sent via SMS or an in-app notification.

**Comment by wwpp3399** [comment]
> The server controls whether the code is sent via SMS or an in-app notification.

Hello, I use the open source code compilation, send unregistered mobile phone number verification, the result is still prompt through other devices Telegram App access

**Comment by JiangHanXin** [comment]
> > 服务器控制代码是通过短信还是应用内通知发送。
> 
> 您好，我使用开源代码编译，发送未注册的手机号码验证，结果仍然提示通过其他设备Telegram App访问

你好 解决了吗？我也遇到这个问题了

**Comment by TianHuaLin** [comment]
> I cloned the project and changed it to create a new version out of it.
> 
> I want to enable code sending via SMS instead of Telegram app while user tries to login.
> 
> I studied the code and api docs regarding this method https://core.telegram.org/constructor/auth.sentCode takes multiple params including codeSettings as param which can allow app to check and enable option of verification code while login. However, I think I am missing something important because I am not able to understand how can I pass desired codeSettings or maybe I have to look for something else.
> 
> Maybe there is a default settings available so that I can change default code sending type.
> 
> Please assist.

Did you make it in the end？
