### ISSUE TITLE
Ogg playback issue

### ISSUE THREAD

**Issue by generalbytes** [TelegramMessenger/Telegram-iOS#1108]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
Ogg files are not played on iOS Telegram variant. Same files play well on Android Telegram and Telegram Desktop.
Android user pastes his OGG music file into chat. File plays well. iOS user clicks on play icon on same file in chat window. File begins to play but no sound is produced.

### Expected Behavior
Should should be produced.

### Actual Behavior
Sound should is not heard.

### Steps to Reproduce
1. Download test OGG file https://drive.google.com/file/d/1p37uLFs6mzaIQOJvjMkqf8wT0R2KAG0P/view?usp=share_link
2. Paste it into chat with your iOS friend on Android device.
3. Play song on My Android device - sound is heard.
4. Play song on Friend's iOS device - sound is NOT heard.

### Environment
**Device:** `iPhone 14 pro`

**iOS version**: ` iOS 15`

**App version:** `Latest`

**Comment by ali-fareed** [comment]
This file appears to use Vorbis, which is not supported on iOS.

**Comment by Laiteux** [comment]
@ali-fareed Wouldn't it be possible to add support?

Spotify uses Vorbis too, for example, so Spotify-downloaded OGG files can't be played on iOS and require conversion.
