### ISSUE TITLE
Cannot edit my own messages in channels 

### ISSUE THREAD

**Issue by NightMachinary** [TelegramMessenger/Telegram-iOS#111]
See:
![82CAD7FD-F3BB-40DA-98FE-802302D02DF9](https://user-images.githubusercontent.com/36224762/62817987-538eea00-bb55-11e9-9e9d-4580fd5baf4f.jpeg)
![7E9DEE6E-69E6-4724-BADD-9C4C44A33493](https://user-images.githubusercontent.com/36224762/62817990-5e497f00-bb55-11e9-92c8-84f6beb59260.jpeg)

Contrast with Telegram Desktop:
![35BF6A6C-B529-4DA8-BEFD-8B8BDE3402D9](https://user-images.githubusercontent.com/36224762/62817997-7caf7a80-bb55-11e9-91c7-451d6739eaa8.jpeg)

**Comment by shivanraptor** [comment]
If the message is too old, it cannot be edited. Post a new message in your channel, and try to edit it; editing should work.

**Comment by NightMachinary** [comment]
No, I had just posted that. And you see it was editable on the desktop
client.

**Comment by laktyushin** [comment]
Fixed in 5.11.1
