### ISSUE TITLE
The account recovery process for Telegram has significant issues

### ISSUE THREAD

**Issue by Rick82** [TelegramMessenger/Telegram-iOS#1117]
After a Telegram account is compromised:
1. The default method for authentication should prioritize SMS verification codes rather than relying on the compromised device (or email).
2. The user should have the option to use SMS-based high-level permissions instead of relying on the compromised device.
3. When using the account deletion API, the verification code should also be primarily sent via SMS.

The entire process raises serious security concerns, as legitimate users are unable to regain control of their compromised accounts, leaving them helpless.

thank you

**Comment by culturetown** [comment]
Have you found a solution to this problem? I'm having the same problem, any account that logs in to get the SMS verification code says "we've sent the code to the Telegram app for ********** on your other device"
