### ISSUE TITLE
I am unable to embed Telegram-IOS into my app

### ISSUE THREAD

**Issue by abhi-m-simformsolutons** [TelegramMessenger/Telegram-iOS#1118]
I want to embed the whole Telegram app into my existing Xcode project. 

I tried with drag and drop the Telegram-IOS repo into my project but it doesn't work (Generated the Telegram project with the given Python script). Also, I am trying to add submodules manually but it is tightly coupled with Bazel dependency.  Could anyone offer suggestions on the most efficient method to accomplish this? 

Thanks.

**Comment by ali-fareed** [comment]
This isn't really a supported mode of operation. It is possible, however, to add the core functionality as a Bazel dependency.
