### ISSUE TITLE
[Feature Request] Native PiP on iPad

### ISSUE THREAD

**Issue by artazol** [TelegramMessenger/Telegram-iOS#112]
it would be very convenient to be able to watch videos not only in the Telegram application, also native PiP is more fluid than current implementation

**Comment by laktyushin** [comment]
It's not possible to support system PIP in the app because AVPictureInPictureController requires AVPlayerLayer to operate and we won't use any of AVPlayer stuff as we have our own media player built with FFMPEG.

**Comment by brandoncote** [comment]
even with iOS allowing background camera access (PiP for video calls), you guys won't revisit this?

**Comment by limdingwen** [comment]
I’m interested in this as well. Lack of Picture in Picture support is one of the main reasons I’m using FaceTime instead of Telegram for video calls.
