### ISSUE TITLE
Black screen after sideloaded 

### ISSUE THREAD

**Issue by df1228** [TelegramMessenger/Telegram-iOS#1120]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
download from ipa from release-9.6.3, and install it to iphone XR by sideloadly.io, i can open it, but it always show a black screen.

### Expected Behavior
Should work as expected

### Actual Behavior
Black screen

### Steps to Reproduce
1.  download sideloadly from https://sideloadly.io/
2. download ipa from release
3. load it to iPhone
4. click telegram icon on iPhone

### Environment
**Device:** `iPhone XR`

**iOS version**: `16.3`

**App version:** `9.6.3`

**Comment by ali-fareed** [comment]
The files on the releases page are not supposed to be functional.

**Comment by LSPBoy** [comment]
can you sovle it
