### ISSUE TITLE
Keyboard not collapsing on iOS 17

### ISSUE THREAD

**Issue by GreenYun** [TelegramMessenger/Telegram-iOS#1122]
After upgrading to iOS 17, Telegram cannot hide the keyboard if I scroll down on the chat view. The correct way to interact with the chat view is to swipe from left side. I do not see any similar circumstances on other apps, thus I think Telegram may have to fix it. 

Tested on iPhone SE (2nd generation) and iPhone SE (3rd generation). Both iOS 17.0 Developer Beta.

**Comment by Magprone** [comment]
Same issue on iPhone XS. Also I have tried to use unofficial client ”nicegram”, it didn't solve the problem.

**Comment by ali-fareed** [comment]
Let's track it in https://github.com/TelegramMessenger/Telegram-iOS/issues/1123

**Comment by rawmean** [comment]
All my apps that are written with SwiftUI are also affected by this iOS 17 bug. Even beta 3 didn’t fix the problem.

**Comment by kamran775** [comment]
Same with my iphone XS ios 17 public beta

**Comment by kamran775** [comment]
Is there any solution?

**Comment by ZSavich** [comment]
How I fixed this:
1. Installed **GBoard** (Keyboard from Google);
2. **Changed** default keyboard to GBoard;
3. **Open Telegram** and try to write a message on **GBoard**;
4. **Switch** GBoard to Default Keyboard;
5. **Now Default Keyboard works fine.**

**Comment by kamran775** [comment]
> How I fixed this:
> 
> 1. Installed **GBoard** (Keyboard from Google);
> 2. **Changed** default keyboard to GBoard;
> 3. **Open Telegram** and try to write a message on **GBoard**;
> 4. **Switch** GBoard to Default Keyboard;
> 5. **Now Default Keyboard works fine.**

It’s not working:-(

**Comment by nihaldivyam** [comment]
It doesn't work with the Google keyboard also, the keyboard doesn't collapse !!

> How I fixed this:
> 
> 1. Installed **GBoard** (Keyboard from Google);
> 2. **Changed** default keyboard to GBoard;
> 3. **Open Telegram** and try to write a message on **GBoard**;
> 4. **Switch** GBoard to Default Keyboard;
> 5. **Now Default Keyboard works fine.**
![IMG_5880](https://github.com/TelegramMessenger/Telegram-iOS/assets/28355141/007a628b-4e57-47b7-81e8-daa1fb0ca247)

**Comment by fglukhov** [comment]
> How I fixed this:
> 
> 1. Installed **GBoard** (Keyboard from Google);
> 2. **Changed** default keyboard to GBoard;
> 3. **Open Telegram** and try to write a message on **GBoard**;
> 4. **Switch** GBoard to Default Keyboard;
> 5. **Now Default Keyboard works fine.**

Works on XR
