### ISSUE TITLE
MPEG-4 video (MP4V) not playing on iOS

### ISSUE THREAD

**Issue by magnusso** [TelegramMessenger/Telegram-iOS#1129]
### Checklist
- [x ] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
Attached 10 second surveillance camera video plays in desktop app, but not on the iOS app.

### Expected Behavior
Should run as in the desktop app

### Actual Behavior
Stuck on fist frame.

### Steps to Reproduce
1 Play attached video in iOS app.
2. 
3. 

### Screenshots and Videos 
`Remove, if not applicable
`
### Environment
**Device:** `iPhone 13`

**iOS version**: `13.2`

**App version: 9.6.3 (25780)

**Comment by magnusso** [comment]
https://github.com/TelegramMessenger/Telegram-iOS/assets/26468823/7652b5c5-0f26-4405-9f77-063d6f6f6044

**Comment by ali-fareed** [comment]
Does it work in QuickTime?
