### ISSUE TITLE
Looping "Who do you want to send it to?" when sending a message via Siri

### ISSUE THREAD

**Issue by whislock** [TelegramMessenger/Telegram-iOS#113]
Version: Telegram 5.10 via iOS App Store
iOS Version: 12.4
Device: iPhone XS Max

Issue: Siri repeatedly asks "who do you want to send it to?" when trying to send a message via Siri.

Trigger: "Hey Siri, send a message to (contact)."

Result: Device displays an empty Telegram message with the correct contact name. Siri asks "who do you want to send it to?" If you respond with a name, it will continue to loop this behavior endlessly.

**Comment by laktyushin** [comment]
Fixed in 5.11
