### ISSUE TITLE
I signed the Telegram.ipa, and when I opened it, the screen is black, how to solve it?

### ISSUE THREAD

**Issue by LSPBoy** [TelegramMessenger/Telegram-iOS#1136]
### Checklist
- [ ] I am reporting an issue in existing functionality that does not work as intended
- [ ] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
I signed the Telegram.ipa, and when I opened it, the screen is black, how to solve it?

### Steps to Reproduce
1. the ipa is created successfully 
2. then signed the Telegram.ipa
3.  then install to iphone and open it, the screen is black

### Environment
**Device:** `iPhone/iPad X`

**iOS version**: `all`

**App version:** `9.6.3`

**Comment by ali-fareed** [comment]
Re-signing the IPA is not really supported. It's recommended to build the IPA with the correct certificate.
