### ISSUE TITLE
Recover telegram chat history from iPhone

### ISSUE THREAD

**Issue by reachanihere** [TelegramMessenger/Telegram-iOS#1138]
Hi,
I, by mistake deleted a very important conversation on Telegram. Is there any way to access cache in iPhone and use that cache to recover lost messages?

**Comment by ali-fareed** [comment]
No, when removing messages from the local SQLite database the application uses the "secure" hint that zeroes out the data on disk.

**Comment by reachanihere** [comment]
Hi Ali, thanks for your prompt reply. Sorry I didn't mention the messages were deleted from other device and the iPhone I mention still has them because it has not been connected to internet yet, which means the data is still on the disk

**Comment by ali-fareed** [comment]
The only option I can think of is manually selecting the messages in chat and using the external share feature to export them to Files.
![image](https://github.com/TelegramMessenger/Telegram-iOS/assets/57234349/3d4835b7-d263-4f37-9761-d5a3e9edc2e2)
