### ISSUE TITLE
Can not share mp3 files

### ISSUE THREAD

**Issue by NightMachinary** [TelegramMessenger/Telegram-iOS#114]
mp3 files have no share (export) option:
![AA0EA056-6B02-4077-8793-5B6890206975](https://user-images.githubusercontent.com/36224762/62831184-6a563f00-bc30-11e9-9ce0-0b89cc0287d1.jpeg)

**Comment by laktyushin** [comment]
What do you mean by that? Audio files have both forwarding and external share options allowing you to save media to Files or share it via another app.

**Comment by NightMachinary** [comment]
Where is the external share option of audio files in iOS? I haven’t found
it.

**Comment by laktyushin** [comment]
Open audio player, tap 3-dots button for share menu and press external share button (a button  with arrow coming out of box on the right side from share sheet title).

**Comment by NightMachinary** [comment]
Thanks!
