### ISSUE TITLE
IPA File Generation fails with error

### ISSUE THREAD

**Issue by tigrandevelandoo** [TelegramMessenger/Telegram-iOS#1141]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
https://github.com/TelegramMessenger/Telegram-iOS#ipa does not work as expected. 
I created all profiles, and identifiers at it is implemented in the fake-codesigning folder

When i`m running this script, I am gettings this kind of error (see attachment)

python3 build-system/Make/Make.py \   
    --cacheDir="$HOME/telegram-bazel-cache" \
    build \          
    --configurationPath="$HOME/telegram-configuration/appstore-configuration.json" \
    --codesigningInformationPath="$HOME/telegram-configuration/fake-codesigning" \
    --buildNumber=100001 \                                                 
    --configuration=release_arm64
    
Do I need to make extra changes in filesystems or maybe in BUILD files, or this is enough?

### Expected Behavior
Should generate IPA file

### Actual Behavior
Returning error

### Steps to Reproduce
Same as in Github README file for ipa generation. 

### Screenshots and Videos 
Remove, if not applicable
<img width="1489" alt="Screenshot 2023-07-04 at 18 29 33" src="https://github.com/TelegramMessenger/Telegram-iOS/assets/122877805/582c3509-f041-48f0-b47f-f7fdb65d4ed2">### Environment
**Device:** `iPhone/iPad X`

**iOS version**: `14.0`

**App version:** `9.6.3`

**XCode:** `14.3.1`
**Bazel:** `6.2.1`

**Comment by ali-fareed** [comment]
This error means that the file names at `$HOME/telegram-configuration/fake-codesigning/profiles` differ from the standard ones:

```
BroadcastUpload.mobileprovision
Intents.mobileprovision
NotificationContent.mobileprovision
NotificationService.mobileprovision
Share.mobileprovision
Telegram.mobileprovision
WatchApp.mobileprovision
WatchExtension.mobileprovision
Widget.mobileprovision
```

**Comment by tigrandevelandoo** [comment]
<img width="733" alt="Screenshot 2023-07-06 at 08 52 42" src="https://github.com/TelegramMessenger/Telegram-iOS/assets/122877805/e896e5bf-8279-4eb4-9067-a5fce84dac1e">

Here is my $HOME/telegram-configuration/fake-codesigning/profiles folder

@ali-fareed is there any complete guide or tutorial for generating xcode project or IPA

**Comment by tigrandevelandoo** [comment]
@ali-fareed cab you please reopen issue?

**Comment by RuslanARmore** [comment]
Have same error but all provisions named properly, what can I check additionaly?
