### ISSUE TITLE
翻译不了

### ISSUE THREAD

**Issue by mlsqq** [TelegramMessenger/Telegram-iOS#1144]
最新版tg，ios16.5.1
![ace75c6b2cd1ece7f687fc8df860a3d](https://github.com/TelegramMessenger/Telegram-iOS/assets/85686342/898cb0c5-ca7c-43f1-a2f9-12e8bb7093fb)
如图翻译不了，需要手动选择更改语言为中文才行

**Comment by hk791** [comment]
问题还是存在呢，有什么解决办法吗

**Comment by bestK** [comment]
中文语言包导致的，切换成英文的之后正常
