### ISSUE TITLE
sms Didn't get the code

### ISSUE THREAD

**Issue by LSPBoy** [TelegramMessenger/Telegram-iOS#1147]
I cloned the project and build ipa packge, can‘t get sms code, how resolve it
<img width="405" alt="Snipaste_2023-07-21_18-30-38" src="https://github.com/TelegramMessenger/Telegram-iOS/assets/24997004/8de440c5-6529-4d56-a7df-99bfbc4a447c">
<img width="363" alt="Snipaste_2023-07-21_18-36-08" src="https://github.com/TelegramMessenger/Telegram-iOS/assets/24997004/aece1251-a4ca-43de-a9d0-6aa43922b8ed">

**Comment by ali-fareed** [comment]
Third-party applications can't request SMS at the moment.

**Comment by LSPBoy** [comment]
didn't get the code, will block user logging in, do you know how to resolve  it, thx
