### ISSUE TITLE
ERROR: BUILD:1752:15: in plist_fragment rule //Telegram:TelegramInfoPlist:

### ISSUE THREAD

**Issue by protodimbo** [TelegramMessenger/Telegram-iOS#1149]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
Getting errors while following the directions in README.md to build Telegram-iOS.

### Expected Behavior
Telegram-iOS should build correctly.

### Actual Behavior
I get the following output:
`ERROR: /Users/Me/Documents/Projects/Telegram-iOS/Telegram/BUILD:1752:15: in plist_fragment rule //Telegram:TelegramInfoPlist:
Traceback (most recent call last):
	File "/Users/Me/Documents/Projects/Telegram-iOS/build-system/bazel-utils/plist_fragment.bzl", line 22, column 17, in _plist_fragment
		fail("Expected value for --define={} was not found".format(key))
Error in fail: Expected value for --define=ddcc74813eed5265 was not found
ERROR: /Users/Me/Documents/Projects/Telegram-iOS/Telegram/BUILD:1752:15: Analysis of target '//Telegram:TelegramInfoPlist' failed
ERROR: Analysis of target '@rules_xcodeproj_generated//generator/Telegram/Telegram_xcodeproj:Telegram_xcodeproj' failed; build aborted:
ERROR: Build failed. Not running target
FAILED: Build did NOT complete successfully (5 packages loaded, 77 targets configured)
    Fetching repository @local_config_xcode; Fetching the default Xcode version
Traceback (most recent call last):
  File "/Users/Me/Documents/Projects/Telegram-iOS/build-system/Make/Make.py", line 1037, in <module>
    generate_project(bazel=bazel_path, arguments=args)
  File "/Users/Me/Documents/Projects/Telegram-iOS/build-system/Make/Make.py", line 565, in generate_project
    generate(
  File "/Users/Me/Documents/Projects/Telegram-iOS/build-system/Make/ProjectGeneration.py", line 184, in generate
    generate_xcodeproj(build_environment, disable_extensions, disable_provisioning_profiles, generate_dsym, configuration_path, bazel_app_arguments, target_name)
  File "/Users/Me/Documents/Projects/Telegram-iOS/build-system/Make/ProjectGeneration.py", line 44, in generate_xcodeproj
    call_executable(bazel_generate_arguments)
  File "/Users/Me/Documents/Projects/Telegram-iOS/build-system/Make/BuildEnvironment.py", line 81, in call_executable
    subprocess.check_call(resolved_arguments, env=resolved_env)
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/Me/Documents/Projects/Telegram-iOS/build-input/bazel-6.1.1-darwin-arm64', 'run', '//Telegram:Telegram_xcodeproj', '--override_repository=build_configuration=/Users/Me/Documents/Projects/Telegram-iOS/build-input/configuration-repository', '--//Telegram:disableExtensions', '--//Telegram:disableStripping']' returned non-zero exit status 1.
`

### Steps to Reproduce
1. I downloaded the Telegram repo into ~.
2. I created the empty Telegram project in ~/Telegram-iOS/Telegram.
3. Changed xcode version in version.json to 14.3.1
4. I updated the template_minimal_development_configuration.json and versions.json files as appropriate. XCode version 14.3.
From the ~/Telegram-iOS directory, I run the command:
`python3 build-system/Make/Make.py \
    --cacheDir="$HOME/telegram-bazel-cache" \
    generateProject \
    --configurationPath=build-system/template_minimal_development_configuration.json \
    --xcodeManagedCodesigning`

### Environment
**Device:** `N/A

**iOS version**: `N/A`

**App version:** `N/A`

**Comment by ali-fareed** [comment]
Could you post your `template_minimal_development_configuration.json` here?

**Comment by alirezarabiei7239** [comment]
same issue.

**Comment by abrosov-sergey** [comment]
how did you fix it?

I'm not going, gives an error... 

1) ERROR: ~/Telegram-iOS/Telegram/BUILD:381:15: in plist_fragment rule //Telegram:UrlTypesInfoPlist: 
Traceback (most recent call last):
	File "~/Telegram-iOS/build-system/bazel-utils/plist_fragment.bzl", line 22, column 17, in _plist_fragment
		fail("Expected value for --define={} was not found".format(key))
Error in fail: Expected value for --define=f8b3db8a71378469 was not found

2) ERROR: ~/Telegram-iOS/Telegram/BUILD:381:15: Analysis of target '//Telegram:UrlTypesInfoPlist' failed

3) ERROR: Analysis of target '@rules_xcodeproj_generated//generator/Telegram/Telegram_xcodeproj:Telegram_xcodeproj' failed; build aborted:

**Comment by Nazarash** [comment]
@protodimbo, how you fix this bug?
