### ISSUE TITLE
Feature request: support critical notifications

### ISSUE THREAD

**Issue by tomlut** [TelegramMessenger/Telegram-iOS#115]
iOS 12 introduced critical notifications that allow notification alerts even when "Do not disturb" is active. It would be great if Telegram could support this.

**Comment by laktyushin** [comment]
There's no need for Critical Alerts in a messenger and Apple won't give a Critical Alert Notifications Entitlement for apps not related to healthcare or public/personal safety.

**Comment by tomlut** [comment]
Using a bot to alert me if my house is burning down?

This would all seem to be personal safety.

**Comment by laktyushin** [comment]
Apple still won't allow this since it is not core functionality of the app and especially if these notifications are pushed by some 3rd parties.

**Comment by tomlut** [comment]
Ok. Thanks for taking the time to explain.

**Comment by kremer-io** [comment]
I'ld like to reopen this issue. Pls have a look on Pushover,  [they got approved for critical alerts](https://blog.pushover.net/posts/2020/2/ios-critical-alerts#:~:text=Added%20in%20iOS%2012%2C%20Critical,and%20been%20approved%20by%20Apple.). They heavily built on 3rd party sources. Reading through the Apple Developer Forum, it seems that many applications have been approved now. Every major smart home software is integrating Telegram, so I definitly see an use case for critical alerts. Some volunteer fire departments also use Telegram and could benefit greatly from this feature.

**Comment by Codelica** [comment]
I agree with @kremer-io and there are others like [Home Assistant's mobile app](https://companion.home-assistant.io/docs/notifications/critical-notifications/) that support critical push alerts that are generated by users of the platform.  Ironically using Home Assistant's [Telegram integration](https://www.home-assistant.io/integrations/telegram/) is why I'm hoping Telegram will support critical alerts in the future.  :)

**Comment by MarcFinns** [comment]
Any development on this front?

**Comment by melyux** [comment]
This is definitely missing.

**Comment by fpalsson** [comment]
Suggest to reopen.
