### ISSUE TITLE
Can't create IPA with instructions in readme (error - security: cert import failed: A default keychain could not be found)

### ISSUE THREAD

**Issue by sergiocasual** [TelegramMessenger/Telegram-iOS#1157]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [ ] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
I can't create IPA with instructions in readme. On build phase I get next error:
ERROR: /Users/s.teteryatnik/Downloads/Telegram-iOS/Telegram/BUILD:1546:14: Processing and signing IntentsExtension failed: (Exit 1): process-and-sign--389255329.sh failed: error executing command (from target //Telegram:IntentsExtension) 
  (cd /private/var/tmp/_bazel_root/887dba9f4a80f0175ab48c6032216a56/execroot/__main__ && \
  exec env - \
    APPLE_SDK_PLATFORM=iPhoneOS \
    APPLE_SDK_VERSION_OVERRIDE=16.2 \
    XCODE_VERSION_OVERRIDE=14.2.0.14C18 \
  bazel-out/applebin_ios-ios_armv7-opt-ST-2967bd56a867/bin/Telegram/IntentsExtension-intermediates/process-and-sign--389255329.sh should_sign should_compress)
# Configuration: c6bb6bd296e25c168482670045b3949392953a77726ba5711b8379efb029e2e3
# Execution platform: @local_config_platform//:host
**security: cert import failed: A default keychain could not be found.
security: problem decoding**

I have successfully created all Identifiers & Distribution Profiles

PLEASE, HELP! :)

### Expected Behavior
IPA successfully created

### Actual Behavior
IPA creation failed

### Steps to Reproduce
1. Copy and edit build-system/appstore-configuration.json
2. Copy build-system/fake-codesigning. Create and download distribution provisioning profiles.
3. Generate an Xcode project:
python3 build-system/Make/Make.py \
    --cacheDir="$HOME/telegram-bazel-cache" \
    generateProject \
    --configurationPath=configuration_from_step_1.json \
    --codesigningInformationPath=directory_from_step_2
4. Run build:
python3 build-system/Make/Make.py \
    --cacheDir="$HOME/telegram-bazel-cache" \
    build \
    --configurationPath=...see previous section... \
    --codesigningInformationPath=...see previous section... \
    --buildNumber=100001 \
    --configuration=release_arm64

### Screenshots and Videos 
<img width="324" alt="Снимок экрана 2023-07-28 в 14 36 51" src="https://github.com/TelegramMessenger/Telegram-iOS/assets/68233712/ee90e158-2354-4e45-b267-8a0155df891f">

### Environment

**Device**: `MacBook Pro Apple M1 Pro`

**Xcode version**: `14.2, 14.3`

**Mac OS version**: `13.4`

**App version:** `9.6.3, 9.6.5`

**Comment by ali-fareed** [comment]
Please post the entire build log.

**Comment by sergiocasual** [comment]
S7-13-042940:telegram-ios s.teteryatnik$ sudo python3 build-system/Make/Make.py --overrideBazelVersion     --cacheDir="$HOME/telegram-bazel-cache"     build     --configurationPath="$HOME/telegram-configuration/appstore-configuration.json"     --codesigningInformationPath="$HOME/telegram-configuration"     --buildNumber=1     --configuration=release_universal
TelegramBuild: running
/Users/s.teteryatnik/Downloads/Telegram-iOS/build-input/bazel-6.1.1-darwin-arm64 build Telegram/Telegram --override_repository=build_configuration=/Users/s.teteryatnik/Downloads/Telegram-iOS/build-input/configuration-repository --announce_rc --features=swift.use_global_module_cache --verbose_failures --experimental_remote_cache_async --features=swift.skip_function_bodies_for_derived_files --jobs=10 --define=buildNumber=1 --define=telegramVersion=9.6.5 --disk_cache=/Users/s.teteryatnik/telegram-bazel-cache -c opt --ios_multi_cpus=armv7,arm64 --watchos_cpus=arm64_32 --apple_generate_dsym --output_groups=+dsyms --features=swift.opt_uses_wmo --features=swift.opt_uses_osize --swiftcopt=-num-threads --swiftcopt=1 --swiftcopt=-j1 --features=dead_strip --objc_enable_binary_stripping --apple_bitcode=watchos=embedded
INFO: Invocation ID: 6c6658e5-657d-42df-bfdb-ec4e9cca9438
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=187
INFO: Reading rc options for 'build' from /Users/s.teteryatnik/Downloads/Telegram-iOS/.bazelrc:
  'build' options: --action_env=ZERO_AR_DATE=1 --apple_platform_type=ios --cxxopt=-std=c++17 --per_file_copt=third-party/webrtc/.*.cpp$,@-std=c++17 --per_file_copt=third-party/webrtc/.*.cc$,@-std=c++17 --per_file_copt=third-party/webrtc/.*.mm$,@-std=c++17 --per_file_copt=submodules/LottieMeshSwift/LottieMeshBinding/Sources/.*.mm$,@-std=c++17 --swiftcopt=-whole-module-optimization --per_file_copt=.*.m$,@-fno-objc-msgsend-selector-stubs --per_file_copt=.*.mm$,@-fno-objc-msgsend-selector-stubs --features=debug_prefix_map_pwd_is_dot --features=swift.cacheable_swiftmodules --features=swift.debug_prefix_map --features=swift.enable_vfsoverlays --strategy=Genrule=standalone --spawn_strategy=standalone --strategy=SwiftCompile=standalone --define RULES_SWIFT_BUILD_DUMMY_WORKER=1
INFO: Analyzed target //Telegram:Telegram (4 packages loaded, 2965 targets configured).
INFO: Found 1 target...
ERROR: /Users/s.teteryatnik/Downloads/Telegram-iOS/Telegram/BUILD:1546:14: Processing and signing IntentsExtension failed: (Exit 1): process-and-sign--389255329.sh failed: error executing command (from target //Telegram:IntentsExtension) 
  (cd /private/var/tmp/_bazel_root/887dba9f4a80f0175ab48c6032216a56/execroot/__main__ && \
  exec env - \
    APPLE_SDK_PLATFORM=iPhoneOS \
    APPLE_SDK_VERSION_OVERRIDE=16.2 \
    XCODE_VERSION_OVERRIDE=14.2.0.14C18 \
  bazel-out/applebin_ios-ios_armv7-opt-ST-2967bd56a867/bin/Telegram/IntentsExtension-intermediates/process-and-sign--389255329.sh should_sign should_compress)
# Configuration: 43867dc44858e723d57b34ea1daee2299af9d804f7c81214f5deda516babf044
# Execution platform: @local_config_platform//:host
security: cert import failed: A default keychain could not be found.
security: problem decoding
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_root/887dba9f4a80f0175ab48c6032216a56/execroot/__main__/bazel-out/darwin_arm64-opt-exec-2B5CBBC6-ST-4f4ca27b179b/bin/external/build_bazel_rules_apple/tools/codesigningtool/codesigningtool.runfiles/build_bazel_rules_apple/tools/codesigningtool/codesigningtool.py", line 418, in <module>
    sys.exit(main(generate_arg_parser().parse_args()))
  File "/private/var/tmp/_bazel_root/887dba9f4a80f0175ab48c6032216a56/execroot/__main__/bazel-out/darwin_arm64-opt-exec-2B5CBBC6-ST-4f4ca27b179b/bin/external/build_bazel_rules_apple/tools/codesigningtool/codesigningtool.runfiles/build_bazel_rules_apple/tools/codesigningtool/codesigningtool.py", line 381, in main
    identity = _find_codesign_identity(args.mobileprovision)
  File "/private/var/tmp/_bazel_root/887dba9f4a80f0175ab48c6032216a56/execroot/__main__/bazel-out/darwin_arm64-opt-exec-2B5CBBC6-ST-4f4ca27b179b/bin/external/build_bazel_rules_apple/tools/codesigningtool/codesigningtool.runfiles/build_bazel_rules_apple/tools/codesigningtool/codesigningtool.py", line 279, in _find_codesign_identity
    mpf = _parse_mobileprovision_file(mobileprovision)
  File "/private/var/tmp/_bazel_root/887dba9f4a80f0175ab48c6032216a56/execroot/__main__/bazel-out/darwin_arm64-opt-exec-2B5CBBC6-ST-4f4ca27b179b/bin/external/build_bazel_rules_apple/tools/codesigningtool/codesigningtool.runfiles/build_bazel_rules_apple/tools/codesigningtool/codesigningtool.py", line 102, in _parse_mobileprovision_file
    plist_xml = subprocess.check_output([
  File "/Users/s.teteryatnik/Downloads/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/s.teteryatnik/Downloads/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['security', 'cms', '-D', '-i', 'external/build_configuration/provisioning/Intents.mobileprovision']' returned non-zero exit status 1.
Target //Telegram:Telegram failed to build
INFO: Elapsed time: 0.998s, Critical Path: 0.18s
INFO: 4 processes: 4 internal.
FAILED: Build did NOT complete successfully
Traceback (most recent call last):
  File "/Users/s.teteryatnik/Downloads/Telegram-iOS/build-system/Make/Make.py", line 1039, in <module>
    build(bazel=bazel_path, arguments=args)
  File "/Users/s.teteryatnik/Downloads/Telegram-iOS/build-system/Make/Make.py", line 605, in build
    bazel_command_line.invoke_build()
  File "/Users/s.teteryatnik/Downloads/Telegram-iOS/build-system/Make/Make.py", line 371, in invoke_build
    call_executable(combined_arguments)
  File "/Users/s.teteryatnik/Downloads/Telegram-iOS/build-system/Make/BuildEnvironment.py", line 81, in call_executable
    subprocess.check_call(resolved_arguments, env=resolved_env)
  File "/Users/s.teteryatnik/Downloads/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/s.teteryatnik/Downloads/Telegram-iOS/build-input/bazel-6.1.1-darwin-arm64', 'build', 'Telegram/Telegram', '--override_repository=build_configuration=/Users/s.teteryatnik/Downloads/Telegram-iOS/build-input/configuration-repository', '--announce_rc', '--features=swift.use_global_module_cache', '--verbose_failures', '--experimental_remote_cache_async', '--features=swift.skip_function_bodies_for_derived_files', '--jobs=10', '--define=buildNumber=1', '--define=telegramVersion=9.6.5', '--disk_cache=/Users/s.teteryatnik/telegram-bazel-cache', '-c', 'opt', '--ios_multi_cpus=armv7,arm64', '--watchos_cpus=arm64_32', '--apple_generate_dsym', '--output_groups=+dsyms', '--features=swift.opt_uses_wmo', '--features=swift.opt_uses_osize', '--swiftcopt=-num-threads', '--swiftcopt=1', '--swiftcopt=-j1', '--features=dead_strip', '--objc_enable_binary_stripping', '--apple_bitcode=watchos=embedded']' returned non-zero exit status 1.

**Comment by sergiocasual** [comment]
@ali-fareed Can you help with this? I can't find nothing about this issue.

**Comment by ali-fareed** [comment]
It's probably not it, but could you try building release_arm64 instead of release_universal? Telegram no longer supports 32-bit devices.

**Comment by sergiocasual** [comment]
Same error

**Comment by ali-fareed** [comment]
Certainly, the latest release successfully builds using GitHub Actions: https://github.com/TelegramMessenger/Telegram-iOS/actions/runs/5659124797

Why are you using sudo to run the build script?

**Comment by summer22** [comment]
Hi, I have the same problem, how do you solve it?
