### ISSUE TITLE
No information about the duration of the video

### ISSUE THREAD

**Issue by Neurotoxin001** [TelegramMessenger/Telegram-iOS#1158]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
All videos do not have their duration displayed. It says 00:00.

### Expected Behavior
Videos should display their duration

### Actual Behavior
Videos do not show their duration

### Steps to Reproduce
1. Open any channel or chat with videos
2. There is no duration, only 00:00

It's started after "stories" update

### Screenshots and Videos 
![image](https://github.com/TelegramMessenger/Telegram-iOS/assets/39812401/c54d9380-aa2a-4ed4-954a-7f98020fee7c)
![image](https://github.com/TelegramMessenger/Telegram-iOS/assets/39812401/aa85f44d-f726-40a2-918b-42a43d2d604a)

### Environment
**Device:** `iPhone 13 Pro`

**iOS version**: `16.6`

**App version:** `9.6.6`

**Comment by Neurotoxin001** [comment]
Many more examples of bugged videos you can find in my channel:
https://t.me/Neurotoxin_001

**Comment by Neurotoxin001** [comment]
I can't even put timecodes like "01:12" in captions under videos, they don't work with "00:00" duration, can you fix this bug?

**Comment by Neurotoxin001** [comment]
10.0.0 version, issue is still here

**Comment by Neurotoxin001** [comment]
It's still bugged on 10.0.1 but now some videos showing duration fine. But not all.
Here is I upload videos and 1 of 5 is fine, but 4 is bugged.
https://t.me/Neurotoxin_001

![Strip 2](https://github.com/TelegramMessenger/Telegram-iOS/assets/39812401/f61d7b2f-6508-47b9-a392-61d57f7a11a5)

**Comment by Neurotoxin001** [comment]
10.0.2 still bugged

**Comment by Neurotoxin001** [comment]
10.0.3 still not fixed.................................

**Comment by shivanraptor** [comment]
This issue should be in high priority. Half of the videos have this issue. (No pattern has been found yet)

**Comment by Neurotoxin001** [comment]
Seems like fixed in 10.1, finally

**Comment by joaquinvacas** [comment]
This keeps happening on Android version as well
