### ISSUE TITLE
Bug in reading blocked_mode from config

### ISSUE THREAD

**Issue by G-200** [TelegramMessenger/Telegram-iOS#1166]
https://github.com/TelegramMessenger/Telegram-iOS/blob/a196a1684b5c2afeea249aaf8c6b668fdb74927b/submodules/TelegramCore/Sources/State/ManagedConfigurationUpdates.swift#L38

Must be:

```
let blockedMode = (flags & (1 << 8)) != 0
```

Reference: https://core.telegram.org/constructor/config

blocked_mode | flags.8?true | Indicates that telegram is probably censored by governments/ISPs in the current region
-- | -- | --

**Comment by ali-fareed** [comment]
Fixed in the internal code, thank you for noticing.

**Comment by ali-fareed** [comment]
Fixed in 10.0.0.
