### ISSUE TITLE
EXC_BAD_INSTRUCTION for xcode 14.3.1 for simulator ios version 16.5

### ISSUE THREAD

**Issue by keepClamDown** [TelegramMessenger/Telegram-iOS#1167]
<img width="1091" alt="image" src="https://github.com/TelegramMessenger/Telegram-iOS/assets/59951516/6612f654-f6fa-4e85-9c1b-5446f60369cd">
hello， I test telegram-ios in my simulator . it seems crash ~ can everyone help me ?   project info:{
    "app": "9.6.5",
    "bazel": "6.3.1",
    "xcode": "14.3.1"
}

**Comment by ali-fareed** [comment]
Should be fixed in 10.1.1.
