### ISSUE TITLE
Disabling Story didn’t disable it completely 

### ISSUE THREAD

**Issue by beerisgood** [TelegramMessenger/Telegram-iOS#1174]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
If I disable new Story feature in notifications settings, i still get notifications in main Telegram window top. 

### Expected Behavior
Whole Story feature should be disabled if user want it. 

### Actual Behavior
Story notifications at top Telegram window. 

### Steps to Reproduce
1. in Telegram go to settings
2. Open notifications 
3. disable everything for Story

### Screenshots and Videos 
-

### Environment
**Device:** `iPhone 14`

**iOS version**: `16.6`

**App version:** `10.0.0`

**Comment by ali-fareed** [comment]
There is currently no way to disable the story feature completely.

**Comment by beerisgood** [comment]
> There is currently no way to disable the story feature completely.

A setting should do what it provides, so this bug issue isn’t completed.
