### ISSUE TITLE
TLS proxy link incompatibility with Android and Desktop

### ISSUE THREAD

**Issue by FreedomPrevails** [TelegramMessenger/Telegram-iOS#118]
Both android and desktop versions of telegram accept TLS secrets encoded with "Base 64 Encoding with URL and Filename Safe Alphabet" (base64url) described here :
https://tools.ietf.org/html/rfc4648#section-5
But ios version does not accept "base64url" encoding resulting in incompatibility with other platforms.
I have a proxy with this secret `7sVKPq6QVE5oo3y-QcXTFEJnb29nbGUuY29t` and because it contains a `-` char, it can not be used in ios devices and `tg://` link doesnt work either.
The same secret and respective links work perfectly on android and desktop version of telegram.

**Comment by laktyushin** [comment]
Fixed in 5.11
