### ISSUE TITLE
The stories are available to my friends, but not to me

### ISSUE THREAD

**Issue by AndryS0** [TelegramMessenger/Telegram-iOS#1180]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
The stories are available to my friends, but not to me. I still see "This month stories are only available to premium telegram users".

### Expected Behavior
The stories are available to me, too

### Actual Behavior
I see it says "This month, publishing stories is only available to Telegram Premium subscribers".

### Steps to Reproduce
1. Be me or have iPhone SE (1st)
2. Open Telegram app
3. Try to create stories and cry

### Screenshots and Videos 
![IMG_0543](https://github.com/TelegramMessenger/Telegram-iOS/assets/64275982/4dea1661-1511-4ed4-ae59-2246f881bcfc)

### Environment
**Device:** `iPhone SE 1st gen`

**iOS version**: `15.7.8`

**App version:** `10.0.1`

**Comment by ali-fareed** [comment]
Platform-wide issues should be reported to https://bugs.telegram.org
