### ISSUE TITLE
data removing

### ISSUE THREAD

**Issue by MohammadtaghiFarkhondekar** [TelegramMessenger/Telegram-iOS#1181]
HelloThe chat between me and my wife was suddenly deleted this evening. All our photos and content and all our text chats were deleted. This happened on two devices at the same time. This chat is 3 years old and contains our important information and photos, such as engagement, wedding; It is our life and work. Please return our chat to us because our life is only saved in telegram chat. We trust telegram to save our lives. and now i have some data in my telegam but not online , it was download and when i onlin agin it will removing because  in telegram web i dont have any thing. how can i backup my last offline data in my iphone or back my lost data

### Environment
**Device:** `iPhone

**iOS version**: `17.0`

**App version:** `last`

**Comment by ali-fareed** [comment]
Currently, chat export is not implemented. It is possible to manually export messages and media by selecting them one by one and using the external share button (an arrow inside a box). To make sure the app doesn't synchronize while you're doing that, activate a non-existent proxy server (e.g. host: "1", port "1") while in airplane mode.

Even though the chat removal feature is guarded with an explicit confirmation, random activations are still a possibility.
