### ISSUE TITLE
How many more months? Telegram does not allow publishing stories without telegram premium for 2 months.

### ISSUE THREAD

**Issue by daniliammo** [TelegramMessenger/Telegram-iOS#1183]
### Checklist
- [X] I am reporting an issue in existing functionality that does not work as intended
- [X] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
Telegram does not allow publishing stories without telegram premium for 2 months.

### Expected Behavior

I think that permission to publish stories without telegram premium should have been a month ago.

### Actual Behavior

Telegram does not allow publishing stories without telegram premium for 2 months.

### Steps to Reproduce
1. Click on the stories button

### Screenshots and Videos 
Remove, if not applicable
![image](https://github.com/TelegramMessenger/Telegram-iOS/assets/67186086/d380255a-5ffe-4345-892d-65ae68ceb6d2)
### Environment
**Device:** `iPad`

**iOS version**: `15`

**App version:** `10.0.1`

**Comment by ali-fareed** [comment]
Platform-wide issues should be reported to https://bugs.telegram.org
