### ISSUE TITLE
How third-party Telegram clients for iOS are supposed to pass App Store review without SMS-codes?

### ISSUE THREAD

**Issue by G-200** [TelegramMessenger/Telegram-iOS#1184]
App Store review team needs to login into the app. When asked to first use official Telegram client to receive code in it, they say that they should be able to login without use of additional apps. Is there a way this can be solved?

**Comment by ali-fareed** [comment]
One option would be to offer an easier way to log into the test environment during the initial setup.

**Comment by Ethan-Conso** [comment]
I am now experiencing this problem, how can I fix it?
