### ISSUE TITLE
Hacking running in the wild and Telegram gives them free reign

### ISSUE THREAD

**Issue by yoelhalb-hitech** [TelegramMessenger/Telegram-iOS#1187]
I will describe here my situation, currently ongoing, and the expected behavior:

**Current Behavior - (Actual ongoing situation)**

1.  Hackers managed to get my sign in one time code
2. They used it to sign in from an IP address in my region, so I assumed it's my desktop app
3. They waited the time period that is required to terminate another session
4. Once the period passed, they threw me out
5. They added other devices, some of them in China/Hong Kong, given that Telegram sends the login code to the existing Telegram sessions
6. When I logged in, I was not able to throw them out, since at this point I was the newer login, so I had to wait
7. I managed to set 2 step verification, but they were not thrown out
8. They noticed that I am inside and threw me out
9. I tried to login in again but I got the message `Too many attempts, retry later`, basically I now had to wait 24 hours
10. I tried contacting Telegram support 1) on the website, 2) via email, and 3) via twitter `@smstelegram` but no one is responding
11. Meanwhile the hackers are trying to spam and hack all of my contacts
12. I tried sending a broadcast on other chat apps to warn all contacts that it is hacked
13. After 24 hours I tried again and I was able to login but they threw me out immediately, this is where I am currently
14. A friend of mine reported a similar thing, and he tried to deactivate the account and it still didn't throw them out.
15. Meanwhile the hackers are continuing to spam and hack people using my account, and I have no way of stopping them
16. If someone they try to spam realizes it's a spam then they back delete the entire chat for the other person

**Expected behavior - (each number corresponds to the number in the original situation)** 

4. Throwing out the original number should require sms verification or similar
5. Adding another number should require sms verification, especially if it's overseas
6.
     - Logging in from the original IP address should be able to throw out the other accounts without delay
     - There should be an option to log out _all sessions (including the current one)_ without any delay
     - There should at least be an option to report hacked
7. This is self contradicting:
     - If a new login is not able to throw out the others, because of security, then it should not be able to set 2 step verification either
     - After setting 2 step verification the norm is that all existing connections are getting logged out and have to login again
 9. Telegram should notice that an overseas login is throwing out a login from an IP address that is being used legitimately for the longest time
10. There should be an option somewhere to report an account as hacked, to at least lock the account temporarily
11. 
      - There should be an option for the contacts to report an account as hacked
      - There should be an option like in what's app `Verify Security Code` so that contacts can force a verification that it is not hacked
      - I can understand that telegram support is overloaded with work, but not handling situations like this will give the hackers free reign to hack others, and thus Telegram support requests will grow exponentially... 
12. There should be a way for the owner of the account to warn the other users that the account is hacked
14. Deactivating the account should throw out all sessions
15. Telegram should notice when all of a sudden an IP address of overseas start to chat to all contacts even ones that I never contacted etc. (especially as I assume that the IP address or region of IP addresses is doing it for many others)
16. This is as ridiculous as it goes (and it might cause you lawsuits and legal issues):
     - A person should not be able to delete an entire chat history for the other person without the consent of the other person, there is no such thing on any chat platform, and you already have secret chats, this is ridiculous IMO
     - There should at least be some form of verification that it is the owner of the chat that wants to do it and not a hacker or bot

Please handle it ASAP before all users on Telegram are getting affected, as this is till ongoing.

**Comment by yoelhalb-hitech** [comment]
I finally managed to login but I am unable to throw out the hackers although they are very clear in Hong Kong which I never was at and my telegram was never there, and also they are using versions of Telegram that I never used.

Your system should have same basic rules before allowing hackers in hacking to throw me out while preventing me from throwing them out

See attached screenshots, you can also clearly see the IP addresses of the hackers.

![Screenshot_20230905-032100_Telegram.jpg](https://github.com/TelegramMessenger/Telegram-iOS/assets/92554300/7c5e87fd-2c19-4c15-bb29-2a95b3236b13)

![Screenshot_20230905-034746_Telegram.jpg](https://github.com/TelegramMessenger/Telegram-iOS/assets/92554300/2ab7a3ef-6a40-443d-b154-d14d673dd0ef)

![Screenshot_20230905-034752_Telegram.jpg](https://github.com/TelegramMessenger/Telegram-iOS/assets/92554300/3bc8b02f-7fd3-4e9c-b283-2bbf29f51587)

![Screenshot_20230905-034757_Telegram.jpg](https://github.com/TelegramMessenger/Telegram-iOS/assets/92554300/6e21ca22-8deb-4bf8-a63b-1649d009887e)

![Screenshot_20230905-034807_Telegram.jpg](https://github.com/TelegramMessenger/Telegram-iOS/assets/92554300/407dc885-52d0-4a5d-ad89-72947c05b6c0)

![Screenshot_20230905-034902_Telegram.jpg](https://github.com/TelegramMessenger/Telegram-iOS/assets/92554300/c93e0e38-8598-4a5d-b591-2b971aabf4a1)

**Comment by yoelhalb-hitech** [comment]
Checking out the Telegram deactivation page (that Telegram provides to permanently delete an account) I noticed a few things:

1. The verification code is being sent only to the Telegram app and NOT by sms or by email which means that any hacker can decide to delete the account

This is even more interesting given that the option to delete the account is not available directly from the Telegram app, which shows that Telegram considers that there is a possibility for the user not to have access to the app when requesting to delete the account, but if so how can he access the security code?

2. But what's a bigger problem is that standard security measures are bypassed, no 2 step verification and no email confirmation, even when the user has set it up explicitly, which obviously just plays into the hand of hackers.

**Comment by yoelhalb-hitech** [comment]
Checking over the 2 step verification and login email settings (now that I have a new login that cannot throw out the hackers) I see that you don't ask for SMS verification when setting these even via a new login that is a potential hacker.

Even though Telegram sends a notification in the app this is of course not enough as a user doesn't always check his phone and of course he doesn't always check the Telegram notifications, so basically a hacker can turn off the 2 step verification or to the contrary set his own password and email and then the user might not be able to login ever.

It looks like you're overrating the extent to which users are supposedly reading the Telegram messages, users don't read it either because they're away from Telegram for a while or simply don't feel the need to look at it.

No other accepted software or website allows to change passwords or emails without entering some identification (such as an existing password etc. which in the case of Telegram should be something like a SMS notification), and no software assumes that just because someone is logged in must be that he is authorized to set/change a password.

Even the most stupid blog or website won't allow to change a password without first providing the original password even though the user is legitimately logged in.

Relying solely on a message sent to the account (and after the fact) is definitely not inline with standard security practices, especially when you're considering a new login to be a potential hacker.

**Comment by ali-fareed** [comment]
Could you share the e-mail address you used to contact support?

**Comment by yoelhalb-hitech** [comment]
I am not comfortable sharing on a public forum my email address.

Fortunately I was able to login without them realizing (might be due to the fact that I logged in from a different IP address as they themselves use IP addresses in the USA see attached images, I actually found that they saved a screenshot of my original IP address to be able to compare a new login with it) and after waiting 24 hours I was able to throw them out.

I notified support as well as the smstelegram twitter account that I got my account back.

However the issues that I described still stand and actually at this point its more an issue for Telegram than for me...

Note that another thing that I did is that as soon as I logged in I immediately deleted the message that Telegram sends in to notify of a login so they shouldn't notice it, I've also noticed that they pinned the Telegram message chat to the top so they should be able to notice me logging in.

(Someone actually suggested to me that I should make a spamming bot to spam them so they shouldn't notice the login message, I didn't do that though...)

Which brings me to a few more issues:

1) any new login can delete all login messages sent by Telegram (even supposedly deleting it for Telegram) which obviously means that you CANNOT rely on it as a medium to secure Telegram.

2) This is besides there might be many reasons why a person should not notice it, especially if he didn't pin the Telegram message chat to the top (as the hackers did), for example if he has a lot of messages incoming, or is being spammed by a bot, or is simply away from the app for 24 hours, or made a habit of ignoring the messages.

No respectable software should rely on passive notifications (and after the fact), would Google allow anyone to change the password without providing the existing passord just because they send an email after the fact? Or even send 2 step verification to an existing email? Would Amazon allow to make changes to the account and just pop up a notification after?

They don't, true they also send an email after the fact as another layer of protection, but they first require some form of verification OUTSIDE of the account.

Speaking now to a friend that lost his account to hackers, he told me how fortunate I am that the hackers didn't set 2 step verification as he actually is no longer able to login since the hacker of his account set 2 step verification on his account.

Guys you gotta do something ASAP, no point in making end to end encryption if hackers can easily get access to the account.

Note that a 5 digit passcode isn't much security in the first place, suppose a hacker selects a random code and tries it on a million phone numbers, he should succeed in average around 50 times at least

![Screenshot_20230906-003640_Telegram.jpg](https://github.com/TelegramMessenger/Telegram-iOS/assets/92554300/d466bcaf-7783-4a9f-a29d-860370ca9198)

![Screenshot_20230906-003629_Telegram.jpg](https://github.com/TelegramMessenger/Telegram-iOS/assets/92554300/89139542-47da-4796-a9b5-a2c01676ff6e)

**Comment by yoelhalb-hitech** [comment]
Thinking about the option of deleting the ebtire chat history for the other party, it's just stunning to watch how you went from not being unable to unsend a message after a short while to being able to delete the entire chat history for the other party even years and years of messages that the other party sent and from the other persons device.

Do you think it's even ethical for a person to be able to have his messages deleted by the other party? Did anyone consent to that? Why would a person continue to use Telegram if all his messages can be wiped at any time?

The next logical step of course will probably be that any participant in a group (not even an admin) should be able to wipe the entire chat history of the group for all the members and on their own devices, why not? Actually you do have already that feature for the admin and I was already bitten by it and now I know that anything important I have to copy over to "saved messages".

There should be at least a setting to opt out of this behavior or at least ask for consent of the user, should I even be able to delete all emails that I sent to someone? Should I be able to delete their emails on their devices just because I was the recipient and I decided to deleted it?

Maybe this feature has some value for hackers and criminals but the average layman doesn't need it, to the contrary it makes Telegram unusable.

**Comment by ali-fareed** [comment]
Platform-wide issues and suggestions belong to https://bugs.telegram.org

**Comment by yoelhalb-hitech** [comment]
Ok I copied it over.

Fortunately I manged to get already my account back so I was able to report it there (as you need to have access to your account in order to report there... once again another thing by Telegram that hinders reporting hacking...)

**Comment by evjsev** [comment]
I have similar thing, but that hapend from my desktop portable version, first i was can`t use my local code to unlock on pc, something without sesion just try ask to connect on phone, and then suddenly all session just terminated, i have relogin from my phone and still is ok, , but i dont know where to find problem on pc or maybe there is a more problem will be with my accout.
Maybe there vulnerability in app for desktop.... And also maybe in web browser will be all fine ?!

**Comment by AlbertoGuerreroMartin** [comment]
@yoelhalb-hitech I couldn't agree more with all you've said. I'm currently under the same situation that you where in 2023, 2 years later and nothing has been fixed. A hacker managed to access my account yesterday, and somehow tricked telegram to think that he was the older session, and kicked me out of all my devices. Since yesterday I've been kicked out two times, and "fortunately" I've always been able to login again, but 11 hours have passed since my last login and I still can't terminate the attacker session. I've tried everything I can think of, and of course I've written to the Telegram support (4 times so far), and I haven't even receive a damn response from the support team.

I can't believe that Telegram ignores situations like this, the current security design it's literally a bed of roses for hackers, but the landing page of https://telegram.org/ still defines Telegram as "Secure. Telegram keeps your messages safe from hacker attacks.". Well, I hace a hacker with access to all of my messages, contacts, media, files, etc, for more than 24 hours, and no one at Telegram seems to care. I know this comment won't solve nothing, I just have so much frustration an desperation, and I've just seen this issue and couldn't agree more with it

I'll keep waiting and crossing fingers to not be kicked out of my session until 24 hours have passed, and I'll keep spamming Telegram support form, hoping that someone reads one of my reports and helps me out... Anyway, thanks @yoelhalb-hitech for all your comments, at least it's comforting to know that I'm not the only one outraged by these security holes.

**Comment by SergejKiller** [comment]
Millions literally millions of accounts are hijacked and Telegram security doesn't let the original account owners to use their accounts.
The approach is quite simple, run voting and trick users to enter their mobile number and telegram sign-in code pretending it's a vote confirmation. (Alternatively just randomly attempt to sign-in entering random phone numbers and security code (we were able to signing into 1 random telegram account once every 100minutes on average.
Then log-in into their account and kick them out after 24 hour (most users don't really know what's just happened).
Once the original owner is kicked,  just spam the login page until the account get automatically blocked so that the owner cannot even attempt to login. They will always see "Too many attempts" error. Sometimes the original owner is able to login, but the hijacker has 24 hours to safely kick the owner. and spam the account sign-in page until the account sign-in is blocked again.

At this point it doesn't really matter that you own the phone number and can confirm the ownership via SMS. You will never be ale to use your account as the nice Telegram security protects hijackers, not the owners.

**Comment by blind-oracle** [comment]
@SergejKiller same thing happened to my wife's account and there's really no way out of it. I was even able to change 2FA password using recovery e-mail but that doesn't kick the old sessions out. And as soon as I login then the hacker's script kicks me out.

Support doesn't react at all.

**Comment by SettSlayer** [comment]
just came here to say 2026 and this problem still on-going.. like wtf is the use of phone number / email if we can't recover / terminate other devices! what kind of security is this! the hacker just logged me out after waiting like 15 hours.. i have to wait again for 2024 while i see my chat history/bots that i'm using for trading getting accessed and if i had money in there they could just withdraw it.. till when telegram will ignore that issue! and ofc there is no support to help us.

**Comment by blind-oracle** [comment]
Yes, I wonder how should I prove that I own an account if I have access to the phone, 2FA password and an e-mail.

But I can't recover access to the account even with all this because the scriptkiddie just kicks my new session out.

**Comment by SettSlayer** [comment]
> Yes, I wonder how should I prove that I own an account if I have access to the phone, 2FA password and an e-mail.
> 
> But I can't recover access to the account even with all this because the scriptkiddie just kicks my new session out.

they keep kicking me out every like 1/1.5 hours from diff ips.. like wtf

**Comment by amex3178-cpu** [comment]
Link

**Comment by JayeshBaranwal** [comment]
Who knows maybe they themselves are involved in this kind of shady hacking, cuz it's happening to me too lmao 🥲 and it's April 2026 btw soo yess nothing changed, maybe they just don't care or they themselves are involved in this shady business 😕

**Comment by vishavkohal** [comment]
The same thing happened with me too, at the end I just deleted the account. though I lost all my data but atleast they won't be able to use my phone number.
