### ISSUE TITLE
BazelDependencies throwing: no provisioning profile was found named 'iOS Team Provisioning Profile: org.{id}.Telegram'

### ISSUE THREAD

**Issue by kevinyou77** [TelegramMessenger/Telegram-iOS#1196]
### Checklist
- [ ] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
Describe the issue that you are experiencing
Generated the project with:
python3 build-system/Make/Make.py \
    --cacheDir="$HOME/telegram-bazel-cache" \
    generateProject \
    --configurationPath=build-system/template_minimal_development_configuration.json \
    --xcodeManagedCodesigning --disableProvisioningProfiles

Did all the steps required in README, but to no avail. I'm trying to run the app in simulator which shouldn't require the Apple Developer Account. Any help would be appreciated, thank you!

### Expected Behavior
Should compile successfully

### Actual Behavior
Bazel dependencies error: no provisioning profile was found named 'iOS Team Provisioning Profile: org.{id}.Telegram'

### Steps to Reproduce
1. Follow the steps required in README
2. Try to regenerate the project with
python3 build-system/Make/Make.py \
    --cacheDir="$HOME/telegram-bazel-cache" \
    generateProject \
    --configurationPath=build-system/template_minimal_development_configuration.json \
    --xcodeManagedCodesigning --disableProvisioningProfiles
3. Try to run the project
4. BazelDependencies will throw an error

### Environment
**Device:** iPhone 14 Pro Simulator
**App version:** Latest Master
Xcode 14.2

**Comment by ali-fareed** [comment]
Could you post your `template_minimal_development_configuration.json` here?
