### ISSUE TITLE
Can't see what I'm typing in caption when sending media

### ISSUE THREAD

**Issue by Neurotoxin001** [TelegramMessenger/Telegram-iOS#1198]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
The text box for entering a caption before sending a photo or video has gone white. The font is white there too.

### Expected Behavior
Text should be black

### Actual Behavior
Text is white

### Steps to Reproduce
1. Write caption before sending media
2. Caption field and text is white
3. You can't see what you're typing

### Screenshots and Videos 

https://github.com/TelegramMessenger/Telegram-iOS/assets/39812401/bafb7bb4-020a-459e-b307-3e600be547ab

### Environment
**Device:** `iPhone 13 Pro`

**iOS version**: `16.6.1`

**App version:** `10.0.3`

**Comment by Marc66** [comment]
Also experienced this on an iPad 5th gen (white text in white text box) but not on my iPhone 14 (white text in dark text box)
This bug seems to have appeared in the last release

**Comment by Neurotoxin001** [comment]
Fixed in 10.1
