### ISSUE TITLE
Please, help me with new issues

### ISSUE THREAD

**Issue by Nazarash** [TelegramMessenger/Telegram-iOS#12]
Showing All Messages
 /Users/Nazar/Downloads/Telegram-iOS-master/Telegram-iOS/Config-AppStore.xcconfig:1: could not find included file '../../Telegram-iOS-Shared/Config-AppStore.xcconfig' in search paths (in target 'Watch Extension')

**Comment by PengsreangSrun** [comment]
After I downloaded this project, I have encountered this above problem too. Please help us to solve this

**Comment by jalalimehdi** [comment]
Hi
Did you solve this problem?
please guide me

**Comment by ichelsearay** [comment]
change to Config-Fork.xcconfig
