### ISSUE TITLE
[Feature Request] Option to disable the vibration for share menu

### ISSUE THREAD

**Issue by Frederick888** [TelegramMessenger/Telegram-iOS#120]
Since a recent version, Telegram started to vibrate for a split second after every successful share via the share menu. I've never seen such a behaviour in other apps and tbh this is slightly irritating to me.

Apologies if there's already a switch for this (I quickly went through the settings without finding one), otherwise it'd be really nice to make it configurable.

**Comment by laktyushin** [comment]
It doesn't vibrate when sharing in the app anymore.
