### ISSUE TITLE
Crash when open Telegram Application

### ISSUE THREAD

**Issue by Amirnlz** [TelegramMessenger/Telegram-iOS#1208]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
Crash when open Telegram application and kick out

### Expected Behavior
Open without any issues

### Actual Behavior
crash on open

### Steps to Reproduce
1. update to 10.1
2. open app

### Environment
**Device:** `iPhone X`

**iOS version**: `16.6.1`

**App version:** `10.1`

**Comment by ShayanTheNerd** [comment]
I’vs had the same problem on iPhone 12 ever since I updated to iOS 17. Please fix the problem ASAP.

**Comment by ho3inpgmer** [comment]
i have same problem in iPhone 11 with IOS 16.7. 
Please fix the problem as soon as possible
tnx

**Comment by LionisIAm** [comment]
Iphone 12 pro max, iOS 17, same

**Comment by daniyousefifar** [comment]
I have the same problem in iPhone XS Max with iOS 17.

**Comment by mo1ein** [comment]
I have the same problem in iPhone 13 and ios 17.0.1

**Comment by ShayanTheNerd** [comment]
> ### Checklist
> * [x]  I am reporting an issue in existing functionality that does not work as intended
> * [x]  I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)
> 
> ### Description
> Crash when open Telegram application and kick out
> 
> ### Expected Behavior
> Open without any issues
> 
> ### Actual Behavior
> crash on open
> 
> ### Steps to Reproduce
> 1. update to 10.1
> 2. open app
> 
> ### Environment
> **Device:** `iPhone X`
> 
> **iOS version**: `16.6.1`
> 
> **App version:** `10.1`

The problem seems to be with proxies on version 10.1. Uninstalling and reinstalling the app fixed it for me. I'll probably just avoid using proxies until they fix this in the next update.

**Comment by ho3inpgmer** [comment]
> The problem seems to be with proxies on version 10.1. Uninstalling and reinstalling the app fixed it for me. I'll probably just avoid using proxies until they fix this in the next update.

Yes, apparently you right. uninstalling the app fixed the problem for me, too. but i can't use proxies anymore, i hope they fix this problem

**Comment by Hosiyume** [comment]
#1088

**Comment by ali-fareed** [comment]
Check out the latest TestFlight build.

**Comment by Hosiyume** [comment]
> Check out the latest TestFlight build.

link？

**Comment by ali-fareed** [comment]
This should be fixed in 10.1.1.
