### ISSUE TITLE
AppStore Reject

### ISSUE THREAD

**Issue by anvar0522** [TelegramMessenger/Telegram-iOS#1215]
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
I have telegram version 9.5.3 App Store rejecting this app because of web deleting test account, cannot delete test account
Please if 9.5.3 has not flow delete account what minimum version of telegram support delete account in app

### Expected Behavior
Should to accept

### Actual Behavior
Reject from apple

**App version:** `9.5.3`

**Comment by shivanraptor** [comment]
why do you submit an old version to the App Store?
