### ISSUE TITLE
Feature Request - Improved Chat Preview Layout

### ISSUE THREAD

**Issue by qiangweihewu** [TelegramMessenger/Telegram-iOS#1221]
Hey there!

I hope this message finds you well. I've been using telegram and have had a great experience so far. I would like to suggest a feature that, in my opinion, would enhance the overall user experience.

Currently, the preview content for each chat dialogue displays three lines most time, including the sender/group/channel name, and one or two lines of the message content. I appreciate the detailed information, but I find that this two-line content layout can sometimes appear cluttered and less visually appealing.

My feature request is to modify the chat preview layout so that it only shows a single, prominent line for the sender's name/group name/channel name, along with a concise line for the message content. In the case of group chats, I suggest combining the sender's name and message content on the same line for a cleaner and more streamlined appearance.

I believe that implementing this change would contribute to a more aesthetically pleasing and user-friendly interface. Thank you for considering my suggestion, and I appreciate your ongoing efforts to improve telegram.

Best regards

**Comment by ali-fareed** [comment]
Suggestions should be filed at https://bugs.telegram.org
