### ISSUE TITLE
Xcode 15  build error

### ISSUE THREAD

**Issue by alirezarabiei7239** [TelegramMessenger/Telegram-iOS#1223]
### Description
after successful build from terminal when i run the project i got this error :

Unable to discover `swiftc` command line tool info: Could not parse Swift versions from: Swift/ErrorType.swift:200: Fatal error: Error raised at top level: Error Domain=NSCocoaErrorDomain Code=4 "The file “swiftc” doesn’t exist." UserInfo=
{NSFilePath=swiftc}

### Environment
**Device:** `simulator`

**Xcode version:** `15.0`

**iOS version**: `17.0`

**App version:** `10.0.3`

**Comment by ali-fareed** [comment]
Could you try 10.1.1?

**Comment by alirezarabiei7239** [comment]
sure I will try and send the result.

**Comment by alirezarabiei7239** [comment]
@ali-fareed 
I see the last version is 1.0.3 
where can I find 10.1.1 ?

**Comment by ali-fareed** [comment]
All release versions are tagged at https://github.com/TelegramMessenger/Telegram-iOS/tags

**Comment by alirezarabiei7239** [comment]
I teste 10.1.1 but i got same error

Unable to discover `swiftc` command line tool info: Could not parse Swift versions from: Swift/ErrorType.swift:200: Fatal error: Error raised at top level: Error Domain=NSCocoaErrorDomain Code=4 "The file “swiftc” doesn’t exist." UserInfo={NSFilePath=swiftc}

<img width="720" alt="image" src="https://github.com/TelegramMessenger/Telegram-iOS/assets/10250441/da2f2caa-9e7f-4c05-883a-524a57e9e6f9">

**Comment by alirezarabiei7239** [comment]
@ali-fareed any update here to help me ?

**Comment by DhruvGovani** [comment]
@ali-fareed Anything that could help here?
