### ISSUE TITLE
How to create folders with different colors?

### ISSUE THREAD

**Issue by twisturn** [TelegramMessenger/Telegram-iOS#123]
How to create folders with different colors?
![1566207343788](https://user-images.githubusercontent.com/17715937/63255253-ea6f4b00-c2a7-11e9-8673-1478f4465749.jpg)

**Comment by fanyuexiang** [comment]
creat a new folder in finder then drag it in your project

**Comment by twisturn** [comment]
@fanyuexiang It's not valid

**Comment by laktyushin** [comment]
Check 'Provides Namespace' for a folder in Attributes Inspector.
