### ISSUE TITLE
WidgetKit extenstion made Required in .ipa build so can't install on iOS < 14

### ISSUE THREAD

**Issue by vritme** [TelegramMessenger/Telegram-iOS#1231]
Steps to Reproduce:

I try to install Telegram 9.6.3.ipa from releases with 3 different methods, always have the same error - can't install app because unsupported on iOS 13 extenstion WidgetKit made "Required" during the build instead of "Optional".

This could be checked in Telegram.app/PlugIns/WidgetExtension.appex/Info.plist/MinimumOSVersion - there is "14.0" value.

Since Telegram 9.6.3.ipa is supposed to work on iOS 13 also, I kindly ask you to attach additional .ipa build as an edit to https://github.com/TelegramMessenger/Telegram-iOS/releases/tag/build-25780 or somewhere else in the releases or any other public hosting, because I do now have an ability to launch Xcode environment to make the new built my self right now.

The solution is from developer.apple.com/forums - https://developer.apple.com/forums/thread/653110.

Screenshots and Videos:
![1](https://github.com/TelegramMessenger/Telegram-iOS/assets/42464402/880ae18d-d714-44ef-ab76-31fd46a726f2)
![2](https://github.com/TelegramMessenger/Telegram-iOS/assets/42464402/edb23514-3c57-4371-8047-6dc72f585357)
![3](https://github.com/TelegramMessenger/Telegram-iOS/assets/42464402/8ac3fdc8-dd6f-4609-acde-f04c0182f4ba)
![4](https://github.com/TelegramMessenger/Telegram-iOS/assets/42464402/ce2d6bee-0e74-4957-9c71-168490966149)
![5](https://github.com/TelegramMessenger/Telegram-iOS/assets/42464402/725119b1-7b8e-4775-b124-5fa325ab7240)
![6](https://github.com/TelegramMessenger/Telegram-iOS/assets/42464402/7153c83f-367a-46ad-8d91-2fb1fbf1444e)
Environment:
Windows: iMazing, SideLoadly
iOS: AppSync

Device: iPhone SE

iOS version: 13.3.1

App version: 9.6.3

**Comment by ali-fareed** [comment]
It is strongly advised to use the latest available build.

**Comment by vritme** [comment]
Will it work if I manage to compile 4.6.3 build on Xcode 14.2 with WidgetKit extension made optional?

**Comment by makarakimleang** [comment]
Open telegram

**Comment by vritme** [comment]
> Open telegram

?

**Comment by vritme** [comment]
I think Reproducible Builds is a good effort and should not be abandoned.

**Comment by makarakimleang** [comment]
Agreed!

**Comment by ali-fareed** [comment]
> Will it work if I manage to compile 4.6.3 build on Xcode 14.2 with WidgetKit extension made optional?

It could work.

**Comment by vritme** [comment]
> > Will it work if I manage to compile 4.6.3 build on Xcode 14.2 with WidgetKit extension made optional?
> 
> It could work.

I managed to compile .ipa from source my self.
And get the same error with WidgetKit extension.

How can I properly set WidgetKit extension to be optional in order to install it on iOS 13?
It probably should be somewhere in BUILD file or other bazel configuration files, not in the xcode gui?

Or if it should be configured in the Xcode, then to what target should I add WidgetKit.framework extension as optional?
To target "WidgetExtension"?
![image](https://github.com/TelegramMessenger/Telegram-iOS/assets/42464402/8a742025-e066-4933-9afa-1ae30f653a83)

**Comment by vritme** [comment]
There is also a code fragment in Telegram/BUILD which seems to be strongly related to this issue, lines 1390-1443:

`genrule(
    name = "SetMinOsVersionWidgetExtension",
    cmd_bash =
"""
    name=WidgetExtension.appex
    cat $(location PatchMinOSVersion.source.sh) | sed -e "s/<<<MIN_OS_VERSION>>>/14\\.0/g" | sed -e "s/<<<NAME>>>/$$name/g" > $(location SetMinOsVersionWidgetExtension.sh)
""",
    srcs = [
        "PatchMinOSVersion.source.sh",
    ],
    outs = [
        "SetMinOsVersionWidgetExtension.sh",
    ],
    executable = True,
    visibility = [
        "//visibility:public",
    ]
)

ios_extension(
    name = "WidgetExtension",
    bundle_id = "{telegram_bundle_id}.Widget".format(
        telegram_bundle_id = telegram_bundle_id,
    ),
    families = [
        "iphone",
        "ipad",
    ],
    infoplists = [
        ":WidgetInfoPlist",
        ":VersionInfoPlist",
        ":RequiredDeviceCapabilitiesPlist",
        ":BuildNumberInfoPlist",
        ":AppNameInfoPlist",
    ],
    minimum_os_version = minimum_os_version, # maintain the same minimum OS version across extensions
    ipa_post_processor = ":SetMinOsVersionWidgetExtension",
    #provides_main = True,
    provisioning_profile = select({
        ":disableProvisioningProfilesSetting": None,
        "//conditions:default": "@build_configuration//provisioning:Widget.mobileprovision",
    }),
    deps = [
        ":WidgetExtensionLib",
    ],
    frameworks = [
        ":SwiftSignalKitFramework",
        ":PostboxFramework",
        ":TelegramCoreFramework",
    ],
    visibility = [
        "//visibility:public",
    ]
)`

**Comment by vritme** [comment]
There is also a code fragment in Telegram/BUILD, which seems to be related to this issue of WidgetExtension and iOS as a requirement to run, lines 1390-1443:

> genrule(
    name = "SetMinOsVersionWidgetExtension",
    cmd_bash =
"""
    name=WidgetExtension.appex
    cat $(location PatchMinOSVersion.source.sh) | sed -e "s/<<<MIN_OS_VERSION>>>/14\\.0/g" | sed -e "s/<<<NAME>>>/$$name/g" > $(location SetMinOsVersionWidgetExtension.sh)
""",
    srcs = [
        "PatchMinOSVersion.source.sh",
    ],
    outs = [
        "SetMinOsVersionWidgetExtension.sh",
    ],
    executable = True,
    visibility = [
        "//visibility:public",
    ]
)

> ios_extension(
    name = "WidgetExtension",
    bundle_id = "{telegram_bundle_id}.Widget".format(
        telegram_bundle_id = telegram_bundle_id,
    ),
    families = [
        "iphone",
        "ipad",
    ],
    infoplists = [
        ":WidgetInfoPlist",
        ":VersionInfoPlist",
        ":RequiredDeviceCapabilitiesPlist",
        ":BuildNumberInfoPlist",
        ":AppNameInfoPlist",
    ],
    minimum_os_version = minimum_os_version, # maintain the same minimum OS version across extensions
    ipa_post_processor = ":SetMinOsVersionWidgetExtension",
    #provides_main = True,
    provisioning_profile = select({
        ":disableProvisioningProfilesSetting": None,
        "//conditions:default": "@build_configuration//provisioning:Widget.mobileprovision",
    }),
    deps = [
        ":WidgetExtensionLib",
    ],
    frameworks = [
        ":SwiftSignalKitFramework",
        ":PostboxFramework",
        ":TelegramCoreFramework",
    ],
    visibility = [
        "//visibility:public",
    ]
)

Should anything be changed here?
