### ISSUE TITLE
Failure on running telegram in Xcode

### ISSUE THREAD

**Issue by MohShMehr** [TelegramMessenger/Telegram-iOS#1232]
After successful build with Bazel and running the command in (read me file) I want to run the app in the simulator iPhone 14 pro max in Xcode but I get an error  
<img width="1792" alt="Screenshot 2023-10-07 at 12 12 49 PM" src="https://github.com/TelegramMessenger/Telegram-iOS/assets/30681940/7aae1c53-d49a-4974-a324-6b1e2cd9d5ed">

**Simulator:** `iPhone 14 pro max`
**App version:** `latest`

Could you please help me to fix it?

**Comment by ali-fareed** [comment]
Are there any messages in the build log?

**Comment by MohShMehr** [comment]
> Are there any messages in the build log?

The bazel build failed, please check the report navigator, which may have more context about the failure.
/var/tmp/_bazel_morz/45deaccb0469cfbf8233174b22fceab3/rules_xcodeproj.noindex/build_output_base/execroot/__main__/clang:1:1 linker command failed with exit code 1 (use -v to see invocation)

**Comment by xiky** [comment]
same issue 

```
ERROR: /Users/yyy/Telegram-iOS/Telegram/BUILD:811:14: Linking Telegram/MtProtoKitFramework_bin failed: (Exit 1): wrapped_clang failed: error executing command (from target //Telegram:MtProtoKitFramework)
  (cd /private/var/tmp/_bazel_yyy/15b401d661c18786c9ddb8a9894537c9/rules_xcodeproj.noindex/build_output_base/execroot/__main__ && \
  exec env - \
    APPLE_SDK_PLATFORM=iPhoneSimulator \
    APPLE_SDK_VERSION_OVERRIDE=16.4 \
    PATH=/bin:/usr/bin \
    RELATIVE_AST_PATH=true \
    XCODE_VERSION_OVERRIDE=14.3.1.14E300c \
    ZERO_AR_DATE=1 \
  external/local_config_apple_cc/wrapped_clang @bazel-out/ios-x86_64-min12.0-applebin_ios-ios_x86_64-dbg-ST-57558e36bc4b/bin/Telegram/MtProtoKitFramework_bin-2.params)
# Configuration: fd9a4c17927284123422db1f23d59f58a76d927a66a11151b49468dbe055c4d0
# Execution platform: @local_config_platform//:host
ld: library not found for -ld_classic
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error in child process '/usr/bin/xcrun'. 1
INFO: Elapsed time: 0.476s, Critical Path: 0.13s
INFO: 13 processes: 13 internal.
FAILED: Build did NOT complete successfully
error: The bazel build failed, please check the report navigator, which may have more context about the failure.
```

Intel  MacBook Pro 2019
MacOS Ventura 13.2 (22D49)
Xcode Version 14.3.1 (14E300c)

Is this information useful?

**Comment by MohShMehr** [comment]
Thanks for your help but when I used that previous error was resolved but now I have this error
/Users/morz/work/ios/Telegram1o11/Telegram-iOS/submodules/AsyncDisplayKit/Source/PublicHeaders/AsyncDisplayKit/ASRecursiveUnfairLock.h:70:3 'OSSpinLock' is deprecated: first deprecated in iOS 10.0 - Use os_unfair_lock() from <os/lock.h> instead [-Werror,-Wdeprecated-declarations]
Could you please help me to resolve this?

**Comment by xiky** [comment]
#949

**Comment by ali-fareed** [comment]
The error should not be present when building for arm64.
