### ISSUE TITLE
xcode 15 run error

### ISSUE THREAD

**Issue by alirezarabiei7239** [TelegramMessenger/Telegram-iOS#1235]
Description
after successful build from terminal when i run the project i got this error :

Unable to discover swiftc command line tool info: Could not parse Swift versions from: Swift/ErrorType.swift:200: Fatal error: Error raised at top level: Error Domain=NSCocoaErrorDomain Code=4 "The file “swiftc” doesn’t exist." UserInfo=
{NSFilePath=swiftc}

Environment
Device: simulator

Xcode version: 15.0

iOS version: 17.0

App version: 10.0.3 and 10.1.1
<img width="720" alt="271825126-da2f2caa-9e7f-4c05-883a-524a57e9e6f9" src="https://github.com/TelegramMessenger/Telegram-iOS/assets/10250441/f634e971-0e9f-423b-8087-f72f9ba7d5bf">

**Comment by w1217358955** [comment]
MacOS sonoma 14.0
Xcode version: 15.0
iOS version: 17.0

same error

**Comment by ali-fareed** [comment]
What does `xcode-select -p` print?

**Comment by w1217358955** [comment]
/Desktop/xcode/Xcode15.0.app/Contents/Developer

**Comment by w1217358955** [comment]
> What does `xcode-select -p` print?

/Desktop/xcode/Xcode15.0.app/Contents/Developer

**Comment by alirezarabiei7239** [comment]
/Applications/Xcode.app/Contents/Developer

**Comment by williamleecn** [comment]
clean all build file: 
1. run `python3 build-system/Make/Make.py clean`
2. delte`telegram-bazel-cache`

rebuild bazel

but build `third-party/libjxl` occur error:
```
-- Performing Test JXL_HWY_DISABLED_TARGETS_FORCED
-- Performing Test JXL_HWY_DISABLED_TARGETS_FORCED - Failed
-- Compiled IDs C:AppleClang, C++:AppleClang
-- Disabled AVX512 (set JPEGXL_ENABLE_AVX512 to enable it)
-- Disabled AVX512_ZEN4 (set JPEGXL_ENABLE_AVX512_ZEN4 to enable it)
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Performing Test ATOMICS_LOCK_FREE_INSTRUCTIONS
-- Performing Test ATOMICS_LOCK_FREE_INSTRUCTIONS - Failed
-- Performing Test ATOMICS_IN_LIBRARY
-- Performing Test ATOMICS_IN_LIBRARY - Failed
CMake Error at cmake/FindAtomics.cmake:49 (message):
  Neither lock free instructions nor -latomic found.
Call Stack (most recent call first):
  CMakeLists.txt:254 (find_package)

```

**Comment by alirezarabiei7239** [comment]
@ali-fareed 
can you please help me ?

**Comment by andy-sheng** [comment]
1.  make sure your code base is up  to date
2.  try `git submodule update --recursive` 
3. clean build file `python3 build-system/Make/Make.py clean` `telegram-bazel-cache`
4. build again

In my case, I believe some outdated /  bazel related submodules cause these errors.

**Comment by imooccodejesse** [comment]
I am encountering the same error.  Has this been solved yet?

**Comment by DhruvGovani** [comment]
I am also facing this error. I have tried everything mentioned above. Nothing seems to be working.

**Comment by infinigent-solutions** [comment]
I'm also facing the same issue

**Comment by 315567599** [comment]
Nothing above working.

**Comment by naguilarp** [comment]
Worked for me after 10 days, just opening the Xcode and changing Project Format to 14.0 for Pods and 15.0 to my app folder. Plus signing.
So weird...but yeah, worked.

**Comment by VinceJee** [comment]
same error on macos 15, xcode 16

**Comment by Tilak1028-st** [comment]
same error on macos 15, xcode 16

**Comment by moonagic** [comment]
I suspect that this issue originates from the external compilation system, and it will require the TG team to switch to the new version of Xcode to make some necessary modifications before it can run correctly.

**Comment by hhfssg** [comment]
same error on macos 15, Xcode 16

**Comment by alirezarabiei7239** [comment]
> 3\. telegram-bazel-cache



> Worked for me after 10 days, just opening in the Xcode and changing Project Format to 14.0 for Pods and 15.0 to my app folder. Plus signing. So weird...but yeah, worked.

Hi, how should I do this ?

**Comment by UniqueSilence** [comment]
<img width="1271" alt="截屏2024-12-20 14 04 42" src="https://github.com/user-attachments/assets/2bf5fcd3-c4be-479d-af5c-fc7c61d5cf91" />
xcode 16.1 compiling error 
how to fix it?
