### ISSUE TITLE
[Suggestion] Make stories UI elements configurable

### ISSUE THREAD

**Issue by Keij0** [TelegramMessenger/Telegram-iOS#1240]
Hello,

I don't know if suggestions are answered in this repository, but I will try anyway.

I have been having constant problems with the UI since the stories were introduced.
There are also some people having the same problems already, like within #1209 or #1190.

I think that a good solution to these problems would be introducing a toggle switch to disable the quick action to open the stories ui within settings. Making stories is already accounted for by an icon in the top bar so I guess not all users need the quick action to open the stories UI. I would also like to see a toggle switch to disable opening stories from the Search UI since I think it's veeery overdone and I am left handed so most of the time I click the left side of the result and open the stories by accident. 

I've tried to implement that myself and submit a PR, but I cannot make sense of this codebase. I'm not an iOS developer by trade and don't understand it. Additionally, I don't have a developer account and can't make myself a provisioning profile to build the ipa properly.

**Comment by ali-fareed** [comment]
Feature requests should be filed at https://bugs.telegram.org
