### ISSUE TITLE
Can't install Telegram on iOS < 14 because of WidgetKit

### ISSUE THREAD

**Issue by vritme** [TelegramMessenger/Telegram-iOS#1241]
Related to https://github.com/TelegramMessenger/Telegram-iOS/issues/1231

> > Will it work if I manage to compile 4.6.3 build on Xcode 14.2 with WidgetKit extension made optional?
> 
> It could work.

I managed to compile .ipa from source my self.
And get the same error with WidgetKit extension.

How can I properly set WidgetKit extension to be optional in order to install it on iOS 13?
It probably should be somewhere in BUILD file or other bazel configuration files, not in the xcode gui?

Or if it should be configured in the Xcode, then to what target should I add WidgetKit.framework extension as optional?
To target "WidgetExtension"?
![image](https://github.com/TelegramMessenger/Telegram-iOS/assets/42464402/8a742025-e066-4933-9afa-1ae30f653a83)

There is also a code fragment in Telegram/BUILD, which seems to be related to this issue of WidgetExtension and iOS 14 as a requirement to run, lines 1390-1443:

> genrule(
    name = "SetMinOsVersionWidgetExtension",
    cmd_bash =
"""
    name=WidgetExtension.appex
    cat $(location PatchMinOSVersion.source.sh) | sed -e "s/<<<MIN_OS_VERSION>>>/14\\.0/g" | sed -e "s/<<<NAME>>>/$$name/g" > $(location SetMinOsVersionWidgetExtension.sh)
""",
    srcs = [
        "PatchMinOSVersion.source.sh",
    ],
    outs = [
        "SetMinOsVersionWidgetExtension.sh",
    ],
    executable = True,
    visibility = [
        "//visibility:public",
    ]
)

> ios_extension(
    name = "WidgetExtension",
    bundle_id = "{telegram_bundle_id}.Widget".format(
        telegram_bundle_id = telegram_bundle_id,
    ),
    families = [
        "iphone",
        "ipad",
    ],
    infoplists = [
        ":WidgetInfoPlist",
        ":VersionInfoPlist",
        ":RequiredDeviceCapabilitiesPlist",
        ":BuildNumberInfoPlist",
        ":AppNameInfoPlist",
    ],
    minimum_os_version = minimum_os_version, # maintain the same minimum OS version across extensions
    ipa_post_processor = ":SetMinOsVersionWidgetExtension",
    #provides_main = True,
    provisioning_profile = select({
        ":disableProvisioningProfilesSetting": None,
        "//conditions:default": "@build_configuration//provisioning:Widget.mobileprovision",
    }),
    deps = [
        ":WidgetExtensionLib",
    ],
    frameworks = [
        ":SwiftSignalKitFramework",
        ":PostboxFramework",
        ":TelegramCoreFramework",
    ],
    visibility = [
        "//visibility:public",
    ]
)

Should anything be changed here in BUILD file?

Also one more idea of conditional import from apple developer forum, could it help?

![image](https://github.com/TelegramMessenger/Telegram-iOS/assets/42464402/e9a48128-632a-4b45-8ace-0a0e69934f3e)

Please don't close the issue immediately, the app is currently uninstallable when build from source on iOS < 14 because WidgetKit is unsupported on iOS < 14.

**Comment by ali-fareed** [comment]
It should not be relevant whether the app bundle contains extensions that are not available on older iOS versions, as the OS is designed to ignore them.

Additionally, 9.6.3 is an outdated and thus unsupported release branch.

**Comment by vritme** [comment]
What actions could I try to avoid Widget error while installing on iPhone with iOS 13.3.1?

**Comment by ali-fareed** [comment]
Does it work when installed via App Store?

**Comment by vritme** [comment]
Yes it is working when installed via App Store with version 10.1.2.
Could I check any config files of this version in git repo or on my iPhone in order to try to copy and past them to 9.6.3 source files and the compile?

**Comment by ali-fareed** [comment]
It should just work when built with the relevant Xcode version (the exact version number is located in `versions.json`).

But again, 9.6.3 is an outdated version. It would be much more convenient to debug issues using the latest app version.

**Comment by vritme** [comment]
Commenting WidgetExtension in Telegram/BUILD -> ios_application section did the job.

> extensions = select({
>         ":disableExtensionsSetting": [],
>         "//conditions:default": [
>             ":ShareExtension",
>             ":NotificationContentExtension",
>             ":NotificationServiceExtension",
>             ":IntentsExtension",
>             #":WidgetExtension",
>             ":BroadcastUploadExtension",
>         ],
>     }),


> It should not be relevant whether the app bundle contains extensions that are not available on older iOS versions, as the OS is designed to ignore them.

When installing via AppStore, unsupported extentions for current iOS do not cause issues.
That is not the case when installing via third-party tools, which are the only available methods when compile yourself.



Also there are two extremely important steps misssed it the guide:

1. The need to install Public.cer certificate on your macOS machine from fake-codesigning in order to sign the build.
2. The need to update submodules via "git submodule update --recursive" if there was transition to a certain commit in the past (a version choice) via "git checkout {commit hash}" .
