### ISSUE TITLE
All imported media falls under import date

### ISSUE THREAD

**Issue by 3raxton** [TelegramMessenger/Telegram-iOS#1242]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
When using the media browser, all imported media (in this example a photo or video) is displayed under the same month and year, rather than the initial sent date. However, when viewing the same media / photo / video in a chat, the original date the media was sent is displayed. 

### Expected Behavior
Rather than the media browser displaying the import date, the original date the media was sent should be displayed. It is incredibly challenging to sort through thousands of photos and videos that were sent in previous chats, which have an accurate import date but are displayed under the single month and year they were imported.

### Actual Behavior
Instead of displaying the original date sent in the media browser, the month and year that the chat was imported is displayed in the media browser. 

### Steps to Reproduce
1. Import a WhatsApp or similar chat to Telegram using the Telegram importer
2. Browse through the chat media
3. Note all media displays the date the chat was imported rather than the date it was originally sent
4. Note that if media is viewed in chat, the initially sent / created date is displayed rather than the import date

#### Adequately displayed media dates
![Correct Media Display](https://github.com/TelegramMessenger/Telegram-iOS/assets/20716142/8c93b038-2c6a-435f-8f13-f1060d4e3a67)

#### Incorrectly displayed media dates from previous import
_Please note the date shown in the media browser is February, 2021. However, the date the media was sent is November 3, 2016_

https://github.com/TelegramMessenger/Telegram-iOS/assets/20716142/6ca19c92-a426-4eae-b407-a6d941b1a109

### Environment
**Device:** `iPhone 12 Pro Max`

**iOS version**: `17.0.3`

**App version:** `10.1.2` — this has persisted since `7.4.2`

**Comment by ali-fareed** [comment]
Unfortunately, the app has no data that would allow it to accurately date imported media.

**Comment by 3raxton** [comment]
I disagree, the app has the initial import date of messages and media as it is displayed in the chat. This could be used to display imported media adequately
