### ISSUE TITLE
MKV vids aren't supported!

### ISSUE THREAD

**Issue by Treata11** [TelegramMessenger/Telegram-iOS#1246]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
Videos in mkv format aren't supported & don't play in Telegram.
When a video in Matroska format is downloaded, The video playback is only a single frame of the thumbnail & the audio playing.
It gets really annoying when the video is shared **in a quick way** & since the format _isn't displayed_ on the compressed vid, you'll end up downloading dozens of bytes, only to see the thumbnail with the audio.

### Expected Behavior
Though the **Matroska** isn't natively supported by apple SDKs, when Telegram allows users to share this format on its platform, it must've had support for .mkv on the app for iOS users too.

### Actual Behavior
The video freezes at a single frame & you are only able to hear the audio.

### Steps to Reproduce
1. Share a video in `.mkv`, `.mk3d`, `.mka` or `.mks`
2. Try playing the vid on any Apple platform.

### Environment
**Device:** `iPhone/iPad/Mac`

**iOS version**: `17.0.3`

**App version:** `10.0.3`

**Comment by ali-fareed** [comment]
Which codec does the video use?

**Comment by Treata11** [comment]
@ali-fareed `Google/On2's VP9 Video (VP90)`

**Comment by ali-fareed** [comment]
iOS does not currently support VP9 playback.

**Comment by PeterNespesny** [comment]
> iOS does not currently support VP9 playback.
iOS supports video stickers and emoji which are in VP9. Why not videos?
https://core.telegram.org/stickers/webm-vp9-encoding

**Comment by ali-fareed** [comment]
Video stickers and video emojis are re-encoded on the device into a custom format designed for quick display of 3-second low-resolution videos. The in-app video player depends on hardware support to decode the full-size videos. Currently, there is no general VP9 hardware decoding support available on iOS.

**Comment by Treata11** [comment]
@ali-fareed 
What does it exactly mean
> "Currently, there is no general VP9 hardware decoding support available on iOS."?

There are dozens of media player apps currently _available_ on the appStore that support VP9 decoding. 
There are _third-party libraries_ for this purpose & there should be other workarounds ...
In my opinion, this situation is a huge inconvenience for users.

**Comment by ali-fareed** [comment]
The Telegram app relies on the iOS video decoding pipeline. iOS does not provide hardware-accelerated VP9 decoding (except for apps approved by Apple, like YouTube).

It is possible to implement software VP9 decoding, but that would require a complete, low-level rewrite of the video player, which is a complex task. Given that mobile apps only produce H264/MP4, the task is not prioritized at the moment.

**Comment by Treata11** [comment]
@ali-fareed 
عزیز اگه هموطنی و ما تا الآن اینگلیسی حرف زدیم :) و اگه از نظرت اشکالی نداره همین تلگرام می‌شه یه آی‌دی، چیزی ازت داشته باشم یه چندتا سوال بپرسم؟
