### ISSUE TITLE
The message I send will turn into the message sent by the other party.

### ISSUE THREAD

**Issue by illusionJP** [TelegramMessenger/Telegram-iOS#1249]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
Describe the issue that you are experiencing

The message you send will turn into the message sent by the other party.

### Expected Behavior
Tell us what should happen
just like message sent on Android
### Actual Behavior
Tell us what happens instead

### Steps to Reproduce
1. 
2. 
3. 

### Screenshots and Videos 
Remove, if not applicable

### Environment
**Device:** `iPhone15pro Max`

**iOS version**: `17.0.3X`

**App version:** 

> `10.1.2

https://github.com/TelegramMessenger/Telegram-iOS/assets/120254464/1f9121c7-f2ea-4f3b-ac69-b9722f8dbd62

**Comment by illusionJP** [comment]
And I can’t delete the messages I sent. Everything works fine on Android.

**Comment by ali-fareed** [comment]
This should be fixed in 10.2.3.
