### ISSUE TITLE
I haven’t received my recovery email

### ISSUE THREAD

**Issue by armin2200** [TelegramMessenger/Telegram-iOS#1252]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
I want to turn off my two-step verification code but I forgot the password so I requested to send the code to my recovery email but I haven’t received any email from Telegram, I checked my junk email, and it wasn’t there.
I connected to my email provider, and everything is fine from my provider. I checked with my new phone and my desktop version but I haven’t received any email.
### Expected Behavior
I received a digital code from the recovery email.

### Actual Behavior
I didn't receive a digital code from the recovery email.

### Steps to Reproduce
1. go to Privacy and Security tap
2. click on Two-step Verification tap
3. click on forgot password

### Screenshots and Videos 
Remove, if not applicable
<img width="1030" alt="Screen Shot 2023-10-25 at 11 15 51 AM" src="https://github.com/TelegramMessenger/Telegram-iOS/assets/19463909/bb1a82de-e4c3-40ca-b8c7-159fb31ab09a">

### Environment
**Device:** `iPhone/Mac`

**iOS version**: `17.X`
**Mac version**: `12.X`

**App version:** `10.1.4.252330 Stable`

**Comment by ali-fareed** [comment]
This does not look like an app issue. Contacting support would be a better option.

**Comment by armin2200** [comment]
nobody has answered me from the support team!
