### ISSUE TITLE
How to use older versions？8.9

### ISSUE THREAD

**Issue by onlypl** [TelegramMessenger/Telegram-iOS#1254]
python3 build-system/Make/Make.py \
    --overrideXcodeVersion \
    --cacheDir="$HOME/telegram-bazel-cache" \
    generateProject \
    --configurationPath="$HOME/telegram-configuration"  \
    --disableExtensions \
    --disableProvisioningProfiles

I want to use version 8.9 which results in the following error：
ERROR: /Users/onlypl/Desktop/telegream/Telegram-iOS-build-23987/WORKSPACE:14:17: fetching local_repository rule //external:build_bazel_rules_apple: java.io.IOException: No WORKSPACE file found in /private/var/tmp/_bazel_onlypl/f8cee717ae660d0f11134621ad26ecfc/external/build_bazel_rules_apple
ERROR: no such package '@build_bazel_rules_apple//apple': No WORKSPACE file found in /private/var/tmp/_bazel_onlypl/f8cee717ae660d0f11134621ad26ecfc/external/build_bazel_rules_apple

**Comment by onlypl** [comment]
Because the communication protocol has changed in versions after 8.9, it does not match the server.

**Comment by sa-ko4969** [comment]
> python3 build-system/Make/Make.py --overrideXcodeVersion --cacheDir="$HOME/telegram-bazel-cache" generateProject --configurationPath="$HOME/telegram-configuration" --disableExtensions --disableProvisioningProfiles
> 
> I want to use version 8.9 which results in the following error： ERROR: /Users/onlypl/Desktop/telegream/Telegram-iOS-build-23987/WORKSPACE:14:17: fetching local_repository rule //external:build_bazel_rules_apple: java.io.IOException: No WORKSPACE file found in /private/var/tmp/_bazel_onlypl/f8cee717ae660d0f11134621ad26ecfc/external/build_bazel_rules_apple ERROR: no such package '@build_bazel_rules_apple//apple': No WORKSPACE file found in /private/var/tmp/_bazel_onlypl/f8cee717ae660d0f11134621ad26ecfc/external/build_bazel_rules_apple

**Comment by sa-ko4969** [comment]
> python3 build-system/Make/Make.py --overrideXcodeVersion --cacheDir="$HOME/telegram-bazel-cache" generateProject --configurationPath="$HOME/telegram-configuration" --disableExtensions --disableProvisioningProfiles
> 
> I want to use version 8.9 which results in the following error： ERROR: /Users/onlypl/Desktop/telegream/Telegram-iOS-build-23987/WORKSPACE:14:17: fetching local_repository rule //external:build_bazel_rules_apple: java.io.IOException: No WORKSPACE file found in /private/var/tmp/_bazel_onlypl/f8cee717ae660d0f11134621ad26ecfc/external/build_bazel_rules_apple ERROR: no such package '@build_bazel_rules_apple//apple': No WORKSPACE file found in /private/var/tmp/_bazel_onlypl/f8cee717ae660d0f11134621ad26ecfc/external/build_bazel_rules_apple

**Comment by ali-fareed** [comment]
Generally, no support for older version is provided. However, in this case the issue probably lies in the lack of `git submodule --update`.

**Comment by onlypl** [comment]
> Generally, no support for older version is provided. However, in this case the issue probably lies in the lack of `git submodule --update`.


I've tried switching to the 8.9 version of the tag, but it still doesn't work

**Comment by onlypl** [comment]
> Generally, no support for older version is provided. However, in this case the issue probably lies in the lack of `git submodule --update`.

I've tried switching to the 8.9 version of the tag, but it still doesn't work
