### ISSUE TITLE
How do I remove callkit?

### ISSUE THREAD

**Issue by twisturn** [TelegramMessenger/Telegram-iOS#126]
How do I remove callkit?

**Comment by shivanraptor** [comment]
What do you mean by that? Remove the VoIP call functionality in Telegram?

**Comment by twisturn** [comment]
@shivanraptor Just remove the callkit function and keep the voip

**Comment by laktyushin** [comment]
https://github.com/TelegramMessenger/Telegram-iOS/blob/7cf95a743cef5090f1f100414a6b2c894056c0db/submodules/TelegramCallsUI/Sources/CallKitIntegration.swift#L14
Change this variable to false to completely disable CallKit.
