### ISSUE TITLE
Version number 8.9 execution build error

### ISSUE THREAD

**Issue by onlypl** [TelegramMessenger/Telegram-iOS#1263]
python3 build-system/Make/Make.py \
    --cacheDir="$HOME/telegram-bazel-cache" \
    generateProject \
    --configurationPath="$HOME/telegram-configuration" \
    --disableExtensions \
    --disableProvisioningProfiles

error:
ERROR: /private/var/tmp/_bazel_onlypl/66f1c1796bcfdc3b2cb355fea1f5c50f/external/local_config_cc/BUILD:48:19: in cc_toolchain_suite rule @local_config_cc//:toolchain: cc_toolchain_suite '@local_config_cc//:toolchain' does not contain a toolchain for cpu 'darwin_x86_64'
ERROR: /private/var/tmp/_bazel_onlypl/66f1c1796bcfdc3b2cb355fea1f5c50f/external/local_config_cc/BUILD:48:19: Analysis of target '@local_config_cc//:toolchain' failed
ERROR: Analysis of target '//:tulsi' failed; build aborted:

**Comment by onlypl** [comment]
what?

**Comment by ali-fareed** [comment]
8.9 is nearly 1.5 years old. Please use the latest code.

**Comment by onlypl** [comment]
> 8.9 is nearly 1.5 years old. Please use the latest code.

Versions after 8.9 have changed a lot. The amount of modification work we have here is too great. Is there no way to use the older version?

**Comment by ali-fareed** [comment]
You can probably keep the 8.x-era codebase if you are ready to keep using Xcode 13, macOS 12, and the corresponding Bazel version.
