### ISSUE TITLE
Full Error List of Telegram?

### ISSUE THREAD

**Issue by shivanraptor** [TelegramMessenger/Telegram-iOS#127]
Some users encountered some errors while logging into Telegram. One of them is 

> Error: 406: PHONE_PASSWORD_FLOOD

Is there any official documentation of the error list, that includes the reasons behind?

By the way, if I don't get it wrong, the above error means they tried 2-factor password too many times?

**Comment by shivanraptor** [comment]
Btw, I found the following error list, not sure if it's accurate or not.

https://github.com/LonamiWebs/Telethon/blob/master/telethon_generator/data/errors.csv

**Comment by laktyushin** [comment]
PHONE_PASSWORD_FLOOD means password was entered incorrectly too many times.

There is no such list at the moment. The one you linked above looks good.
