### ISSUE TITLE
Text field for message in secret chat continuously resets caret's state and user is not able to select text.

### ISSUE THREAD

**Issue by hexlogic** [TelegramMessenger/Telegram-iOS#1273]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
When I try to select text in message that I typed in message box, the caret is resetting its state continuously. I'm not able to select, format, change caret's placing. Also this causes a device overheating.

### Steps to Reproduce
1. Create secret chat
2. Type a message
3. Try to select the text, change caret's position.
4. Check device temperature.

### Environment
**Device:** `iPhone 14 Pro`

**iOS version**: `17.1`

**App version:** `10.2.2`

**Comment by ali-fareed** [comment]
Should be fixed in 10.2.4.
