### ISSUE TITLE
Invalid Cert File

### ISSUE THREAD

**Issue by twisturn** [TelegramMessenger/Telegram-iOS#128]
Invalid Cert File
![1566372347738](https://user-images.githubusercontent.com/17715937/63411419-16193f00-c428-11e9-9a0f-f058d4cb9a7c.jpg)

**Comment by shivanraptor** [comment]
Duplicate of #29. Follow the command of the first comment.

**Comment by twisturn** [comment]
@shivanraptor I changed the App api_id and App api_hash, but I didn't get the push message

**Comment by shivanraptor** [comment]
As I mentioned, notification doesn't work. See #88

**Comment by twisturn** [comment]
@shivanraptor I still don't know how to modify it

**Comment by twisturn** [comment]
@shivanraptor My version is 5.5-Fork

**Comment by laktyushin** [comment]
Duplicate of #29

**Comment by twisturn** [comment]
I completed all the operations but did not receive the notification
