### ISSUE TITLE
Missing CONTRIBUTING.md

### ISSUE THREAD

**Issue by fopina** [TelegramMessenger/Telegram-iOS#1287]
### Checklist
- [ ] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description

There are a few bug fixes I'd like to contribute (eg: current version does not allow easily copy of multi line code block as before) but I cannot any contributing guidelines.
Also, there isn't a single merged PR, are they not acceptable at all?

### Expected Behavior

CONTRIBUTING.md with the guidelines, located at root of project or in .github (like telegram-desktop has)

**Comment by ali-fareed** [comment]
Done: https://github.com/TelegramMessenger/Telegram-iOS/blob/master/.github/CONTRIBUTING.md
