### ISSUE TITLE
Login issue. Can't receive code via SMS

### ISSUE THREAD

**Issue by Trongnguyen-IT** [TelegramMessenger/Telegram-iOS#1291]
### Checklist
- 1. I am reporting an issue in existing functionality that does not work as intended
- 2 I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
I have installed Telegram IOS appa and try to login. The system show We've sent code to your other device despite don't login any where. I also can't see option Tap to send code via SMS.

### Expected Behavior
Send SMS code

### Actual Behavior
Sends to non-existent "other device". This happens on IOS.

Support also has not responded for over a week.

### Steps to Reproduce
1. Install Telegram application.
2. Input phone number.
3. Show this message: "We've sent code to your other device".

### Screenshots and Videos 
![ecc9d44f-ca39-443c-9726-4e7546ffb684](https://github.com/TelegramMessenger/Telegram-iOS/assets/26566323/6f7645b4-1777-44f0-96ff-28097a5f19ce)

### Environment
**Device:** `iPhone 12 Promax`

**iOS version**: `17.1.1`

**App version:** `10.3`

**Comment by shivanraptor** [comment]
It already said Telegram has sent the code (not SMS) to your other logged-in device.

**Comment by Trongnguyen-IT** [comment]
Could you please give me the reference link?

**Comment by Trongnguyen-IT** [comment]
In description. I have mentioned I don't login in anywhere so far. In last
week, I have logged app in Window laptop and I reinstalled windows OS a few
days ago and I have only one the phone. How can resolve issue now?

Vào Th 2, 4 thg 12, 2023 vào lúc 09:23 Raptor K ***@***.***>
đã viết:

**Comment by ali-fareed** [comment]
There is the "Didn't get the code" button.

**Comment by Trongnguyen-IT** [comment]
Hi guy,
The issue is still not resolved.I will create a new ticket for this because
the status is closed.

Vào Th 2, 4 thg 12, 2023 vào lúc 17:57 Trong Nguyen <
***@***.***> đã viết:

**Comment by maddinpsy** [comment]
I had a similar issue when using a phone without google play services. Te get the code by SMS you need google play services installed and active.

**Comment by Trongnguyen-IT** [comment]
Hi @maddinpsy ,
It' resolved after update IOS version. I think some cache with operation

**Comment by danee1** [comment]
I have the same issue.
Nothing helps. Support hasn't answered for 3 weeks.
Telegram for iOS v11.1
iOS v17.6.1

**Comment by sunlit777** [comment]
They just don’t care or they are doing it on purpose. For USA numbers the option to send SMS is always available. For some other countries, e.g. Indonesia there is no way to register a new account EVEN with newly purchased SIM that you’ve never used before, if Telegram was registered by some previous owner of this number (cellular operators don’t ditch old numbers they reuse them!) 
No option to contact support either, way to go Telegram app, you are upholding your “fame” as pirates and crooks haven!

**Comment by aminanasir2132-byte** [comment]
> ### Checklist
> * 1. I am reporting an issue in existing functionality that does not work as intended
> * 2 I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)
> 
> ### Description
> I have installed Telegram IOS appa and try to login. The system show We've sent code to your other device despite don't login any where. I also can't see option Tap to send code via SMS.
> 
> ### Expected Behavior
> Send SMS code
> 
> ### Actual Behavior
> Sends to non-existent "other device". This happens on IOS.
> 
> Support also has not responded for over a week.
> 
> ### Steps to Reproduce
> 1. Install Telegram application.
> 2. Input phone number.
> 3. Show this message: "We've sent code to your other device".
> 
> ### Screenshots and Videos
> ![ecc9d44f-ca39-443c-9726-4e7546ffb684](https://github.com/TelegramMessenger/Telegram-iOS/assets/26566323/6f7645b4-1777-44f0-96ff-28097a5f19ce)
> 
> ### Environment
> **Device:** `iPhone 12 Promax`
> 
> **iOS version**: `17.1.1`
> 
> **App version:** `10.3`

**Comment by ktdzt5kd5c-cyber** [comment]
0889674640
