### ISSUE TITLE
Login issue. Can't receive code via SMS reference id #1291 is closed but the issue still not resolved.

### ISSUE THREAD

**Issue by Trongnguyen-IT** [TelegramMessenger/Telegram-iOS#1293]
### Description
When install Telegram, the system inform have sent the code to your other devide but I have not logged any device so far.
I already press button Didn't get the code and send email many time but no response.

### Expected Behavior
I would like to receive the code either SMS or email address.

### Actual Behavior
1. Install app
2. Input phone number
3. Press button Didn't get the code
4. Send email
5. Nothing what happend

### Steps to Reproduce
1. Install app
2. Input phone number
3. Press button Didn't get the code
4. Send email
5. Nothing what happend

### Environment
**Device:** `iPhone`

**iOS version**: `17.1`

**App version:** `10.3`

**Comment by ali-fareed** [comment]
Do you have an e-mail account configured in Mail app?

**Comment by Trongnguyen-IT** [comment]
Yes,  When I press the button Didn't get code, the system sends an email
directly from this email account.to  ***@***.*** about 10 times but
no response.
[image: image.png]
Vào Th 3, 5 thg 12, 2023 vào lúc 15:07 ali-fareed <
***@***.***> đã viết:

**Comment by ali-fareed** [comment]
In that case the app itself performs as expected. Login issues are handled via login@stel.com.
