### ISSUE TITLE
does not display changes in the simulator

### ISSUE THREAD

**Issue by Sa1ntProd** [TelegramMessenger/Telegram-iOS#1299]
hi. Xcode version 15.0.1. 
Did everything according to the instructions. I can't edit the text in any way, for example... as soon as I did not change the text from the settings section of the "Telegram FAQ". but when running in the simulator, the text remained old. I tried to clean the cache and in bazel, through the terminal, what am I doing wrong?

**Comment by ali-fareed** [comment]
Localized strings are pulled from the server.

**Comment by Sa1ntProd** [comment]
then how do I localize it to my needs?
