### ISSUE TITLE
cannot compile source code for this project.

### ISSUE THREAD

**Issue by PengsreangSrun** [TelegramMessenger/Telegram-iOS#13]
I downloaded this project then I started compiling but it showed many errors. Please help me to check this?

**Comment by Lb0728** [comment]
I can't compile, ask for help.

**Comment by iceloveboa** [comment]
> I can't compile, ask for help.

you can compile the Telegram-ios Fork scheme, other need some config file

**Comment by Selina-ZHENG** [comment]
Have you cloned this project including submodules? I cloned this project including submodules. After I have fixed some error, such installing yasm and add gas-preprocessor.pl to /usr/local/bin/ in my Mac, I can compile the Telegram-ios Fork scheme.
Here is the command which clones this project including submodules: git clone --recurse-submodules https://github.com/peter-iakovlev/Telegram-iOS.git

> I downloaded this project then I started compiling but it showed many errors. Please help me to check this?

**Comment by DavisGuohua-xie** [comment]
Can someone please guide the new guys build this project from xcode ? I have clone with 

> git clone --recurse-submodules https://github.com/peter-iakovlev/Telegram-iOS.git

but still no luck. 

I also attempted this guide,  but not sure if it still valid since I can't get it working 

https://github.com/peter-iakovlev/Telegram/issues/264

please someone add a guide to build this project for emulators or own ios devices, Thank you in advance.

**Comment by Vanyoo** [comment]
> Telegram-ios

Excuse me, do you mean import `./Telegram-iOS.xcworkspace/xcshareddata/xcschemes/Telegram-iOS-Fork.xcscheme` this scheme file? But when I import this scheme file and compile, it showes me
`error: No profile for team 'X834Q8SBVP' matching 'match Development org.telegram.Telegram-iOS.SiriIntents' found: Xcode couldn't find any provisioning profiles matching 'X834Q8SBVP/match Development org.telegram.Telegram-iOS.SiriIntents'. Install the profile (by dragging and dropping it onto Xcode's dock item) or select a different one in the General tab of the target editor. (in target 'SiriIntents')`

**Comment by Selina-ZHENG** [comment]
> > Telegram-ios
> 
> Excuse me, do you mean import `./Telegram-iOS.xcworkspace/xcshareddata/xcschemes/Telegram-iOS-Fork.xcscheme` this scheme file? But when I import this scheme file and compile, it showes me
> 
> `error: No profile for team 'X834Q8SBVP' matching 'match Development org.telegram.Telegram-iOS.SiriIntents' found: Xcode couldn't find any provisioning profiles matching 'X834Q8SBVP/match Development org.telegram.Telegram-iOS.SiriIntents'. Install the profile (by dragging and dropping it onto Xcode's dock item) or select a different one in the General tab of the target editor. (in target 'SiriIntents')`
> 
> Could help me? Thank you really much.

Sorry for my misleading words. 
"compile the Telegram-ios Fork scheme" means choose the "Telegram-ios Fork" scheme and then compile the project. I have attached a screenshot.
![image](https://user-images.githubusercontent.com/14055879/58762602-fb9b9c00-8583-11e9-85ba-f6e8ee3a27ed.png)

**Comment by nanirocks125** [comment]
I am also facing the same issue.
