### ISSUE TITLE
No Push Notification was received via Telegram Fork (v5.5)

### ISSUE THREAD

**Issue by twisturn** [TelegramMessenger/Telegram-iOS#130]
I have successfully uploaded the certificate with.pem suffix,but No Push Notification was received via Telegram Fork (v5.5)

**Comment by shivanraptor** [comment]
As mentioned in other issues, push notification does **not** work in Fork at this moment. 
See #88, #74, #43, #29. It's server-side's issues. Client code can't help at all.

**Comment by twisturn** [comment]
I want to know about the push content of receiving phone calls from others in the background,Is there any way?

**Comment by shivanraptor** [comment]
Do you mean VoIP call in Telegram or standard phone call?

**Comment by twisturn** [comment]
VOIP call
