### ISSUE TITLE
Generate Xcode Project With Extensions(At least with Broadcast Extension)

### ISSUE THREAD

**Issue by mehmetbaykar** [TelegramMessenger/Telegram-iOS#1300]
### Checklist
- [ ] I am reporting an issue in existing functionality that does not work as intended and there is not enough info to fix the issue.
- [ ] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
I am trying to generate the Xcode project to test the BroadCastUpload Extension behavior. Unfortunately in the read.me file there is not enough info to generate the project without codesigning and enabling the extension that runs on simulator or development devices.

### Expected Behavior
I want to be able to generate the extensions at least the Broadcast Upload Extension and run on a real device. Using the Advanced Compilation Guide.

### Actual Behavior
It does accept the fake coding signing as well as the example-configuration 

### Steps to Reproduce
1.  ` python3 build-system/Make/Make.py \
python3 build-system/Make/Make.py \l-cache" \   python3 build-system/Make/Make.py
    --cacheDir="$HOME/telegram-bazel-cache" \
    generateProject \th=build-system/template_minimal_development_configuration.json \
    --configurationPath=build-system/template_minimal_development_configuration.json \
    --disableProvisioningProfiles \ild-system/example-configuration
    --codesigningInformationPath=build-system/example-configuration
`

### Environment

**iOS version**: `17.X`

**Xcode version:** `15.0.1`

**Comment by ali-fareed** [comment]
```
python3 build-system/Make/Make.py \ python3 build-system/Make/Make.py \l-cache" \   python3 build-system/Make/Make.py --cacheDir="$HOME/telegram-bazel-cache" \ generateProject \th=build-system/template_minimal_development_configuration.json \ --configurationPath=build-system/template_minimal_development_configuration.json \ --disableProvisioningProfiles \ild-system/example-configuration --codesigningInformationPath=build-system/example-configuration
```

This command does not make any sense. Please follow the steps in README.

**Comment by mehmetbaykar** [comment]
Sorry, I copied it two times. Please check the updated code.

**Comment by mehmetbaykar** [comment]
@ali-fareed did you check the updated command?

**Comment by ali-fareed** [comment]
It's not possible to run extensions on a real device without real provisioning profiles.
