### ISSUE TITLE
AppleStore App Review

### ISSUE THREAD

**Issue by WYStudioEx** [TelegramMessenger/Telegram-iOS#1303]
Hello, may I ask how to pass Apple's review? Our application is developed based on Telegram, which means we are unable to provide accounts for the reviewers to log in and inspect. We have been rejected twice so far, and we are feeling anxious. Could you please help us with some guidance?

**Comment by ali-fareed** [comment]
You may have to rely on the testing environment: https://core.telegram.org/api/auth#test-accounts
