### ISSUE TITLE
How to properly customize an application? (localization, name, "Advanced Compilation" assembly)

### ISSUE THREAD

**Issue by Sa1ntProd** [TelegramMessenger/Telegram-iOS#1306]
Hello
I have a few questions, sorry if they may seem “**stupid**” to you, I’m new to this....

**1)**
Previously, I was interested in why some lines were not changed (after changing the localization files) when running the project in the simulator
PS: Here they gave me the answer: #1299 
"Localized strings are pulled from the server."

ok, but how can I change it correctly then (for example, “Telegram” -> “Cusom Messenger”)
Because everything changes, but in the settings the menu items remain the same...
Because I changed it to:
/en.lproj/*
/ru.lproj/*
and in xcode itself in Localizable.strings

And which cache will need to be cleared? 
Because I'm already in the simulator, 
in xcode 
and in the terminal (bazel clean --expunge)
: 
cleared (out of despair) :)

**2)**
How to correctly change the “name” of the application? (in xcode itself the parameters contain variables like CFBundleName)
But in which file exactly are these parameters?
If I understand correctly, they are all set through Bazel?
Because I started watching courses on xcode/swift/uikit
But I didn’t find any instructions where xcode+bazel is used((
Although I even looked on the official website... - I couldn’t find it (due to lack of knowledge and experience, most likely)

**3)**
The instructions also say:
"...
Copy and edit build-system/appstore-configuration.json.
Copy build-system/fake-codesigning. Create and download provisioning profiles, using the profiles folder as a reference for the entitlements.
..."
Where exactly should I copy these files?
(Or this is simply indicated in order to copy the “example” for the project and then use it in the next command)

PS:  Xcode version 15.0.1

**Comment by ali-fareed** [comment]
build-system/appstore-configuration.json is the exact configuration file that the official app uses for App Store builds. build-system/fake-codesigning contains provisioning profiles with entitlements identical to those in the official App Store build. This information is essential for creating a customized build.

I would suggest that you familiarize yourself with iOS / Xcode development before moving on to a complex project.

**Comment by agates4** [comment]
The display name can be changed here:
https://github.com/TelegramMessenger/Telegram-iOS/blob/master/Telegram/BUILD#L644-L652

In the `Telegram/BUILD` file, update the value of the `CFBundleDisplayName` key.
