### ISSUE TITLE
Unable to open photos from link embeds

### ISSUE THREAD

**Issue by dancojocaru2000** [TelegramMessenger/Telegram-iOS#1308]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
Since the latest update, tapping a photo in  a link embed opens the link.

### Expected Behavior
The photo preview should open as in previous updates.

### Actual Behavior
The link opens as if tapping the link.

### Steps to Reproduce
1. Find a message with a link embed that contains a photo.
2. Tap the photo.

### Environment
**Device:** `iPhone XR`

**iOS version**: `16.0`

**App version:** `10.3.1`

**Comment by ali-fareed** [comment]
This is intended.

**Comment by dancojocaru2000** [comment]
Woo, removing functionality to do things nobody asked for and that [people then complain about](https://bugs.telegram.org/c/33679). Looks like Telegram isn't spared from the common trend of apps becoming worse. Awesome.
