### ISSUE TITLE
How to generate the Swift version of the Api ？

### ISSUE THREAD

**Issue by Sherlockzms** [TelegramMessenger/Telegram-iOS#1319]
Hi, how does the official Telegram generate the Swift version of the API based on the tl scheme (telegram_api.tl)? Is it similar to Google's Protocol Buffers, where they write their own compiler/parser --> (similar protoc)?

**Comment by ali-fareed** [comment]
There is a script that generates the TL serialization/deserialization code. It's only useful when upgrading to a new API.
