### ISSUE TITLE
Checkout with `--recursive` fails when forking the repository

### ISSUE THREAD

**Issue by bclark8923** [TelegramMessenger/Telegram-iOS#1322]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
When forking the repo, `rlottie` and `tgcalls` failed to update due to using `../` to reference the `TelegramMessenger` github account

### Expected Behavior
`git checkout --recursive` should have worked on my fork

### Actual Behavior
repos `rlottie` and `tgcalls` could not be found

### Next Steps
Fix included in PR linked in comment below

**Comment by bclark8923** [comment]
Submitted a PR to fix this issue https://github.com/TelegramMessenger/Telegram-iOS/pull/1321

**Comment by ali-fareed** [comment]
The team uses a number of private repositories that follow the structure of the public account. A better solution might be to use the git URL rewrite feature.
