### ISSUE TITLE
Build did NOT complete successfully Build failed. Not running target

### ISSUE THREAD

**Issue by xq312704108** [TelegramMessenger/Telegram-iOS#1323]
uc@ucdeiMac Telegram-iOS % python3 build-system/Make/Make.py \
    --cacheDir="$HOME/telegram-bazel-cache" \
    generateProject \
    --configurationPath=build-system/template_minimal_development_configuration.json \
    --xcodeManagedCodesigning
INFO: Analyzed target //Telegram:Telegram_xcodeproj (1 packages loaded, 1 target configured).
INFO: Found 1 target...
INFO: From CalculateExecutionRoot Telegram/Telegram_xcodeproj_execution_root_file:
: command not found
ERROR: /Users/uc/Desktop/Telegram-iOS/Telegram/BUILD:2017:10: output 'Telegram/Telegram_xcodeproj_execution_root_file' was not created
ERROR: /Users/uc/Desktop/Telegram-iOS/Telegram/BUILD:2017:10: CalculateExecutionRoot Telegram/Telegram_xcodeproj_execution_root_file failed: not all outputs were created or valid
Target //Telegram:Telegram_xcodeproj failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.902s, Critical Path: 0.09s
INFO: 2 processes: 1 internal, 1 local.
FAILED: Build did NOT complete successfully
ERROR: Build failed. Not running target
Traceback (most recent call last):
  File "/Users/uc/Desktop/Telegram-iOS/build-system/Make/Make.py", line 1050, in <module>
    generate_project(bazel=bazel_path, arguments=args)
  File "/Users/uc/Desktop/Telegram-iOS/build-system/Make/Make.py", line 568, in generate_project
    generate(
  File "/Users/uc/Desktop/Telegram-iOS/build-system/Make/ProjectGeneration.py", line 58, in generate
    generate_xcodeproj(build_environment, disable_extensions, disable_provisioning_profiles, include_release, generate_dsym, configuration_path, bazel_app_arguments, target_name)
  File "/Users/uc/Desktop/Telegram-iOS/build-system/Make/ProjectGeneration.py", line 51, in generate_xcodeproj
    call_executable(bazel_generate_arguments)
  File "/Users/uc/Desktop/Telegram-iOS/build-system/Make/BuildEnvironment.py", line 81, in call_executable
    subprocess.check_call(resolved_arguments, env=resolved_env)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/uc/Desktop/Telegram-iOS/build-input/bazel-6.4.0-darwin-x86_64', 'run', '//Telegram:Telegram_xcodeproj', '--override_repository=build_configuration=/Users/uc/Desktop/Telegram-iOS/build-input/configuration-repository', '--//Telegram:disableExtensions', '--//Telegram:disableStripping']' returned non-zero exit status 1.

**Comment by xq312704108** [comment]
{
    "app": "10.6",
    "bazel": "6.4.0",
    "xcode": "15.2",
    "macos": "13.0"
}

**Comment by ali-fareed** [comment]
Could you show the contents of `build-system/template_minimal_development_configuration.json`?

**Comment by xq312704108** [comment]
> uc@ucdeiMac Telegram-iOS % python3 build-system/Make/Make.py --cacheDir="$HOME/telegram-bazel-cache" generateProject --configurationPath=build-system/template_minimal_development_configuration.json --xcodeManagedCodesigning INFO: Analyzed target //Telegram:Telegram_xcodeproj (1 packages loaded, 1 target configured). INFO: Found 1 target... INFO: From CalculateExecutionRoot Telegram/Telegram_xcodeproj_execution_root_file: : command not found ERROR: /Users/uc/Desktop/Telegram-iOS/Telegram/BUILD:2017:10: output 'Telegram/Telegram_xcodeproj_execution_root_file' was not created ERROR: /Users/uc/Desktop/Telegram-iOS/Telegram/BUILD:2017:10: CalculateExecutionRoot Telegram/Telegram_xcodeproj_execution_root_file failed: not all outputs were created or valid Target //Telegram:Telegram_xcodeproj failed to build Use --verbose_failures to see the command lines of failed build steps. INFO: Elapsed time: 0.902s, Critical Path: 0.09s INFO: 2 processes: 1 internal, 1 local. FAILED: Build did NOT complete successfully ERROR: Build failed. Not running target Traceback (most recent call last): File "/Users/uc/Desktop/Telegram-iOS/build-system/Make/Make.py", line 1050, in generate_project(bazel=bazel_path, arguments=args) File "/Users/uc/Desktop/Telegram-iOS/build-system/Make/Make.py", line 568, in generate_project generate( File "/Users/uc/Desktop/Telegram-iOS/build-system/Make/ProjectGeneration.py", line 58, in generate generate_xcodeproj(build_environment, disable_extensions, disable_provisioning_profiles, include_release, generate_dsym, configuration_path, bazel_app_arguments, target_name) File "/Users/uc/Desktop/Telegram-iOS/build-system/Make/ProjectGeneration.py", line 51, in generate_xcodeproj call_executable(bazel_generate_arguments) File "/Users/uc/Desktop/Telegram-iOS/build-system/Make/BuildEnvironment.py", line 81, in call_executable subprocess.check_call(resolved_arguments, env=resolved_env) File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call raise CalledProcessError(retcode, cmd) subprocess.CalledProcessError: Command '['/Users/uc/Desktop/Telegram-iOS/build-input/bazel-6.4.0-darwin-x86_64', 'run', '//Telegram:Telegram_xcodeproj', '--override_repository=build_configuration=/Users/uc/Desktop/Telegram-iOS/build-input/configuration-repository', '--//Telegram:disableExtensions', '--//Telegram:disableStripping']' returned non-zero exit status 1.

**Comment by Mehrafruz** [comment]
How did you fix this bug?

**Comment by Mehrafruz** [comment]
How did you fix this bug?

**Comment by Pogosito** [comment]
Same issue
