### ISSUE TITLE
 introduction screen will freeze when connect to teamgram-server

### ISSUE THREAD

**Issue by 2547409617** [TelegramMessenger/Telegram-iOS#1325]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [ ] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
Telegram-iOS app connected teamgram-server in custom deployment.
The introduction screen will freeze but the app is still alive when button is pressed on first launch ios app.  Then the app was killed and launched it again,  It will skip  introduction screen and mobile  login screen will work well.

### Expected Behavior
The introduction screen will NOT freeze when button is pressed on first launch ios app

### Actual Behavior
The introduction screen will freeze when button is pressed on first launch ios app

### Steps to Reproduce
NA

### Environment
**Device:** `iPhone simulator`

**iOS version**: `15 Pro`

**App version:** NA

**Comment by ali-fareed** [comment]
If the app performs as intended in the default configuration, the issue might be on the server side.
