### ISSUE TITLE
 Showing Recent Issues The bazel build failed, please check the report navigator, which may have more context about the failure.

### ISSUE THREAD

**Issue by xq312704108** [TelegramMessenger/Telegram-iOS#1326]
<img width="1226" alt="截屏2024-01-18 21 58 39" src="https://github.com/TelegramMessenger/Telegram-iOS/assets/19202501/b4a8bea2-5238-4e1d-a580-a2e47ef1afa8">
sudo python3 build-system/Make/Make.py \
    --cacheDir="$HOME/telegram-bazel-cache" \
    generateProject \
    --configurationPath=build-system/template_minimal_development_configuration.json \
    --xcodeManagedCodesigning
And then there's this problem

**Comment by xq312704108** [comment]
xcode 15.2
macos 15.0
apple M1
bazel 6.4.0

**Comment by ali-fareed** [comment]
Please use the issue that you already opened. Re-open if needed.
