### ISSUE TITLE
[BUG] Telegram crashes when sending 1500 "❤" symbols

### ISSUE THREAD

**Issue by NotStatilko** [TelegramMessenger/Telegram-iOS#133]
Hello! When I send 1500 "❤" characters to a user with Iphone 7 his Telegram crashes

**[Device on which bug]**
`Telegram version: 5.10`
`Model: Iphone 7`

**[Device from which i send this message]**
`Telegram version: 5.10.0 (1684) arm-v7a`
`Model: Samsung Galaxy J730F (Android 9)`

**[REPRODUCE]**
Just use inline bot `@rextester_bot` with the following query
```
@rextester_bot python3 print('❤' * 1500, end='')
```
![Screenshot_20190828-120208_Instagram](https://user-images.githubusercontent.com/43419673/63846176-f20fad80-c993-11e9-9ad2-921d7ec47efb.jpg)

**Comment by laktyushin** [comment]
Could you check it on 5.11 please? It couldn't reproduce the issue so it might be fixed already.

**Comment by NotStatilko** [comment]
Yes, there is no more error. Tested in 5.11. I close issue
