### ISSUE TITLE
.mobileprovision' not declared in package 'provisioning

### ISSUE THREAD

**Issue by xq312704108** [TelegramMessenger/Telegram-iOS#1333]
ERROR: /Users/luzhixue/Desktop/Telegram-iOS/Telegram/BUILD:1563:14: no such target '@build_configuration//provisioning:Intents.mobileprovision': target 'Intents.mobileprovision' not declared in package 'provisioning' defined by /private/var/tmp/_bazel_luzhixue/c11ca6528f7310020ff12bf86a1d45a8/external/build_configuration/provisioning/BUILD (Tip: use `query "@build_configuration//provisioning:*"` to see all the targets in that package) and referenced by '//Telegram:IntentsExtension'

**Comment by CoderWeiLee** [comment]
如何解决的呢

**Comment by Tilak1028-st** [comment]
@jackiewu I have checked the appid and profile_name_mapping it is same but still getting the same error. 
@xq312704108 Can you please how did you resolved this issue?
