### ISSUE TITLE
Voice record does not start instantly

### ISSUE THREAD

**Issue by Neurotoxin001** [TelegramMessenger/Telegram-iOS#136]
I have iPhone 5S with iOS 12.4.1 and on this setup I have strange thing - voice record does not start instantly, but my friend have iPhone 7 with same iOS and all is fine with it.

https://i.imgur.com/hQGc7nR.mp4 - demonstration

I test it on 5.10 official Telegram app and 5.10 Nicegram, result the same.

**Comment by ethylmorphine** [comment]
I would like to add that voice recordings abruptly stop before you actually send them (5.10, 12.4.1, iPhone 7). Both of these issues have something to do with improved sound quality because there hasn’t been such a problem before.

**Comment by ethylmorphine** [comment]
P.S. These issues are present on both iPhone 7 and iPhone 8 Plus, so I don’t think it’s hardware-related bug.

**Comment by atineo** [comment]
The voice recording problem that @ethylmorphine describes also happens on both iPhone X and XS

**Comment by Neurotoxin001** [comment]
5.11 not fixed

**Comment by Neurotoxin001** [comment]
Seems like this issue only on "old" iphones, issue is still here on 5.12.2 and ios 12.4.3 (iphone 5s) and there is no this issue on iphone XR and ios 13.2.2

**Comment by nick318** [comment]
@Neurotoxin001 have you fixed the problem? I have a similar problem with the iPhone 11. When I start recording a voice message there is a small time gap ~20ms after which ios actually starts recording and shows a microphone picture.

**Comment by Neurotoxin001** [comment]
It fixed for me after I switched from iPhone 5S to XR. And now on 13 Pro all is fine with voice recording too.
