### ISSUE TITLE
"Updating" is circling, no new message coming in

### ISSUE THREAD

**Issue by qiangweihewu** [TelegramMessenger/Telegram-iOS#1367]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
A lot of users in China reported that when they reopened the app after a period(few minutes to few hours), on the top of the app the "Updating" kept circling without any new message coming in.  

### Expected Behavior
if there was new message, then updating shoud work.

### Actual Behavior
Updating stucked.

### Steps to Reproduce
1. Using Mtproxy or other proxy tools for Telegram
2. Wait for few minutes or few hours before open it
3. Open it and look at the top, "Updating" is circling but no new message coming in.

### Screenshots and Videos 

https://github.com/TelegramMessenger/Telegram-iOS/assets/91766951/6a745e3e-0a13-4a73-bb1f-d73d627b0a4c

### Environment
Device: iPhone

iOS version: 17.X and 15.X

App version: 10.9.2

**Comment by shivanraptor** [comment]
China is blocking Telegram from time to time. Are you using VPN?

**Comment by qiangweihewu** [comment]
> China is blocking Telegram from time to time. Are you using VPN?

I have both VPN and mtproxy, and switch them around. And when using the same mtproxy, Android phone is very smooth, but iOS always stucks in updating. Could this have anything to do with the push or notification mechanism of the ios system?
