### ISSUE TITLE
main actor-isolated class 'ItemListRevealOptionsItemNode' has different actor isolation from nonisolated superclass 'ListViewItemNode'; this is an error in Swift 6

### ISSUE THREAD

**Issue by shivanraptor** [TelegramMessenger/Telegram-iOS#1369]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
When compiling the source code of the release tag `release-10.9.1` with Xcode 15.3 (not the suggested Xcode 15.2), the compilation process shows the following error:

```
ERROR: /my/path/to/release-10.9.1/submodules/ItemListStickerPackItem/BUILD:3:14: Compiling Swift module //submodules/ItemListStickerPackItem:ItemListStickerPackItem failed: (Exit 1): worker failed: error executing SwiftCompile command (from target //submodules/ItemListStickerPackItem:ItemListStickerPackItem) 
  (cd /private/var/tmp/_bazel_adv/7e48386866ee23156157e935023ecb07/execroot/__main__ && \
  exec env - \
    APPLE_SDK_PLATFORM=iPhoneOS \
    APPLE_SDK_VERSION_OVERRIDE=17.4 \
    PATH=/my/path/to/Library/Caches/bazelisk/downloads/sha256/0a9bfb9581a37049b7dcf204cc569b0458bedba20e84c55c0952161e036525ba/bin:/usr/bin:/bin:/usr/sbin:/sbin \
    SWIFT_AVOID_WARNING_USING_OLD_DRIVER=1 \
    XCODE_VERSION_OVERRIDE=15.3.0.15E204a \
    ZERO_AR_DATE=1 \
  bazel-out/darwin_x86_64-opt-exec-ST-13d3ddad9198/bin/external/build_bazel_rules_swift/tools/worker/worker swiftc @bazel-out/ios_arm64-opt-ios-arm64-min12.0-applebin_ios-ST-ee6c0995fb68/bin/submodules/ItemListStickerPackItem/ItemListStickerPackItem.swiftmodule-0.params)
# Configuration: c52a350d5cefbd4aec5f5c3769a2097366e17eb950c841760e6985afea4e56bd
# Execution platform: @@local_config_platform//:host
/private/var/tmp/_bazel_adv/7e48386866ee23156157e935023ecb07/execroot/__main__/submodules/ItemListUI/Sources/Items/ItemListEditableItem.swift:61:12: error: main actor-isolated class 'ItemListRevealOptionsItemNode' has different actor isolation from nonisolated superclass 'ListViewItemNode'; this is an error in Swift 6
open class ItemListRevealOptionsItemNode: ListViewItemNode, UIGestureRecognizerDelegate {
           ^
Target //Telegram:Telegram failed to build
```

I have not tried to downgrade to Xcode 15.2 yet.

### Expected Behavior
The source code should be compiled

### Actual Behavior
The build process ended with an error.

### Steps to Reproduce
1. Execute the build IPA command as usual: `USE_BAZEL_VERSION=7.0.2 python3 build-system/Make/Make.py --overrideXcodeVersion --bazel="/usr/local/bin/bazel" --cacheDir="$HOME/telegram-bazel-cache" build --configurationPath="$HOME/telegram-configuration/development-configuration.json" --buildNumber=12001 --configuration=release_arm64 --codesigningInformationPath="$HOME/telegram-configuration/fake-codesigning"`
2. The build process ends with the error above.

### Environment
**Device:** `iMac with macOS Sonoma 14.2.1`

**iOS version**: `17.3.1`

**App version:** `release-10.9.1`

**Comment by shivanraptor** [comment]
Added info: The build process completes successfully with Xcode 15.2

**Comment by ali-fareed** [comment]
Xcode 15.3 is not currently supported

**Comment by benben2019** [comment]
same issue

**Comment by leeliangliang** [comment]
![image](https://github.com/TelegramMessenger/Telegram-iOS/assets/5946002/589a436e-0508-417b-b593-390b76bf4530)
