### ISSUE TITLE
SharedWakeupManager:  issue of code design

### ISSUE THREAD

**Issue by zhoubo2015** [TelegramMessenger/Telegram-iOS#1378]
func allowBackgroundTimeExtension(timeout: Double, extendNow: Bool = false) {}

Hi,  why is need start activeExplicitExtensionTimer timer in this function,  and why  the timeout is 20 seconds? 
I guesss ,  the iOS API  (- (UIBackgroundTaskIdentifier)beginBackgroundTaskWithName:(nullable NSString *)taskName expirationHandler:(void(^ __nullable)(void))handler),   the expirationHandler callback may not called sometimes  ?

Please help, Thanks.

**Comment by zhoubo2015** [comment]
https://github.com/TelegramMessenger/Telegram-iOS/blob/d41b2d9e58b7c1f9bffc5e06629eaf295833464e/submodules/TelegramUI/Sources/SharedWakeupManager.swift#L204

**Comment by ali-fareed** [comment]
What is the issue?

**Comment by zhoubo2015** [comment]
> What is the issue?

Why is the code designed like this? Is there any reason?

Thanks.

**Comment by ali-fareed** [comment]
Sometimes the app needs time to finish its tasks when moving to background.

**Comment by zhoubo2015** [comment]
> Sometimes the app needs time to finish its tasks when moving to background.

Thanks for your help, but there are two points I still don’t understand.
1、 why the activeExplicitExtensionTimer's  timeout is 20 seconds ?
2、There are already background tasks(activeExplicitExtensionTask), why do we need a timer(activeExplicitExtensionTimer's)?

**Comment by ali-fareed** [comment]
We don't want the app to run for too long, so 20 seconds is an arbitrary value. The app will pause its threads when either the 20-second timer expires or the system invokes the background task timeout handler—whichever occurs first.
