### ISSUE TITLE
Google Links not working when sent by Telegram

### ISSUE THREAD

**Issue by Ephaltes** [TelegramMessenger/Telegram-iOS#138]
# I found a bug to report

Hello 

My problem is when I sent a google maps link through telegram I cant open the link in google Maps, but when i send the exact same link through whatsapp or email it is working.

### Steps to reproduce

I used this link, sent it through my bot and then clicked on it google maps error says that this link is not supported 

[Link](https://www.google.com/maps/dir/Ottakringer%20Stra%C3%9Fe,%20Vienna,%20Austria/Herbeckstra%C3%9Fe%2038,%20Vienna,%20Austria/D%C3%B6blinger%20Hauptstra%C3%9Fe,%20Vienna,%20Austria/FH%20Technikum%20Wien,%20H%C3%B6chst%C3%A4dtplatz,%20Vienna,%20Austria/Donauzentrum,%20Wagramer%20Stra%C3%9Fe,%20Vienna,%20Austria/Lobau,%20Vienna,%20Austria/Aspern,%20Vienna,%20Austria/Flughafen%20Wien%20(VIE),%20Wien-Flughafen,%20Schwechat,%20Austria/Erdberg,%20Vienna,%20Austria/Yip%20Hint%20Import-Export%20GmbH,%20Favoritenstra%C3%9Fe,%20Vienna,%20Austria
)

but when I press on the link in telegram and choose "copy link" and paste it in whatsapp or send it to me via mail and open it, then google maps is opening the map normal

I also checked the link both from whatsapp/email with the one from telegram ( "copy link address" )
and it is the exact same link not a single char is different

### Expected  behavior

open google maps map with route

### Actual behavior

Error : "Nicht unterstützter Link"
"Dieser Link kann nicht in Google Maps geöffnet werden"

"Link not supported"
"This Link cant be opened in Google Maps"

Short Video, As you can see in Telegram i get an error but when i copy the exact same link to whatsapp its working.
Moreover in Telegram it looks like when it opens the link it gets passed url encoded because in the search field you can see the %20 which is just a whitespace when you open the same link in whatsapp

https://www.dropbox.com/s/3ov2cw2m78qt5pz/2019-08-31%2002.23.03.mp4?dl=0

Link to gif, better quality 
https://www.dropbox.com/s/m7q7alycf6d6jnh/2019-08-31%2002.37.12.gif?dl=0

### Environment data

Iphone 6  IOS 12.4

On the Desktop App it is working normal

**Comment by laktyushin** [comment]
Fixed in 5.12
