### ISSUE TITLE
The speaker is being turned on involuntarily

### ISSUE THREAD

**Issue by B1Z0N** [TelegramMessenger/Telegram-iOS#1381]
It's not a bug exactly but undesirable behavior. 

When the person that talks with you via Telegram without video turns the video on it automatically turns on the loud speaker. 

It hurts my ears, I suggest changing this if possible. I hope I addressed right repo.

**Comment by ali-fareed** [comment]
This works as expected.

**Comment by B1Z0N** [comment]
> This works as expected.

Excuse me, as expected by whom? Because clearly my expectation for it does not conform with what was expected. 

As I understand Telegram is a commercial company and is interested in user feedback. Isn't it a place for such feedback especially when we're talking about concrete features?
