### ISSUE TITLE
How should I build a Network Extension?

### ISSUE THREAD

**Issue by huangzqh** [TelegramMessenger/Telegram-iOS#1390]
How should I build a Network Extension?

**Comment by ali-fareed** [comment]
This is a tracker dedicated to Telegram-iOS.

**Comment by huangzqh** [comment]
> 这是专用于Telegram-iOS的跟踪器。

I want to add a Network Extension to my app, but I don't seem to be generating Targets successfully. How do I write the bazel BUILD file?

**Comment by huangzqh** [comment]
> 这是专用于Telegram-iOS的跟踪器。

I want to add a Network Extension to Telegram, but I don't seem to have succeeded in generating Targets. How do I write the bazel BUILD file?
