### ISSUE TITLE
Unable to see changes after build

### ISSUE THREAD

**Issue by alex-faryna** [TelegramMessenger/Telegram-iOS#1391]
Hello, 
sorry if this is a dumb question.
I tried to follow the README file to compile and run the Telegram iOS app. I successfully created the Xcode project using this command: 
```
python3 build-system/Make/Make.py \
    --cacheDir="$HOME/telegram-bazel-cache" \
    generateProject \
    --configurationPath=build-system/template_minimal_development_configuration.json \
    --xcodeManagedCodesigning
```

When I run the app (from inside Xcode) it opens the emulator and the app runs fine.
The problem is, that when I do some changes in the code, i build and run the app (using this button):
<img width="241" alt="Screenshot 2024-04-18 at 16 46 52" src="https://github.com/TelegramMessenger/Telegram-iOS/assets/109907113/a63c33b3-2b8c-46da-b345-184609ff9baa">

and when the app launches in the emulator I don't see the changes.
My questions are:
- Do I have to follow the 'Advanced Compilation Guide' too to be able to see the changes? (I assumed the 'Quick compilation guide' would be enough)
- Do I need to run the makefile script every time I make code changes? (I tried doing that with no luck)
- How do you guys do changes and re-compile/build the application?

Thanks in advance

**Comment by ali-fareed** [comment]
Which changes are you making?

**Comment by alex-faryna** [comment]
Tried to modify the UI for learning purposes a little bit, with no luck

**Comment by ali-fareed** [comment]
What kind of modification?

**Comment by alex-faryna** [comment]
Tried adding a button in **TGMediaPickerSendActionSheetController**, tried changing the labels, tried hiding existing buttons etc

**Comment by ali-fareed** [comment]
Try changing something more obvious. Note that changing localization strings may not have any effect because they are reloaded from server.
