### ISSUE TITLE
bazel build failed

### ISSUE THREAD

**Issue by laichunhui** [TelegramMessenger/Telegram-iOS#1393]
### Checklist
- [ ] I am reporting an issue in existing functionality that does not work as intended
- [ ] I've searched for existing [[GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues](https://github.com/TelegramMessenger/Telegram-iOS/issues/1196))

### Description
The project was successfully created following the readme, but an error occurred during build. I have tried repeating the readme steps and deleting telegram-bazel-cache, but still failed.

### Screenshots and Videos 
<img width="662" alt="截屏2024-04-23 11 57 19" src="https://github.com/TelegramMessenger/Telegram-iOS/assets/11333652/015b511c-3241-4142-8ba0-20940cf7c854">

<img width="497" alt="截屏2024-04-23 11 57 59" src="https://github.com/TelegramMessenger/Telegram-iOS/assets/11333652/d0a6af50-bd31-401d-b246-d3ddcc8040fc">

<img width="450" alt="截屏2024-04-23 11 59 53" src="https://github.com/TelegramMessenger/Telegram-iOS/assets/11333652/5afec299-26a3-49fe-85f5-e6709471bb80">

### Environment
**Device:** `iPhone 15 pro`

**iOS version**: `17.4`

**App version:** `last`

**Comment by ali-fareed** [comment]
The screenshots indicate that you did not follow the README. Please try again.

**Comment by ehsan927** [comment]
👍

Nader F reacted via Gmail
<https://www.google.com/gmail/about/?utm_source=gmail-in-product&utm_medium=et&utm_campaign=emojireactionemail#app>
