### ISSUE TITLE
AppleWatch: Voice Messages are recorded extremely fast

### ISSUE THREAD

**Issue by anon1338** [TelegramMessenger/Telegram-iOS#140]
When I send voice messages with my Apple Watch they are recorded extremely fast (chipmunk style).
I tried restarting iPhone and Watch, reinstalling the App. I even changed the iPhone. But I still have the issue. On my iPhone the recordings are normal.

Environment:

Apple Watch: WatchOs 6
IPhone: tested with iOS 13 and iOS 13.1 beta 2

**Comment by laktyushin** [comment]
What is your app version? Is it 5.11?

**Comment by laktyushin** [comment]
Fixed in 5.11
