### ISSUE TITLE
Submitted to Apple Store, but got rejected

### ISSUE THREAD

**Issue by sunwaylive** [TelegramMessenger/Telegram-iOS#1405]
Hi, dear friends:
      Recently, I have created my own unofficial Telegram based on the official repo (added some new features), I have replaced the icon, name and some other basic information. 
     And then I submitted my app to the Apple Store, but got the reply as follows, how to pass the Apple review, can anyone give me a hand please ?
    If succeed, I can offer some tips :)  My email: sunwayliving2@gmail.com  
 
<img width="1273" alt="111" src="https://github.com/TelegramMessenger/Telegram-iOS/assets/3489246/4003baf9-9493-4d0f-aeff-09133914e193">

**Comment by ali-fareed** [comment]
You can remove the UIBackgroundModes values that you don't need.
