### ISSUE TITLE
Add New Language

### ISSUE THREAD

**Issue by laichunhui** [TelegramMessenger/Telegram-iOS#1409]
### Description
I need to add Traditional Chinese language support, and I have made the changes shown in the sample image. But it doesn't work.
<img width="273" alt="截屏2024-05-29 18 13 30" src="https://github.com/TelegramMessenger/Telegram-iOS/assets/11333652/6257db81-cda8-402a-89e2-8fd690277ebc">
<img width="545" alt="截屏2024-05-29 18 10 27" src="https://github.com/TelegramMessenger/Telegram-iOS/assets/11333652/a24bdb63-df5a-45fe-b402-863d39ea190a">
<img width="594" alt="截屏2024-05-29 18 10 58" src="https://github.com/TelegramMessenger/Telegram-iOS/assets/11333652/284b3495-baed-462b-b590-0037ee99c66a">
<img width="932" alt="截屏2024-05-29 18 11 49" src="https://github.com/TelegramMessenger/Telegram-iOS/assets/11333652/75a5b7a2-d405-4ec3-8d6f-50c11e405f9f">

### Steps to Reproduce
Should I modify the availableOfficialLocalizations configuration, and how to modify it?
`
         for info in localizationListState.availableOfficialLocalizations {
                    if existingIds.contains(info.languageCode) {
                        continue
                    }
                    existingIds.insert(info.languageCode)
                    entries.append(.localization(index: entries.count, info: info, type: .official, selected: info.languageCode == activeLanguageCode, activity: applyingCode == info.languageCode, revealed: revealedCode == info.languageCode, editing: false))
                }
`

### Screenshots and Videos 
Remove, if not applicable

### Environment
**App version:** `10.11`

**Comment by ali-fareed** [comment]
Translations are downloaded from the server: https://translations.telegram.org/zh-hant/
