### ISSUE TITLE
Weird UI glitch

### ISSUE THREAD

**Issue by ethylmorphine** [TelegramMessenger/Telegram-iOS#141]
iOS 12.4.1, Telegram 5.11, iPhone 7. The video speaks for itself, I can’t quite describe it better. I just tried to share an article and that happened. I managed to “fix” it by restarting the app.

[https://drive.google.com/file/d/1eOw-C1dVouCdFHYWgzoq963xT3CJMqnM/view?usp=drivesdk]()

**Comment by laktyushin** [comment]
Fixed in 5.11.1
