### ISSUE TITLE
Crashe on iOS 13

### ISSUE THREAD

**Issue by EngineHG** [TelegramMessenger/Telegram-iOS#142]
`
var statusBarWindow: UIView? {

    if let statusBarWindow = UIApplication.shared.value(forKey: "statusBarWindow") as? UIWindow {
        return statusBarWindow
    }
}
`

When getting an internal property, it crashes

**Comment by laktyushin** [comment]
Currently the app is meant to be built with iOS 12 SDK only, use Xcode 10.3 for that.
