### ISSUE TITLE
Group Messages Not Marked as Read

### ISSUE THREAD

**Issue by p3lo** [TelegramMessenger/Telegram-iOS#1428]
### Checklist
- [ x ] I am reporting an issue in existing functionality that does not work as intended
- [ x ] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
Since last month, I've noticed that group messages are not being marked as read after viewing them. This issue is particularly inconvenient as it disrupts the tracking of read and unread messages within group chats.

### Expected Behavior
After viewing the messages in the group chat, they should be marked as read.

### Actual Behavior
The messages remain marked as unread even after scrolling through them.

### Steps to Reproduce
1. Open Telegram.
2. Navigate to a group chat with unread messages.
3. Scroll through the unread messages.

### Screenshots and Videos 
Remove, if not applicable

### Environment
**Device:** Iphone 14 pro max

**iOS version**: 17.5.1

**App version:** 10.14

**Comment by xezrunner** [comment]
I am also encountering with issue, but with all chat types, including groups, channels and private chats. Scrolling is affected within the chats too.

iOS 17.5.1 and iOS 18 Beta 2 on iPhone 14 Pro Max

This does not occur on the desktop apps (macOS native app and Unigram on Windows)

https://github.com/TelegramMessenger/Telegram-iOS/assets/8061077/f4ba37d7-fec2-494c-a084-e0c50261824d

**Comment by xezrunner** [comment]
Looks like this is fixed on my end, though I'm not sure if it was 10.14.1 or a server-side change that fixed it.

I was still having the issue for a while after updating the app, but the issue appears to be resolved now.

**Comment by p3lo** [comment]
10.14.1 fixed this issue.
