### ISSUE TITLE
Telegram mini apps сlose on swipe after update

### ISSUE THREAD

**Issue by devjavy** [TelegramMessenger/Telegram-iOS#1447]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
I'm making a webapp that uses swipe gesture a lot. I've found a solution that helped me to prevent swipe, but after the last update this function seems to be broken (not only in my app, even in other apps using the same method, like tapswap). Here's the [link to code](https://github.com/deptyped/vue-telegram/issues/11#issuecomment-1999265843) I've been using to prevent close on swipe 

### Expected Behavior
My app should close only when user presses "Cancel" or swipes app holding the special header (I'm not sure how to call this part, the one with a title of app)

### Actual Behavior
App's closing when i'm making a swipe inside my page, even if I have a touchmove and touchstart events on both body element and swipeable element

### Steps to Reproduce
1. Copy the code from [here](https://github.com/deptyped/vue-telegram/issues/11#issuecomment-1999265843)
2. Make a swipe inside app

### Environment
**Device:** `iPhone 13 Pro Max`

**iOS version**: `17.5.1`

**App version:** `Telegram iOS 10.14.1 (29180)`

**Comment by TraderLeon** [comment]
try your solution today but it doesn't work. I guess it's due to the new version of telegram 6.30.  However, it seems that Tapswap still works

**Comment by devjavy** [comment]
> try your solution today but it doesn't work. I guess it's due to the new version of telegram 6.30. However, it seems that Tapswap still works

It seems they fixed it yesterday. It was closing like my app when I reported it.
Still, I can't find any suggestions in their code how they fixed this issue. Is there any working solution that helps to prevent swipe down on iOS?

**Comment by TraderLeon** [comment]
I am checking with TON staff now

devjavy ***@***.***>于2024年7月8日 周一17:26写道：

**Comment by TraderLeon** [comment]
it seems that a new api 7.7 could sovle this with 
Added the field isVerticalSwipesEnabled and the methods enableVerticalSwipes, disableVerticalSwipes to the class [WebApp](https://core.telegram.org/bots/webapps#initializing-mini-apps).
however, when I try to use it, it is said 7.7 is not supported yet

**Comment by pietrociatta** [comment]
Any update on why it says 7.7 not supported? I see that is a client problem stuck at version 7.4

**Comment by muhammadsalam** [comment]
hey everyone. did anyone solve that problem?
