### ISSUE TITLE
App icon badge unexpectedly appears when closing app

### ISSUE THREAD

**Issue by xezrunner** [TelegramMessenger/Telegram-iOS#1461]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
When closing the app with no unread messages, a badge sometimes appears on the app icon when it shouldn't.

Opening and closing the app often fixes it, but the behavior is very random.

This may be related to the iOS 18 Beta.

### Expected Behavior
The badge should reflect non-muted, unread items

### Actual Behavior
App icon badge is inconsistently glitching out on app exit

### Steps to Reproduce
1. Open Telegram
2. Close Telegram
3. Observe badge
4. Repeat

### Screenshots and Videos 
https://github.com/user-attachments/assets/a9dc4241-5b81-456a-a9a4-c543fb287d80

### Environment
**Device:** `iPhone 14 Pro Max`

**iOS version**: `18.0 Beta 4 (22A5316j)`, `iOS 18.0 Beta 6 (22A5338b)`, `iOS 18.0 Beta 8 (22A5350a)`

**App version:** `10.14.2 (29212)`, `11.0 (29502)`, `11.0.2 (29522)`

**Comment by Thazzr** [comment]
Confirm bug
iOS 18 Developer Preview 4
Telegram 10.14.2

**Comment by iamfromreallife** [comment]
Can confirm.

**Comment by xezrunner** [comment]
Still happening on 10.15.1 as well, iOS 18 Beta 5 (`22A5326f`)

**Comment by iamfromreallife** [comment]
Still happening on ios 18 Beta 6.

**Comment by iamfromreallife** [comment]
This is still not resolved. IOS 18 is just around the corner.

**Comment by xezrunner** [comment]
I can also confirm that this is still an issue in iOS 18.0 Beta 8 (22A5350a)

I haven't seen any reports of this happening in other apps. The Feedback app entry I filed for Telegram specifically shows that there are More than 10 similar reports, so users are reporting this with Telegram specifically.

**Comment by CarlosJoseChaconChavarria** [comment]
still an issue

**Comment by xezrunner** [comment]
The Feedback report I made in the Feedback app had its Resolution status change to "Potential fix identified - For a future OS update".

This might be an OS-side issue after all and could get fixed in an iOS update.

Leaving this open still, as it's still something Telegram for iOS developers should look into.

![image](https://github.com/user-attachments/assets/fb25da50-b5dc-44d5-ac14-c248187c3ed3)

**Comment by iamfromreallife** [comment]
IOS 18 rc was released today and still this issue persists. Only happens with telegram but as per the screenshot above, could be apple's to fix.

**Comment by xezrunner** [comment]
> IOS 18 rc was released today and still this issue persists. Only happens with telegram but as per the screenshot above, could be apple's to fix. 

I saw somebody mention that this is also happening with TikTok in some scenarios, so that suggests it is more of an iOS-side issue.

I doubt Apple is going to issue another build instead of the RC for release, so perhaps this is to be fixed in an upcoming minor update, or 18.1 in October.

**Comment by Dantasstic** [comment]
This issue still exists on iOS 18 and Telegram 11.1.1

**Comment by xezrunner** [comment]
It appears to have been fixed with iOS 18.1 Beta 4.

**Comment by DarthChillash** [comment]
Does that means that it wasn't a Telegram bug but actually an iOS18 bug? It seems to be fixed for me as well on latest 18.1 beta.

**Comment by xezrunner** [comment]
> Does that means that it wasn't a Telegram bug but actually an iOS18 bug? It seems to be fixed for me as well on latest 18.1 beta.

Yes, that appears to have been the case, as some people also reported this with TikTok.

Closing this, as it is fixed from the iOS side.

**Comment by Dantasstic** [comment]
> Yes, that appears to have been the case, as some people also reported this with TikTok.
> 
> Closing this, as it is fixed from the iOS side.

Err, how come it doesn't happen with Spark, Signal, Discord, Skype, or other apps that have message notification badge counters if this is an "iOS issue" only? How have those devs worked around it, and if that can be down, why can't the Telegram devs?

**Comment by iamfromreallife** [comment]
Fixed in 18.1 beta 5. It really was an IOS issue.

**Comment by Dantasstic** [comment]
> Fixed in 18.1 beta 5. It really was an IOS issue.

...No, it was an iOS 18 _and_ **Telegram** issue. 

It is _not_ an iOS 18 and Signal issue, or iOS 18 and Discord issue. But sure, let's just "hand wave" those away other messenger apps without issues in iOS 18 away 🙄

**Comment by xezrunner** [comment]
To me, it seems like a handful of apps (Telegram and TikTok are the ones I'm aware of) handle the badge APIs a bit differently to most apps that were unaffected by this. That is what was broken in 18.0.

> To add to that, lots of us don't run iOS Beta builds, so we all gonna be stuck with this issue until the end of October when 18.1 drops RC? Nah fam, that ain't it. 👋

Apple acknowledged this bug on their side, as the issue was reported in their Feedback Assistant specifically with Telegram and received a change of status (see above):

> Potential fix identified - For a future OS update

Now we know that the future OS update is definitely 18.1, but it doesn't rule out that an earlier 18.0.1 could also fix it.

Historically, it doesn't seem like the iOS Telegram app developers fix/comment on issues within this repository, nor on their official bug tracker, so the more likely scenario for a fix is with an iOS update.

**Comment by AquaSimulacra** [comment]
Can confirm. The bug is fixed in iOS 18.1 Beta 5.
