### ISSUE TITLE
[Feature Request] Show user id in profiles

### ISSUE THREAD

**Issue by Neurotoxin001** [TelegramMessenger/Telegram-iOS#147]
It's very usefull for ban people in all chats where I have my bot because bots can only ban by id if there is no people in chat with bot.

Now for view id I must use Nicegram for iOS, because official iOS TG app doesn't support this.

**Comment by shivanraptor** [comment]
I think the User ID is not interested by most of the users of Telegram.

**Comment by Neurotoxin001** [comment]
At least add this checkmark to debug menu...

**Comment by SGmuwa** [comment]
We can implement it this way: a long press on the contact name shows its id.

**Comment by Neurotoxin001** [comment]
> We can implement it this way: a long press on the contact name shows its id.

It's would be great.

**Comment by Derad6709** [comment]
Any updates?

> We can implement it this way: a long press on the contact name shows its id.

**Comment by SGmuwa** [comment]
> Any updates?
> 
> > We can implement it this way: a long press on the contact name shows its id.

No, I didn’t manage to implement this
