### ISSUE TITLE
Required Xcode version is 15.2, but 15.4 is reported by 'xcode-select -p'

### ISSUE THREAD

**Issue by mabeljarsdel** [TelegramMessenger/Telegram-iOS#1487]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
Describe the issue that you are experiencing

### Expected Behavior
Tell us what should happen

### Actual Behavior
Tell us what happens instead

### Steps to Reproduce
1.  Clone the repo
2. Have installed Xcode 15.4
3. run the generate script:
```
python3 build-system/Make/Make.py \
    --cacheDir="$HOME/telegram-bazel-cache" \
    generateProject \
    --configurationPath=build-system/template_minimal_development_configuration.json \
    --xcodeManagedCodesigning
```

### Screenshots and Videos 
Remove, if not applicable

### Environment
**Device:** `iPhone/iPad X`

**iOS version**: `13.X`

**App version:** `7.X`

**Comment by ali-fareed** [comment]
You can either install Xcode 15.2 or use README.

**Comment by mabeljarsdel** [comment]
@ali-fareed , why do you force me to install Xcode 15.2? I wanna use Xcode 15.4.

**Comment by yarodevuci** [comment]
@mabeljarsdel did you figure it out?
