### ISSUE TITLE
itms-services://?action=download-manifest&url= 

### ISSUE THREAD

**Issue by KupQ** [TelegramMessenger/Telegram-iOS#1490]
### Checklist
- [ I am reporting an issue in existing functionality that does not work as intended ]
- [  I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues) ]

### Description
The telegram in-app browser does not currently support the "itms-services://?action=download-manifest&url=" URL format, which is commonly used for installing applications on iOS devices. In contrast, Safari and other browsers fully support this format. Forcing users to use the in-app browser negatively impacts the iOS distributing experience. We hope that this issue will be addressed in a future update.

### Expected Behavior
The itms-services URL, which ends with a .plist file, prompts an installation dialog for the user in default browsers.  

### Actual Behavior
On the other hand, the Telegram in-app browser does trigger the itms-services URL, but it results in a blank screen. without appearing any installation dialog.  

### Environment
**Device:** `iPhone 15 pro Max`

**iOS version**: `18`

**App version:** `10.15.1`

**Comment by zwaggy12** [comment]
the best 🥇

**Comment by KupQ** [comment]
> Change the browser in the Telegram settings. This error has nothing to do with the telegram, especially it is not a bug. If you need manifest to distribute pirated applications, use a regular safari

If Telegram is being used on Apple Ecosystem, it must support functionalities that are standard for it, including a proper distribution of manifests.

**Comment by soufgameyt** [comment]
i am facing the same issue here i hope they fix it very soon

**Comment by Ravand-Tech** [comment]
> ### Checklist
> * [ I am reporting an issue in existing functionality that does not work as intended ]
> * [  I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues) ]
> 
> ### Description
> The telegram in-app browser does not currently support the "itms-services://?action=download-manifest&url=" URL format, which is commonly used for installing applications on iOS devices. In contrast, Safari and other browsers fully support this format. Forcing users to use the in-app browser negatively impacts the iOS distributing experience. We hope that this issue will be addressed in a future update.
> 
> ### Expected Behavior
> The itms-services URL, which ends with a .plist file, prompts an installation dialog for the user in default browsers.
> 
> ### Actual Behavior
> On the other hand, the Telegram in-app browser does trigger the itms-services URL, but it results in a blank screen. without appearing any installation dialog.
> 
> ### Environment
> **Device:** `iPhone 15 pro Max`
> 
> **iOS version**: `18`
> 
> **App version:** `10.15.1`

Also getting same problem i hope they can fix it as soon as possible

**Comment by KupQ** [comment]
This issue has been fixed. i guess there was an internal update for this.

**Comment by HRP-Harper** [comment]
I'm having a problem. If you could contact me via Telegram to resolve it, I would be very grateful. My username is @HRP_Harper

**Comment by KupQ** [comment]
@gyke69 that my telegram.

**Comment by uoj372362-source** [comment]
Ok
