### ISSUE TITLE
Send Message URL Scheme not working

### ISSUE THREAD

**Issue by de1mat** [TelegramMessenger/Telegram-iOS#15]
I used to integrate with Telegram via my app, and allow users to send prepopulated messages using the following URL Scheme:  `tg://msg?text=Hello&to=+42333`

Where the `to` would match to an existing Contact if present in Telegram, and the `text` would autofill as the message.

Sometime over the last month or so this has stopped working. Are we able to restore this feature?

**Comment by MisutaaUrufu** [comment]
This hasn't been working in the iOS version of Telegram X (which is now just Telegram). When they switched to Swift they seem to of broken the URI scheme.

Same with Siri too. She just keeps saying "who do you want to send it to" in a loop.

+1 needs fixed.

**Comment by de1mat** [comment]
I can see that this has been fixed ... kind of. It only works if the Telegram app is already open in the background. If you force close Telegram, and then try the URL Scheme, then Telegram opens, but the scheme is not activated.

**Comment by spankders** [comment]
is this still working because its not working for me
