### ISSUE TITLE
How to unblock adult content

### ISSUE THREAD

**Issue by SteveYf** [TelegramMessenger/Telegram-iOS#152]
From home screen of Telegram, keep tapping on settings icon 10 times continuously to see a debug menu.  What options are turned on or off afterwards?

**Comment by laktyushin** [comment]
There's no such option. Use web.telegram.org or desktop apps.

**Comment by jollygee** [comment]
Unlocked + 18 content

**Comment by jerieluchiha18** [comment]
how?

**Comment by vicky0718** [comment]
how??
