### ISSUE TITLE
Could not find a valid aps-environment entitlement in the provided provisioning profiles 

### ISSUE THREAD

**Issue by iosdemo66** [TelegramMessenger/Telegram-iOS#1524]
python3 build-system/Make/Make.py \
    --cacheDir="$HOME/telegram-bazel-cache" \
    generateProject \
    --configurationPath="$HOME/telegram-configuration/development-configuration.json" \
    --codesigningInformationPath="$HOME/telegram-configuration/fake-codesigning" \
    --disableProvisioningProfiles \
    --disableExtensions

Why check for an xcode project that only wants to build a simulator to run

**Comment by ali-fareed** [comment]
Please follow the README.
