### ISSUE TITLE
Adding external dependency!

### ISSUE THREAD

**Issue by Tilak1028-st** [TelegramMessenger/Telegram-iOS#1557]
How can I add the external dependency ?

Is there any doc for this to follow?

@ali-fareed can you please help me

**Comment by ali-fareed** [comment]
You can follow Bazel documentation.

**Comment by Tilak1028-st** [comment]
> You can follow Bazel documentation.

@ali-fareed I have to migrate bazel from WORKSPACE to Module based for using the external dependency. I tried to migrate it but not able to achieve any document that will help me. 

I have use this as resource:  https://github.com/bazelbuild/bazel/issues/18958
