### ISSUE TITLE
[Feature Request] Easy way to switch accounts

### ISSUE THREAD

**Issue by rvnikita** [TelegramMessenger/Telegram-iOS#157]
Please add easy way to switch accounts in ios telegram account.
Please see how Gmail ios account do that (a very convenient way to do it).
Example in gmail: https://www.youtube.com/watch?time_continue=5&v=tNKhhAu65r4

**Comment by laktyushin** [comment]
You can long tap the Settings tab icon to easily switch between accounts.

**Comment by rvnikita** [comment]
That anyway 2 clicks instead of 1 swipe :(
Better than nothing, but could be better.
