### ISSUE TITLE
Confusing vibration for newly saved message

### ISSUE THREAD

**Issue by tooomm** [TelegramMessenger/Telegram-iOS#159]
When I save a message with Telegram Desktop and open Telegram on iOS, the iPhone vibrates but doesn't show a notification or something.
At fist i was very confused but found out that it's because the "new" saved message.

Since this message is not new to me, only for the device, it should not trigger any sound, vibration or notification.

Telegram iOS 5.11.1
iOS 13

**Comment by laktyushin** [comment]
Fixed in 5.12
