### ISSUE TITLE
no provisioning profile was found named 'iOS Team Provisioning Profile: 104d3ba1c63b0d7a'

### ISSUE THREAD

**Issue by hanytmail** [TelegramMessenger/Telegram-iOS#1591]
Simulator run tips：no provisioning profile was found named 'iOS Team Provisioning Profile: 104d3ba1c63b0d7a'
![screenshot-20241015-144245](https://github.com/user-attachments/assets/d5f3dc99-2eb6-4954-b40a-8ffe6b17179e)

**Comment by antoniopantaleo** [comment]
Take a look here: #1568

**Comment by hanytmail** [comment]
> 看看这里：#1568

thank you
