### ISSUE TITLE
Test accounts don't work

### ISSUE THREAD

**Issue by Anatoli4** [TelegramMessenger/Telegram-iOS#1594]
- [x ] I am reporting an issue in existing functionality that does not work as intended
- [ x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
I try logging in with test accounts, no combination succeeds. (https://core.telegram.org/api/auth#test-accounts)

### Expected Behavior
Enter number +7 999 661 4321, enter code 111111 and get error "Wrong code please try again later"

### Actual Behavior
Complete login flow with test accounts. 

### Steps to Reproduce
1.  Enter test account number like +7 999 66X YYYY. X - 1-3, YYYY - random numbers.
2. Enter code XXXXXX.

### Environment
**Device:** `iPhone 15`

**iOS version**: `18.0.1`

**App version:** `11.2.1 (29722)`

**Comment by ali-fareed** [comment]
Unless iOS-specific, this issue should be filed at https://bugs.telegram.org
