### ISSUE TITLE
"This channel can't be displayed because it was used to spread pornographic content".

### ISSUE THREAD

**Issue by Victorio115** [TelegramMessenger/Telegram-iOS#161]
I have entered a telegram channel with NSFW art, and no real-life porn on it, from App Store version of MacOS App, and the app displayed me that message.  
  
I've tried downloading an app version which is offered from the telegram's website, and stoped seeing that message.  
  
But that message appears me when I'm trying to see that channel from iOS App.  
  
That message has stopped appearing me when I've singed in on Telegram Web from my iPhone.  
  
It seems, Apple is blocking NSFW channels in telegram applications, because the same is not happening in the app for android and the app for other computer operating systems.  
  
Will it be solved in a future update?  
  
I've seen some Text Channels on some Discord Servers, which contains NSFW content on it, and I haven't had a problem like this. I think because Discord has an option to mark a Text Channel on a Server has NSFW Channel, and display a waring before entering on that channel.  
  
I suggest: Adding an option to mark a Telegram Channel, or a Telegram Group as NSFW, to add a waring before entering in a channel or a group.  
  
*Previously posted [on r/Telegram](https://www.reddit.com/r/Telegram/comments/d7nu7f/this_channel_cant_be_displayed_because_it_was/).*

**Comment by ethylmorphine** [comment]
Apple goes nuts about porn and piracy. I don’t think Telegram devs can do something about it. I suggest you to use either PC or Android version.

**Comment by LarsBoeckel** [comment]
There is a Fork of telegram called nicegram. This allows you to get the nsfw chats with apples approved method. Official telegram still lacks this option and nicegram is a bit behind in development because the source is behind the releases. So my suggestion to the telegram team: take a look at nicegram or open your source in time please. Thanks.

**Comment by Eerosal** [comment]
> I suggest: Adding an option to mark a Telegram Channel, or a Telegram Group as NSFW, to add a waring before entering in a channel or a group.

^This. 

How are other apps evading the rule or complying with it? Wouldn't it just be enough to warn the user before seeing content of the channel? Since there is already a system for flagging the groups based on reports, I don't see reason why it would be difficult to allow users set the group to "nsfw mode". Similar system to Discord. I think would also significantly reduce the amount of reports.

**Comment by LarsBoeckel** [comment]
The system is now in place. You can enable it in the settings of another application.

**Comment by iDevPro** [comment]
> There is a Fork of telegram called nicegram. This allows you to get the nsfw chats with apples approved method. Official telegram still lacks this option and nicegram is a bit behind in development because the source is behind the releases. So my suggestion to the telegram team: take a look at nicegram or open your source in time please. Thanks.

Also doesn't support this type of channel with same error :)

**Comment by iDevPro** [comment]
> > I suggest: Adding an option to mark a Telegram Channel, or a Telegram Group as NSFW, to add a waring before entering in a channel or a group.
> 
> ^This.
> 
> How are other apps evading the rule or complying with it? Wouldn't it just be enough to warn the user before seeing content of the channel? Since there is already a system for flagging the groups based on reports, I don't see reason why it would be difficult to allow users set the group to "nsfw mode". Similar system to Discord. I think would also significantly reduce the amount of reports.

Like all Apple products move you to child group :))))) And you can't see what you want although you buy this device yourself and you above 21 year  :)

**Comment by Kylmakalle** [comment]
> Also doesn't support this type of channel with same error :)

You're probably facing Region-block or global ban (for something illegal)
Read more: https://nicegram.app/unblock#additional-notes

**Comment by M4DGENIUS0** [comment]
And What About Android Users
Any one Can Help Im Entering into non-pornographic Channel and still its Showing Me The Same Error

**Comment by DanteMarshal** [comment]
> 
> 
> And What About Android Users
> Any one Can Help Im Entering into non-pornographic Channel and still its Showing Me The Same Error

Same here
I tried all possible solutions I could find on the internet.
They said there's an option in Privacy and Security on the Web versions, And there's none.
Also said install APK from telegram.org and yet there's still nothing there to switch this off.

**Comment by tilsgee** [comment]
> And What About Android Users Any one Can Help Im Entering into non-pornographic Channel and still its Showing Me The Same Error

This. Still waiting.  Or i just use 3rd party telegram app instead?

**Comment by gzqx** [comment]
There is an option in the desktop version of telegram, in privacy and security, disable the filter and restart ios app will allow it to show "pornographic" content.

**Comment by foldfree** [comment]
I have this message with one pornographic channel, while others adult channel are not affected. I have disabled filtering and I'm using the foss version of telegram on android. What could be the issue?

**Comment by EthanHuntProductions** [comment]
How to create  porn-ios channel

**Comment by EthanHuntProductions** [comment]
How to make porn-ios group

**Comment by EthanHuntProductions** [comment]
Anyone have porn-ios channel & group please contact me.

**Comment by Sanju1t85** [comment]
> How to create porn-ios channel

**Comment by Sanju1t85** [comment]
Please help anybody, I want to know how to create iOS banned channel in telegram 

🙏🙏🙏🙏🙏🙏🙏

**Comment by DreadIron** [comment]
I can relate but you have to read the page in discord  for iOS and do it in
iOS or a laptop with Drivers Liscrnce so what fuck Tim Cook if it was
little boys he’d be all over it which is probably why Apple got caught
iCloud moving kiddie porn evil Mr Rogers cock sucker

**Comment by Sanju1t85** [comment]
Bro can you teach me how to create iOS banned channel if yes then contact here in telegram @san_245

**Comment by TechSlugz** [comment]
Lol all the people saying 'uhmm, sooo I was looking at a group, it had nothing in it, there wasn't any porn, I swear!'. Lol!! I am on an S22+, and guess what..? It still does it! Finally!, I don't know if it's related to the update level, but if I got to

SETTINGS >> PRIVACY & SECURITY >> (Now there are no options related to disabling a sensitive content filter, or anything even remotely close)

So how do I turn off this bloody thing so I can see the porn posts and chat to the local DTF Ladies????

**Comment by Azim-Ahmed** [comment]
<img width="1258" alt="image" src="https://github.com/user-attachments/assets/1a1af253-e564-4cc2-9fbb-931e77640987">
This is the solution I found.

**Comment by Azim-Ahmed** [comment]
<img width="1278" alt="image" src="https://github.com/user-attachments/assets/177cec21-da22-4627-9ba9-b58f934c166f">
This is the solution
