### ISSUE TITLE
Build old version

### ISSUE THREAD

**Issue by MohShMehr** [TelegramMessenger/Telegram-iOS#1611]
How to build old version of telegram (10.2.4) with xcode 16?
I clone the project by "git clone --recursive -j8 https://github.com/TelegramMessenger/Telegram-iOS.git" and checkout to "release-10.2.4" tag and after doing all steps of read me file i run the command for making the xcode project but it leads to error 
could you please help me?

ERROR: /private/var/tmp/_bazel_morz/5b3e148d01ed9f53464afa73ef65a97b/rules_xcodeproj.noindex/build_output_base/external/rules_xcodeproj_generated/generator/Telegram/Telegram_xcodeproj/BUILD:12:10: every rule of type xcodeproj implicitly depends upon the target '@rules_xcodeproj//tools/unique_directories:unique_directories', but this target could not be found because of: error loading package '@rules_xcodeproj//tools/unique_directories': Unable to find package for @rules_python//python:defs.bzl: The repository '@rules_python' could not be resolved: Repository '@rules_python' is not defined.
ERROR: Analysis of target '@rules_xcodeproj_generated//generator/Telegram/Telegram_xcodeproj:Telegram_xcodeproj' failed; build aborted: Analysis failed
INFO: Elapsed time: 0.082s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (4 packages loaded, 1 target configured)
    currently loading: @rules_xcodeproj//tools/generators/pbxnativetargets ... (7 packages)
ERROR: Build failed. Not running target
Traceback (most recent call last):
  File "/Users/morz/work/ios/Telegram-last/Telegram-iOS/build-system/Make/Make.py", line 1050, in <module>
    generate_project(bazel=bazel_path, arguments=args)
  File "/Users/morz/work/ios/Telegram-last/Telegram-iOS/build-system/Make/Make.py", line 568, in generate_project
    generate(
  File "/Users/morz/work/ios/Telegram-last/Telegram-iOS/build-system/Make/ProjectGeneration.py", line 53, in generate
    generate_xcodeproj(build_environment, disable_extensions, disable_provisioning_profiles, include_release, generate_dsym, configuration_path, bazel_app_arguments, target_name)
  File "/Users/morz/work/ios/Telegram-last/Telegram-iOS/build-system/Make/ProjectGeneration.py", line 46, in generate_xcodeproj
    call_executable(bazel_generate_arguments)
  File "/Users/morz/work/ios/Telegram-last/Telegram-iOS/build-system/Make/BuildEnvironment.py", line 81, in call_executable
    subprocess.check_call(resolved_arguments, env=resolved_env)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/morz/work/ios/Telegram-last/Telegram-iOS/build-input/bazel-6.4.0-darwin-arm64', 'run', '//Telegram:Telegram_xcodeproj', '--override_repository=build_configuration=/Users/morz/work/ios/Telegram-last/Telegram-iOS/build-input/configuration-repository', '--//Telegram:disableExtensions', '--//Telegram:disableStripping']' returned non-zero exit status 1.

**Comment by ali-fareed** [comment]
It is not possible to build an old version with Xcode 16.

**Comment by alirezarabiei7239** [comment]
@ali-fareed 
Is it really impossible mission ?
