### ISSUE TITLE
Clicking on the clock does not trigger "scroll to top"

### ISSUE THREAD

**Issue by tooomm** [TelegramMessenger/Telegram-iOS#162]
As used from all over the iOS system and many many apps, I miss that Telegram App does not scroll to the top of lists when clicking on the clock.

For example you are scrolling your list of available chats all the way down. And now you want to text the persons you text most... on top of the list.
It would be very handy to just click on the clock/time in the top status bar to get to the beginning of the list instead manually scrolling through all entries again.

Telegram iOS 5.11.1
iOS 13

**Comment by laktyushin** [comment]
Fixed in 5.12

**Comment by tooomm** [comment]
Awesome!
