### ISSUE TITLE
Why can't you register a new account after successful source code compilation?

### ISSUE THREAD

**Issue by hanytmail** [TelegramMessenger/Telegram-iOS#1620]
Why can't you register a new account after successful source code compilation?

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
https://github.com/Telegram-FOSS-Team/Telegram-FOSS/issues/639
It seems to be a special limitation.

**Comment by ali-fareed** [comment]
Account registration is limited to official Telegram apps.
