### ISSUE TITLE
bug with privacy secret photos

### ISSUE THREAD

**Issue by Kiryakor** [TelegramMessenger/Telegram-iOS#1648]
### Description
You can open and screen a secret photo through notifications

### Expected Behavior
You cannot view or take a screenshot of a secret photo through notifications

### Actual Behavior
You can take a screenshot of a secret photo through notifications, and the machine will think that the photo has not been viewed

### Steps to Reproduce
1. Receive a notification with a disappearing photo
2. Long press to open push
3. A secret photo opens that you can screenshot

### Environment
**Device:** `iPhone 15 pro`

**iOS version**: `18.1.1`

**App version:** `11.5.2`

**Comment by Kiryakor** [comment]
photo 

![telegram-cloud-photo-size-2-5422419219796058336-y](https://github.com/user-attachments/assets/795b82ec-210a-4681-beec-0c15d23d936c)

**Comment by ali-fareed** [comment]
Fixed in 11.5.3.
