### ISSUE TITLE
Alarming power/battery usage by Notifications in update 11.5.2

### ISSUE THREAD

**Issue by andresmakesgames** [TelegramMessenger/Telegram-iOS#1649]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description

iPhone 16 Pro Max on iOS 18.2, Telegram version 11.5.2. I began noticing significant battery drain after updating to iOS 18.2 and updating my applications; I tracked this down to, of all things, Telegram notifications. My phone is now draining almost twice as fast as it used to - from the exact same or even less usage. If I disable Telegram notifications, my battery usage rate goes back to the normal expected rate.

I don't believe this is a quantity of notifications issue, as I don't typically receive more than a handful of notifications per hour. I have even left muted channels that were busier to verify this, but I'm still seeing the same drain rate. I did a handful of experiments with leaving messages in the Lock Screen unread, and just unlocking my phone and using it, but I haven't yet been able to pinpoint any deterministic patterns.

This Reddit thread appears to have other people experiencing this same issue: https://www.reddit.com/r/Telegram/comments/1hhxcb2/new_telegram_update_1152/

### Expected Behavior
While Telegram notifications are enabled, the impact to battery should be roughly the same as it was for prior updates. 

### Actual Behavior
While Telegram notifications are enabled, impact to battery is dramatically higher than prior updates.

### Steps to Reproduce
1. Update to latest Telegram version.
2. Enable Telegram notifications.
3. Use Telegram for an hour, on and off.
4. Disable Telegram notifications.
5. Use Telegram for another hour, on and off.
6. Go to iOS Settings > Battery and review the battery usage. Note the massive discrepancy between costs.

### Environment
**Device:** iPhone 16 Pro Max

**iOS version**: `18.2`

**App version:** `11.5.2`

**Comment by absolutelynothelix** [comment]
can confirm on iphone 11, ios 18.2, telegram 11.5.2. for me, when telegram is open, the phone gets noticeable warmer within a minute. this makes the app literally unusable.

**Comment by RepliedSage11** [comment]
Same thing on an iPhone 15 Pro with 18.2 and iPhone 11 Pro Max with 18.2. The battery drain is very noticeable after the update.

**Comment by Backhomejjk** [comment]
Hello

**Comment by absolutelynothelix** [comment]
[a very active telegram bugs report regarding this issue](https://bugs.telegram.org/c/46625)

**Comment by JonnyKong** [comment]
Can confirm on an iPhone 14 Pro with iOS 18.2 and telegram 11.5.2.

**Comment by abcen7** [comment]
Same issue on an iPhone 15 Pro with iOS 18.2 and telegram 11.5.2.

**Comment by Schtewee** [comment]
Same here, iPhone 16 Pro Max with iOS 18.1.1 + 18.2 and Telegram 11.5.2

**Comment by sanek3541** [comment]
16 PM, 19.2 , same problem with Telegram 11.5.2 . It is completely useless now

**Comment by AuroraWright** [comment]
Can confirm the issue, and it's not related to notifications, it just drains with the app being open. I downgraded to 11.5.1 with https://github.com/NyaMisty/ipatool-py and no more drain. You can also do this to disable app store updates for the app temporarily: https://github.com/qnblackcat/How-to-Downgrade-apps-on-AppStore-with-iTunes-and-Charles-Proxy/issues/26

**Comment by DorokiDarogan** [comment]
Same issue here, iPhone Pro Max 15 iOS 18.2 TG 11.5.2. Phone gets hot and drains very quickly.

**Comment by cergutiv** [comment]
Hi guys, in the forum thread a user called Vladyslav Skrynnyk found a workaround that worked for me:

Hi everyone,

> I somewhat managed to resolve Telegram’s overheating and battery drain issues by tapping all the “clear,” “reset,” and “optimize” options in the advanced settings I also cleared all the storage cache. You can access these by tapping the “Settings” tab 10 times. Now the app is much better—no major battery drain, though it’s still slightly warm (but this cannot compare with what I experienced a couple days earlier).
> 
> I’ve marked the options I tapped in the attached screenshot. For reference, I’m using iOS 18.2 and Telegram 11.5.2. Hope this helps!
> 
Image of the settings he's referring to (link from the forum image):
https://telegra.ph/file/6e12dd5f332a80b41c78e-c986282f2df4cfc8cd.jpg

From my testing the phone's battery drain was reduced pretty much to normal rate and the phone does not overheat for now.

**Comment by sanek3541** [comment]
I am too lazy to downgrade, just got another telegram client. No issues after I uninstalled telegram official app. 3 days, no fix ? Gg

**Comment by hardlemondrink** [comment]
Same issue on an iPhone 13 with iOS 18.2 and telegram 11.5.2.

**Comment by silveoo** [comment]
Same on iPhone 16 Pro, iOS 18.2, Telegram 11.5.2

**Comment by sshrmr** [comment]
Same on iPhone 15 Pro Max, iOS 18.2, Telegram 11.5.2

**Comment by feelthatvib3** [comment]
> Hi guys, in the forum thread a user called Vladyslav Skrynnyk found a workaround that worked for me:
> 
> > Hi everyone,
> 
> > I somewhat managed to resolve Telegram’s overheating and battery drain issues by tapping all the “clear,” “reset,” and “optimize” options in the advanced settings I also cleared all the storage cache. You can access these by tapping the “Settings” tab 10 times. Now the app is much better—no major battery drain, though it’s still slightly warm (but this cannot compare with what I experienced a couple days earlier).
> > I’ve marked the options I tapped in the attached screenshot. For reference, I’m using iOS 18.2 and Telegram 11.5.2. Hope this helps!
> 
> Image of the settings he's referring to (link from the forum image): https://telegra.ph/file/6e12dd5f332a80b41c78e-c986282f2df4cfc8cd.jpg
> 
> From my testing the phone's battery drain was reduced pretty much to normal rate and the phone does not overheat for now.

https://bugs.telegram.org/c/46625/69 (FEI)

**Comment by nqvan** [comment]
> > Hi guys, in the forum thread a user called Vladyslav Skrynnyk found a workaround that worked for me:
> > > Hi everyone,
> > 
> > 
> > > I somewhat managed to resolve Telegram’s overheating and battery drain issues by tapping all the “clear,” “reset,” and “optimize” options in the advanced settings I also cleared all the storage cache. You can access these by tapping the “Settings” tab 10 times. Now the app is much better—no major battery drain, though it’s still slightly warm (but this cannot compare with what I experienced a couple days earlier).
> > > I’ve marked the options I tapped in the attached screenshot. For reference, I’m using iOS 18.2 and Telegram 11.5.2. Hope this helps!
> > 
> > 
> > Image of the settings he's referring to (link from the forum image): https://telegra.ph/file/6e12dd5f332a80b41c78e-c986282f2df4cfc8cd.jpg
> > From my testing the phone's battery drain was reduced pretty much to normal rate and the phone does not overheat for now.
> 
> https://bugs.telegram.org/c/46625/69 (FEI)

Hi,

i had tried this method but my iphone stil overheat and battery drain. 

My iphone 11 pro ios 17.7 and latest Telegram app version.

I tried use Telegram web and my phone had normal.

how can i fix this error

**Comment by feelthatvib3** [comment]
> > > Hi guys, in the forum thread a user called Vladyslav Skrynnyk found a workaround that worked for me:
> > > > Hi everyone,
> > > 
> > > 
> > > > I somewhat managed to resolve Telegram’s overheating and battery drain issues by tapping all the “clear,” “reset,” and “optimize” options in the advanced settings I also cleared all the storage cache. You can access these by tapping the “Settings” tab 10 times. Now the app is much better—no major battery drain, though it’s still slightly warm (but this cannot compare with what I experienced a couple days earlier).
> > > > I’ve marked the options I tapped in the attached screenshot. For reference, I’m using iOS 18.2 and Telegram 11.5.2. Hope this helps!
> > > 
> > > 
> > > Image of the settings he's referring to (link from the forum image): https://telegra.ph/file/6e12dd5f332a80b41c78e-c986282f2df4cfc8cd.jpg
> > > From my testing the phone's battery drain was reduced pretty much to normal rate and the phone does not overheat for now.
> > 
> > 
> > https://bugs.telegram.org/c/46625/69 (FEI)
> 
> Hi,
> 
> i had tried this method but my iphone stil overheat and battery drain.
> 
> My iphone 11 pro ios 17.7 and latest Telegram app version.
> 
> I tried use Telegram web and my phone had normal.
> 
> how can i fix this error

I wish I could help, but my iPhone still overheats when recording video messages and occasionally gets warm even while texting. It’s a bit unstable. The only option left is to wait for a patch. Some users suggest switching to Nicegram, as long as they don’t update their app and introduce the same issue, like Swiftgram did.

**Comment by nqvan** [comment]
I installed Nicegram while waiting for the update from Telegram. I tried the web version, the phone is still normal but quite inconvenient

**Comment by kostomakha** [comment]
> Same issue on an iPhone 13 with iOS 18.2 and telegram 11.5.2.

Same issue on my iPhone 13 Pro. Before try tips in Advanced (debug) settings, I tried to disable or reduce background updates - no effect, still try to cook my lag from the pocket.

Then,  I go to Tg storage settings menu and reduce cache size to 5Gb, and clear. After this phone starts to cool down immediately.

**Comment by ZenIsBestWolf** [comment]
Same issue on iPhone 15 Pro iOS 18.2

**Comment by nqvan** [comment]
> > Same issue on an iPhone 13 with iOS 18.2 and telegram 11.5.2.
> 
> Same issue on my iPhone 13 Pro. Before try tips in Advanced (debug) settings, I tried to disable or reduce background updates - no effect, still try to cook my lag from the pocket.
> 
> Then, I go to Tg storage settings menu and reduce cache size to 5Gb, and clear. After this phone starts to cool down immediately.

I tried reduce cache size but this method doesn't work for my phone. it still overheats

**Comment by cendyne** [comment]
A new release just went out to the app store

**Comment by nqvan** [comment]
> A new release just went out to the app store

Is this version fix this bugs?

**Comment by cendyne** [comment]
> Is this version fix this bugs?

My iOS devices no longer heat up and my battery is lasting longer

**Comment by wukko** [comment]
funny how there’s no source code for the latest version again

**Comment by ali-fareed** [comment]
Fixed in 11.5.3
