### ISSUE TITLE
Impossible to share a portrait photo from Photo application on iOS 13.1

### ISSUE THREAD

**Issue by xtlabor** [TelegramMessenger/Telegram-iOS#165]
Impossible to share a portrait photo from Photo application on iOS 13.1
Take a portrait photo on main camera, open it in Photo application, share using telegram, chose  the recipient. It won’t be shared.
But it’s possible to share the photo from the telegram itself.

If you sent the photo to anybody as a file from the telegram. It’s still impossible to send a portrait photo from the photo application, even the file was received through the telegram as a file

**Comment by laktyushin** [comment]
Fixed in 5.12.1
