### ISSUE TITLE
a bug The bazel build failed, please check the report navigator, which may have more context about the failure.

### ISSUE THREAD

**Issue by xq312704108** [TelegramMessenger/Telegram-iOS#1652]
This error occurred when I upgraded my mac to 15.1 “The bazel build failed, please check the report navigator, which may have more context about the failure.”

**Comment by xq312704108** [comment]
help

**Comment by xq312704108** [comment]
I need you help

**Comment by rakeshmalviya0069** [comment]
Same issue here can you please write solution?
