### ISSUE TITLE
[Bug] Broken markup

### ISSUE THREAD

**Issue by softeip** [TelegramMessenger/Telegram-iOS#166]
There is a bug after switching keyboard to floating mode and moving it
Finally I have broken markup
[Video](https://drive.google.com/file/d/1XLdfW2ZpNEOleiAe2e-NbKDVzKImFIW_/view?usp=drivesdk)

iPadOS 13.1

**Comment by Erdbeergeist** [comment]
happens for me aswell, also happens while chat window is open

**Comment by softeip** [comment]
Fixed in new version
