### ISSUE TITLE
Telegram iOS app cannot build in xcode

### ISSUE THREAD

**Issue by rakeshmalviya0069** [TelegramMessenger/Telegram-iOS#1663]
Hi,
when i try to download 11.5.2 version source code and try to build in xcode then issue came like this

The bazel build failed, please check the report navigator, which may have more context about the failure

can anyone please help?

screenshot attached.
<img width="1272" alt="Screenshot 2024-12-27 at 11 59 50 PM" src="https://github.com/user-attachments/assets/b5d8320f-0f35-4be4-b02c-46a2fad60370" />

**Comment by liuxingyubm** [comment]
I saw the real machine test you used to make sure that the real machine related certificate configuration is complete?

**Comment by liuxingyubm** [comment]
You can click command+9 to see what the error is

**Comment by ali-fareed** [comment]
x86_64 simulator is not supported. You can either use an Apple Silicon-based Mac, or build for an actual device.

**Comment by zake1989** [comment]
> x86_64 simulator is not supported. You can either use an Apple Silicon-based Mac, or build for an actual device.

with Apple Silicon-based Mac got same issue with version 11.6

**Comment by kevinkate2025** [comment]
I do not know how to salve this

<img width="1135" alt="Image" src="https://github.com/user-attachments/assets/5b1abbc2-b3db-47d2-b08e-a057cd6e595b" />
