### ISSUE TITLE
#include "<opus/opus.h>" file not found

### ISSUE THREAD

**Issue by kshipeng** [TelegramMessenger/Telegram-iOS#168]
The first compilation error 'opus/opus.h' was not found. How to solve it?

**Comment by XavierLost** [comment]
I do.

**Comment by XavierLost** [comment]
Me too.

**Comment by shivanraptor** [comment]
See #21

**Comment by kshipeng** [comment]
I'm in Mojave and still get this error despite installed yasm and pkg-config
(tested on both Xcode 11 and 10)

**Comment by k1er** [comment]
Has anyone solved this problem? 
Xcode 11 
macOS 10.14.6

**Comment by mr-smit** [comment]
Solution:

open: libtgvoip_Xcode -> libtgvoip -> Build Settings

Go to Search Paths:
Header Search Paths:
$(inherited)
webrtc_dsp
$(PROJECT_DIR)/../ffmpeg/opus/include

And every next error you will see after this is fixed, just fix search paths, because Telegram programmers forgot to do it.

**Comment by mr-smit** [comment]
the other problem that the source code is only for xcode 10.3 not for ios 13 jet

**Comment by xRuby** [comment]
do you connect the server, why error is "Connection reset by peer"

<img width="790" alt="屏幕快照 2019-10-22 上午10 31 46" src="https://user-images.githubusercontent.com/11939075/67255936-306aaa00-f4b7-11e9-9aae-69a39608d837.png">

**Comment by xRuby** [comment]
do you resolved it

**Comment by XavierLost** [comment]
*** Try a lot of methods or not

**Comment by xRuby** [comment]
> Try a lot of methods invalid

run   Scheme -> Telegram-iOS-AppStoreLLC

**Comment by ali-fareed** [comment]
Please see the updated build instructions in README.md.
