### ISSUE TITLE
UI bug: no bot link (mention) near the animated sticker sent from inline menu

### ISSUE THREAD

**Issue by stasusov** [TelegramMessenger/Telegram-iOS#169]
[Bot mention](https://core.telegram.org/bots/inline#spreading-virally) is missing for animated stickers in the latest version of the app. However, non-animated stickers work fine. Moreover, MacOS client (5.7 (181163) AppStore) shows the link for any type of sticker.
The screenshot below is given for an example.

App: Telegram Messenger for iOS v5.11.1 (latest available in store)

<details>
  <summary>Screenshot iOS</summary>

![IMG_118BC0172634-1](https://user-images.githubusercontent.com/9000973/65887298-63cd8380-e3a6-11e9-8dde-f3a428507871.jpeg)  
</details>

<details>
  <summary>Screenshot MacOS</summary>

<img width="326" alt="salkfjdasf" src="https://user-images.githubusercontent.com/9000973/65887537-c1fa6680-e3a6-11e9-98a0-6d4c444d83e5.png">

</details>

**Comment by laktyushin** [comment]
Fixed in 5.12
