### ISSUE TITLE
[Feature request] Support sharing to specific contact in Telegram in the global share dialog

### ISSUE THREAD

**Issue by netvl** [TelegramMessenger/Telegram-iOS#170]
In iOS 13 the share system dialog has been changed significantly - it now can show contacts in various applications to shorten the action sequence needed for sharing, so instead of tapping first on the application and then on the contact name, it is now possible to send something to a contact right away.

![3C51B827-A8C1-4DC6-8EDD-F2EC67DFF51D](https://user-images.githubusercontent.com/280456/66064792-26f4be80-e557-11e9-8e02-41a1201931cf.jpeg)

I don’t know if it is something exposed in the iOS API right now, but it would be great if Telegram supported this, i.e. if it provided icons for contacts for quick sharing.

**Comment by HaikuOezu** [comment]
It most certainly **is** exposed! All it takes is supporting Send Message Intents and the app donating intents when you send a message or use the share extension
It's all outlined very clearly in this guide
https://developer.apple.com/documentation/foundation/app_extension_support/supporting_suggestions_in_your_app_s_share_extension

**Comment by laktyushin** [comment]
Added in 5.12.2.
