### ISSUE TITLE
[Feature Request] Support global dark mode functionality on iOS 13 and iPadOS 13

### ISSUE THREAD

**Issue by ssdeg7** [TelegramMessenger/Telegram-iOS#171]
I love Telegram's dark mode but it limits change to brightness and time. With the global rollout of iOS 13 and iPadOS 13 it would be great to be able to select an option to change to dark mode with the global iOS dark mode framework. Sometimes I want to have dark mode enabled during the day and don't really want to manually change one app at a time and currently this is the only option for Telegram :)

**Comment by laktyushin** [comment]
Added in 5.12.2.
