### ISSUE TITLE
[Theming] The app expects ARGB, not RGBA

### ISSUE THREAD

**Issue by MasterGroosha** [TelegramMessenger/Telegram-iOS#173]
Hello. I'm using Telegram 5.11.1 (15296) on iPad Pro 10.5" 2017
I'm participating in theming contest and having issues with setting transparency in app.

For example, 2F2F2FDE color results in light blue instead of dark gray. And FFFFFF00 results in light yellow instead of plain white.

In tgiostests chat it was suggested that the problem might be here: https://github.com/TelegramMessenger/Telegram-iOS/blob/97eca304f8cee20fad75185bce2189cdb3e98005/submodules/SettingsUI/Sources/Themes/ThemeNameGenerator.swift#L304

**Comment by MasterGroosha** [comment]
It seems that the app expects ARGB, not RGBA (though official [Theme Editor](https://themes.telegram.org/theme/SolidDarkGreen_beta) generates RGBA).

**Comment by laktyushin** [comment]
It is a bug in the online editor. I've reported it to the dev, should be fixed today.

**Comment by laktyushin** [comment]
The issue has been fixed in the editor. The app uses ARGB in its theme files but the editor displays color entries in RGBA and automatically converts them back on save.

**Comment by MasterGroosha** [comment]
Thank you! I guess all existing themes should be edited again if affected with this issue? (I don't have access to editor atm)

**Comment by laktyushin** [comment]
Yes, you have to manually fix all incorrectly saved color entries.
