### ISSUE TITLE
add socks5/http/https proxy suporrt

### ISSUE THREAD

**Issue by xdown-org** [TelegramMessenger/Telegram-iOS#175]
add socks5/http/https proxy suporrt

**Comment by laktyushin** [comment]
You can already use MtProto and SOCKS5 proxies.
Proxy settings are located in Settings > Data & Storage > Proxy.

**Comment by f4nff** [comment]
I didn't find where you are talking.
Friefox ipad does not set the address of the socks5 proxy.
