### ISSUE TITLE
Overlay issue when previewing a chat

### ISSUE THREAD

**Issue by tooomm** [TelegramMessenger/Telegram-iOS#177]
When previewing a chat (long pressing a conversation) the iOS system status bar on the top and the label of the conversation overlap each other and are very difficult to read. That only happens with the "new" preview, the old style worked fine.

Telegram iOS 5.12
iOS 13.1.2
iPhone 5 SE (4")

**Comment by laktyushin** [comment]
I can't reproduce this. The status bar should become hidden when a context menu is presented.
![iPhone SE](https://user-images.githubusercontent.com/491013/66714887-6330e600-edc5-11e9-9002-630c8386364d.png)

**Comment by tooomm** [comment]
It isn’t for me. What’s your phone and software versions?

**Comment by tooomm** [comment]
Fixed now!
