### ISSUE TITLE
[Serverside] VoIP notifications not received by forked apps

### ISSUE THREAD

**Issue by Kylmakalle** [TelegramMessenger/Telegram-iOS#178]
Forked clients not getting VoIP pushes at all. My own fork [Nicegram](https://itunes.apple.com/app/id1457369322) and issues like #131, #49, #34 only approve that.

Unfortunately, creating a unique cert (APNS + VoIP + Sandbox) and uploading it to https://my.telegram.org/apps, does not help.

After small code investigation, it looks like VoIP pushes are very cool "hacks", which syncs messages in background, update bage number and etc. 

Also, VoIP pushes provides:
- Calls
- Live Location Updates
- Datacenter IP updates (useful for countries where Telegram may be blocked)
- Notifications revoke (if message was deleted)
- Remote Sessions revoke

And other... 
Keep in mind, that last two **missing features can harm users' privacy**

Any forked client misses those features which is kinda sad. ☹️
**Q:** Are there any possible ways to enable VoIP notifications for forked Apps on Telegram side?

**Comment by mr-smit** [comment]
I need it too. Why forked Telegram does not receive VoIP pushes when app is closed ?

**Comment by Kylmakalle** [comment]
It looks like VOIP pushes works fine now. Make sure you've properly uploaded certificates to https://my.telegram.org/apps

Unfortunately, iOS 13+ will crash your app in background if you've not invoked some method that shows call screen (even if it was just location update or message fetch, not a call)

For further info please read https://github.com/TelegramMessenger/Telegram-iOS/issues/81#issuecomment-585990544

**Comment by RajatVaghani** [comment]
Hi,

I'm facing the same problem as above.

I've managed to upload the APNS certs from (https://my.telegram.org/apps/apns_cert) but can't find a place to upload any VOIP cert. 

Also, even after uploading the APNS certs, i'm not receiving any messages or notifications when the app is in background. Am I missing something? or is there any delay and I have to wait after uploading them?

**Comment by Kylmakalle** [comment]
@RajatVaghani You can create combined certificate for APNS and VOIP and upload it to the my.telegram.org

![image](https://user-images.githubusercontent.com/24507532/167941424-43772253-91c2-4221-b840-5da2a2ae0803.jpeg)


Any further issues with VOIP pushes that are getting ignored or background crashes are due to iOS 13+ restrictions mentioned above

**Comment by RajatVaghani** [comment]
Hi @Kylmakalle thank you for the reply!

So do I just upload the same cert for sandbox and production?

Is this much enough to make sure push notifications come through?

**Comment by Kylmakalle** [comment]
Yes, It works for me with desired certificate type
