### ISSUE TITLE
Badge shows message count from muted conversations

### ISSUE THREAD

**Issue by dawnerd** [TelegramMessenger/Telegram-iOS#179]
I have a conversation muted but still getting badge numbers for that conversation. I’d expect it would work like desktop and completely mute it. Kinda annoying to see it pop up only to find out it’s the muted ones.

**Comment by ethylmorphine** [comment]
Settings -> Notifications and Sounds -> Badge counter -> disable Include Muted Chats.

**Comment by dawnerd** [comment]
🤦🏻‍♂️ Thanks!
