### ISSUE TITLE
Unable to unhide the archived chats

### ISSUE THREAD

**Issue by medicalwei** [TelegramMessenger/Telegram-iOS#181]
If the Archived Chats are hidden from the chats menu, and the Chats menu is not yet scrollable, I cannot unhide the Archives Chats menu item by pulling down from the menu.

The archived menu item is shown but it is immediately pulled up on touch release and it is not clickable.

Telegram iOS version 5.12 with iOS 13.1.2

**Comment by laktyushin** [comment]
Fixed in 5.12.1
