### ISSUE TITLE
v5.12 Release?

### ISSUE THREAD

**Issue by shivanraptor** [TelegramMessenger/Telegram-iOS#183]
It seems that there is no `release-5.12` yet. Is the v5.11 the last open-source version?

**Comment by shivanraptor** [comment]
Dear Telegram team,
I wish to help debugging the latest version of Telegram, but since version 5.12, source codes are no longer available. Will source code be available in future versions, e.g. 5.13?

Thanks.

**Comment by kebbbnnn** [comment]
Hi, anyone from Telegram team? When are you going to push the latest updates? Or any plans for the future of this repo? We will appreciate any words from you guys :)

**Comment by laktyushin** [comment]
Source code of 5.13 is available now.
