### ISSUE TITLE
Animated sticker cause Telegram iOS crash and lock out user from a chat 

### ISSUE THREAD

**Issue by Hyracan** [TelegramMessenger/Telegram-iOS#186]
So apparently there's a sticker pack that can cause iPhone application of Telegram to crash. Works on last update.

https://t.me/addstickers/julia_the_carterpillar

Even if you open up sticker page on Telegram in your iOS app - it crashes. Some stickers don't crash application immediately, but if you send many of them - your app will crash and chat will be locked out until this stickers to disappear from the loading (e.g. many new messages appear in the chat or stickers deleted).

**Comment by Hyracan** [comment]
![image](https://user-images.githubusercontent.com/22239145/66915667-79cb7d00-f011-11e9-8a5f-d2a6dd5a9870.png)
This sticker cause my iOS app crash instantly, and all other iOS users as well

**Comment by roddyk** [comment]
You are best russian pidor on github

**Comment by laktyushin** [comment]
Fixed in 5.12.1
