### ISSUE TITLE
[Bug] Freezing after choosing a geo-location when creating a geo-chat

### ISSUE THREAD

**Issue by vecherkin** [TelegramMessenger/Telegram-iOS#187]
Steps:

1. Contacts
2. Add People Nearbly
3. Create a Local Group
4. Start Group
5. Change Location
6. Move marker

As a result:
- Unable to close controller
- Unable to set location
- Freeze occurs

Devices:
- iPhone 5s, Xr, X (iOS 12.4.1, 13)

Screenshots (iPhone 5s):
![photo_2019-10-16_17-37-20](https://user-images.githubusercontent.com/9555391/66929450-b57b3c80-f03b-11e9-9a45-d07b9dfead6f.jpg)
![photo_2019-10-16_17-31-25](https://user-images.githubusercontent.com/9555391/66929470-bf04a480-f03b-11e9-99b9-2d20bceac974.jpg)
![photo_2019-10-16_17-31-28](https://user-images.githubusercontent.com/9555391/66929479-c2982b80-f03b-11e9-9638-457a91cfb73d.jpg)
![photo_2019-10-16_17-31-30](https://user-images.githubusercontent.com/9555391/66929483-c5931c00-f03b-11e9-909f-8cd5beabf979.jpg)

**Comment by laktyushin** [comment]
Fixed in 5.12.1
