### ISSUE TITLE
Add support for Siri message announcements

### ISSUE THREAD

**Issue by agottardo** [TelegramMessenger/Telegram-iOS#188]
This is a new feature that will be introduced in iOS 13.2, and is already available in the beta. From the [Apple documentation](https://developer.apple.com/documentation/sirikit/insendmessageintent?language=objc): 

> To have messages automatically heard by a user wearing AirPods, you must implement both INSearchForMessagesIntent and INSendMessageIntent. Add UNAuthorizationOptionAnnouncement to the options when calling requestAuthorizationWithOptions:completionHandler:. Finally, add UNNotificationCategoryOptionAllowAnnouncement to the category option and INSearchForMessagesIntent to the category intent identifier.

Telegram already provides Siri integration, so most of this functionality is already implemented.

**Comment by MrSnakeOil** [comment]
I would delay love to see this feature added.

I've used 'Announce Messages with Siri' with iMessage and find it a superb user experience, especially when I'm carrying my five year old, or out running.

If you need a guy to test the UX hit me right up.

**Comment by wjwalcher** [comment]
Agreed, this would be super nice to have - someone please implement this :)

**Comment by koellemichael** [comment]
This would be really great to see! :)

**Comment by Derad6709** [comment]
Great idea!

**Comment by kingmatusevich** [comment]
Is this not getting implemented?

**Comment by QiuYueBaiJXW** [comment]
Good idea！

**Comment by agottardo** [comment]
This feature is now available, closing this issue. For more details: https://www.reddit.com/r/iOSBeta/comments/k4na20/telegram_has_announcements_with_airpods_on_ios/
