### ISSUE TITLE
Inline Query location data not provided on IOS version.

### ISSUE THREAD

**Issue by Dextroz** [TelegramMessenger/Telegram-iOS#19]
In reference to issue: https://github.com/python-telegram-bot/python-telegram-bot/issues/1265

The IOS version of Telegram does not request the user to provide location as the Android version does.
This issue leads to bots not being able to access inline location data.

**Comment by midianet** [comment]
I have the same problem....

**Comment by laktyushin** [comment]
Fixed in 5.12.1
