### ISSUE TITLE
do you connect the server, why error is "Connection reset by peer"

### ISSUE THREAD

**Issue by Azimshah** [TelegramMessenger/Telegram-iOS#193]
do you connect the server, why error is "Connection reset by peer"

<img width="790" alt="屏幕快照 2019-10-22 上午10 31 46" src="https://user-images.githubusercontent.com/11939075/67255936-306aaa00-f4b7-11e9-9aae-69a39608d837.png">

_Originally posted by @xRuby in https://github.com/TelegramMessenger/Telegram-iOS/issues/168#issuecomment-544783023_

**Comment by xRuby** [comment]
this is because can't connect the server

**Comment by xRuby** [comment]
I connect the server by iphone not simulator

**Comment by shivanraptor** [comment]
It's obviously a network problem. Not related to the codes / app itself.

**Comment by laktyushin** [comment]
This is caused by your internet connection. Telegram servers are unreachable due to your network or ISP blocking them. You can try using MTProto proxy to bypass the block.
