### ISSUE TITLE
Markdown issues

### ISSUE THREAD

**Issue by Neurotoxin001** [TelegramMessenger/Telegram-iOS#197]
1 - When I press "copy" on post - app don't copy the links in text, example:
https://i.imgur.com/mKnbeU6.mp4
But when I "copy" when editing post - links is copying fine, example:
https://i.imgur.com/TdhqiWr.mp4
And even `code formatted` text, example:
https://i.imgur.com/cKnfDSt.mp4

2 - I can't remove markdown in this case — create post like this:

test

**test**

Then try to add some text, it's all will be **bold** and you can't remove the bold markdown from this text. Same issue with _italic_

Example:
https://i.imgur.com/by8gPGs.mp4
When I press on markdown icon nothing happens.

Telegram 5.12.1
iOS 13.2.2

**Comment by Kezzsim** [comment]
Yeah that text input context menu element seems to be broken on iOS 13.2.*
[Video documenting issue](https://twitter.com/Kezzism/status/1190683821089394688)

I thought I saw another issue pertaining it was closed but I'm not so sure now.
Encountered bug on iPhone 11 Pro Max

**Comment by Kezzsim** [comment]
My issue was fixed by the most recent release just now

**Comment by Neurotoxin001** [comment]
> 1 - When I press "copy" on post - app don't copy the links in text

Not fully fixed in 5.12.2, not links can be copied, but not from posts with buttons, for example it can be copied from https://t.me/dvachannel/42410 but not from https://t.me/dvachannel/42397

> 2 - I can't remove markdown in this case — create post like this:
Still not fixed in 5.12.2, now even markdown-button is disappears

**Comment by Neurotoxin001** [comment]
Are you going to fix this?

**Comment by Neurotoxin001** [comment]
Seems like all is fixed in 5.13

**Comment by Neurotoxin001** [comment]
In 5.14 there is no markdown settings for text in caption when you want to post image with caption:
![image](https://user-images.githubusercontent.com/39812401/73116959-eaa6fd00-3f4f-11ea-86b8-872c3b688501.png)

**Comment by Neurotoxin001** [comment]
7.1.2 still have this issue https://github.com/TelegramMessenger/Telegram-iOS/issues/197#issuecomment-578379822

**Comment by Neurotoxin001** [comment]
7.2.1 still have this issue https://github.com/TelegramMessenger/Telegram-iOS/issues/197#issuecomment-578379822

And here is another one. When text is in `()` and you edit it – link is dissapears from ` ()`. Why?
Video demonstration - https://i.imgur.com/hMwzrOr.mp4

Just write post like this:
Test [(lol)](http://example.com/) test

and tap edit and write something
