### ISSUE TITLE
[Bug] Reply to Push Notifications does't work | Iphone X (iOS 13.1.3) 

### ISSUE THREAD

**Issue by Dyrdin** [TelegramMessenger/Telegram-iOS#198]
Sometimes (more than 50% of the time) if I reply to a message in the lockedscreen notification and send this message won't be sent. I noticed weeks ago that messages I sent don't appear in the Chat in Telegram itself, today I waited hours for a reply then I asked the receiver if he got this message. No he doesn't... Happened around 100 times for weeks.

I use Iphone X with iOS 13.1.3 with Telegram 5.12.1 (always up to date)

anyone else experiencing this?

**Comment by laktyushin** [comment]
Fixed in 5.12.2.
