### ISSUE TITLE
Mute is not work on some group

### ISSUE THREAD

**Issue by huio** [TelegramMessenger/Telegram-iOS#2]
Version 5.0.17.

2 days ago,I upgrade Telegram X to the latest version,Then I found mute is note work on some Group. I not work after Unmute then Mute.The groups always the same 2 or 3 groups.The total group I join is around 15.

**Comment by huio** [comment]
and I found that if some group is muted, The apple notification is disappear,but the app's Tab Nav still has superscript

**Comment by PengsreangSrun** [comment]
Hello @huio ,
Do you know how to run this sample successfully? Please help me.
