### ISSUE TITLE
Simple Passcode login form is shown even when Simple Passcode is turned off

### ISSUE THREAD

**Issue by ispyropoulos** [TelegramMessenger/Telegram-iOS#20]
I just encountered this serious bug on my iOS client and I basically locked myself out.

Steps to reproduce:
1. Settings > Privacy & security > Passcode & Touch ID
2. Turn on passcode
3. Input a 4 digit passcode, twice
4. Switch on Touch ID (otherwise you won’t be able to login at all)
5. Turn off Simple Passcode option
6. Enter a complex passcode, twice

Now, if you lock your chats or time out period expires you will be presented with the 4 digit input form (or the Touch ID input)! You are now locked out of managing your passcode forever...

iOS 12.1.2
Telegram 5.1.1

I originally posted this here peter-iakovlev/Telegram#333, but heard nothing since.

**Comment by SiNaPsEr0x** [comment]
I notice apple for resolve code of iOS to touch or face becouse some sue forme bypass protection of local app
