### ISSUE TITLE
iOS 13 Share sheet: Recent chats should be optional.

### ISSUE THREAD

**Issue by emadhegab** [TelegramMessenger/Telegram-iOS#209]
As a *User* : in iOS 13 new Share sheet , I should have the ability from options to disable recent contacts from being shown on the share sheet, specially it shows the whole contact and image details. which is counter to the privacy that telegram have in every corner. 
what I expect either same behaviour like the messages app in iOS , that removes that  recent contact after removing the thread , or better disable it per user or disable it at all.

**Comment by darklord1807** [comment]
Same issue. Technically if the message thread is deleted it should be removed from the contact share sheet. The contact name share sheet appears everywhere (Photo, Safari etc)

**Comment by emadhegab** [comment]
It’s totally counter intuitive. Also on holding on telegram icon it shows the app widget with all the recents. Which give idea who did i talked with !

**Comment by nepshaaa** [comment]
> Same issue. Technically if the message thread is deleted it should be removed from the contact share sheet.

It does not work this way, unfortunately.
I’ve tried deleting a thread, deleting a contact from telegram and from my contact list- it didn’t work.

The only way for me to remove someone from the sharesheet suggestions - is to text 10 other people instead. So that the person I want to be removed from the list wouldn’t be recent anymore.

I wish the sharesheet list was configurable.

**Comment by emadhegab** [comment]
> The only way for me to remove someone from the sharesheet suggestions - is to text 10 other people instead. So that the person I want to be removed from the list wouldn’t be recent anymore.
 
well you can just logout and login again.. yet.. it's irritating , it's unconfigurable from iOS side, neither on telegram side.

**Comment by darklord1807** [comment]
One solution is to use telegram web. But it’s frustrating.

**Comment by laktyushin** [comment]
Share Suggestions are now customisable in Settings > Data & Storage > Share Sheet.
