### ISSUE TITLE
FFMpeg Compiling Error

### ISSUE THREAD

**Issue by miomirradovanovic** [TelegramMessenger/Telegram-iOS#21]
When I try to build the project I get FFMpeg compiling error:

building x86_64...
Generating opus.pc
ERROR: opus not found using pkg-config

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.
Command PhaseScriptExecution failed with a nonzero exit code

Is there any building guide with straightforward instructions?

**Comment by badgentlemen** [comment]
just install yasm and pkg-config for prebuilding ffmpeg

`brew install pkg-config`
`brew install yasm`

**Comment by lotus-lotus** [comment]
@badgentlemen  next ??

**Comment by laktyushin** [comment]
https://github.com/TelegramMessenger/Telegram-iOS/blob/master/README.md

**Comment by hoootan** [comment]
I'm in Catalina and still get this error despite installed yasm and pkg-config

**Comment by stevenwy** [comment]
@hoootan Have you solved this issue?

**Comment by hoootan** [comment]
@stevenwy Not yet, I think I have to test it on Xcode 10.
