### ISSUE TITLE
[Feature Request] Group/Chat Icon in Notification

### ISSUE THREAD

**Issue by Flightliner380** [TelegramMessenger/Telegram-iOS#210]
Hello,

on Notification on iPhone/IWatch there is only the Telegram Icon.
Is't to to  **replace** the telegram icon with the **group** or **chat** icon in the notifications?
This is more visible to user to see the source of the message/notification.

Kind Regards
Flightliner

**Comment by laktyushin** [comment]
There is no such API on iOS.
