### ISSUE TITLE
Unable to connect to the proxy for the first time when the network is blocked

### ISSUE THREAD

**Issue by tion126** [TelegramMessenger/Telegram-iOS#212]
Unable to connect to the proxy for the first start when the network is blocked。
It's OK for the second startup

**Comment by ethylmorphine** [comment]
I have the same issue periodically. Tor logs say that SOCKS requests are invalid, so I believe the problem is that Telegram sends corrupted requests.

**Comment by tion126** [comment]
> I have the same issue periodically. Tor logs say that SOCKS requests are invalid, so I believe the problem is that Telegram sends corrupted requests.

I have solved this problem by calling network?.context.updateApiEnvironment before first set proxy
