### ISSUE TITLE
"chatlist"   "onlyGroup"   "onlyChannels"  "onlyPrivateChat"  problem

### ISSUE THREAD

**Issue by NiConEG** [TelegramMessenger/Telegram-iOS#215]
<img width="388" alt="WeChat3dbf7ef6b5c2613b19041cb52a12936c" src="https://user-images.githubusercontent.com/11752103/71431335-2316a980-270c-11ea-8838-1a48d2d21935.png">
Has anyone done anything like that

**Comment by cfcor** [comment]
I have done this.May I have a chat with you?
