### ISSUE TITLE
project build  help

### ISSUE THREAD

**Issue by alyfreym** [TelegramMessenger/Telegram-iOS#216]
Seriously guys I don’t understand how to compile this. I can’t do it for the third day already; did anyone manage to do it? Please exactly how you did it. steps are written in the description but they do not work for me. Any help would be appreciated. Thanks. My errors are not related to signatures. Mostly bugs are linked using frameworks. Project cannot compile dependencies

**Comment by Floris497** [comment]
What exactly is going wrong? nobody can help you if you don't show what errors you have.

I was able to build using the instructions from here: https://core.telegram.org/reproducible-builds#reproducible-builds-for-ios

Make sure you have the exact same Xcode version as described.. I tried with newer first time and it did not work.

Also i did not use a VM but another machine booted from an external drive and editing the build script a bit with the IP to my other machine.

**Comment by alyfreym** [comment]
> What exactly is going wrong? nobody can help you if you don't show what errors you have.
> 
> I was able to build using the instructions from here: https://core.telegram.org/reproducible-builds#reproducible-builds-for-ios
> 
> Make sure you have the exact same Xcode version as described.. I tried with newer first time and it did not work.
> 
> Also i did not use a VM but another machine booted from an external drive and editing the build script a bit with the IP to my other machine.

Thanks for the link. I didn’t know that there is documentation on the build of the project. Maybe you should add her read me file? Because what is described in there does not work.
