### ISSUE TITLE
Readme's build instructions are incorrect

### ISSUE THREAD

**Issue by michaeleisel** [TelegramMessenger/Telegram-iOS#230]
The readme suggests opening a `.workspace` file when there isn't one. It seems like it should be updated to reference https://core.telegram.org/reproducible-builds#reproducible-builds-for-ios ?
### Checklist
- [X] I am reporting an issue in existing functionality that does not work as intended
- [X] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

**Comment by shivanraptor** [comment]
you can create a pull request to update the README file. As mentioned in the link, the build instructions might be simplified soon.

**Comment by michaeleisel** [comment]
Sure, generally pull requests are generally accepted for open source repos. Anyways, Telegram should at least remove the incorrect instructions so that people don’t waste their time.

Although it’s quite surprising that this doesn’t seem to be a super high priority. Isn’t being able to build it pretty crucial?

**Comment by h3afif** [comment]
Why looking to update the README file, instead of knowing why the workspace and xCode files are missing and especially if the Telegram-iOS community intends to add them in the future or will they just be satisfied with the BULCK commands.
I'm really disappointed that these xCode files are missing, especially for people who just want to understand how Telegram-iOS is designed and an IDE interface is really useful for them.

**Comment by Kylmakalle** [comment]
@h3afif try this instruction to create project file https://github.com/TelegramMessenger/Telegram-iOS/issues/219#issuecomment-570533746

**Comment by michaeleisel** [comment]
It seems strange that maintainers would rather keep responding to issues like this, than to address the root of the problem, which is that the readme should be updated. It also somewhat defeats the purpose of an open-source repo not to have clear, easily accessible instructions on how to build it.

**Comment by michaeleisel** [comment]
Even if I updated it, would the maintainers keep it up-to-date in the future? I’m not so sure.

**Comment by Kylmakalle** [comment]
@michaeleisel You also should check this guide https://core.telegram.org/reproducible-builds#reproducible-builds-for-ios

**Comment by michaeleisel** [comment]
The issue is that that guide is not mentioned in the readme. Instead, the readme, which is the first place a lot of people go to for a project, lays out an alternate and incorrect set of steps. It’s baffling

**Comment by ali-fareed** [comment]
Please see the updated build instructions in README.md.
