### ISSUE TITLE
Add support for http proxy

### ISSUE THREAD

**Issue by Katsusan** [TelegramMessenger/Telegram-iOS#232]
The proxy app on my device provides a http proxy with fixed port and a socks5 proxy with dynamic port，so  I have to do port scan my device for that dynamic port and use it in Telegram proxy setting。    

I would appreciate it if developers could add http proxy on Telegram-IOS(just like Telegram Desktop do)。

**Comment by Katsusan** [comment]
Switch to another proxy app and it works.

**Comment by bezludny** [comment]
Still need this option on iOS

**Comment by diskman79** [comment]
Still need this option on iOS-app
