### ISSUE TITLE
hide push notifications

### ISSUE THREAD

**Issue by bim13** [TelegramMessenger/Telegram-iOS#234]
Hello! Could you explain what mechanisms are used to hide notifications of read messages?

**Comment by Kylmakalle** [comment]
Telegram sends VOIP push notifications which syncs current state of read/deleted messages and so App remove (revoke) redundant notifications.

**Comment by Eradicator** [comment]
Hello! And how this is done currently, after iOS begun to force developer to show CallKit screen when receive VoIP push?

**Comment by Kylmakalle** [comment]
> iOS begun to force developer 

Unfortunately, there's not so much that Telegram team can do.
https://github.com/TelegramMessenger/Telegram-iOS/issues/178#issuecomment-696988756
