### ISSUE TITLE
Rlottie submodule commit 0ee2e9c is not public (Release 5.14)

### ISSUE THREAD

**Issue by Kylmakalle** [TelegramMessenger/Telegram-iOS#235]
It still builds with `a09896` from `@laktyushin`'s [repo](https://github.com/laktyushin/rlottie) , but i'm afraid of lacking some performance improvements.

**Comment by laktyushin** [comment]
https://github.com/TelegramMessenger/rlottie/commit/0ee2e9c5843257ccd11672611829b9bb5d02aa98
