### ISSUE TITLE
[iPad] Inconsistent Input From Bluetooth Keyboard

### ISSUE THREAD

**Issue by thomas-williams** [TelegramMessenger/Telegram-iOS#238]
I’m not sure myself how to pinpoint this issue, but I have tested enough to know it is specific to Telegram and not an issue with my keyboard. I have the Logitech Slim Folio for my iPad and it works perfectly in every other app I have tried typing in. When I am typing in the message box I have to intentionally slow my typing speed to a point that is almost uncomfortable to avoid bizarre behavior. Sometime it just misses a keystroke, others it essentially replaces any given keystroke with a backspace input, sometimes letters get swapped around. I could message you a gif of such behavior if that would help.

**Comment by nachogt** [comment]
Exactly the same thing happens to me, only on Telegram. With two different Logitech Bluetooth keyboards, a Slim folio and an Ultrathin.

iPad 2 Air 128GB with cellular.

It's been happening for a few weeks now.

**Comment by pycta** [comment]
I can confirm this issue on iPad 7 with the Logitech Slim Folio. Does not happen all the time, sometimes, restarting the app seems to fix it.
It appears as most of what i'm typing is deleted as I type. I am not entirely sure, but it looks like a portion of the letters I type get selected and then deleted.

**Comment by linasayuri** [comment]
I have the same issue with my iPad Air 2 and the Apple Wireless Keyboard A1314.

**Comment by nikomtis** [comment]
I faced this issue using iPad mini 4 (iOS 13.3.1) and Magic Keyboard.
Telegram version is 5.15.2.

**Comment by Fallboard** [comment]
Also adding to this issue with 2018 iPad Pro 12.9 and iClever BK05 bluetooth keyboard. No problems in other apps, but in Telegram the input almost second-guesses itself, with rapid keystrokes appearing briefly, then being deleted (a common combo is the rapid spacebar before comma). I have autocorrect turned off on all keyboards. 

Telegram version 5.15.2  but has been a problem for months on other bluetooth keyboards before this.

**Comment by bertani** [comment]
Same issue here with iPad Pro 11 on iPadOS 13.3 and the Apple Smart Folio Keyboard

**Comment by DrJolly** [comment]
Same issue here, still nit fixed!

**Comment by luizphr** [comment]
Saem issue here. Almost giving up on using Telegram for iPad.

iPad(6th Gen)
iOS 13.3.1
Apple Magic Keyboard
Telegram iOS 5.15.2

**Comment by nachogt** [comment]
Indeed, it makes it almost unusable on ipad + keyboard.

**Comment by Michelasso** [comment]
Same problem here. iPad 2018, iOS 13.3.1, Omoton keyboard. It jumps or erases 20-30% of characters

**Comment by Fduch1984** [comment]
I have same issue. iPad Pro 2019 12.9’’.

**Comment by siulman** [comment]
Hello,

Same issue here. Ipad 2018 with Logitech Slim Folio Keyboard. Any known workaround? I didn't have this issue before... So it's related with the telegram version...

**Comment by rittermo** [comment]
I have the exact same issue on my iPad Pro 11" and Smart Folio Keyboard, Telegram v5.12.2

**Comment by laktyushin** [comment]
Fixed in one of the previous releases.
