### ISSUE TITLE
Option to mute for 1h or 2 days not available anymore

### ISSUE THREAD

**Issue by Sixcross** [TelegramMessenger/Telegram-iOS#239]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
Since the new Update 5.15 the UI for group display changed. While most features are still accessible, the option to mute for a defined time period (1h or 2 days) is absent.
Previously when you clicked on the mute panel, you got to select from 3 (or 4?) options to mute the chat. Neither a long press nor in another place i can find the option to mute for a time period instead of compleetly mute.

### Expected Behavior
When clicking the new mute Icon, it should give the old options for different mute times.

### Actual Behavior
Klicking the mute button automatically mutes that particular chat for ever (until you klick it again)

### Steps to Reproduce
1. Open any chat (private, group or Chanel)
2. Klick on the Chat title to see the new UI with the options for it
3. Klick on "Mute"

### Environment
**Device:** `iPhone`

**iOS version**: `13.3`

**App version:** `5.15`

**Comment by laktyushin** [comment]
This is intended. Different notification mute time intervals are available when you tap Edit in the top right corner and select Notifications.
