### ISSUE TITLE
9GAG link preview not working on iOS

### ISSUE THREAD

**Issue by dimitarvp** [TelegramMessenger/Telegram-iOS#243]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
Up until several days ago, sending 9GAG links showed rich previews. Telegram no longer shows these now.

### Expected Behavior
Rich link preview should appear

### Actual Behavior

No rich link preview appears

### Steps to Reproduce
1. Open 9GAG on iOS
2. Press “Share” on any post
3. Send to your contacts or yourself (Saved Messages)

### Screenshots and Videos 
Remove, if not applicable

### Environment
**Device:** `iPhone 8 Plus`, `iPad Pro 10.5”`

**iOS version**: `13.3.1`

**App version:** `5.15.2`

**Comment by laktyushin** [comment]
It's not an iOS client issue. I've forwarded the issue to server devs.

**Comment by dimitarvp** [comment]
Thank you. Is there a ticket link I can be periodically checking out?

**Comment by fvannee** [comment]
Experiencing similar issues

**Comment by icaroalvarez** [comment]
Any news? 9gag preview still not working on telegram.

**Comment by SGmuwa** [comment]
This problem may be on the 9gag server side. Though I discovered today that Telegram didn't display the instagram link today. My second theory is copyright. Perhaps Telegram does not display some links so that the link owners do not lose traffic.

**Comment by dimitarvp** [comment]
9GAG and copyright? Not very likely.

Either the site is making it intentionally difficult to pull the post details (plausible) or the Telegram team has no interest in fixing the problem.

**Comment by icaroalvarez** [comment]
Funny thing is that the second screenshot of official [Telegram preview page](https://telegram.org/blog/link-preview) is a 9gag url. Also WhatsApp preview 9gag urls, so I don't thing the issue is in the site side.
