### ISSUE TITLE
ITMS-90429: Invalid Swift Support

### ISSUE THREAD

**Issue by zerxon** [TelegramMessenger/Telegram-iOS#245]
I archived the project in XCode  and submit it, but received an email from App Store Connect:

`ITMS-90429: Invalid Swift Support - The files libswiftDarwin.dylib, libswiftMetal.dylib, libswiftCoreAudio.dylib, libswiftsimd.dylib, libswiftCallKit.dylib, libswiftIntents.dylib, libswiftQuartzCore.dylib, libswiftos.dylib, libswiftObjectiveC.dylib, libswiftDispatch.dylib, libswiftCoreLocation.dylib, libswiftCoreGraphics.dylib, libswiftCoreFoundation.dylib, libswiftUIKit.dylib, libswiftCoreMedia.dylib, libswiftAVFoundation.dylib, libswiftContacts.dylib, libswiftCore.dylib, libswiftFoundation.dylib, libswiftCloudKit.dylib, libswiftCoreImage.dylib aren’t at the expected location /Payload/FlyChat.app/Frameworks. Move the file to the expected location, rebuild your app using the current public (GM) version of Xcode, and resubmit it.`

 Xcode Version is 11.3.1 

I tried using fastlane for packaging, it generated Archive.xcarchive,  but still doesn't work.
This problem has bothered me for a few days and can't find any solution. Can anyone help me? Thanks a lot.

**Comment by kungfuit** [comment]
me too, cant fix it also

**Comment by kungfuit** [comment]
who has fix it already? can share it?

**Comment by patriciy** [comment]
Most probably it's dylib's in Frameworks folder.
See more here, "Embedded .dylib Files"
https://developer.apple.com/library/archive/technotes/tn2435/_index.html#//apple_ref/doc/uid/DTS40017543-CH1-ADD_FRAMEWORK_TARGET

> The following errors may indicate your app is embedding a dynamic library that is not packaged as a framework. Dynamic libraries outside of a framework bundle, which typically have the file extension .dylib, are not supported on iOS, watchOS, or tvOS, except for the system Swift libraries provided by Xcode.

There're plenty of them in Telegram target. The suggested way is to replace them with frameworks.

**Comment by zzmasoud** [comment]
same here

**Comment by BaiXiaoYan** [comment]
I'm getting same issue.
Did anyone fix this issue?

**Comment by zhongliIOS** [comment]
if anyone fix it,please share to me. The good man will be safety by his whole life

**Comment by zhongliIOS** [comment]
It should make Telegram.app/Frameworks/libMtProtoKit.dylib

Telegram.app/Frameworks/libTelegramApi.dylib

Telegram.app/Frameworks/libTelegramCore.dylib

Telegram.app/Frameworks/libSyncCore.dylib
Telegram.app/Frameworks/libDisplay.dylib
Telegram.app/Frameworks/libTelegramUI.dylib

Telegram.app/Frameworks/libAsyncDisplayKit.dylib
Telegram.app/Frameworks/libPostbox.dylib

to .framework or .a  Because Apple doesn't support dylib without itself.

**Comment by ali-fareed** [comment]
Please see the updated build instructions in README.md.
