### ISSUE TITLE
Appearance → Reduce Motion doesn't stop sticker animations

### ISSUE THREAD

**Issue by anohren** [TelegramMessenger/Telegram-iOS#246]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
Enabling Reduced Motion in Appearance settings should, according to its own description, disable sticker animations. It doesn't. 

### Expected Behavior
Sticker animations should be disabled according to the setting description. 

### Actual Behavior
Sticker animations loop in chats. 

### Steps to Reproduce
1. Enable Reduce Motion
2. Send or receive a sticker
3. Watch it move

### Environment
**Device:** `iPhone 8`

**iOS version**: `13.3.1`

**App version:** `5.14`

**Comment by laktyushin** [comment]
Reduce motion disables list items animations. You can disable animated stickers looping in Settings > Stickers > Loop Animated Stickers.

**Comment by anohren** [comment]
> Reduce motion disables list items animations.

As you can see both in the issue description and in the app that's not what the settings description says. 

Why did you close the issue? Does unexpected behavior not concern you?
