### ISSUE TITLE
Clicking t.me link in a webpage (Telegram webview) does not open the account

### ISSUE THREAD

**Issue by zulhfreelancer** [TelegramMessenger/Telegram-iOS#25]
Hi,

I want to report a bug in Telegram v5.4.1 (I'm using iOS 12.1.4). Steps to reproduce:

1. Send https://telegram.org/faq#q-how-does-t-me-work link to yourself (Saved Messages)
2. From your Telegram iOS app, click on that link
3. Now, click on `t.me/username` link that you see on the screen
4. You should be stucked
5. Now, click on Done on top left of the Telegram app
6. That account has opened in the background

As a user, I was expecting to see that account straight away i.e. Telegram auto-closes the webview and bring me straight into that account.

Can we fix this bug?

Thank you!

**Comment by zulhfreelancer** [comment]
Any update on this @laktyushin?

**Comment by laktyushin** [comment]
It appears to be fixed some time ago, works fine for me on 5.9.1. 
Please report if you can still reproduce it on your end.

**Comment by A91y** [comment]
If `t.me/<username>` doesn't work, try `telegram.me/<username>`

**Comment by hamdan-Deb** [comment]
tried both i.e., t.me/<username> and telegram.me/<username>
_
still  doesn't work on web

**Comment by VadimBirkos** [comment]
@hamdan-Deb <a href="https://t.me/{username}"> works for me.

**Comment by hamdan-Deb** [comment]
> @hamdan-Deb href="[https://t.me/{username}](https://t.me/%7Busername%7D)" works for me.


ok thanks, let me test it
