### ISSUE TITLE
iOS 13 Showing Notification to Users.

### ISSUE THREAD

**Issue by kumarSudhir7891** [TelegramMessenger/Telegram-iOS#254]
Can some body help me out in taking the right approach to show Notification to User. Previously to show a new chat message to user(when he is offline) we were using Voip Notification , But from iOS 13 we have to use APNS. But APNS are slow as well as not guaranteed delivery and its hampering user experience. Any help is appreciated.
Thanks in advance

**Comment by Kylmakalle** [comment]
You probably looking for `BackgroundTasks`
You can reach me in private on TG [@Kylmakalle](https://t.me/Kylmakalle) for more info.
Also, check out this https://github.com/TelegramMessenger/Telegram-iOS/issues/81#issuecomment-585990544 with more info on what's going on

**Comment by Bryophyllum** [comment]
@Kylmakalle Isn't `BackgroundTasks` suited for periodical, power-intensive, or long tasks scheduled to be performed when the device is idling? Pardon my ignorance, but I don't quite understand how that is going to help with delivering APNS notifications in time.
