### ISSUE TITLE
[Feature Request] Shortcut for switching between accounts on Mac

### ISSUE THREAD

**Issue by brmb** [TelegramMessenger/Telegram-iOS#259]
### Is your feature request related to a problem?
No.

### Describe the solution you'd like
It would be amazingly convenient if you could implement a shortcut to switch between accounts like in Slack. You can switch between Slack accounts with Command+1, Command+2 and so on but I see this as a necessity on Telegram as well. It would be a lot more convenient to use. Also, regarding https://github.com/TelegramMessenger/Telegram-iOS/issues/157 issue, there is no Settings icon that we could longtap.

### Describe alternatives you've considered
There aren't many of the alternatives, you need to go to accounts and press on a different account that you want to use.

### Additional context
This is what I am talking in Slack:
<img width="263" alt="Screenshot 2020-03-24 at 5 23 38 PM" src="https://user-images.githubusercontent.com/51971082/77444454-85a74080-6df4-11ea-9657-b6cb37d725ca.png">

**Comment by laktyushin** [comment]
This tracker is not the right place for macOS app feature requests.
