### ISSUE TITLE
Problem secret chat message from telegram-cli to Iphone

### ISSUE THREAD

**Issue by sergiokovalski** [TelegramMessenger/Telegram-iOS#26]
Sending secret chat messages from telegram-cli to Iphone does not work.
To Android is ok.
Create secret chat is ok.
After create secret chat with Iphone, send messages, but it is empty.
Telegram-cli no error, but in log - "can not decrypt message".

Telegram-cli use old tgl lib.
Maybe problem in the old version MTProto or TL-schema in tgl?
It can somehow be fixed?
Any ideas why secret chat doesn't work from telegram-cli with iphone? 
Thx.

**Comment by laktyushin** [comment]
telegram-cli uses outdated secret chats layer which is not supported by modern client apps. You should switch to something based on https://github.com/tdlib/td
