### ISSUE TITLE
Dice Roll feature

### ISSUE THREAD

**Issue by otacon94** [TelegramMessenger/Telegram-iOS#264]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [ ] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
The new dice roll feature is bugged into private chats as it gives always 1.

### Expected Behavior
It should give a random number every dice send.

### Steps to Reproduce
1. Create a new Private chat
2. Send dice to see what number turns out

### Screenshots and Videos 
https://imgur.com/a/IyADVWp

### Environment
**Device:** `iPhone XS Max`

**iOS version**: `13.4`

**App version:** `6.0`

**Comment by A-jay98** [comment]
I believe this functionality was intentionally removed in this commit https://github.com/TelegramMessenger/Telegram-iOS/commit/055dfe503c9026ca91134823345c96c3dca287b0 and is not a bug.

**Comment by laktyushin** [comment]
Dice roll is not available in secret chats.
