### ISSUE TITLE
Stopped working in iOS 9.3.5

### ISSUE THREAD

**Issue by Thyname** [TelegramMessenger/Telegram-iOS#265]
Today's update doesn't open in iOS 9.3.5, last version for the ancient iPad 2.
When displaying the open apps, the Telegram window is there so maybe it's opened in the background but selecting it it flashes and disappears.

**Comment by neyold** [comment]
> Today's update doesn't open in iOS 9.3.5, last version for the ancient iPad 2.
> When displaying the open apps, the Telegram window is there so maybe it's opened in the background but selecting it it flashes and disappears.

I'm experiencing the same issue on the same device (A1432).

Switched to using [Nicegram](https://apps.apple.com/us/app/nicegram/id1457369322#?platform=ipad) until this resolves.

**Comment by ndnkle** [comment]
Same issue on iPhone 5C running iOS 10.3.3.

**Comment by vmatyushin** [comment]
iPad 3, iOS 9.3.5, Telegram crashes on start.

**Comment by avalonanders** [comment]
Same issue on iPhone 5C running iOS 10.3.3, It was fine until then v.v

**Comment by Panuchi** [comment]
Same issue  on iPhone 5 iOS 10.3.3

**Comment by isharonov** [comment]
Same issue on iPhone 4S iOS 9.3.6

**Comment by rahim1234** [comment]
Same issue on iPhone 5 iOS 10.3.4

**Comment by neyold** [comment]
I got 6.0.1 update which fixed the issue on iPad2 (iOS 9.3.5)

**Comment by Thyname** [comment]
It's working again, thank you very much!

**Comment by vlazar** [comment]
Latest version 8.8.1 is crashing on iOS 9.3.6 (iPad 3rd gen)

**Comment by Telemakos** [comment]
Same issue here on iOS 9.3.6 (iPad 2): the app keeps crashing even after deleting it and reinstalling the newest version. Restarting iPad did not solve the issue either.

**Comment by v-fedorova** [comment]
Same issue on iOS 9.3.6 (iPad 2 mini): when displaying the open apps, the Telegram window is there, but when it is selected -- it flashes and disappears.
