### ISSUE TITLE
Doesn't work on iPhone 5

### ISSUE THREAD

**Issue by Panuchi** [TelegramMessenger/Telegram-iOS#268]
Today's update doesn't open in iOS 10.3.3.
white screen and app is crashing 
When displaying the open apps, the Telegram window is there so maybe it's opened in the background but selecting it it flashes and disappears.

**Comment by sanaph** [comment]
I'm on an iPhone 5 too, iOS 10.3.4. Was able to use Telegram before going to bed last night. When I woke up this morning and opened the app, the same thing happened to me. I click on the telegram icon, it opens into a white screen, and then it disappears. Already tried rebooting my phone, reseting all settings, and reinstalling the app.

**Comment by matvienkoLT** [comment]
I have met the same issue, ios 10.3.4.
Just white screen and further app is crashing.

**Comment by A-jay98** [comment]
I got the same issue on iPad 4th gen iOS 10.3.3

**Comment by martinhebart** [comment]
My sister has the same issue (IPhone 5).

**Comment by okageshadow** [comment]
Yeah, me too, with my iPhone5 eith iOS 10.3.4
I sent message to support but there's no reply yet. Hope they notice us if we make the problem visible.

**Comment by promero1207** [comment]
Me too iphone 5 ios 10.3.4

**Comment by kulichkov** [comment]
Fixed in 6.0.1

**Comment by Panuchi** [comment]
Working again.

**Comment by Panuchi** [comment]
Working again

**Comment by A-jay98** [comment]
@Panuchi please do close the issue now that it's been fixed

**Comment by Panuchi** [comment]
Working again.
