### ISSUE TITLE
cant open telegram in iphone ios 10.3.4

### ISSUE THREAD

**Issue by rahim1234** [TelegramMessenger/Telegram-iOS#269]
I have iphone 5 with ios 10.3.4
After update telegram can't open that 
I remove the app and restart the phone and install it agane but still have the problem 
31 march 2020

**Comment by Zlo0oy** [comment]
Same issue, Iphone 5, ios 10.3.4, app doesn't open after update from 03.30.2020

**Comment by incal** [comment]
same issue in iPad2 iOS 9.3.5

**Comment by babaMar** [comment]
Same here

**Comment by bashmish** [comment]
same, ipad ios 10.3.4

**Comment by alirezaac** [comment]
Same all 32bit devices

**Comment by rahim1234** [comment]
tanks it fix in new update

**Comment by xana-rahmani** [comment]
I have iphone 5
6S with ios 14.6
After update telegram can't open that

29 june 2021

**Comment by geralltgriffiths** [comment]
Done it again, with v8.8 on iPad4, running iOS 10.3.3 -- goes to blank screen then crashes back to OS.

**Comment by Shbnv** [comment]
> Same issue, Iphone 5, ios 10.3.4, app doesn't open after update from 03.30.2020

Yes. I also have this issue on the same configuration.
