### ISSUE TITLE
Home button/bar not fixed after viewing media

### ISSUE THREAD

**Issue by vistaero** [TelegramMessenger/Telegram-iOS#281]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
When you start the app in a device without physical home button, the virtual home button is visible, but after viewing a photo or a video, it keeps on auto-hide, although it always has its reserved space at the bottom of the screen.

### Expected Behavior
The virtual home button mode should change to fixed after closing the media.

### Actual Behavior
The virtual home button keeps on auto-hide after viewing media.
### Steps to Reproduce
1. Start Telegram
2. Open a photo from a chat and zoom in
3. Virtual home button will disappear
4. Return to the chats list
5. Home button will disappear again after a few moments without touching the screen.
### Environment
**Device:** `iPhone 11 Pro Max`

**iOS version**: `13.4.1`

**App version:** `6.0.1`

**Comment by laktyushin** [comment]
Fixed.
