### ISSUE TITLE
The .ipa file generated by packaging is very huge

### ISSUE THREAD

**Issue by WuFengDeYinJi** [TelegramMessenger/Telegram-iOS#284]
The .ipa file generated by packaging is very huge, with more than 1G

**Comment by hailuomax** [comment]
![79B7B5D4BD122CC9AC877B14CBC6EAEC](https://user-images.githubusercontent.com/62380503/87421183-1eaed100-c609-11ea-9536-8e163ea4c855.jpg)

Could you tell me how to generate ipa

**Comment by ali-fareed** [comment]
Please refer to the updated build instructions in README.md.
