### ISSUE TITLE
Embedded JavaScript in HTML files does not work when open it

### ISSUE THREAD

**Issue by nikialeksey** [TelegramMessenger/Telegram-iOS#288]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
When I send html files through telegram I think a receiver can open it and can see the content of html with all embedded js in it.

### Expected Behavior
Embedded in html js executed when I open html file from message

### Actual Behavior
Embedded in html js not worked.

### Steps to Reproduce
1. Send html file as message with the following content:
```html
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Debug</title>
  </head>

  <body>
    <form>
      <p id="debug"></p>
    </form>

    <script type="text/javascript">
      document.addEventListener("DOMContentLoaded", function() {
        document.getElementById('debug').innerHTML = "debug!!!";
      });
    </script>
  </body>
</html>
```
2. Click on sent message in app
3. `debug!!!` has not appeared on the screen

### Environment
**Device:** `iPad 7`

**iPadOS version**: `13.3.1`

**App version:** `6.1`

**Comment by gbenisty** [comment]
It looks as an ios bug : try to send to yourself the html file by mail. When reading, embedded js are not executed

**Comment by Thoufak** [comment]
Has this been solved? I can reproduce it in one of the latest versions. This prevents me from seeing charts in my HTML files which use JS to be rendered. 

Please note that I have enabled JS in the iOS settings at `Settings>Safari>Advanced>Javascript`.

iOS 15.5
Telegram iOS 9.3 (24832)

**Comment by nikialeksey** [comment]
No, it was not fixed

**Comment by ali-fareed** [comment]
JavaScript is intentionally disabled for security reasons.
