### ISSUE TITLE
[FR] Make the message user supplies when sharing files via share sheet, that file’s caption

### ISSUE THREAD

**Issue by NightMachinary** [TelegramMessenger/Telegram-iOS#297]
Currently the message is sent as extra message. It’s better to use that message to set the caption of the file instead.
This can be an option if it is not desirable as the default.

**Comment by Derad6709** [comment]
Hmm seems like they should refactor forward message too and join them in one like a dialogue :-)

**Comment by laktyushin** [comment]
Fixed.
