### ISSUE TITLE
The currency sign within payment invoice message is always '$'

### ISSUE THREAD

**Issue by behlbor** [TelegramMessenger/Telegram-iOS#3]
Telegram version 5.0.17
The issue is related only to iOS (everything works fine on Android)

In our case, we accpet Russian Rubles only (RUB), but it is still reflected as $. See the screenshot. You still pay in the required currency (RUB), but this issue may confuse our buyers - as USD/RUB Fx rate is ~65 today :)

Thanks for solving.

![image](https://user-images.githubusercontent.com/2179958/48648081-1dc23800-e9ff-11e8-9823-aad9b6ec7883.png)

**Comment by shivanraptor** [comment]
Do you mean changing the currency sign only, or automatically convert the price tag based on the current Fx rate?

**Comment by behlbor** [comment]
@shivanraptor only currency sign. Price tag is right: 250 rubles for example from attached screenshot.
