### ISSUE TITLE
I am trying to compile the build but geting error one by one 

### ISSUE THREAD

**Issue by balajihadole** [TelegramMessenger/Telegram-iOS#302]
![Screenshot 2020-05-26 at 10 13 24 AM](https://user-images.githubusercontent.com/57698775/82861195-8a45bd80-9f39-11ea-96af-93ebb725fe4a.png)
this is the issue i am working on compiling the build but after solving one issue it creates one more . i am stuck in it please guide me in compiling the source code thank you

**Comment by balajihadole** [comment]
![Screenshot 2020-05-26 at 10 41 02 AM](https://user-images.githubusercontent.com/57698775/82862524-77cd8300-9f3d-11ea-8208-47e6fb0b58ff.png)
like this it shows one by one

**Comment by balajihadole** [comment]
![Screenshot 2020-05-26 at 3 22 50 PM](https://user-images.githubusercontent.com/57698775/82886861-c4788480-9f64-11ea-9531-268b77cb0cf1.png)
some time shows these issues

**Comment by balajihadole** [comment]
![Screenshot 2020-05-27 at 10 02 56 AM](https://user-images.githubusercontent.com/57698775/82978058-3f8f7880-a001-11ea-9880-d0acc5f41dc6.png)

**Comment by balajihadole** [comment]
![Screenshot 2020-05-27 at 3 50 53 PM](https://user-images.githubusercontent.com/57698775/83007830-daa04680-a031-11ea-86eb-9ce477378d11.png)
This is what happening after solving one bye one issue

**Comment by virtyaluk** [comment]
@balajihadole, relax, mate. They just don't care. The [build guide](https://core.telegram.org/reproducible-builds#reproducible-builds-for-ios) is outdated and doesn't work for at least 6 months now (since python2.7 got deprecated) and telegram team keeps pretending everything is ok. This is what you need to know about code quality at telegram.org

**Comment by ali-fareed** [comment]
Please see the updated build instructions in README.md.
