### ISSUE TITLE
InlineQueryResultLocation not displaying

### ISSUE THREAD

**Issue by Banashek** [TelegramMessenger/Telegram-iOS#304]
### Checklist
- [X ] I am reporting an issue in existing functionality that does not work as intended
- [X ] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
I've created a bot which attempts to send an `InlineQueryResultLocation` response upon receiving an inline query.

This behavior appears to work on the Android Telegram client, however I tested on 3 iOS devices and was unable to receive any feedback when attempting to invoke an inline command that responded with an `InlineQueryResultLocation`.

The bot is configured with `/setinline`, `/setinlinegeo`, and `/setinlinefeedback`.
The iOS devices are configured to allow location access while using the app.

When the Android Client receives the response, it has the following behavior:

* Prompt user to access location
* Display map in the inline keyboard that the user can press to send the location

Other inline query results (photo, etc) are verified working through a similar flow.

### Expected Behavior
When an inline bot command is triggered and an `InlineQueryResultLocation` response is received, there should be a UI update indicating an action for the user to take.

### Actual Behavior
No feedback is received and the keyboard remains in inline command mode.

#### iPhone

Telegram `6.1.2`
iOS `12.4.4`

#### iPad

Telegram `6.1.2`
iOS `13.4.1`

**Comment by laktyushin** [comment]
Fixed in 7.2
