### ISSUE TITLE
[Crash] App crashes when editing a photo and adding a sticker

### ISSUE THREAD

**Issue by Siskas** [TelegramMessenger/Telegram-iOS#305]
### Checklist
- [ X ] I am reporting an issue in existing functionality that does not work as intended
- [ X ] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
Since the update from today (6.2), editing of a picture in a chat doesn’t allow anymore to add a sticker to it

### Expected Behavior
We should be able to use the sticker editing feature on existing pictures

### Actual Behavior
App crashes as soon as the sticker edition icon is touched

### Steps to Reproduce
1. Open a conversation with a picture in it
2. Select the picture and try to modify it (long tap -> modify -> paperclip icon in lowerleft -> modify the current picture)
3. In the picture editor, select the submenu with a brush icon, then click the sticker icon (face with a ⊕)
4. The app crashes

### Screenshots and Videos 

![](https://i.ibb.co/wyJMLfx/E4407366-6603-4-F13-89-AE-E842-F8-CDFA6-C.png)

### Environment
**Device:** `iPhone 6S and iPad Pro 10.5“`

**iOS version**: `13.5 for both the iPhone and the iPad`

**App version:** `6.2`

**Comment by Siskas** [comment]
Fixed in 6.2.1

**Comment by Neurotoxin001** [comment]
Not fixed in 6.2.1

1. make photo
2. open editor
3. click on stickers icon
4. crash

iOS 13.6
iPhone XR

**Comment by Neurotoxin001** [comment]
6.3 not fixed

**Comment by Neurotoxin001** [comment]
7.1.2 not fixed

**Comment by Neurotoxin001** [comment]
Btw to reproduce it you need to delete all masks in settings

**Comment by Neurotoxin001** [comment]
7.1.2 not fixed. To reproduce it you need to delete all masks in settings. If you add some masks packs all will be fine, but this is a bug.
