### ISSUE TITLE
ITMS-90430: Invalid Swift Support 

### ISSUE THREAD

**Issue by vchernyshov** [TelegramMessenger/Telegram-iOS#306]
I got this error when tried to upload app to App Store Connect.
Are any ideas how to solve it, I have already spent 3 days but haven't got any results.

ITMS-90430: Invalid Swift Support - The file libAsyncDisplayKit.dylib doesn’t have a signing ID. Sign the file, rebuild your app using the current public (GM) version of Xcode, and resubmit it.

**Comment by patriciy** [comment]
Did you try to sign it as suggested? Open project settings in xcode and change dylib type from "Embed without signing" to "Embed & Sign"

**Comment by ali-fareed** [comment]
Please see the updated build instructions in README.md.
