### ISSUE TITLE
Repository 'https://github.com/TelegramMessenger/webrtc-ios.git/' not found

### ISSUE THREAD

**Issue by MinakovPavel** [TelegramMessenger/Telegram-iOS#307]
I got this error, when trying to pull the project last time. Webrtc is in .gitsubmodules file, but the defined url is unreachable.

**Comment by SinglePlme** [comment]
你现在解决了这个问题了没有？我现在也遇见同样的问题了

**Comment by MinakovPavel** [comment]
They have already fixed it here https://github.com/TelegramMessenger/Telegram-iOS/commit/1e777ef1db714aac50286ca8d65b1f07aba291c2

**Comment by SinglePlme** [comment]
我没有进一步说明：
现在我还替换了另一个的url=../rlottie.git   为 https://github.com/ali-fareed/rlottie
事实上这些操作我都进行，再修改完之后  接着命令行  执行 
git submodule sync
git submodule update --init --recursive
不成功

**Comment by SinglePlme** [comment]
这些子模块  我git 不成功  你能帮我看下是哪方面的原因吗
首先是  Telegram_Buck.xcworkspace，编译之后少了VoIPController.h 和一个第三方库的.h或者rlottie.h
总是提示着这些  所以才想到是不是子模块没有git 全
但是git 这些 子模块 也一直不成功

**Comment by SinglePlme** [comment]
| |
ios开发
|
|
zhaolw_yc@163.com
|
签名由网易邮箱大师定制
你好，我再GitHub上有回复些新的问题
On 06/11/2020 16:55，MinakovPavel<notifications@github.com> wrote：

Closed #307.

**Comment by bitcard** [comment]
compile 6.3 with xcode 11.3 link error:

I use buck generate the Telegram_Buck.xcworkspace file.

it seems no build third-party/webrtc/webrtc-ios, I use this project: https://github.com/ali-fareed/webrtc-ios.git

Undefined symbol: cricket::IsSameCodec(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&, std::__1::map<std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator >, std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const, std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > > > > const&, std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&, std::__1::map<std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator >, std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const, std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > > > > const&)
Undefined symbol: webrtc::SdpVideoFormat::operator=(webrtc::SdpVideoFormat&&)
Undefined symbol: cricket::kRtcpFbParamCcm
Undefined symbol: cricket::kRtcpFbCcmParamFir
Undefined symbol: cricket::kRtcpFbParamNack
Undefined symbol: cricket::kRtcpFbNackParamPli
Undefined symbol: cricket::kRedCodecName
Undefined symbol: cricket::kFlexfecFmtpRepairWindow
Undefined symbol: cricket::VideoCodec::VideoCodec(webrtc::SdpVideoFormat const&)
Undefined symbol: absl::EqualsIgnoreCase(absl::string_view, absl::string_view)
Undefined symbol: webrtc::operator==(webrtc::SdpVideoFormat const&, webrtc::SdpVideoFormat const&)
Undefined symbol: webrtc::SdpVideoFormat::ToString() const
Undefined symbol: webrtc::SdpVideoFormat::SdpVideoFormat(webrtc::SdpVideoFormat&&)
Undefined symbol: webrtc::SdpVideoFormat::SdpVideoFormat(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&)
Undefined symbol: webrtc::JsepIceCandidate::Initialize(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&, webrtc::SdpParseError*)
Undefined symbol: webrtc::JsepIceCandidate::candidate() const
Undefined symbol: cricket::Candidate::Candidate()
Undefined symbol: rtc::SocketAddress::operator=(rtc::SocketAddress const&)
Undefined symbol: webrtc::JsepIceCandidate::ToString(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator >) const
Undefined symbol: typeinfo for webrtc::ObjCVideoTrackSource
Undefined symbol: rtc::AdaptedVideoTrackSource::GetStats(webrtc::VideoTrackSourceInterface::Stats)
Undefined symbol: rtc::MessageHandler::~MessageHandler()
Undefined symbol: vtable for rtc::MessageHandler
Undefined symbol: webrtc::internal::SynchronousMethodCall::SynchronousMethodCall(rtc::MessageHandler*)
Undefined symbol: webrtc::internal::SynchronousMethodCall::Invoke(rtc::Location const&, rtc::Thread*)
Undefined symbol: webrtc::internal::SynchronousMethodCall::~SynchronousMethodCall()
Undefined symbol: rtc::TimestampAligner::~TimestampAligner()
Undefined symbol: rtc::VideoBroadcaster::~VideoBroadcaster()
Undefined symbol: rtc::AdaptedVideoTrackSource::~AdaptedVideoTrackSource()
Undefined symbol: webrtc::ObjCVideoTrackSource::ObjCVideoTrackSource()
Undefined symbol: webrtc::ObjCToNativeVideoDecoderFactory(id)
Undefined symbol: absl::variant_internal::ThrowBadVariantAccess()
Undefined symbol: rtc::CopyOnWriteBuffer::CopyOnWriteBuffer(unsigned long)
Undefined symbol: cricket::VideoCodec::VideoCodec(cricket::VideoCodec&&)
Undefined symbol: cricket::Candidate::Candidate(cricket::Candidate const&)
Undefined symbol: vtable for webrtc::BasicAsyncResolverFactory
Undefined symbol: rtc::SocketAddress::SocketAddress(rtc::SocketAddress const&)
Undefined symbol: rtc::ToString(int)
Undefined symbol: webrtc::SequenceCheckerImpl::IsCurrent() const
Undefined symbol: rtc::PacketOptions::PacketOptions()
Undefined symbol: rtc::PacketOptions::~PacketOptions()
Undefined symbol: cricket::ICE_UFRAG_LENGTH
Undefined symbol: cricket::ICE_PWD_LENGTH
Undefined symbol: rtc::BasicPacketSocketFactory::BasicPacketSocketFactory(rtc::Thread*)
Undefined symbol: cricket::RelayServerConfig::~RelayServerConfig()
Undefined symbol: rtc::SocketAddress::SocketAddress(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&, int)
Undefined symbol: cricket::PortAllocator::SetConfiguration(std::__1::set<rtc::SocketAddress, std::__1::lessrtc::SocketAddress, std::__1::allocatorrtc::SocketAddress > const&, std::__1::vector<cricket::RelayServerConfig, std::__1::allocatorcricket::RelayServerConfig > const&, int, webrtc::PortPrunePolicy, webrtc::TurnCustomizer*, absl::optional const&)
Undefined symbol: cricket::IceConfig::IceConfig()
Undefined symbol: cricket::IceConfig::~IceConfig()
Undefined symbol: cricket::kAv1CodecName
Undefined symbol: cricket::SsrcGroup::SsrcGroup(cricket::SsrcGroup const&)
Undefined symbol: cricket::AudioCodec::AudioCodec(cricket::AudioCodec const&)
Undefined symbol: webrtc::AudioDecoderOpus::SdpToConfig(webrtc::SdpAudioFormat const&)
Undefined symbol: webrtc::AudioDecoderOpus::AppendSupportedDecoders(std::__1::vector<webrtc::AudioCodecSpec, std::__1::allocatorwebrtc::AudioCodecSpec >)
Undefined symbol: webrtc::AudioEncoderOpus::MakeAudioEncoder(webrtc::AudioEncoderOpusConfig const&, int, absl::optionalwebrtc::AudioCodecPairId)
Undefined symbol: webrtc::AudioEncoderOpusConfig::~AudioEncoderOpusConfig()
Undefined symbol: webrtc::AudioEncoderOpus::SdpToConfig(webrtc::SdpAudioFormat const&)
Undefined symbol: webrtc::AudioEncoderOpus::QueryAudioEncoder(webrtc::AudioEncoderOpusConfig const&)
Undefined symbol: webrtc::SdpAudioFormat::~SdpAudioFormat()
Undefined symbol: vtable for webrtc::RtcEventLogNull
Undefined symbol: rtc::webrtc_logging_impl::Log(rtc::webrtc_logging_impl::LogArgType const, ...)
Undefined symbol: SetVTSessionProperty(void const*, __CFString const*, __CFString const*)
Undefined symbol: vtable for cricket::VideoCodec
Undefined symbol: cricket::kUlpfecCodecName
Undefined symbol: rtc::AdaptedVideoTrackSource::RemoveSink(rtc::VideoSinkInterfacewebrtc::VideoFrame)
Undefined symbol: webrtc::H264BitstreamParser::ParseBitstream(unsigned char const, unsigned long)
Undefined symbol: rtc::CopyOnWriteBuffer::UnshareAndEnsureCapacity(unsigned long)
Undefined symbol: vtable for webrtc::FieldTrialBasedConfig
Undefined symbol: rtc::CopyOnWriteBuffer::CopyOnWriteBuffer(rtc::CopyOnWriteBuffer&&)
Undefined symbol: rtc::TimeMillis()
Undefined symbol: rtc::SentPacket::SentPacket(long long, long long, rtc::PacketInfo const&)
Undefined symbol: cricket::VideoCodec::VideoCodec(cricket::VideoCodec const&)
Undefined symbol: webrtc::H264CMSampleBufferToAnnexBBuffer(opaqueCMSampleBuffer*, bool, rtc::BufferT<unsigned char, false>, std::__1::unique_ptr<webrtc::RTPFragmentationHeader, std::__1::default_deletewebrtc::RTPFragmentationHeader >)
Undefined symbol: webrtc::RtpExtension::ToString() const
Undefined symbol: webrtc::ObjCVideoTrackSource::state() const
Undefined symbol: cricket::kFlexfecCodecName
Undefined symbol: cricket::SsrcGroup::SsrcGroup(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&, std::__1::vector<unsigned int, std::__1::allocator > const&)
Undefined symbol: webrtc::CallConfig::~CallConfig()
Undefined symbol: webrtc::LocalAudioSinkAdapter::LocalAudioSinkAdapter()
Undefined symbol: vtable for webrtc::ObjCVideoTrackSource
Undefined symbol: webrtc::BitrateSettings::BitrateSettings()
Undefined symbol: webrtc::field_trial::InitFieldTrialsFromString(char const*)
Undefined symbol: webrtc::JsepIceCandidate::JsepIceCandidate(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&, int)
Undefined symbol: webrtc::Call::Create(webrtc::CallConfig const&)
Undefined symbol: cricket::kCodecParamMaxBitrate
Undefined symbol: webrtc::CryptoOptions::NoGcm()
Undefined symbol: _jpeg_destroy_compress
Undefined symbol: cricket::kCodecParamUseInbandFec
Undefined symbol: cricket::VideoCodec::ToString() const
Undefined symbol: cricket::kCodecParamPTime
Undefined symbol: webrtc::ObjCVideoTrackSource::is_screencast() const
Undefined symbol: cricket::AudioSendParameters::AudioSendParameters()
Undefined symbol: rtc::ByteBufferReader::ReadUInt16(unsigned short*)
Undefined symbol: webrtc::RtpExtension::kTransportSequenceNumberUri
Undefined symbol: cricket::VideoOptions::~VideoOptions()
Undefined symbol: webrtc::LocalAudioSinkAdapter::~LocalAudioSinkAdapter()
Undefined symbol: cricket::CreateMediaEngine(cricket::MediaEngineDependencies)
Undefined symbol: webrtc::CreateVideoFormatDescription(unsigned char const*, unsigned long)
Undefined symbol: webrtc::RTCStatsReport::begin() const
Undefined symbol: cricket::Codec::~Codec()
