### ISSUE TITLE
Bad audio quality

### ISSUE THREAD

**Issue by ethylmorphine** [TelegramMessenger/Telegram-iOS#31]
Telegram 5.5.1, iOS 12.2.

Sound quality of audio messages is absolutely terrible. Desktop version doesn’t compress the audio so atrociously much, and does provide way better sound. Is it possible to add an option to regulate sound compression?

I understand the reason behind it (to save bandwidth, I speculate), but I’d love to actually have an audio that doesn’t sound like a cheap toy.

**Comment by shivanraptor** [comment]
I don't have the same problem.
Check Settings > Data and Storage > Voice Calls > Use Less Data. 

Did you set it to "On Mobile Network" / "Always"?

**Comment by ethylmorphine** [comment]
It’s set on “Never”. I don’t think this setting affects the quality of voice messages.

**Comment by laktyushin** [comment]
Fixed in 5.10 release.
