### ISSUE TITLE
Telegram-iOS.workspace not found

### ISSUE THREAD

**Issue by GPX-NSlog** [TelegramMessenger/Telegram-iOS#310]
![image](https://user-images.githubusercontent.com/17864687/84563147-faeb3780-ad8b-11ea-9ee6-4454c51103d2.png)

**Comment by ajfigueroa** [comment]
From this [comment](https://github.com/TelegramMessenger/Telegram-iOS/issues/219#issuecomment-570533746), it sounds like we need to use BUCK to generate the workspace file.

However, when I try to run `make project` I run into an issue with the `.buckversion` missing.

**Comment by HareshGediya** [comment]
Can I get proper step or install.md file to create Telegram-iOS.workspace?
Thank you

**Comment by AbdulAli** [comment]
I have the same issue. Couldn't seem to find `Telegram-iOS.workspace` as suggested in the [Readme.md ](https://github.com/TelegramMessenger/Telegram-iOS/blob/master/README.md)

**Comment by balajihadole** [comment]
i also have same issue . if anybody have the proper compiled source code
please let us know

**Comment by deepal15** [comment]
Please could you provide a proper Readme.md file that contains steps to build and run the project

**Comment by shivanraptor** [comment]
Guys, please search through the issue list before asking this repeating issue.
See this procedure to build your project:
https://github.com/TelegramMessenger/Telegram-iOS/issues/219#issuecomment-570533746

**Comment by Gargo** [comment]
@shivanraptor 
"reproducible builds" instruction allows to generate ipa files via *censored* but it seems it doesn't allow to generate xcworkspace file
