### ISSUE TITLE
Compilation fails for 6.2.1

### ISSUE THREAD

**Issue by hailuomax** [TelegramMessenger/Telegram-iOS#312]
![WeChat7cdfed87ec62284e0f0afc41ea0fe3c3](https://user-images.githubusercontent.com/62380503/84869959-46198900-b0b1-11ea-851f-7699bc38160f.png)

Do I need to configure anything？

**Comment by shivanraptor** [comment]
It's not a bug. How do you generate the workspace? Did you update the `Makefile`?

**Comment by hailuomax** [comment]
Yes, I update the Makefile,and 'make project'

**Comment by ali-fareed** [comment]
Please see the updated build instructions in README.md.
