### ISSUE TITLE
iPad mini chat list width

### ISSUE THREAD

**Issue by alessaro92** [TelegramMessenger/Telegram-iOS#315]
Since commit 91f02f42fe9b2f5c22c00326890bdff7fdcaddf4, the main screen with the chat list on the left has changed the width of both the chat list and the current chat. It seems to be related to the fixed width set to 375 in the submodules/Display/Source/Navigation/NavigationSplitContainer.swift file. I can guarantee that on iPad mini screen form factor is worse. Can it be restored or at least add a setting parameter to control this behaviour?

**Comment by laktyushin** [comment]
Fixed in 6.3
