### ISSUE TITLE
Suggestion: Enable inline media playback in HTML5 games

### ISSUE THREAD

**Issue by GranPC** [TelegramMessenger/Telegram-iOS#316]
Hey, I've been experimenting with the Telegram game API to build a live game. While everything seems to work mostly as expected on Android, Desktop and other platforms, the UX on Telegram for iPhone is very confusing because my background video element is automatically brought fullscreen when the game is loaded, even with the `playsinline` attribute enabled.

After doing some digging I learnt that the app needs to enable `allowsInlineMediaPlayback` on the `WKWebViewConfiguration` for this attribute to work. So it would be awesome if you folks would consider enabling that option, which would enable for some fairly interesting Telegram games. Thanks!

**Comment by samzanemesis** [comment]
For reference as mentioned on Twitter, this is the part of code where there'd be changes: https://github.com/TelegramMessenger/Telegram-iOS/blob/master/submodules/GameUI/Sources/GameControllerNode.swift#L64

**Comment by GranPC** [comment]
This has been fixed with 2c52ee06dee0a0752a0480053f29db26628c8a2e. Thanks @laktyushin!!
