### ISSUE TITLE
Play button when editing video makes the app crash (could have to do with iOS 14 beta)

### ISSUE THREAD

**Issue by Laiteux** [TelegramMessenger/Telegram-iOS#324]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
When clicking the play button on the video edit screen, the app will crash. Same happens when clicking the sound button to disable video sound / make it a GIF.

### Expected Behavior
Shouldn't crash but do the requested action

### Actual Behavior
The app crashes/closes

### Steps to Reproduce
1. Open a chat
2. Click the attachment button so you can select a video to send
3. Click the video you wanna send
4. Perform actions I talked about
5. Crash

### Environment
**Device:** `iPhone 11`

**iOS version**: `14.0 beta 2/3`

**App version:** `6.2.1/6.3`

**Comment by AmyrAhmady** [comment]
I can also confirm this, not just Play button, but even when you are trying to trim the video it crashes and when you press sound button to mute it and send it as a gif
Works perfectly fine in playing it with no sound when you try to change the quality

**Comment by lumapii** [comment]
Same with iOS 10.2 and Telegram 6.3.1 here

**Comment by Oyshoboy** [comment]
Same Issue on iOS 14 beta 5, and Telegram 7.0

( can't edit video, play video in edit mode and convert it to gif )

**Comment by Laiteux** [comment]
Still reproducible with 7.0.1

**Comment by piccinnigius** [comment]
still in ios 14 full

**Comment by Oyshoboy** [comment]
It's finally fixed on **Telegram Version 7.0.2**, on **iOS 14.2**+

**Comment by Laiteux** [comment]
> It's finally fixed on **Telegram Version 7.0.2**, on **iOS 14.2**+

Confirmed. Thanks for letting us know!
