### ISSUE TITLE
Crash and blank screen

### ISSUE THREAD

**Issue by SpectreMz** [TelegramMessenger/Telegram-iOS#33]
Hi, i have this problem, Anyone Can help me?
https://i.imgur.com/aIOLS20.jpg
Last xcode version for High Sierra of xcode and last version of Telegram x (5.5)

**Comment by SpectreMz** [comment]
😊

**Comment by shivanraptor** [comment]
I didn't have the same issue. I noticed that you run it in Simulator. Does the same problem occur in real device?  When does this problem occur (e.g. during app launch)?

p.s. I run in real iPhone XR, didn't have such problem.

**Comment by SpectreMz** [comment]
When the app launch there is a sleep for few second and next crashes. 
I use a simulator because with my iPhone i get this error:
 :-1: No profile for team 'Manu (Personal Team)' matching 'match Development org.telegram.Telegram-iOS.Share' found: Xcode couldn't find any provisioning profiles matching 'DQ3CVYZ84C/match Development org.telegram.Telegram-iOS.Share'. Install the profile (by dragging and dropping it onto Xcode's dock item) or select a different one in the General tab of the target editor. (in target 'Share')

I'm a beginner 😊 thanks for reply

**Comment by patriciy** [comment]
Did you set fill Config-Fork.xcconfig?

I guess you should change your Bundle ID and register it on developer.apple.com. If 'org.telegram.Telegram-iOS.Share' is your own bundle ID (I can't recall what is official one) then just check any provision profile issue in xcode -> click Telegram iOS -> click share target, general tab, signing.
