### ISSUE TITLE
Compilation fails for 6.3

### ISSUE THREAD

**Issue by hailuomax** [TelegramMessenger/Telegram-iOS#330]
make project failed, and show me thise tips:
------------------------------------------------
 When running <genrule>.
    When building rule //third-party/webrtc:webrtc_build.
make: *** [project] Error 1
-------------------------------------------------

**Comment by ArtemTin** [comment]
Have you tried `git submodule update --init --recursive` just after cloning (inside repo folder)?

**Comment by cuzv** [comment]
Make project will pass, however build will fail.

**Comment by bitcard** [comment]
> Make project will pass, however build will fail.

are you solved it? I have same error.

**Comment by bitcard** [comment]
compile 6.3 with xcode 11.3 link error:

I use buck generate the Telegram_Buck.xcworkspace file.

it seems no build third-party/webrtc/webrtc-ios, I use this project: https://github.com/ali-fareed/webrtc-ios.git

Undefined symbol: cricket::IsSameCodec(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&, std::__1::map<std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator >, std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const, std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > > > > const&, std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&, std::__1::map<std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator >, std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const, std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > > > > const&)
Undefined symbol: webrtc::SdpVideoFormat::operator=(webrtc::SdpVideoFormat&&)
Undefined symbol: cricket::kRtcpFbParamCcm
Undefined symbol: cricket::kRtcpFbCcmParamFir
Undefined symbol: cricket::kRtcpFbParamNack
Undefined symbol: cricket::kRtcpFbNackParamPli
Undefined symbol: cricket::kRedCodecName
Undefined symbol: cricket::kFlexfecFmtpRepairWindow
Undefined symbol: cricket::VideoCodec::VideoCodec(webrtc::SdpVideoFormat const&)
Undefined symbol: absl::EqualsIgnoreCase(absl::string_view, absl::string_view)
Undefined symbol: webrtc::operator==(webrtc::SdpVideoFormat const&, webrtc::SdpVideoFormat const&)
Undefined symbol: webrtc::SdpVideoFormat::ToString() const
Undefined symbol: webrtc::SdpVideoFormat::SdpVideoFormat(webrtc::SdpVideoFormat&&)
Undefined symbol: webrtc::SdpVideoFormat::SdpVideoFormat(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&)
Undefined symbol: webrtc::JsepIceCandidate::Initialize(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&, webrtc::SdpParseError*)
Undefined symbol: webrtc::JsepIceCandidate::candidate() const
Undefined symbol: cricket::Candidate::Candidate()
Undefined symbol: rtc::SocketAddress::operator=(rtc::SocketAddress const&)
Undefined symbol: webrtc::JsepIceCandidate::ToString(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator >) const
Undefined symbol: typeinfo for webrtc::ObjCVideoTrackSource
Undefined symbol: rtc::AdaptedVideoTrackSource::GetStats(webrtc::VideoTrackSourceInterface::Stats)
Undefined symbol: rtc::MessageHandler::~MessageHandler()
Undefined symbol: vtable for rtc::MessageHandler
Undefined symbol: webrtc::internal::SynchronousMethodCall::SynchronousMethodCall(rtc::MessageHandler*)
Undefined symbol: webrtc::internal::SynchronousMethodCall::Invoke(rtc::Location const&, rtc::Thread*)
Undefined symbol: webrtc::internal::SynchronousMethodCall::~SynchronousMethodCall()
Undefined symbol: rtc::TimestampAligner::~TimestampAligner()
Undefined symbol: rtc::VideoBroadcaster::~VideoBroadcaster()
Undefined symbol: rtc::AdaptedVideoTrackSource::~AdaptedVideoTrackSource()
Undefined symbol: webrtc::ObjCVideoTrackSource::ObjCVideoTrackSource()
Undefined symbol: webrtc::ObjCToNativeVideoDecoderFactory(id)
Undefined symbol: absl::variant_internal::ThrowBadVariantAccess()
Undefined symbol: rtc::CopyOnWriteBuffer::CopyOnWriteBuffer(unsigned long)
Undefined symbol: cricket::VideoCodec::VideoCodec(cricket::VideoCodec&&)
Undefined symbol: cricket::Candidate::Candidate(cricket::Candidate const&)
Undefined symbol: vtable for webrtc::BasicAsyncResolverFactory
Undefined symbol: rtc::SocketAddress::SocketAddress(rtc::SocketAddress const&)
Undefined symbol: rtc::ToString(int)
Undefined symbol: webrtc::SequenceCheckerImpl::IsCurrent() const
Undefined symbol: rtc::PacketOptions::PacketOptions()
Undefined symbol: rtc::PacketOptions::~PacketOptions()
Undefined symbol: cricket::ICE_UFRAG_LENGTH
Undefined symbol: cricket::ICE_PWD_LENGTH
Undefined symbol: rtc::BasicPacketSocketFactory::BasicPacketSocketFactory(rtc::Thread*)
Undefined symbol: cricket::RelayServerConfig::~RelayServerConfig()
Undefined symbol: rtc::SocketAddress::SocketAddress(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&, int)
Undefined symbol: cricket::PortAllocator::SetConfiguration(std::__1::set<rtc::SocketAddress, std::__1::lessrtc::SocketAddress, std::__1::allocatorrtc::SocketAddress > const&, std::__1::vector<cricket::RelayServerConfig, std::__1::allocatorcricket::RelayServerConfig > const&, int, webrtc::PortPrunePolicy, webrtc::TurnCustomizer*, absl::optional const&)
Undefined symbol: cricket::IceConfig::IceConfig()
Undefined symbol: cricket::IceConfig::~IceConfig()
Undefined symbol: cricket::kAv1CodecName
Undefined symbol: cricket::SsrcGroup::SsrcGroup(cricket::SsrcGroup const&)
Undefined symbol: cricket::AudioCodec::AudioCodec(cricket::AudioCodec const&)
Undefined symbol: webrtc::AudioDecoderOpus::SdpToConfig(webrtc::SdpAudioFormat const&)
Undefined symbol: webrtc::AudioDecoderOpus::AppendSupportedDecoders(std::__1::vector<webrtc::AudioCodecSpec, std::__1::allocatorwebrtc::AudioCodecSpec >)
Undefined symbol: webrtc::AudioEncoderOpus::MakeAudioEncoder(webrtc::AudioEncoderOpusConfig const&, int, absl::optionalwebrtc::AudioCodecPairId)
Undefined symbol: webrtc::AudioEncoderOpusConfig::~AudioEncoderOpusConfig()
Undefined symbol: webrtc::AudioEncoderOpus::SdpToConfig(webrtc::SdpAudioFormat const&)
Undefined symbol: webrtc::AudioEncoderOpus::QueryAudioEncoder(webrtc::AudioEncoderOpusConfig const&)
Undefined symbol: webrtc::SdpAudioFormat::~SdpAudioFormat()
Undefined symbol: vtable for webrtc::RtcEventLogNull
Undefined symbol: rtc::webrtc_logging_impl::Log(rtc::webrtc_logging_impl::LogArgType const, ...)
Undefined symbol: SetVTSessionProperty(void const*, __CFString const*, __CFString const*)
Undefined symbol: vtable for cricket::VideoCodec
Undefined symbol: cricket::kUlpfecCodecName
Undefined symbol: rtc::AdaptedVideoTrackSource::RemoveSink(rtc::VideoSinkInterfacewebrtc::VideoFrame)
Undefined symbol: webrtc::H264BitstreamParser::ParseBitstream(unsigned char const, unsigned long)
Undefined symbol: rtc::CopyOnWriteBuffer::UnshareAndEnsureCapacity(unsigned long)
Undefined symbol: vtable for webrtc::FieldTrialBasedConfig
Undefined symbol: rtc::CopyOnWriteBuffer::CopyOnWriteBuffer(rtc::CopyOnWriteBuffer&&)
Undefined symbol: rtc::TimeMillis()
Undefined symbol: rtc::SentPacket::SentPacket(long long, long long, rtc::PacketInfo const&)
Undefined symbol: cricket::VideoCodec::VideoCodec(cricket::VideoCodec const&)
Undefined symbol: webrtc::H264CMSampleBufferToAnnexBBuffer(opaqueCMSampleBuffer*, bool, rtc::BufferT<unsigned char, false>, std::__1::unique_ptr<webrtc::RTPFragmentationHeader, std::__1::default_deletewebrtc::RTPFragmentationHeader >)
Undefined symbol: webrtc::RtpExtension::ToString() const
Undefined symbol: webrtc::ObjCVideoTrackSource::state() const
Undefined symbol: cricket::kFlexfecCodecName
Undefined symbol: cricket::SsrcGroup::SsrcGroup(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&, std::__1::vector<unsigned int, std::__1::allocator > const&)
Undefined symbol: webrtc::CallConfig::~CallConfig()
Undefined symbol: webrtc::LocalAudioSinkAdapter::LocalAudioSinkAdapter()
Undefined symbol: vtable for webrtc::ObjCVideoTrackSource
Undefined symbol: webrtc::BitrateSettings::BitrateSettings()
Undefined symbol: webrtc::field_trial::InitFieldTrialsFromString(char const*)
Undefined symbol: webrtc::JsepIceCandidate::JsepIceCandidate(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&, int)
Undefined symbol: webrtc::Call::Create(webrtc::CallConfig const&)
Undefined symbol: cricket::kCodecParamMaxBitrate
Undefined symbol: webrtc::CryptoOptions::NoGcm()
Undefined symbol: _jpeg_destroy_compress
Undefined symbol: cricket::kCodecParamUseInbandFec
Undefined symbol: cricket::VideoCodec::ToString() const
Undefined symbol: cricket::kCodecParamPTime
Undefined symbol: webrtc::ObjCVideoTrackSource::is_screencast() const
Undefined symbol: cricket::AudioSendParameters::AudioSendParameters()
Undefined symbol: rtc::ByteBufferReader::ReadUInt16(unsigned short*)
Undefined symbol: webrtc::RtpExtension::kTransportSequenceNumberUri
Undefined symbol: cricket::VideoOptions::~VideoOptions()
Undefined symbol: webrtc::LocalAudioSinkAdapter::~LocalAudioSinkAdapter()
Undefined symbol: cricket::CreateMediaEngine(cricket::MediaEngineDependencies)
Undefined symbol: webrtc::CreateVideoFormatDescription(unsigned char const*, unsigned long)
Undefined symbol: webrtc::RTCStatsReport::begin() const
Undefined symbol: cricket::Codec::~Codec()

**Comment by shivanraptor** [comment]
> ## make project failed, and show me thise tips:
> ## When running .
> When building rule //third-party/webrtc:webrtc_build.
> make: *** [project] Error 1

How do you change the `Makefile` before issuing `make project`?

**Comment by freyzou** [comment]
@shivanraptor 
Have you solved that issue?

**Comment by shivanraptor** [comment]
No problem encountered during `make project` phase. Failed during the compilation of the workspace (same as #333 for release 7.0 and 7.0.1 ). Suspected the deployment iOS target version as the culprit; still investigating.

**Comment by klaus01** [comment]
Please see https://github.com/TelegramMessenger/Telegram-iOS/issues/333#issuecomment-693513087

**Comment by xingye** [comment]
it can be built using Xcode11.x. `find_sdk.py`file use the regular expression:'^MacOSX(10\.\d+)\.sdk$' to find the sdk, it fails within Xcode12.x.

**Comment by ali-fareed** [comment]
Please see the updated build instructions in README.md.
