### ISSUE TITLE
No send options (send with timer, without sound, schedule) for images pasted from clipboard

### ISSUE THREAD

**Issue by arx8x** [TelegramMessenger/Telegram-iOS#334]
### Checklist 
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
In a recent update, telegram moved the functionality of setting timer on Images and videos to the send button. Previously it was accessed through a button in the toolbar displayed below the media item. Now, when you select an image from albums, you can long tap on the send button and get the send options, including the button to set timer. But this doesn't work for images pasted from clipboard. 
 

### Expected Behavior
After pasting an image from clipboard to the message input box, long tapping on the send button should show send options (send with timer, schedule message, send silently etc)

### Actual Behavior
After pasting an image from clipboard to the message input box, nothing happens if you long tap the send button

### Steps to Reproduce
1. Open sharesheet for an image (from photos app or anywhere else) and copy the image
2. Open a chat on Telegram, long tap the message input box to get the option to paste and tap "paste"
3. Tap an image it shows and long tap the send button

### Screenshots and Videos 

![image](https://user-images.githubusercontent.com/16128407/89969193-6ad64b00-dc73-11ea-8b6a-4b9d4de465ce.png)

### Environment
**Device:** `iPhone X, iPhone 6s, iPhone 6, iPhone 5`

**iOS version**: `13.X, 10.x, 12.x`

**App version:** `6.3.1`

**Comment by laktyushin** [comment]
Fixed.
