### ISSUE TITLE
GPL license violation!

### ISSUE THREAD

**Issue by Gargo** [TelegramMessenger/Telegram-iOS#336]
Men provide normal instructions how to build these sources please!

Tried instructions from readme - your sources don't contain workspace file.

Tried these instructions:
https://core.telegram.org/reproducible-builds#reproducible-builds-for-ios
1)Why do I need Parallels if telegram is a native iOS app and could be built with xcode only?
2)"Step 6. Obtaining the source code" - git contains no telegram versions to checkout but ok, let skip this step
3)`cd $HOME/telegram-ios/tools/buck-build && mkdir -p $HOME/buck_source sh ./prepare_buck_source.sh $HOME/buck_source` - doesn't work at all because of error `mkdir: ./prepare_buck_source.sh: Not a directory`

If you missed some resources then you violate GPL!

**Comment by SergeyKolokolnikov** [comment]
do it separately
1) mkdir $HOME/buck_source
2) cd $HOME/telegram-ios/tools/buck-build
3) sh ./prepare_buck_source.sh $HOME/buck_source

**Comment by BlokenClockCrisps** [comment]
This is nuts -- I'd love to make a contribution, but there's no adequate guide on how to even generate working Xcode project files -- that guide on reproducible builds is just too complex to make the project actually work out of the box. 
There's a comment in #219 with instructions that lead to generating workspace files but Xcode hangs upon opening them and there are also errors during buck build. I don't need to check my build against what's in App Store, I don't want to install a proprietary virtualization suite just to make it work -- please, update README to make it possible to build the app for yourself -- otherwise absence of proper build instructions defeats the purpose of having an open-source repo for this app in the first place!

**Comment by Gargo** [comment]
@BlokenClockCrisps 
1)I simply don't have so much disk space to install project sources+virtual machine+macos (which should be redundant because I already run the same macos version) + another set of sources and libs inside virtual machine
2)the guide is too complex
3)why don't you create and pull workspace file at least for releases? On my work we pull cocoapods to prevent the situation when github becomes unavailable. Why don't you do that with workspace? The only reason I see is to prevent most of other developers use these sources. But you forget that workspace file belongs to sources too so you violate GPL
4)you said about contribution to the repo... how can I contribute if I can't even compile it?

**Comment by BlokenClockCrisps** [comment]
@Gargo 
I believe that the omission of workspace files is just an overlook and there's no malicious intention behind that -- AFAIK making reproducible builds work (which, I think, is why there are no workspace files at all) is not an easy thing to accomplish. But I also see that this trait anyway is useless if you want to contribuite to the project, so it's to everybody's benefit that there be an easier and documented way to compile it. Either using Buck or including workspace files if that's possible.

**Comment by Gargo** [comment]
@BlokenClockCrisps somehow I downgraded java version to 11 and was able to build buck:
```
export JAVA_HOME=`/usr/libexec/java_home -v 11`
```
BUT the next step requires a virtual machine.

And suddenly I find out that guide doens't generate a workspace file you mention in Readme.md! Instead it somehow takes sources and generates ipa from them directly.
Is it the only way I can build an app? Again I don't need to make an app which fully compatible with your "reproducible builds" yet. I just need to compile sources somehow to see what they represent in general. So steps with ipa/jailbroken device are really extra (of course if you don't violate gpl to make ios build compilation harder or even impossible)

**Comment by Gargo** [comment]
И люди вы там в конец охренели что ли? Думаете что можно тырить чужие разработки под открытой лицензией и запрещать их использование?

**Comment by ali-fareed** [comment]
Please see the updated build instructions in README.md.
