### ISSUE TITLE
How Can I build a .ipa file and upload AppStore.

### ISSUE THREAD

**Issue by zhongliIOS** [TelegramMessenger/Telegram-iOS#339]
I archive the project. But can‘t find the way to upload to appstore or export a .ipa file

**Comment by shivanraptor** [comment]
This is not a bug. You just don't know how to compile the App for App Store.

**Comment by zezezea** [comment]
I have the same problem. Solved it？

**Comment by ali-fareed** [comment]
Please see the updated build instructions in README.md.
