### ISSUE TITLE
Sending Photos With EXIF Data

### ISSUE THREAD

**Issue by FaroukZeino** [TelegramMessenger/Telegram-iOS#340]
Currently there is no way on Telegram on iOS to send photos with their EXIF data, even while sending photos as files, it doesn't work and the EXIF data get erased. While that works fine on Telegram for Android.

**Comment by horak** [comment]
This is so unfortunate. Does anyone know why this is the case? Or any messaging bot services that do include this crucial information?

**Comment by horak** [comment]
@FaroukZeino, I am receiving EXIF data when I send photos as files, on iOS. Can you be explicit about what steps you are taking to reproduce this?

**Comment by FaroukZeino** [comment]
@horak This has changed recently (don't know exactly in which update), when I opened the issue even sending as a file wasn't retaining EXIF data.

**Comment by horak** [comment]
Gotcha. All good now though, right? Shall we close this?
