### ISSUE TITLE
Git clone does not work

### ISSUE THREAD

**Issue by Zeriamans** [TelegramMessenger/Telegram-iOS#352]
Hey everybody!

I'm facing a problem when downloading code by 
```
git clone --recursive https://github.com/TelegramMessenger/Telegram-iOS.git
``` 

I receive an error
```
fatal: remote error: upload-pack: not our ref b906b5a955f1e6e195cb91c4513d4cb7b3620ea6
fatal: the remote end hung up unexpectedly
Fetched in submodule path 'submodules/TgVoipWebrtc/tgcalls', but it did not contain b906b5a955f1e6e195cb91c4513d4cb7b3620ea6. Direct fetching of that commit failed.
```

It seems that commit b906b5a955f1e6e195cb91c4513d4cb7b3620ea6 was not pushed in https://github.com/TelegramMessenger/tgcalls
or we should use another commit here
<img width="1218" alt="Screenshot 2020-09-04 at 17 29 37" src="https://user-images.githubusercontent.com/57899633/92250498-37828700-eed4-11ea-82e1-0999c77e1a87.png">

Thank you and have a nice day!

**Comment by shivanraptor** [comment]
If you are unable to clone the latest version, try specifying the branch:

    git clone --recursive --branch release-7.0.1 https://github.com/TelegramMessenger/telegram-ios.git

**Comment by Zeriamans** [comment]
Thank you @shivanraptor 

I've checked now `git clone --recursive https://github.com/TelegramMessenger/Telegram-iOS.git` and it works as expected because now https://github.com/TelegramMessenger/tgcalls contains commit `b906b5a955f1e6e195cb91c4513d4cb7b3620ea6`
