### ISSUE TITLE
make project failed, version 7.0, also 7.0.1

### ISSUE THREAD

**Issue by freyzou** [TelegramMessenger/Telegram-iOS#353]
### Checklist
- [ ] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
Describe the issue that you are experiencing

### Expected Behavior
Tell us what should happen

### Actual Behavior
Tell us what happens instead

### Steps to Reproduce
1. clone source
2. follow #219 
3. make project failed

### err messages

stderr: + echo SRCDIR=/Users/xxx/Telegram-iOS-release-7.0.1/buck-out/gen/third-party/webrtc/webrtc_build__srcs
+ BUILD_ARCH=arm64
+ BUILD_DIR_ARM64=/Users/xxx/Telegram-iOS-release-7.0.1/buck-out/gen/third-party/webrtc/webrtc_build__srcs/arm64
+ BUILD_DIR=/Users/xxx/Telegram-iOS-release-7.0.1/buck-out/gen/third-party/webrtc/webrtc_build__srcs/arm64
+ rm -rf /Users/xxx/Telegram-iOS-release-7.0.1/buck-out/gen/third-party/webrtc/webrtc_build__srcs/arm64
+ mkdir -p /Users/xxx/Telegram-iOS-release-7.0.1/buck-out/gen/third-party/webrtc/webrtc_build__srcs/arm64
+ mkdir -p /Users/xxx/Telegram-iOS-release-7.0.1/buck-out/gen/third-party/webrtc/webrtc_build__srcs/arm64/webrtc-ios
+ cp -R /Users/xxx/Telegram-iOS-release-7.0.1/buck-out/gen/third-party/webrtc/webrtc_build__srcs/webrtc-ios/src /Users/xxx/Telegram-iOS-release-7.0.1/buck-out/gen/third-party/webrtc/webrtc_build__srcs/arm64/webrtc-ios/src
+ DEPOT_TOOLS_PATH=/Users/xxx/Telegram-iOS-release-7.0.1/buck-out/gen/third-party/depot_tools_sources__/depot_tools_sources
+ rm -rf /Users/xxx/Telegram-iOS-release-7.0.1/buck-out/gen/third-party/webrtc/webrtc_build__srcs/arm64/depot_tools
+ cp -R /Users/xxx/Telegram-iOS-release-7.0.1/buck-out/gen/third-party/depot_tools_sources__/depot_tools_sources /Users/xxx/Telegram-iOS-release-7.0.1/buck-out/gen/third-party/webrtc/webrtc_build__srcs/arm64/
+ rm -rf /Users/xxx/Telegram-iOS-release-7.0.1/buck-out/gen/third-party/webrtc/webrtc_build__srcs/arm64/openssl
+ cp -R /Users/xxx/Telegram-iOS-release-7.0.1/buck-out/gen/submodules/openssl/openssl_build_merged/openssl /Users/xxx/Telegram-iOS-release-7.0.1/buck-out/gen/third-party/webrtc/webrtc_build__srcs/arm64/openssl/
+ cp -R /Users/xxx/Telegram-iOS-release-7.0.1/buck-out/gen/submodules/openssl/openssl_libssl_merged/libssl /Users/xxx/Telegram-iOS-release-7.0.1/buck-out/gen/third-party/webrtc/webrtc_build__srcs/arm64/libssl/
+ sh /Users/xxx/Telegram-iOS-release-7.0.1/buck-out/gen/third-party/webrtc/webrtc_build__srcs/build-webrtc-buck.sh /Users/xxx/Telegram-iOS-release-7.0.1/buck-out/gen/third-party/webrtc/webrtc_build__srcs/arm64 arm64
+ set -e
+ BUILD_DIR=/Users/xxx/Telegram-iOS-release-7.0.1/buck-out/gen/third-party/webrtc/webrtc_build__srcs/arm64
+ ARCH=arm64
+ echo BUILD_DIR=/Users/xxx/Telegram-iOS-release-7.0.1/buck-out/gen/third-party/webrtc/webrtc_build__srcs/arm64
+ echo ARCH=arm64
+ export PATH=/Users/xxx/.sdkman/candidates/springboot/current/bin:/Users/xxx/.sdkman/candidates/java/current/bin:/usr/local/opt/openjdk/bin:/usr/local/opt/icu4c/sbin:/usr/local/opt/icu4c/bin:/usr/local/opt/openssl@1.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/xxx/Telegram-iOS-release-7.0.1/buck-out/gen/third-party/webrtc/webrtc_build__srcs/arm64/depot_tools_sources/depot_tools
+ PATH=/Users/xxx/.sdkman/candidates/springboot/current/bin:/Users/xxx/.sdkman/candidates/java/current/bin:/usr/local/opt/openjdk/bin:/usr/local/opt/icu4c/sbin:/usr/local/opt/icu4c/bin:/usr/local/opt/openssl@1.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/xxx/Telegram-iOS-release-7.0.1/buck-out/gen/third-party/webrtc/webrtc_build__srcs/arm64/depot_tools_sources/depot_tools
+ rm -rf /Users/xxx/Telegram-iOS-release-7.0.1/buck-out/gen/third-party/webrtc/webrtc_build__srcs/arm64/webrtc-ios/src/openssl
+ cp -R /Users/xxx/Telegram-iOS-release-7.0.1/buck-out/gen/third-party/webrtc/webrtc_build__srcs/arm64/openssl /Users/xxx/Telegram-iOS-release-7.0.1/buck-out/gen/third-party/webrtc/webrtc_build__srcs/arm64/webrtc-ios/src/
+ cp -R /Users/xxx/Telegram-iOS-release-7.0.1/buck-out/gen/third-party/webrtc/webrtc_build__srcs/arm64/libssl /Users/xxx/Telegram-iOS-release-7.0.1/buck-out/gen/third-party/webrtc/webrtc_build__srcs/arm64/webrtc-ios/src/
+ pushd /Users/xxx/Telegram-iOS-release-7.0.1/buck-out/gen/third-party/webrtc/webrtc_build__srcs/arm64/webrtc-ios/src
+ mv openssl/lib/libcrypto.a openssl/
+ mv libssl/lib/libssl.a openssl/
+ OUT_DIR=ios
+ '[' arm64 == arm64 ']'
+ OUT_DIR=ios_64
+ buildtools/mac/gn gen out/ios_64 '--args=use_xcode_clang=true  target_cpu="arm64" target_os="ios" is_debug=false is_component_build=false rtc_include_tests=false use_rtti=true rtc_use_x11=false use_custom_libcxx=false use_custom_libcxx_for_host=false rtc_build_ssl=false rtc_build_examples=false rtc_build_tools=false ios_deployment_target="9.0" ios_enable_code_signing=false is_unsafe_developer_build=false rtc_enable_protobuf=false rtc_include_builtin_video_codecs=true rtc_build_libvpx=true rtc_libvpx_build_vp9=true rtc_use_gtk=false rtc_use_metal_rendering=true'

    When running <genrule>.
    When building rule //third-party/webrtc:webrtc_build.
make: *** [project] Error 1

### Environment
macOS: 10.15.6
Xcode: 11.3

**Comment by SergeyKolokolnikov** [comment]
for generate webrtc project arm64 update your BUCK file in third-party/webrtc/BUCK 
it should be like this

> load("//Config:buck_rule_macros.bzl", "static_library")
> 
> webrtc_lib_flags = [
>     "-lframework_objc_static"
> ]
> 
> genrule(
>     name = "webrtc_build",
>     srcs = [
>         "build-webrtc-buck.sh",
>         "webrtc-ios",
>     ],
>     bash =
> """
>     set -x
>     echo "SRCDIR=$SRCDIR"
> 
>     BUILD_ARCH=arm64
> 
>     BUILD_DIR_ARM64="$SRCDIR/$BUILD_ARCH"
> 
>     BUILD_DIR="$BUILD_DIR_ARM64"
>     rm -rf "$BUILD_DIR"
>     mkdir -p "$BUILD_DIR"
> 
>     mkdir -p "$BUILD_DIR/webrtc-ios"
>     cp -R "$SRCDIR/webrtc-ios/src" "$BUILD_DIR/webrtc-ios/src"
> 
>     DEPOT_TOOLS_PATH="$(location //third-party:depot_tools_sources)"
> 
>     rm -rf "$BUILD_DIR/depot_tools"
>     cp -R "$DEPOT_TOOLS_PATH" "$BUILD_DIR/"
> 
>     rm -rf "$BUILD_DIR/openssl"
>     cp -R "$(location //submodules/openssl:openssl_build_merged)" "$BUILD_DIR/openssl/"
>     cp -R "$(location //submodules/openssl:openssl_libssl_merged)" "$BUILD_DIR/libssl/"
> 
>     sh $SRCDIR/build-webrtc-buck.sh "$BUILD_DIR" $BUILD_ARCH
> 
>     BUILD_ARCH=arm
> 
>     BUILD_DIR_ARMV7="$SRCDIR/$BUILD_ARCH"
> 
>     BUILD_DIR="$BUILD_DIR_ARMV7"
> 
>     rm -rf "$BUILD_DIR"
>     mkdir -p "$BUILD_DIR"
> 
>     mkdir -p "$BUILD_DIR/webrtc-ios"
>     cp -R "$SRCDIR/webrtc-ios/src" "$BUILD_DIR/webrtc-ios/src"
> 
>     DEPOT_TOOLS_PATH="$(location //third-party:depot_tools_sources)"
> 
>     rm -rf "$BUILD_DIR/depot_tools"
>     cp -R "$DEPOT_TOOLS_PATH" "$BUILD_DIR/"
> 
>     rm -rf "$BUILD_DIR/openssl"
>     cp -R "$(location //submodules/openssl:openssl_build_merged)" "$BUILD_DIR/openssl/"
>     cp -R "$(location //submodules/openssl:openssl_libssl_merged)" "$BUILD_DIR/libssl/"
> 
>     sh $SRCDIR/build-webrtc-buck.sh "$BUILD_DIR" $BUILD_ARCH
> 
>  BUILD_ARCH=x64
>     BUILD_DIR_X64="$SRCDIR/$BUILD_ARCH"
>     BUILD_DIR="$BUILD_DIR_X64"
>     rm -rf "$BUILD_DIR"
>     mkdir -p "$BUILD_DIR"
>     mkdir -p "$BUILD_DIR/webrtc-ios"
>     cp -R "$SRCDIR/webrtc-ios/src" "$BUILD_DIR/webrtc-ios/src"
>     DEPOT_TOOLS_PATH="$(location //third-party:depot_tools_sources)"
>     rm -rf "$BUILD_DIR/depot_tools"
>     cp -R "$DEPOT_TOOLS_PATH" "$BUILD_DIR/"
>     rm -rf "$BUILD_DIR/openssl"
>     cp -R "$(location //submodules/openssl:openssl_build_merged)" "$BUILD_DIR/openssl/"
>     cp -R "$(location //submodules/openssl:openssl_libssl_merged)" "$BUILD_DIR/libssl/"
>     sh $SRCDIR/build-webrtc-buck.sh "$BUILD_DIR" $BUILD_ARCH
> 
> 
>     mkdir -p "$OUT"
> lipo -create "$BUILD_DIR_ARMV7/webrtc-ios/src/out/ios/obj/sdk/libframework_objc_static.a" "$BUILD_DIR_ARM64/webrtc-ios/src/out/ios_64/obj/sdk/libframework_objc_static.a" "$BUILD_DIR_X64/webrtc-ios/src/out/ios_sim/obj/sdk/libframework_objc_static.a" -output "$OUT/libframework_objc_static.a"
> """,
>     out = "libwebrtc",
>     visibility = ["PUBLIC"]
> )
> 
> apple_library(
>     name = "webrtc_lib",
>     visibility = [
>         "PUBLIC",
>     ],
>     linker_flags = [
>         "-L$(location :webrtc_build)",
>     ] + webrtc_lib_flags,
>     exported_linker_flags = [
>         "-L$(location :webrtc_build)",
>     ] + webrtc_lib_flags,
>     deps = [
>         ":webrtc_build"
>     ],
> )


after that in terminal make project

**Comment by freyzou** [comment]
@SergeyKolokolnikov. That's right. Now `make project` passed, but build in Xcode failed. Any ideas?

**Comment by SergeyKolokolnikov** [comment]
@freyzou after cloning project you should checkout branch release-7.0.1 and make project.

**Comment by freyzou** [comment]
@SergeyKolokolnikov I mean build error below, in Xcode 11.6.
<img width="1171" alt="Screen Shot 2020-09-08 at 4 10 04 PM" src="https://user-images.githubusercontent.com/19159299/92450541-24cac380-f1ee-11ea-9e2b-6c6639c22288.png">

**Comment by klaus01** [comment]
> @SergeyKolokolnikov I mean build error below, in Xcode 11.6.
> <img alt="Screen Shot 2020-09-08 at 4 10 04 PM" width="1171" src="https://user-images.githubusercontent.com/19159299/92450541-24cac380-f1ee-11ea-9e2b-6c6639c22288.png">

https://github.com/TelegramMessenger/Telegram-iOS/issues/333#issuecomment-693513087

**Comment by twisturn** [comment]
> for generate webrtc project arm64 update your BUCK file in third-party/webrtc/BUCK
> it should be like this
> 
> > load("//Config:buck_rule_macros.bzl", "static_library")
> > webrtc_lib_flags = [
> > "-lframework_objc_static"
> > ]
> > genrule(
> > name = "webrtc_build",
> > srcs = [
> > "build-webrtc-buck.sh",
> > "webrtc-ios",
> > ],
> > bash =
> > """
> > set -x
> > echo "SRCDIR=$SRCDIR"
> > ```
> > BUILD_ARCH=arm64
> > 
> > BUILD_DIR_ARM64="$SRCDIR/$BUILD_ARCH"
> > 
> > BUILD_DIR="$BUILD_DIR_ARM64"
> > rm -rf "$BUILD_DIR"
> > mkdir -p "$BUILD_DIR"
> > 
> > mkdir -p "$BUILD_DIR/webrtc-ios"
> > cp -R "$SRCDIR/webrtc-ios/src" "$BUILD_DIR/webrtc-ios/src"
> > 
> > DEPOT_TOOLS_PATH="$(location //third-party:depot_tools_sources)"
> > 
> > rm -rf "$BUILD_DIR/depot_tools"
> > cp -R "$DEPOT_TOOLS_PATH" "$BUILD_DIR/"
> > 
> > rm -rf "$BUILD_DIR/openssl"
> > cp -R "$(location //submodules/openssl:openssl_build_merged)" "$BUILD_DIR/openssl/"
> > cp -R "$(location //submodules/openssl:openssl_libssl_merged)" "$BUILD_DIR/libssl/"
> > 
> > sh $SRCDIR/build-webrtc-buck.sh "$BUILD_DIR" $BUILD_ARCH
> > 
> > BUILD_ARCH=arm
> > 
> > BUILD_DIR_ARMV7="$SRCDIR/$BUILD_ARCH"
> > 
> > BUILD_DIR="$BUILD_DIR_ARMV7"
> > 
> > rm -rf "$BUILD_DIR"
> > mkdir -p "$BUILD_DIR"
> > 
> > mkdir -p "$BUILD_DIR/webrtc-ios"
> > cp -R "$SRCDIR/webrtc-ios/src" "$BUILD_DIR/webrtc-ios/src"
> > 
> > DEPOT_TOOLS_PATH="$(location //third-party:depot_tools_sources)"
> > 
> > rm -rf "$BUILD_DIR/depot_tools"
> > cp -R "$DEPOT_TOOLS_PATH" "$BUILD_DIR/"
> > 
> > rm -rf "$BUILD_DIR/openssl"
> > cp -R "$(location //submodules/openssl:openssl_build_merged)" "$BUILD_DIR/openssl/"
> > cp -R "$(location //submodules/openssl:openssl_libssl_merged)" "$BUILD_DIR/libssl/"
> > 
> > sh $SRCDIR/build-webrtc-buck.sh "$BUILD_DIR" $BUILD_ARCH
> > ```
> > 
> > 
> > BUILD_ARCH=x64
> > BUILD_DIR_X64="$SRCDIR/$BUILD_ARCH"
> > BUILD_DIR="$BUILD_DIR_X64"
> > rm -rf "$BUILD_DIR"
> > mkdir -p "$BUILD_DIR"
> > mkdir -p "$BUILD_DIR/webrtc-ios"
> > cp -R "$SRCDIR/webrtc-ios/src" "$BUILD_DIR/webrtc-ios/src"
> > DEPOT_TOOLS_PATH="$(location //third-party:depot_tools_sources)"
> > rm -rf "$BUILD_DIR/depot_tools"
> > cp -R "$DEPOT_TOOLS_PATH" "$BUILD_DIR/"
> > rm -rf "$BUILD_DIR/openssl"
> > cp -R "$(location //submodules/openssl:openssl_build_merged)" "$BUILD_DIR/openssl/"
> > cp -R "$(location //submodules/openssl:openssl_libssl_merged)" "$BUILD_DIR/libssl/"
> > sh $SRCDIR/build-webrtc-buck.sh "$BUILD_DIR" $BUILD_ARCH
> > ```
> > mkdir -p "$OUT"
> > ```
> > 
> > 
> > lipo -create "$BUILD_DIR_ARMV7/webrtc-ios/src/out/ios/obj/sdk/libframework_objc_static.a" "$BUILD_DIR_ARM64/webrtc-ios/src/out/ios_64/obj/sdk/libframework_objc_static.a" "$BUILD_DIR_X64/webrtc-ios/src/out/ios_sim/obj/sdk/libframework_objc_static.a" -output "$OUT/libframework_objc_static.a"
> > """,
> > out = "libwebrtc",
> > visibility = ["PUBLIC"]
> > )
> > apple_library(
> > name = "webrtc_lib",
> > visibility = [
> > "PUBLIC",
> > ],
> > linker_flags = [
> > "-L$(location :webrtc_build)",
> > ] + webrtc_lib_flags,
> > exported_linker_flags = [
> > "-L$(location :webrtc_build)",
> > ] + webrtc_lib_flags,
> > deps = [
> > ":webrtc_build"
> > ],
> > )
> 
> after that in terminal make project

'mozjpeg/turbojpeg.h' file not found

**Comment by alyfreym** [comment]
HI. Why is closed? You found a solution? I have the same problem.

**Comment by alyfreym** [comment]
Just remove this import header. And replace compression code in to UIImageJPEGRepresentation() or see in 6.3 release how to as implemented there without fucking mozjpeg lib.

**Comment by amadeu01** [comment]
@SergeyKolokolnikov I copied the code for Buck script as you comment in https://github.com/TelegramMessenger/Telegram-iOS/issues/333#issuecomment-701288888

However, it is still failing to generate the project duet to web `webrtc `

**Comment by freyzou** [comment]
I'm not sure what's going on there. 
Open again because it's still failed on version 7.2.

**Comment by freyzou** [comment]
The project make process will fail on one of my machine, while always goes well on another. So the problem may at the Env.

**Comment by ali-fareed** [comment]
Please see the updated build instructions in README.md.
