### ISSUE TITLE
[FR] Publish two instances of the app in the App Store

### ISSUE THREAD

**Issue by NightMachinery** [TelegramMessenger/Telegram-iOS#354]
I want to control the notifications from different accounts using iOS's notifications settings, which is easily possible by just having two Telegram apps. In the old days, we had Telegram X, but that was discontinued. Having Telegram X back as just a copy of this client will not hurt anyone and can help people like me who use multiple accounts (with widely different usages).

PS: Nicegram's notifications are buggy. Loopy also seems to have big lags for notifications. So third-party apps aren't much of an answer to this problem.

**Comment by shivanraptor** [comment]
Is this an issue of the Telegram app itself? Seems not.

**Comment by NightMachinary** [comment]
> Is this an issue of the Telegram app itself? Seems not.

It’s first and foremost an issue of Apple’s dictatorship, but Telegram is in a position to mitigate the issue.

**Comment by xsKk** [comment]
> 

I have encountered the problem of ios listing review others, can you provide any help?

**Comment by culturetown** [comment]
请问怎么提供审核测试账号呢
