### ISSUE TITLE
Compilation fails for 7.0.1

### ISSUE THREAD

**Issue by twisturn** [TelegramMessenger/Telegram-iOS#364]
make project failed, and show me thise tips:

Command failed with exit code 127.

command: [/bin/bash, -e, /Users/xx/Desktop/tg the last/Telegram-iOS-3/buck-out/tmp/genrule-5095195852774295951.sh]

stderr: sh: /Users/xx/Desktop/tg: No such file or directory

    When running <genrule>.
    When building rule //submodules/openssl:openssl_build_arm64.
make: *** [project] Error 1

**Comment by shivanraptor** [comment]
How does your `Makefile` look like?

**Comment by twisturn** [comment]
Insert before include Utils.makefile in the Makefile file:
export BUCK=buck
export TELEGRAM_ENV_SET=1
export DEVELOPMENT_CODE_SIGN_IDENTITY=iPhone Distribution: Digital Fortress LLC (C67CF9S4VU)
export DISTRIBUTION_CODE_SIGN_IDENTITY=iPhone Distribution: Digital Fortress LLC (C67CF9S4VU)
export DEVELOPMENT_TEAM=C67CF9S4VU
export API_ID=8
export API_HASH=7245de8e747a0d6fbe11f7cc14fcc0bb
export BUNDLE_ID=ph.telegra.Telegraph
export IS_INTERNAL_BUILD=false
export IS_APPSTORE_BUILD=true
export APPSTORE_ID=686449807
export APP_SPECIFIC_URL_SCHEME=tgapp
export BUILD_NUMBER=199
export ENTITLEMENTS_APP=Telegram-iOS/Telegram-iOS-AppStoreLLC.entitlements
export DEVELOPMENT_PROVISIONING_PROFILE_APP=match Development ph.telegra.Telegraph
export DISTRIBUTION_PROVISIONING_PROFILE_APP=match AppStore ph.telegra.Telegraph
export ENTITLEMENTS_EXTENSION_SHARE=Share/Share-AppStoreLLC.entitlements
export DEVELOPMENT_PROVISIONING_PROFILE_EXTENSION_SHARE=match Development ph.telegra.Telegraph.Share
export DISTRIBUTION_PROVISIONING_PROFILE_EXTENSION_SHARE=match AppStore ph.telegra.Telegraph.Share
export ENTITLEMENTS_EXTENSION_WIDGET=Widget/Widget-AppStoreLLC.entitlements
export DEVELOPMENT_PROVISIONING_PROFILE_EXTENSION_WIDGET=match Development ph.telegra.Telegraph.Widget
export DISTRIBUTION_PROVISIONING_PROFILE_EXTENSION_WIDGET=match AppStore ph.telegra.Telegraph.Widget
export ENTITLEMENTS_EXTENSION_NOTIFICATIONSERVICE=NotificationService/NotificationService-AppStoreLLC.entitlements
export DEVELOPMENT_PROVISIONING_PROFILE_EXTENSION_NOTIFICATIONSERVICE=match Development ph.telegra.Telegraph.NotificationService
export DISTRIBUTION_PROVISIONING_PROFILE_EXTENSION_NOTIFICATIONSERVICE=match AppStore ph.telegra.Telegraph.NotificationService
export ENTITLEMENTS_EXTENSION_NOTIFICATIONCONTENT=NotificationContent/NotificationContent-AppStoreLLC.entitlements
export DEVELOPMENT_PROVISIONING_PROFILE_EXTENSION_NOTIFICATIONCONTENT=match Development ph.telegra.Telegraph.NotificationContent
export DISTRIBUTION_PROVISIONING_PROFILE_EXTENSION_NOTIFICATIONCONTENT=match AppStore ph.telegra.Telegraph.NotificationContent
export ENTITLEMENTS_EXTENSION_INTENTS=SiriIntents/SiriIntents-AppStoreLLC.entitlements
export DEVELOPMENT_PROVISIONING_PROFILE_EXTENSION_INTENTS=match Development ph.telegra.Telegraph.SiriIntents
export DISTRIBUTION_PROVISIONING_PROFILE_EXTENSION_INTENTS=match AppStore ph.telegra.Telegraph.SiriIntents
export DEVELOPMENT_PROVISIONING_PROFILE_WATCH_APP=match Development ph.telegra.Telegraph.watchkitapp
export DISTRIBUTION_PROVISIONING_PROFILE_WATCH_APP=match AppStore ph.telegra.Telegraph.watchkitapp
export DEVELOPMENT_PROVISIONING_PROFILE_WATCH_EXTENSION=match Development ph.telegra.Telegraph.watchkitapp.watchkitextension
export DISTRIBUTION_PROVISIONING_PROFILE_WATCH_EXTENSION=match AppStore ph.telegra.Telegraph.watchkitapp.watchkitextension
export BUILDBOX_DIR=buildbox
export CODESIGNING_PROFILES_VARIANT=appstore
export PACKAGE_METHOD=appstore

**Comment by klaus01** [comment]
Please see https://github.com/TelegramMessenger/Telegram-iOS/issues/333#issuecomment-693513087

**Comment by shivanraptor** [comment]
> Insert before include Utils.makefile in the Makefile file:
> export BUCK=buck
> export TELEGRAM_ENV_SET=1
> export DEVELOPMENT_CODE_SIGN_IDENTITY=iPhone Distribution: Digital Fortress LLC (C67CF9S4VU)
> export DISTRIBUTION_CODE_SIGN_IDENTITY=iPhone Distribution: Digital Fortress LLC (C67CF9S4VU)
> export DEVELOPMENT_TEAM=C67CF9S4VU
> export API_ID=8
> export API_HASH=7245de8e747a0d6fbe11f7cc14fcc0bb
> export BUNDLE_ID=ph.telegra.Telegraph
> export IS_INTERNAL_BUILD=false
> export IS_APPSTORE_BUILD=true
> export APPSTORE_ID=686449807
> export APP_SPECIFIC_URL_SCHEME=tgapp
> export BUILD_NUMBER=199
> export ENTITLEMENTS_APP=Telegram-iOS/Telegram-iOS-AppStoreLLC.entitlements
> export DEVELOPMENT_PROVISIONING_PROFILE_APP=match Development ph.telegra.Telegraph
> export DISTRIBUTION_PROVISIONING_PROFILE_APP=match AppStore ph.telegra.Telegraph
> export ENTITLEMENTS_EXTENSION_SHARE=Share/Share-AppStoreLLC.entitlements
> export DEVELOPMENT_PROVISIONING_PROFILE_EXTENSION_SHARE=match Development ph.telegra.Telegraph.Share
> export DISTRIBUTION_PROVISIONING_PROFILE_EXTENSION_SHARE=match AppStore ph.telegra.Telegraph.Share
> export ENTITLEMENTS_EXTENSION_WIDGET=Widget/Widget-AppStoreLLC.entitlements
> export DEVELOPMENT_PROVISIONING_PROFILE_EXTENSION_WIDGET=match Development ph.telegra.Telegraph.Widget
> export DISTRIBUTION_PROVISIONING_PROFILE_EXTENSION_WIDGET=match AppStore ph.telegra.Telegraph.Widget
> export ENTITLEMENTS_EXTENSION_NOTIFICATIONSERVICE=NotificationService/NotificationService-AppStoreLLC.entitlements
> export DEVELOPMENT_PROVISIONING_PROFILE_EXTENSION_NOTIFICATIONSERVICE=match Development ph.telegra.Telegraph.NotificationService
> export DISTRIBUTION_PROVISIONING_PROFILE_EXTENSION_NOTIFICATIONSERVICE=match AppStore ph.telegra.Telegraph.NotificationService
> export ENTITLEMENTS_EXTENSION_NOTIFICATIONCONTENT=NotificationContent/NotificationContent-AppStoreLLC.entitlements
> export DEVELOPMENT_PROVISIONING_PROFILE_EXTENSION_NOTIFICATIONCONTENT=match Development ph.telegra.Telegraph.NotificationContent
> export DISTRIBUTION_PROVISIONING_PROFILE_EXTENSION_NOTIFICATIONCONTENT=match AppStore ph.telegra.Telegraph.NotificationContent
> export ENTITLEMENTS_EXTENSION_INTENTS=SiriIntents/SiriIntents-AppStoreLLC.entitlements
> export DEVELOPMENT_PROVISIONING_PROFILE_EXTENSION_INTENTS=match Development ph.telegra.Telegraph.SiriIntents
> export DISTRIBUTION_PROVISIONING_PROFILE_EXTENSION_INTENTS=match AppStore ph.telegra.Telegraph.SiriIntents
> export DEVELOPMENT_PROVISIONING_PROFILE_WATCH_APP=match Development ph.telegra.Telegraph.watchkitapp
> export DISTRIBUTION_PROVISIONING_PROFILE_WATCH_APP=match AppStore ph.telegra.Telegraph.watchkitapp
> export DEVELOPMENT_PROVISIONING_PROFILE_WATCH_EXTENSION=match Development ph.telegra.Telegraph.watchkitapp.watchkitextension
> export DISTRIBUTION_PROVISIONING_PROFILE_WATCH_EXTENSION=match AppStore ph.telegra.Telegraph.watchkitapp.watchkitextension
> export BUILDBOX_DIR=buildbox
> export CODESIGNING_PROFILES_VARIANT=appstore
> export PACKAGE_METHOD=appstore

You didn't even change the parameters.

Also, have you installed Xcode command line tools (which includes the OpenSSL)

**Comment by twisturn** [comment]
Need to change the parameters？
I have installed Xcode command line tools.Is there a limit to the Xcode version? I am using xcode 11

**Comment by andy-yx-chen** [comment]
I am getting the error as below, any thoughts?

java.nio.file.NoSuchFileException: /Users/xxxx/xx/src/telegram/iOS/buck-out/gen/third-party/depot_tools_sources__/depot_tools_sources
	at com.facebook.buck.util.cache.impl.StackedFileHashCache.lambda$1(StackedFileHashCache.java:186)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at com.facebook.buck.util.cache.impl.StackedFileHashCache.get(StackedFileHashCache.java:186)
	at com.facebook.buck.rules.keys.RuleKeyBuilder.setPath(RuleKeyBuilder.java:248)
	at com.facebook.buck.rules.keys.InputBasedRuleKeyFactory$Builder.setPath(InputBasedRuleKeyFactory.java:201)
	at com.facebook.buck.rules.keys.InputBasedRuleKeyFactory$Builder.setPath(InputBasedRuleKeyFactory.java:1)
	at com.facebook.buck.rules.keys.RuleKeyBuilder.setSourcePathDirectly(RuleKeyBuilder.java:175)
	at com.facebook.buck.rules.keys.InputBasedRuleKeyFactory$Builder.setSourcePath(InputBasedRuleKeyFactory.java:220)
	at com.facebook.buck.rules.keys.InputBasedRuleKeyFactory$Builder.setSourcePath(InputBasedRuleKeyFactory.java:1)
	at com.facebook.buck.rules.keys.AbstractRuleKeyBuilder.setReflectively(AbstractRuleKeyBuilder.java:88)
	at com.facebook.buck.rules.keys.AbstractRuleKeyBuilder.setReflectively(AbstractRuleKeyBuilder.java:61)
	... 110 more

    When adding path with value Pair(//third-party:depot_tools_sources, buck-out/gen/third-party/depot_tools_sources__/depot_tools_sources)
    When amending path.
    When amending args.
    When amending bash.
    When amending buildableForRuleKey.
    When building rule //third-party/webrtc:webrtc_build.

**Comment by kebbbnnn** [comment]
Hi, how did you solved this issue?
