### ISSUE TITLE
[iPadOS 14] Scribble feature not working properly on text field

### ISSUE THREAD

**Issue by duckdodger** [TelegramMessenger/Telegram-iOS#367]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
When I try to use the Scribble feature introduced in iPadOS 14 on Telegram's text field in chats, it doesn't work. On rare occasions I see Apple Pencil being recognised as I'm able to scribble something, but it bugs out, the keyboard pops up and nothing happens.
 
### Expected Behavior
Scribble should work properly just like on Safari, Notes and other native first-party apps.  
### Actual Behavior
Scribble doesn't work or is buggy on Telegram.

### Steps to Reproduce
1. Try writing something on the text field in Telegram with Apple Pencil on an iPad.

### Environment
**Device:** `iPad (6th Gen)`

**iOS version**: `iPadOS 14.0`

**App version:** `7.0.1`

**Comment by duckdodger** [comment]
Scribble seems to work properly on the latest update of Telegram (7.1). So I'm closing this issue. Thanks!

**Comment by DavisAndhersonF** [comment]
In facing the same issue. I'm on the latest update of telegram too

**Comment by emaba** [comment]
I've issues on the latest version, too. It seems to be buggy

**Comment by SuibianP** [comment]
Same issue, on the latest version.
iPad Air generation 4 if it helps.

**Comment by GeneralistDev** [comment]
This still occurs after sending a couple of messages and app needs restarting in order to fix it temporarily

**Comment by YogurtTheHorse** [comment]
I can confirm the issue on iPad 8th gen with current latest Telegram version

**Comment by 44-5-53-6-k** [comment]
iPad Pro 11 M1. Scribble doesn't work. Apple Pencil typing in keybord works with bugs. Selection of wordsdoesn't work withapple pencil.
