### ISSUE TITLE
build failed version 7.0.1

### ISSUE THREAD

**Issue by twisturn** [TelegramMessenger/Telegram-iOS#369]
Parsing buck files: finished in 4.7 sec
Generating project: finished in 06:12.3 min (100%)
Building: finished in 06:06.9 min (100%) 114/224 jobs, 114 updated
  Total time: 06:12.3 min
Command failed with exit code 1.

command: [/bin/bash, -e, /Users/zj/Desktop/ttg/Telegram-iOS/buck-out/tmp/genrule-8222193683197515025.sh]

stderr: + echo SRCDIR=/Users/zj/Desktop/ttg/Telegram-iOS/buck-out/gen/third-party/webrtc/webrtc_build__srcs
+ BUILD_ARCH=arm64
+ BUILD_DIR_ARM64=/Users/zj/Desktop/ttg/Telegram-iOS/buck-out/gen/third-party/webrtc/webrtc_build__srcs/arm64
+ BUILD_DIR=/Users/zj/Desktop/ttg/Telegram-iOS/buck-out/gen/third-party/webrtc/webrtc_build__srcs/arm64
+ rm -rf /Users/zj/Desktop/ttg/Telegram-iOS/buck-out/gen/third-party/webrtc/webrtc_build__srcs/arm64
+ mkdir -p /Users/zj/Desktop/ttg/Telegram-iOS/buck-out/gen/third-party/webrtc/webrtc_build__srcs/arm64
+ mkdir -p /Users/zj/Desktop/ttg/Telegram-iOS/buck-out/gen/third-party/webrtc/webrtc_build__srcs/arm64/webrtc-ios
+ cp -R /Users/zj/Desktop/ttg/Telegram-iOS/buck-out/gen/third-party/webrtc/webrtc_build__srcs/webrtc-ios/src /Users/zj/Desktop/ttg/Telegram-iOS/buck-out/gen/third-party/webrtc/webrtc_build__srcs/arm64/webrtc-ios/src
cp: /Users/zj/Desktop/ttg/Telegram-iOS/buck-out/gen/third-party/webrtc/webrtc_build__srcs/webrtc-ios/src: No such file or directory

    When running <genrule>.
    When building rule //third-party/webrtc:webrtc_build.
make: *** [project] Error 1

**Comment by amadeu01** [comment]
@twisturn same error here. Have you found a solution?

**Comment by zhanqi** [comment]
same error

**Comment by zhwlkj** [comment]
same error

**Comment by twisturn** [comment]
Have you found a solution?

**Comment by ali-fareed** [comment]
Please see the updated build instructions in README.md.
