### ISSUE TITLE
'mozjpeg/turbojpeg.h' file not found

### ISSUE THREAD

**Issue by twisturn** [TelegramMessenger/Telegram-iOS#370]
The turbojpeg.h file exists, but it prompt 'mozjpeg/turbojpeg.h' file not found

**Comment by alyfreym** [comment]
Did you solve the same problem? I got the same problem

**Comment by alyfreym** [comment]
Just remove this import header. And replace compression code in to `UIImageJPEGRepresentation()` or see in 6.3 release how to as implemented there without fucking mozjpeg lib.

**Comment by ali-fareed** [comment]
Please refer to the updated build instructions in README.md.

**Comment by elemanhillary** [comment]
Same thing here i want to use the compression somewhere else
