### ISSUE TITLE
Failed to build with Xcode 12.0 (supports iOS 14)

### ISSUE THREAD

**Issue by shivanraptor** [TelegramMessenger/Telegram-iOS#374]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
Describe the issue that you are experiencing
The project can be compiled in Xcode 11, but unable to be compiled in Xcode 12 (in order to test the functionality in iOS 12), when targeting iOS 14 physical device (iPhone XR)

There are 2 main issues:

1. Ambigious use of 'generateImage' in various Swift classes, including `LocationMapHeaderNode.swift` line 13 & `LocationmapNode.swift` line 72, which the function candidate is found at `GenerateImage.swift` line 113 and 145.

Seems the compiler behavior in Xcode 12 has changed.

2. The `dylib` has errors: Could not find {module name} for target 'armv7-apple-ios'; found: arm64, arm64-apple-ios

Seems the default value of Architecture in Build Settings `$(STANDARD_ARCH)` does not include `armv7-apple-ios`. Example module is `Display`.

### Expected Behavior
Tell us what should happen
The project should be able to compile in Xcode 12.

### Actual Behavior
Tell us what happens instead

### Steps to Reproduce
1. Install Xcode 12 (the official version from App Store, not beta versions)
2. Clean build folder of the generated project
3. Build and Run with the target "iOS Device": iPhone XR

### Environment
**Device:** `iPhone XR 256GB`
**iOS version**: `14.0`
**App version:** `7.0.1`
**Xcode version:** `12.0`

**Comment by shivanraptor** [comment]
The relevant changes in Xcode 12 are:

> The Build Settings editor no longer includes the Valid Architectures build setting (VALID_ARCHS), and its use is discouraged. Instead, there is a new Excluded Architectures build setting (EXCLUDED_ARCHS). If a project includes VALID_ARCHS, the setting is displayed in the User-Defined section of the Build Settings editor. (15145028)

https://developer.apple.com/documentation/xcode-release-notes/xcode-12-release-notes

**Comment by TimorYang** [comment]
@shivanraptor 
You need to modify the caller of this method and fill in other parameters. After you modify, this problem will be resolved

**Comment by ali-fareed** [comment]
Please see the updated build instructions in README.md.
