### ISSUE TITLE
SettingsController.swift not called

### ISSUE THREAD

**Issue by shivanraptor** [TelegramMessenger/Telegram-iOS#375]
I don't think it's a bug, but the codes in the `SettingsController.swift`, which is responsible for the Settings tab, not called in `release-7.0.1`. Previously the codes are called in `release-6.2.1` and below.

Are the codes relocated to other Swift class? Thanks in advance.

**Comment by Kylmakalle** [comment]
It's now `PeerInfoScreen.swift`
