### ISSUE TITLE
README.md build instructions are misleading

### ISSUE THREAD

**Issue by DevilDimon** [TelegramMessenger/Telegram-iOS#377]
### Checklist
- [ ] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
README.md hosts a build instruction that does not work. Following the instruction step-by-step does not lead to a successful build, as noted by many existing issues (#336, #328, #325, #230, #219, #310, #222, #216, ). I personally was not able to build the project with readme as well. Using other issues to help with the build was also futile and as a result I abandoned any hope to build this locally.
I've wasted enough time on this to continue, but maybe an improved build instruction would enable potential contributors to at least build the actual project. Blindly making changes to the codebase can only go so far. Please note that this issue is not about reproducible build, but is rather about local builds for development.

**Comment by amadeu01** [comment]
@DevilDimon maybe we could build a wiki with proper instructions to build and contribute with the project.

**Comment by ali-fareed** [comment]
Please see the updated build instructions in README.md.
