### ISSUE TITLE
Telegram-7.0.1 build failed.

### ISSUE THREAD

**Issue by alyfreym** [TelegramMessenger/Telegram-iOS#378]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
'libavcodec/avcodec.h' file not found

Has anyone managed to solve this problem?

### Environment
XCode - Version 12.0 (12A7209)

**Comment by xingye** [comment]
encounter the same error. have any solution?

**Comment by ali-fareed** [comment]
Please see the updated build instructions in README.md.
