### ISSUE TITLE
Time-stamps for Youtube don't work

### ISSUE THREAD

**Issue by ghost** [TelegramMessenger/Telegram-iOS#384]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
Sending a time-stamp for a Youtube video doesn’t work and it starts from the beginning of the video.

### Expected Behavior
The video should start at the specified time.

### Actual Behavior
It starts from the very beginning of the video with the timing of the bar on the bottom messed up.

### Steps to Reproduce
1. Send a Youtube link
2. Reply with at time-stamp - ie: 3:30
3. Click the time-stamp

### Screenshots and Videos 
![photo_2020-10-04_09-34-19](https://user-images.githubusercontent.com/57873259/95009771-d2ca6180-0624-11eb-9d89-fb6b31f04e4a.jpg)

### Environment
**Device:** `iPhone SE 2`

**iOS version**: `14.0.1`

**App version:** `7.1`

**Comment by laktyushin** [comment]
Fixed in 7.2

**Comment by mu3** [comment]
Replying with a time code to a message that includes YouTube link doesn't work on:

- Telegram 7.4.1 on iOS 14.4
- Telegram 7.3 on macOS 11.1

The time code is highlighted but not clickable.
