### ISSUE TITLE
Cannot upload app because .dylib inside in Frameworks.

### ISSUE THREAD

**Issue by alyfreym** [TelegramMessenger/Telegram-iOS#386]
Hi, I added telegrams to my application and everything is okay. When I upload the application I to ItunesConnect get an error. - _ITMS-90429: Invalid Swift Support - The files libswiftMetal.dylib, libswiftsimd.dylib, libswiftCallKit.dylib, libswiftos.dylib, libswiftMapKit.dylib, libswiftCoreLocation.dylib, libswiftAccelerate.dylib, libswiftCoreGraphics.dylib, libswiftCoreData.dylib, libswiftUIKit.dylib, libswiftCore.dylib, libswiftFoundation.dylib, libswiftPhotos.dylib, libswiftModelIO.dylib, libswiftDarwin.dylib, libswiftCoreAudio.dylib, libswiftIntents.dylib, libswiftQuartzCore.dylib, libswiftObjectiveC.dylib, libswiftDispatch.dylib, libswiftCoreFoundation.dylib, libswiftCoreMedia.dylib, libswiftAVFoundation.dylib, libswiftContacts.dylib, libswiftGLKit.dylib, libswiftMediaPlayer.dylib, libswiftCloudKit.dylib, libswiftCoreImage.dylib aren’t at the expected location /Payload/OU7.app/Frameworks. Move the file to the expected location, rebuild your app using the current public (GM) version of Xcode, and resubmit it_ This is because Apple does not allow the use of dylib in release ipa. I created a separate framework where I added all the .dylibs. Then I added this to my main project. When trying to load it into itunes connect I got the following error - _Invalid bundle. The bundle contains disallowed file. _ This is a mistake on my .framework  in which I put all tg .dylibs. Structure framework my.framework/Frameworks/ all .dylibs. Question - How to pack correctly .dylibs? _libDisplay.dylib, libMtProtoKit.dylib, libPostbox.dylib, libAsyncDisplayKit.dylib, libSwiftSignalKit.dylib, libSyncCore.dylib, libTelegramApi.dylib, libTelegramCore.dylib, libTelegramUI.dylib_

**Comment by ali-fareed** [comment]
Please see the updated build instructions in README.md.

**Comment by Don-oneself** [comment]
I introduced libtdjson in the React-native project and encountered this situation after uploading it. What should I adjust in Xcode?@ali-fareed
