### ISSUE TITLE
Rich notifications not working on iOS

### ISSUE THREAD

**Issue by alexqzd** [TelegramMessenger/Telegram-iOS#392]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
Rich notifications are not working on iOS.

### Expected Behavior
iOS should show a preview of a picture when received.

### Actual Behavior
The notification just says 'Photo' and an emoji of a camera.

### Steps to Reproduce
1. Receive a picture while the iPhone is locked.
2. Open the notification preview by long pressing it.

### Screenshots and Videos 
Expected:
![Webp net-resizeimage-2](https://user-images.githubusercontent.com/5033308/95887057-043dde00-0d45-11eb-8dd8-0b6015a7b2ab.png)

Actual:
![Webp net-resizeimage](https://user-images.githubusercontent.com/5033308/95887155-1e77bc00-0d45-11eb-8c72-facfa9359709.jpg)

### Environment
**Device:** `iPhone 11 Pro Max`

**iOS version**: `14.0.1`

**App version:** `7.1.2`

**Comment by JesseWebDotCom** [comment]
I know this bug is old but its still an issue.  Any update?

**Comment by alexqzd** [comment]
A couple months ago it started working again like for 3 weeks and then stopped for some reason

**Comment by JesseWebDotCom** [comment]
Why was this closed?  Is it fixed?

**Comment by alexqzd** [comment]
Works for me in the latest beta 8.2.1 (22323)

**Comment by JesseWebDotCom** [comment]
> Works for me in the latest beta 8.2.1 (22323)

How do I install the beta on my iPhone?

**Comment by alexqzd** [comment]
> How do I install the beta on my iPhone?

With TestFlight. But the beta program is currently full
https://testflight.apple.com/join/u6iogfd0

**Comment by Winor** [comment]
Works for me since the latest update 8.2.1(22323). It's now available on the app store,
thank you! 🎉
