### ISSUE TITLE
Hey guys!. please help with upload in iTunesConnect 

### ISSUE THREAD

**Issue by alyfreym** [TelegramMessenger/Telegram-iOS#393]
I have an application to which I add telegram. When I try to upload into iTunesConnect I get an error related to .dylibs. Telegram generates _libDisplay.dylib, libPostbox.dylib etc..._ but according to the documentation apple, in ios can't use .dylibs. only system lib support. In Debug mode its working perfect but when upload all fail. I see that telegram has scripts for packing and loading, but I cannot use it because it is not used in my project buck and cmake. I ask for help how to solve this problem, maybe there is some way to convert .dylibs in to .a or .framework. thank you very much for your help!

**Comment by zezezea** [comment]
Can you tell me how to generate an IPA file？ thanks

**Comment by alyfreym** [comment]
> Can you tell me how to generate an IPA file？ thanks

my email alyfreym@gmail.com. i have script file for build.

**Comment by ali-fareed** [comment]
Please see the updated build instructions in README.md.
