### ISSUE TITLE
Missing Secret Chat Option after last update

### ISSUE THREAD

**Issue by nemanjapetrovic** [TelegramMessenger/Telegram-iOS#395]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
I've noticed after the latest update I am missing an option to create a new Secret Chat.

### Expected Behavior

I should be able to create a new secret chat.

### Actual Behavior

Missing that option in the menu.

### Steps to Reproduce
1. Open Telegram App
2. Go to the Right top corner icon to write a new message
3. New message window is displayed without New Secret Chat option

### Screenshots

![image](https://user-images.githubusercontent.com/15672932/96014749-05573400-0e47-11eb-9b2b-3a9e74225a75.png)

### Environment
**Device:** `iPhone 8`

**iOS version**: `14.0.1`

**App version:** `7.1.2`

**Comment by joroek** [comment]
I have noticed the same issue.

**Comment by joroek** [comment]
I found the solution... You need to go into contacts and click on the contact you wish to initiate a new secret chat with, and then select it from the drop down menu there.

**Comment by nemanjapetrovic** [comment]
@joroek Yup, that is currently the only way to create a Secret Chat. But, before there was a quicker option via New Message Menu.

**Comment by pwndumb** [comment]
> I found the solution... You need to go into contacts and click on the contact you wish to initiate a new secret chat with, and then select it from the drop down menu there.

In IOS in iPhone 7 and 10 this not work. Doesn't have this option.

**Comment by pwndumb** [comment]
> I found the solution... You need to go into contacts and click on the contact you wish to initiate a new secret chat with, and then select it from the drop down menu there.

Please can you explain this ? I can't create a Secret Chat in my Telegram in IPHONE 10 with IOS 13.

**Comment by pwndumb** [comment]
> I found the solution... You need to go into contacts and click on the contact you wish to initiate a new secret chat with, and then select it from the drop down menu there.

Please can you explain this ? I can't start a secret chat in Iphone 10 with iOS 13. The option not appear and when I hold some contact this options not appear at all.
