### ISSUE TITLE
x86_64 issue

### ISSUE THREAD

**Issue by JianBinWu** [TelegramMessenger/Telegram-iOS#399]
i use Xcode 11 to run this project on simulator. but Xcode show the error like this:

Undefined symbols for architecture x86_64:
  "static UIKit.UIPointerShape.defaultCornerRadius.getter : CoreGraphics.CGFloat", referenced from:
      Display.(PointerInteractionImpl in _B39DD7E7F85F24DF4F7212BCFE28692F).pointerInteraction(_: __C.UIPointerInteraction, styleFor: __C.UIPointerRegion) -> __C.UIPointerStyle? in PointerInteraction.o
  "enum case for UIKit.UIPointerShape.roundedRect(UIKit.UIPointerShape.Type) -> (__C.CGRect, CoreGraphics.CGFloat) -> UIKit.UIPointerShape"

How can I solve this error

**Comment by ali-fareed** [comment]
Please see the updated build instructions in README.md.
