### ISSUE TITLE
Little design issue in blocked list

### ISSUE THREAD

**Issue by anfimovir** [TelegramMessenger/Telegram-iOS#4]
Version **5.0.17**

Screenshot:
![photo_2018-11-20_13-47-26](https://user-images.githubusercontent.com/10336636/48768799-2353a280-eccb-11e8-9761-0327d9c90a8c.jpg)

In this section (in setting) description for page fixed in center on page, your need to make it fixed under the button

**Comment by laktyushin** [comment]
Fixed in 5.10 release.
