### ISSUE TITLE
Context menu is invisible on iPad with Slide Over

### ISSUE THREAD

**Issue by MasterGroosha** [TelegramMessenger/Telegram-iOS#40]
When using Telegram on iPad in [SlideOver](https://support.apple.com/en-jo/HT207582) mode (so that the app is shown above the current one), context menu is missing. Screenshot below. Can reproduce in versions 5.4-5.6 (the most recent one)
**iOS version**: 12.2

![изображение](https://user-images.githubusercontent.com/2780044/57560046-39deda80-738d-11e9-9311-3244c4b5802b.png)

**Comment by laktyushin** [comment]
Fixed in 5.10 release.

**Comment by MasterGroosha** [comment]
@laktyushin It's not fixed in 5.10 (14289). Even became worse in some cases (instead of just showing empty space, it appears as invisible overlay). Please reopen.
![изображение](https://user-images.githubusercontent.com/2780044/62793301-eee27980-bad9-11e9-85b7-994bb9784abc.png)
![изображение](https://user-images.githubusercontent.com/2780044/62793307-f3a72d80-bad9-11e9-8f69-7e7d219cf7c4.png)

**Comment by laktyushin** [comment]
It works fine for me. What iPad model do you have?

**Comment by MasterGroosha** [comment]
When I opened this issue I had iPad 2018 (9.7"). Now I tested with iPad Pro 2017 (10.5"). 
Will check with iPad 2018 again

**Comment by MasterGroosha** [comment]
![изображение](https://user-images.githubusercontent.com/2780044/62798032-f445c100-bae5-11e9-9eb6-9936468b583b.png)
![изображение](https://user-images.githubusercontent.com/2780044/62798039-f740b180-bae5-11e9-8ec7-e0339e9e23f8.png)

Same here on iPad 2018 with iOS 12.4. I didn't annotate screenshots this time, everything from previous ones apply to these images

**Comment by LucaRed** [comment]
Given the new context menu, this now looks fixed, at least on iPadOS 13.1

![07D47C28-2516-4B9D-9180-A40F37B638A9](https://user-images.githubusercontent.com/16584297/66267534-3fecc080-e832-11e9-890c-2f3c66e14bc8.png)

**Comment by MasterGroosha** [comment]
Ouch, sorry for the delay. Yes, the issue is now solved, closing in.
