### ISSUE TITLE
Configure proxy before logging in

### ISSUE THREAD

**Issue by rixtox** [TelegramMessenger/Telegram-iOS#402]
In regions where Telegram is censored by ISP, the login flow would be stucked at the "Start Messaging" welcome screen.
Even if one has a working MTProxy, he/she would not be given an option to set it without logging in.
I think this is a flaw in the proxy setting design. Telegram should provide proxy setting options in the login flow.

**Comment by laktyushin** [comment]
When you try to log in and the app can't reach servers you get an alert suggesting you to setup proxy.
![proxy](https://user-images.githubusercontent.com/491013/96913773-24903a00-14b5-11eb-92ab-a98da5247d23.png)

**Comment by rixtox** [comment]
Here is the screen recording: [https://imgur.com/Ntlx03h](https://imgur.com/Ntlx03h.gif)

**Comment by MikePryadko** [comment]
Why this issue is closed? Problem still exists! (version`10.8.2`) After pressing "Start messaging" nothing happens (because servers unavalilable from my internet-provider) -- how should I get settings for configuring proxy??
