### ISSUE TITLE
Crash when sending "#7+@" by typing the secondary characters of each letter in the word "SUCA"

### ISSUE THREAD

**Issue by delivrance** [TelegramMessenger/Telegram-iOS#406]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
Crash when sending "#‌‌‎7+@" by typing the secondary characters of each letter in the word "SUCA".

### Steps to Reproduce
1. Open a chat.
2. Long press/swipe down each letter of the word "SUCA" (without quotes).
3. Send the resulting text "#‌‌‎7+@". 

### Environment
**Device:** `iPad Air 4 & iPhone 12`

**iOS version**: `14.1`

**App version:** `7.2 (18230)`

**Comment by SergeyKolokolnikov** [comment]
same on android and ios

**Comment by laktyushin** [comment]
Fixed in 7.2.1
