### ISSUE TITLE
Message field bugged after updating to iOS 14.2

### ISSUE THREAD

**Issue by Neurotoxin001** [TelegramMessenger/Telegram-iOS#409]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
When I tap on text field to write message it's stucks after I close it

### Steps to Reproduce
1. Update iOS to 14.2
2. Try to write message
3. Text field to write message will stuck

### Screenshots and Videos 
https://i.imgur.com/hAX4USf.mp4

### Environment
**Device:** `iPhone XR`

**iOS version**: `14.2`

**App version:** `7.2`

**Comment by semprix** [comment]
Experiencing the same on the following environment

Device: iPhone XS
iOS Version: 14.2
App Version: 7.2

I did try to remove all other existing keyboards (emoji and grammarly), uninstall-reinstall, still problem exists.

![image](https://user-images.githubusercontent.com/208085/98351700-05b6a980-2058-11eb-8551-37bc39511e62.png)

**Comment by nltommynl** [comment]
Also experiencing the same:

Device: iPhone 6S
iOS Version: 14.2
App Version: 7.2

**Comment by paulbazinet** [comment]
Same issue here. It’s been weeks. So frustrating.

**Comment by Neurotoxin001** [comment]
Disabling "reduce motion" is helped, but bug is still needs to be fixed:
![image](https://user-images.githubusercontent.com/39812401/98470311-d178ef80-21f5-11eb-8532-ccf5bda1434c.png)

**Comment by Neurotoxin001** [comment]
Lol, I'm just enabled "Reduce Motion" again and bug is not come back, so all you must do if you have this issue just disable Reduce Motion, open telegram, and enable Reduce Motion again

**Comment by semprix** [comment]
Confirmed the quick fix by @Neurotoxin001

**Comment by laktyushin** [comment]
Fixed in 7.2.1
