### ISSUE TITLE
Voice message via voice recorder

### ISSUE THREAD

**Issue by hookzof** [TelegramMessenger/Telegram-iOS#417]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
A voice message recorded by the standard "Voice recorder" application is not sent.

### Expected Behavior
A voice message is sent to the chat.

### Actual Behavior
Voice message is not sent.

### Steps to Reproduce
1. Record any audio message through the Voice recorder application.
2. Share it in any chat
3. See it:
![image](https://user-images.githubusercontent.com/22233835/99247095-81aeaf80-2817-11eb-9fc6-702da6a0800f.png)

### Environment
**Device:** `iPad Air 2`

**iOS version**: `14.2`

**App version:** `7.2 (18230)`

**Comment by rottvinc** [comment]
Same goes for iPhone SE 2, same iOS and app versions.
The bug has been around at least since 20-11-12 (Nov 12th) when I first encountered it.

**Comment by laktyushin** [comment]
Fixed in 7.2.1
