### ISSUE TITLE
Add Moovit as navigation/mapping URI scheme

### ISSUE THREAD

**Issue by igor-makarov** [TelegramMessenger/Telegram-iOS#42]
I am an iOS developer at Moovit. I've noticed that the app supports opening several mobility apps via a URI scheme.

I would like to add Moovit to the list (which has 430+ million users worldwide).

I've managed to checkout the app source and to write the relevant code modification (in Telegram-iOS & in TelegramUI). It works. 

Do I submit a PR? What are the contribution rules? Thanks!

**Comment by shivanraptor** [comment]
I don't think the author will respond. You can just submit a Pull Request & see if the author will merge it.

**Comment by igor-makarov** [comment]
Do you know why they don't respond? Any way to contact them?

**Comment by laktyushin** [comment]
Added in 5.10 release.

**Comment by igor-makarov** [comment]
Thanks! 🎉
