### ISSUE TITLE
Firebase with BUCK

### ISSUE THREAD

**Issue by SergeyKolokolnikov** [TelegramMessenger/Telegram-iOS#425]
I want integrate firebase crashlytics and analytics frameworks in telergram-ios app.

I edited BUCK file in submodule TelegramUI and after execute `make project` no problem. It work awesome. Firebase configured.
But I try execute `make app` and faced error  "no such module 'FirebaseCore'"

who faced integration Firebase in Telegram-ios project, tell me how you did it? Thanks for any ideas!

**Comment by ali-fareed** [comment]
The project has migrated to Bazel as its build system.

**Comment by wweevv-johndpope** [comment]
I have sample bazel + firebase 9.5.0 sample here
https://github.com/vikage/DemoBazel/pull/5

but when I use with this project it blows up httpbody error.  not sure why...
