### ISSUE TITLE
When pasting an image, there's no way to set a caption

### ISSUE THREAD

**Issue by WhyNotHugo** [TelegramMessenger/Telegram-iOS#426]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description

When pasting an image, there's no way to set a caption.

Because of this **and** #311, sending an image with a caption is always required editing the sent image. First send the image, then edit it and add the caption.

### Actual Behavior

![image](https://user-images.githubusercontent.com/730811/100861285-85823900-3489-11eb-956b-d57cd6128cf6.png)

### Expected Behavior

There should be a field to set a caption when pasting an image.

Here's an example of what WhatsApp does. Other messaging clients have similar behaviours:

![image](https://user-images.githubusercontent.com/730811/100861482-cbd79800-3489-11eb-926c-c18d7179c182.png)

The Telegram desktop app _does_ implement this:

![2020-12-02T11:35:51,843892674+01:00](https://user-images.githubusercontent.com/730811/100861827-43a5c280-348a-11eb-8708-910cd471e2c2.png)

### Steps to Reproduce

1. Open iOS's Photos app.
2. Select any photo.
3. Copy it.
4. Open a Telegram chat.
5. Tap on the text input field.
6. Tap paste.

### Environment
**Device:** iPhone 11 Pro, iPad Pro 2020

**iOS version**: `14.2`

**App version:** `7.2.1`

**Comment by laktyushin** [comment]
You can tap on a photo on this screen and enter a caption there.

**Comment by WhyNotHugo** [comment]
Oh, interesting. This is a pretty hidden feature, I've heard friends complains about the same thing and nobody would have guessed this.

Why not prompt for a caption directly, and skip the extra step?
