### ISSUE TITLE
Shared audios fail to upload

### ISSUE THREAD

**Issue by vCrespoP** [TelegramMessenger/Telegram-iOS#429]
### Checklist
- [ x] I am reporting an issue in existing functionality that does not work as intended
- [ x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
When sharing an audio from a different application (for instance, Whatsapp, or Apple's Voice Recorder) the always fail to upload. Interesting point, is they can be played and work well, but they do no upload and always fail with error, instantly.
Maybe related to the type somehow? Could be iOS 14? 

### Expected Behavior
1) I have an audio I want to share from a Whatsapp message (or Voice Recorder)
2) I select from the bottom share menu one of my contacts in the Telegram section
3) Audio shows up, can be played and gets uploaded correctly

### Actual Behavior
1) I have an audio I want to share from a Whatsapp message (or Voice Recorder)
2) I select from the bottom share menu one of my contacts in the Telegram section
3) Audio shows up, can be played and *DOES NOT*  get uploaded correctly <~ Bug in here

### Steps to Reproduce
Described above, step 3 is the one containing the bug.

### Screenshots and Videos 
![IMG_27B82A1F909E-1](https://user-images.githubusercontent.com/7558064/100982153-01db5180-3548-11eb-84b9-f43b52c934b7.jpeg)

### Environment
**Device:** `iPhone 12 Pro`

**iOS version**: `14.2.1`

**App version:** `7.2.1`

**Comment by progging** [comment]
Can confirm that I experience the same problem (7.2.1, 14.2.1) when sharing audio from Garageband, and when sending a GIF (from storage - not from the GIF search).

![PNG image](https://user-images.githubusercontent.com/2796968/102178926-8f069a80-3ea6-11eb-99bf-79fb27068051.png)

**Comment by laktyushin** [comment]
Fixed in 7.3.
