### ISSUE TITLE
Video sent from stock photos app has severe white balance issues. 

### ISSUE THREAD

**Issue by FarOut2020** [TelegramMessenger/Telegram-iOS#430]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [ ] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
iPhone 12 Pro Max running iOS 14.2.1 has serious video issues. This was not present 1-2 weeks ago. Video recorded on the phone, and sent to a user, is now severely washed out. The white balance is very extreme. Almost as if a bad filter has been applied. Color reproduction is very bad. Easily reproducible for me. Developers can contact me and I can help diagnose, if needed. 

### Expected Behavior
Video should be 1:1 accurate 

### Actual Behavior
Video is 0.5:1 accurate 

### Steps to Reproduce
1. Record video with iPhone 12 Pro Max
2. Send to user
3. Open eyes

### Environment
**Device:** `iPhone 12 Pro Max`

**iOS version**: `14.2.1`

**App version:** `7.2.1`

**Comment by nach0boss** [comment]
I confirm the sam issue:

iPhone 12 Pro
14.2.1
App 7.2.1

**Comment by mariselli** [comment]
I confirm the issue.
Either sending a video either in video calls.

**Comment by DmitryBarskov** [comment]
Same issue on iPhone XS (iOS 14.4.1 and Telegram 7.6) and on iPhone 11 (iOS 14.4 and Telegram 7.6)

**Comment by laktyushin** [comment]
Fixed.
