### ISSUE TITLE
make project error!

### ISSUE THREAD

**Issue by twisturn** [TelegramMessenger/Telegram-iOS#431]
![1607320447655](https://user-images.githubusercontent.com/17715937/101314672-f499cc00-3893-11eb-8a05-85eedf26d860.jpg)

**Comment by SergeyKolokolnikov** [comment]
try
git clone --recursive https://github.com/TelegramMessenger/telegram-ios.git

But I faced another problem making project, bug related with webrtc-ios module

**Comment by twisturn** [comment]
> try
> git clone --recursive https://github.com/TelegramMessenger/telegram-ios.git
> 
> But I faced another problem making project, bug related with webrtc-ios module

I tried and I got the same result

**Comment by SergeyKolokolnikov** [comment]
> > try
> > git clone --recursive https://github.com/TelegramMessenger/telegram-ios.git
> > But I faced another problem making project, bug related with webrtc-ios module
> 
> I tried and I got the same result

<img width="820" alt="Screenshot 2020-12-08 at 10 29 02" src="https://user-images.githubusercontent.com/7039183/101459068-6e878f00-3940-11eb-9cd0-6a62de16cc85.png">

check src folder your repo. If not download manually from 
https://github.com/ali-fareed/webrtc-ios/tree/782743c7931d09c1d2e4a0cf6cd349ee45452f1d

**Comment by alyfreym** [comment]
what is your version of Mac os?

**Comment by ali-fareed** [comment]
Please see the updated build instructions in README.md.
