### ISSUE TITLE
[Feature Request] Share sheet for sharing Text/Messages system wide

### ISSUE THREAD

**Issue by maxgrass** [TelegramMessenger/Telegram-iOS#437]
### Is your feature request related to a problem?
Can't share any messages/text outside of Telegram and as a result can't print any messages (physically on my printer), e.g. texts as a writer etc.

### Describe the solution you'd like
Generic "Share sheet" for iOS e.g. so I can share the text outside of Telegram. And eventually be able e.g. to natively print a text message.

### Describe alternatives you've considered
Copying the text and pasting it in any other app which supports normal sharing.

**Comment by migael0412** [comment]
Nube de Telegram

**Comment by laktyushin** [comment]
It's already there. Long press on a message, tap Select and press Share button in the toolbar.

**Comment by maxgrass** [comment]
Thanks.
I guess it's not available in a one-message menu to de-clutter it and this way of sharing is/would be used not that intensive?
Otherwise don't see why is it not directly integrated into the default menu.
