### ISSUE TITLE
make project errors: submodule not found

### ISSUE THREAD

**Issue by ikrom92** [TelegramMessenger/Telegram-iOS#442]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
I've cloned the repo with --recursive attribute. Then I've applied fix as described at https://github.com/TelegramMessenger/Telegram-iOS/issues/219#issuecomment-570533746. 
Trying `make project` reports an error:

> No build file at third-party/cmake/BUCK when resolving target //third-party/cmake:cmake.
> This error happened while trying to get dependency '//third-party/cmake:cmake' of target '//third-party/yasm:yasm'

I've solved this by removing this line: `export PATH=\"$PATH:$(location //third-party/cmake:cmake)/cmake-3.16.0/bin\` from `third-party/yasm/BUCK` file, because I have cmake.

After this, `make project` gives another (same) error:

> No build file at third-party/cmake/BUCK when resolving target //third-party/cmake:cmake.
> This error happened while trying to get dependency '//third-party/cmake:cmake' of target '//third-party/mozjpeg:libmozjpeg_build'

I've solved this by removing CMAKE variable (and all references to it) from `//third-party/mozjpeg/BUCK`.

And now, after `make project` I receive this error:
> No build file at submodules/WalletUrl/BUCK when resolving target //submodules/WalletUrl:WalletUrl.

> This error happened while trying to get dependency '//submodules/WalletUrl:WalletUrl' of target '//submodules/UrlHandling:UrlHandling'

What is the proper way of generating Xcode project?

### Expected Behavior
Generate Xcode project file

### Actual Behavior
Reports error

**Comment by lbjhzj** [comment]
same question, any answer?

**Comment by ikrom92** [comment]
Ok, I had to fix it myself and have done it.
I've (again) removed this line:
`"//submodules/WalletUrl:WalletUrl",`
from /submodules/UrlHandling/BUCK file and successfully generated project. 
Hope there will be no issues with compiling)

**Comment by misteu** [comment]
Does it work for you when removing all of this?

I get this one after some time:
```
    When running <genrule>.
    When building rule //third-party/mozjpeg:libmozjpeg_build.
make: *** [project] Error 1
```

**Comment by lexuanquynh** [comment]
the same issue
