### ISSUE TITLE
deep link not working

### ISSUE THREAD

**Issue by Mirrdhyn** [TelegramMessenger/Telegram-iOS#45]
Hello, 
Deep linking is not working on iOS.
So, we can't add a secure token to start a bot.
e.g. https://t.me/botusername?start=supersecuretoken

**How to reproduce :** 

Version : iOS 12.3 with the Telegram v5.6.3 (1658).

1/ if the bot view is the current view, the start is not interpreted and no start command at all is loaded from the link.

2/ if the list chat view is the current view, the start is working as it should be with the secure token. We can see that the chat list view become the bot view then a big start button with the secure token behind appears.

This functional part is not seen by "normal" users because : 
1) they open a private discussion with the bot
2) they are doing /start which is giving an external auth button e.g. Google Auth/AD Auth/...
3) after auth from system, the deep link is used with a temporary token to link user and system
4) the link is opened by the iOS to Telegram but nothing happens because we are in bot view in the 1/ above.

This issue was opened in the old repo by someone else => https://github.com/peter-iakovlev/Telegram/issues/309 (29 Sep 2018)

**Comment by laktyushin** [comment]
Fixed in 5.10 release.
