### ISSUE TITLE
Latest Update Breaks CarPlay Integration

### ISSUE THREAD

**Issue by roryhardy** [TelegramMessenger/Telegram-iOS#450]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
After the latest update to Telegram for iOS, the CarPlay integration has stopped working. The app is no longer accessible. Notifications still pop up however.

### Expected Behavior
The app is accessible in CarPlay

### Actual Behavior
The app is not accessible in CarPlay

### Steps to Reproduce
1. Connect iOS device to CarPlay
2. Look for Telegram
3. Don't find Telegram

### Environment
**Device:** `iPhone XS`

**iOS version**: `14.3`

**App version:** `7.3.1`

**Comment by laktyushin** [comment]
Fixed in 7.4
