### ISSUE TITLE
update README

### ISSUE THREAD

**Issue by alyfreym** [TelegramMessenger/Telegram-iOS#453]
Add in to README how to build using BUCK or it is no longer supported? In the latest update in many config files missing dependency

**Comment by ali-fareed** [comment]
The project has migrated to Bazel. Buck is no longer supported.

Which dependencies are missing?

**Comment by alyfreym** [comment]
> The project has migrated to Bazel. Buck is no longer supported.
> 
> Which dependencies are missing?

For Example in TelegramUI project BUILD contains  "//submodules/AudioBlob:AudioBlob" module but BUCK file does not contains when you compile this Xcode generate error AudioBlob so such module because is not included in BUCK file. And there are a lot of such problems. With BUCK I added all submodules in my project with targets and it works well. Will this be possible with Bazel?

**Comment by alyfreym** [comment]
> The project has migrated to Bazel. Buck is no longer supported.
> 
> Which dependencies are missing?

What is the reason for migrate in to Bazel?

**Comment by ali-fareed** [comment]
Bazel does not require custom patches to build this project and updates more frequently.

It is possible to build the project using any other build system if you are ready to support it.

**Comment by mihaicris-adoreme** [comment]
How can the project be build without code signing?

**Comment by ali-fareed** [comment]
It is technically possible to build the project with code signing disabled (it requires a little bit of patching the build rules), but what would be the use case?

**Comment by mihaicris-adoreme** [comment]
I have no developer account active, so I can't generate certificates or provisioning profiles. Usually ese are generated automatically by Xcode which I guess it is not the case with Bazel. 

My use case is just to study the codebase, learn bazel and play with tulsi generated project. I am not sure if the app on the simulator will be usable without the API, but I can't finish the build due to an error with code signing.

There was some patching idea here https://itnext.io/build-and-run-telegram-ios-v7-3-in-simulator-with-bazel-fe36f305bd55?gi=e82ac3699812, but the Makefile has been refactored and no longer used.

Thanks

**Comment by ali-fareed** [comment]
It might be possible to do that if you are ready to create a dummy Xcode project and extract the generated provisioning profile from it. I will check this option and update the build instructions if it works.

**Comment by mihaicris-adoreme** [comment]
I was not able to extract the provisioning profiles created by Xcode, I am not sure this is possible.

However I was able to build and run the iOS app on the Simulator (Intel machine, not Apple Silicone).

From the Bazel iOS sample tutorial (https://docs.bazel.build/versions/master/tutorial/ios-app.html) for Simulator build I saw that I have to omit the `provisioning_profile` from `ios_application`, `ios_extension`, `watchos_application` and `watchos_extension` rules.  I didn't know how to conditionally define the parameter depending on the type of build (with or without provisioning profile) so for my case I just deleted the line. Passing an empty string to provisioning_profile = "" will not work.

I added a new configuration option in the Make.py :  'debug_x86_64' with `x86_64` cpu type.

I ran the build command with the new option:
`python3 build-system/Make/Make.py --bazel="$HOME/bazel-dist/bazel" --cacheDir="$HOME/telegram-bazel-cache" build --configurationPath="./build-system/example-configuration" --buildNumber=100001 --configuration=debug_x86_64`

The diff is attached.
[0002-Build-for-intel-simulator.patch.zip](https://github.com/TelegramMessenger/Telegram-iOS/files/5825706/0002-Build-for-intel-simulator.patch.zip)

**Comment by alyfreym** [comment]
I created an empty project and added a dependency libSwiftSignalKit from Telegram Project. When I upload this project in to iTunes Connect this give me error - Invalid Binary. and so on with all  Has anyone encountered such a problem? iTunes except this error says nothing. I Using BUCK to build. Maybe problem in BUCK? How do you load the project in to iTunes Connect?

**Comment by ali-fareed** [comment]
There was a custom packaging script for generating a correct .ipa file for uploading. With Bazel it is no longer required. Please move to the new build system.

**Comment by v4to** [comment]
Do I need paid developer account to build program and run it in simulator or real device?

**Comment by ali-fareed** [comment]
@mihaicris-adoreme it is now possible to build the app for simulator via Xcode without generating and installing provisioning profiles and certificates. Add `--disableProvisioningProfiles` to the command line:

```
python3 build-system/Make/Make.py \
    --bazel="$HOME/bazel-dist/bazel" \
    --cacheDir="$HOME/telegram-bazel-cache" \
    generateProject \
    --configurationPath="$HOME/telegram-configuration" \
    --disableExtensions \
    --disableProvisioningProfiles
```

(`--disableExtensions` is not mandatory in this case, but it speeds up development significantly)

**Comment by ali-fareed** [comment]
@v4to you don't need a developer account to run the app on simulator anymore.

**Comment by mihaicris-adoreme** [comment]
Thanks @ali-fareed. Building in Xcode works fine now.

Would that be possile to have the new option `--disabelProvisioningProfiles` also for the build command?

**Comment by ali-fareed** [comment]
You would still need to codesign the ipa at some point, otherwise it won't be possible to install it on a device or upload it to the App Store.

Please describe your use case, maybe there is a better solution.

**Comment by mihaicris-adoreme** [comment]
The possibility to make a build for Simulator also from terminal command, not only from Xcode (which is the case now), such that I can see the progress status. I assume that a later build from Xcode will use the cache from previous builds (either from terminal or Xcode).

**Comment by ali-fareed** [comment]
You can see the same progress by going to the Report Navigator pane in Xcode and opening the current Build log. Due to some internal Bazel mechanics terminal builds and Xcode builds may share no cache, so you will end up rebuilding things anyway.

This all might seem suboptimal, but Bazel really does increase the development process, so it ends up being worth it.

**Comment by mihaicris-adoreme** [comment]
Ok, thanks! Got it.

**Comment by alyfreym** [comment]
I build this using buck and upload success. I hope that the BUCK will be supported in the future

**Comment by ali-fareed** [comment]
Buck will not be supported. Good news is that Bazel has the same syntax, so you can port your build files easily.

**Comment by aze20** [comment]
https://core.telegram.org/reproducible-builds#step-7-building-the-app
I run the commands:
cd $HOME/telegram-ios BAZEL="$HOME/bazel/bazel" sh buildbox/build-telegram.sh verify
but log Error:
Base VM: "macos10_15_Xcode12_4"
Building on macOS
+ find . -type f -a -not -regex '\.' -a -not -regex '.*\./git' -a -not -regex '.*\./git/.*' -a -not -regex '\./bazel-bin' -a -not -regex '\./bazel-bin/.*' -a -not -regex '\./bazel-out' -a -not -regex '\./bazel-out/.*' -a -not -regex '\./bazel-testlogs' -a -not -regex '\./bazel-testlogs/.*' -a -not -regex '\./bazel-telegram-ios' -a -not -regex '\./bazel-telegram-ios/.*' -a -not -regex '\./buildbox' -a -not -regex '\./buildbox/.*' -a -not -regex '\./buck-out' -a -not -regex '\./buck-out/.*' -a -not -regex '\./\.buckd' -a -not -regex '\./\.buckd/.*' -a -not -regex '\./build' -a -not -regex '\./build/.*' -print0
+ tar cf buildbox/transient-data/source.tar --null -T -
+ PROCESS_ID=30764
+ '[' -z '' ']'
++ openssl rand -hex 10
+ VM_NAME=macos10_15_Xcode12_4-e8fe4a5938027b912b2b-build-telegram-30764
+ '[' macOS == linux ']'
+ '[' macOS == macOS ']'
+ '[' -z '' ']'
+ prlctl clone macos10_15_Xcode12_4 --linked --name macos10_15_Xcode12_4-e8fe4a5938027b912b2b-build-telegram-30764
buildbox/build-telegram.sh: line 158: prlctl: command not found
How should I solve this problem？ tks



> You can see the same progress by going to the Report Navigator pane in Xcode and opening the current Build log. Due to some internal Bazel mechanics terminal builds and Xcode builds may share no cache, so you will end up rebuilding things anyway.
> 
> This all might seem suboptimal, but Bazel really does increase the development process effectiveness, so it ends up being worth it.

**Comment by ali-fareed** [comment]
@aze20 the script can't find the Parallels installation.

Please open a new issue.
