### ISSUE TITLE
Build error: com.apple.security.application-groups

### ISSUE THREAD

**Issue by ikrom92** [TelegramMessenger/Telegram-iOS#456]
ERROR: Target "//Telegram:Telegram_entitlements" uses entitlements "com.apple.security.application-groups" value of "group.*****", but the profile does not support it (["group.*****"]).

Even if I enabled the group, I am getting this error

**Comment by ali-fareed** [comment]
It appears that you have set the telegram_bundle_id variable in variables.bzl to an empty string.

**Comment by ikrom92** [comment]
no, I've set 'telegram_bundle_id'. I've just removed the group id from log. the original was:

ERROR: Target "//Telegram:Telegram_entitlements" uses entitlements "com.apple.security.application-groups" value of "group.my_bundle_id", but the profile does not support it (["group.my_bundle_id"]).

**Comment by ikrom92** [comment]
I've set only these variables:
```
telegram_bundle_id = "$MY_APPS_BUNDLE_ID"
telegram_api_id = "$MY_APID_ID"
telegram_api_hash = "$MY_API_HASH"
telegram_team_id = "$MY_TEAM_ID"
telegram_app_center_id = "0"
telegram_is_internal_build = "false"
telegram_is_appstore_build = "true"
telegram_appstore_id = "0"
telegram_app_specific_url_scheme = "tg"
telegram_aps_environment = "production"
```

Are they enaugh, or should I set these variables too:
```
telegram_app_center_id = "0"
telegram_is_internal_build = "false"
telegram_is_appstore_build = "true"
telegram_appstore_id = "0"
telegram_app_specific_url_scheme = "tg"
telegram_aps_environment = "production"
```
?

**Comment by ikrom92** [comment]
I could successfully build & run the project for simulator (with --disableProvisioningProfile).
But, for actual device it fails

**Comment by ali-fareed** [comment]
Please make sure the provisioning profile in your `configuration/profiles/Telegram.mobileprovisioning` file is in fact equal to "group.$MY_APPS_BUNDLE_ID".

`telegram_app_center_id ` — used for internal update tracking
`telegram_is_internal_build ` — does what it says
`telegram_is_appstore_build ` — just like the previous one
`telegram_appstore_id ` — ID of the app from the App Store
`telegram_app_specific_url_scheme ` — the app will handle links with this scheme. The official app uses `tg://`

**Comment by ali-fareed** [comment]
Make sure the value for `com.apple.security.application-groups` in your provisioning profile (placed at `configuration/provisioning/Telegram.mobileprovision`) is in fact equal to "group.your_application_bundle_id".

The other variables are for internal use. You can search BUILD files for specific references.

**Comment by ikrom92** [comment]
Thank you. These solved the problem. 

Could you comment out the purpose of these variables, please:

telegram_app_center_id = "0"
telegram_is_internal_build = "false"
telegram_is_appstore_build = "true"
telegram_appstore_id = "0"
telegram_app_specific_url_scheme = "tg"
telegram_aps_environment = "production"

If I change telegram_aps_environment = "development", should I regenerate project?

**Comment by crocodile305** [comment]
I got same error.
Are you able to let me know how to solve this bug?
![2021-11-13_07h31_27](https://user-images.githubusercontent.com/38894059/141595200-b955bb23-de43-4f00-9809-11a08346916f.png)

Please help me.

**Comment by ikrom92** [comment]
Have you tried `--disableProvisioningProfile `?
