### ISSUE TITLE
cp -R build-system/example-configuration/* $HOME/telegram-configuration/

### ISSUE THREAD

**Issue by 51100480** [TelegramMessenger/Telegram-iOS#457]
After run that command , it is error :
cp -R build-system/example-configuration/* $HOME/telegram-configuration
alert:
cp: build-system/example-configuration/: No such file or directory

Plz check help me. THanks you

**Comment by ali-fareed** [comment]
In which directory are you running this command?

**Comment by 51100480** [comment]
This is:
mac@macs-MacBook-Air bazel-dist % cp -R build-system/example-configuration/* $HOME/telegram-configuration/

**Comment by ali-fareed** [comment]
You need to change directory to where you checked out the code (in README it's `$HOME/telegram-ios`).

**Comment by 51100480** [comment]
Still have issuse :

mac@macs-MacBook-Air telegram-ios % cp -R build-system/example-configuration/* $HOME/telegram-configuration/
zsh: no matches found: build-system/example-configuration/*

plz help me. Thanks you

**Comment by ikrom92** [comment]
Do these from beginning:
```
mkir telegram
cd telegram
mkdir config
cd config
export TELEGRAM_PROJECT_CONFIG=`pwd`
cd ..
mkdir cache
cd cache
export TELEGRAM_PROJECT_CACHE=`pwd`
cd ..
git clone --recursive -j8 https://github.com/TelegramMessenger/Telegram-iOS.git
cd Telegram-iOS
cp -R cp -R build-system/example-configuration/* "$TELEGRAM_PROJECT_CONFIG"
```
