### ISSUE TITLE
Please, give more details in README.md

### ISSUE THREAD

**Issue by ikrom92** [TelegramMessenger/Telegram-iOS#458]
First of all, big thanks to all telegram team for a great product.

Until I successfully build the project, I had to try solve several issues. 
It would be good if you provide more information for building project.
Especially:

1. App ID - what capabilities MUST be enabled
2. What are the purpose of some variables in variables.bzl file:

```
telegram_app_center_id = "0"
telegram_is_internal_build = "false"
telegram_is_appstore_build = "true"
telegram_appstore_id = "0"
telegram_app_specific_url_scheme = "tg"
telegram_aps_environment = "production"
```

3. If I change telegram_aps_environment = "development", to "production", should I regenerate project or I can edit some script in already generated project?
4. What provision profiles (development or distribution) must be copied to telegram-config/provisioning folder 

Again, thank you for your effort!

**Comment by ikrom92** [comment]
Also, please give instructions how to rename app without altering working project

**Comment by alyfreym** [comment]
> Also, please give instructions how to rename app without altering working project

Могу помочь, через PayMe или Click будешь оплачивать?

**Comment by ikrom92** [comment]
> > Also, please give instructions how to rename app without altering working project
> 
> Могу помочь, через PayMe или Click будешь оплачивать?

thank you for your effort, but I've already build the project. Quoting my post above "Until I successfully build the project, I had to try solve several issues." This issue I've opened in order to help for those who will encounter such issues.
