### ISSUE TITLE
How to rename app name from Telegram?

### ISSUE THREAD

**Issue by ikrom92** [TelegramMessenger/Telegram-iOS#459]
Hello, everyone.
According to this policy:

> Please do not use the name Telegram for your app — or make sure your users understand that it is unofficial.

I've changed the files:
1. Telegram-iOS/BUILD: ios_application(name="MyAppName")
2. build-system/Make/Make.py: 
```
def invoke_build(self):
        combined_arguments = [
            self.build_environment.bazel_path,
            'build',
            'Telegram/MyAppName'
        ]
```
Building project fails on last step, during code-signing.
Is this the right way to rename app name?

**Comment by tboxSol** [comment]
Is this the right way or what? @ikrom92

**Comment by agates4** [comment]
The display name can be changed here:
https://github.com/TelegramMessenger/Telegram-iOS/blob/master/Telegram/BUILD#L644-L652

In the `Telegram/BUILD` file, update the value of the `CFBundleDisplayName` key.
