### ISSUE TITLE
When I execute make build_arm64, the following error is reported

### ISSUE THREAD

**Issue by twisturn** [TelegramMessenger/Telegram-iOS#461]
Parsing buck files: finished in 6.6 sec
Creating action graph: finished in 6.6 sec
Building: finished in 27:40.5 min (100%) 1277/3189 jobs, 1277 updated
  Total time: 27:53.8 min
Command failed with exit code 1.

command: [/Users/zj/Downloads/Xcode.app/Contents/Developer/usr/bin/actool, --platform, iphoneos, --minimum-deployment-target, 9.0, --compile, /Users/zj/Desktop/tg7.2.1/telegram-7.1/tg-7.1/Telegram-iOS/buck-out/gen/Telegram/Telegram#apple-asset-catalog,dwarf-and-dsym,iphoneos-arm64/Merged.bundle, --output-partial-info-plist, /Us...
<truncated>
...

stderr: 
    When running <actool>.
    When building rule //Telegram:Telegram#apple-asset-catalog,dwarf-and-dsym,iphoneos-arm64.
make: *** [build_arm64] Error 1

**Comment by ali-fareed** [comment]
Please update to the latest commit and follow the updated readme.
