### ISSUE TITLE
Do not convert "8)" to emoji

### ISSUE THREAD

**Issue by leoblum** [TelegramMessenger/Telegram-iOS#465]
Hi. I often use numbered lists when I'm chatting on Telegram. Everything is cool except when I get to the eighth menu item I write "8)" and it automatically turns into "😍" emoji. It's weird, especially in business correspondence. 

Please can you make it like when I write a numbered list, the eighth item doesn't turn into an emoji. And when my partner receive the message he also will see "8)" instead of an emoji.

Example:
6) blah blah blah.
7) blah blah blah.
8) blah-blah-blah // Because there were "6)" and "7)" before, "8)" did not turn into an emoji

But if I just write a text like, "you're awesome 8)" its translates to "you're awesome 😍". 

Or, if that will be easier to you, maybe you can change the combination for "😍" from "8)" to "8-)" or something.

**Comment by laktyushin** [comment]
There’s no text to emoji conversion in Telegram for iOS.
