### ISSUE TITLE
Cannot run simulator on M1 Mac

### ISSUE THREAD

**Issue by mahenzon** [TelegramMessenger/Telegram-iOS#467]
I built XCode project using bazel (point 6 at README), trying to build the app and run it in the simulator, but getting this error:

```
In cc_toolchain_suite rule @local_config_cc//:toolchain: cc_toolchain_suite '@local_config_cc//:toolchain' does not contain a toolchain for cpu 'ios_sim_arm64'
```
<img width="725" alt="image" src="https://user-images.githubusercontent.com/20804158/105847891-4d155c00-5fef-11eb-9d44-43a3f12db467.png">

I think it's related to this line https://github.com/TelegramMessenger/Telegram-iOS/blob/72633df91f3f28c70185790efc52f4788bba81dd/build-system/Make/ProjectGeneration.py#L149
> ios_sim_arm64

There's some patch containing `ios_sim_arm64`, but I'm not sure how to apply it
https://gist.github.com/brentleyjones/17d8bcf308558a19dd54a30e4a6db57a

did you test it running on M1 Mac? I see the repo is updated for arm CPU, but I cannot run it on my machine because sim is not starting

### Environment
**Device:** `Apple MacBook Pro (13-inch, M1, 2020)`

**macOS version**: `11.1 (20C69)`

___

Some more screenshots in case it can help:

<img width="557" alt="image" src="https://user-images.githubusercontent.com/20804158/105848545-2a377780-5ff0-11eb-8c18-5139919d3cd9.png">
<img width="710" alt="image" src="https://user-images.githubusercontent.com/20804158/105848595-43402880-5ff0-11eb-97cc-057b653044c6.png">

**Comment by ali-fareed** [comment]
Building for arm64 simulator is currently implemented is an internal branch. The patches will be published with the next release build.

**Comment by ali-fareed** [comment]
With the latest commit it's possible to build the app for arm64 simulators.
To do this a patched Bazel is required. The Bazel itself should not be older than https://github.com/bazelbuild/bazel/commit/8c7e11a81c35563d951062fe6f00e4e85b3009fb

After checking out Bazel apply this patch: https://github.com/bazelbuild/rules_apple/issues/980#issuecomment-738645357 (rules_swift is already patched and points to our internal fork for now).

An x86_64 version of Bazel is still required to build Tulsi (until https://github.com/bazelbuild/bazel/issues/12671 is resolved).

After that, use the following command to generate a project file:

```
python3 build-system/Make/Make.py \
	--bazel="$HOME/bazel/bazel" \
	--cacheDir="$HOME/build/telegram/bazel-cache" \
	--overrideBazelVersion \
	generateProject \
	--bazel_x86_64=$HOME/bazel/bazel_x86_64 \
	--configurationPath="$HOME/telegram-configuration" \
	 --disableExtensions
```

**Comment by mahenzon** [comment]
tried to build bazel for `darwin_arm64`, but getting an error, described it here https://github.com/bazelbuild/bazel/pull/12900#issuecomment-769519999

but if you succeeded building bazel for arm and generating project, maybe you could help me with this? my steps were:

- clone bazel
- apply patch
- build bazel for arm using bazel for x86 (this ends up with an error)

**Comment by mahenzon** [comment]
**UPD**: this is solved: https://github.com/bazelbuild/bazel/pull/12900#issuecomment-769900027

Full list of steps for building TG:
- Download bazel 4.0.0 `curl -O -L https://github.com/bazelbuild/bazel/releases/download/4.0.0/bazel-4.0.0-darwin-x86_64` (or there'll be a newer version). I downloaded it to `~/bazel-dist-4.0.0`
- `mv bazel-4.0.0-darwin-x86_64 bazel`
- `chmod +x bazel`
- download bazel source (`git clone https://github.com/bazelbuild/bazel.git` or whatever). It should contain this commit https://github.com/bazelbuild/bazel/commit/8c7e11a81c35563d951062fe6f00e4e85b3009fb
- do the patches you need: download https://gist.github.com/indragiek/e14162c0098d97ee976bceae9441f04d (it's from this comment https://github.com/bazelbuild/rules_apple/issues/980#issuecomment-738645357)
- go to bazel source directory, run `git apply ~/patches/ios_sim_arm64.patch`
- build new bazel from source using bazel 4.0.0 `~/bazel-dist-4.0.0/bazel build --cpu=darwin_arm64 //src:bazel`

Your build will be in `bazel-bin/src/bazel`. Copy it where you need it and run `chmod +x bazel`

Note that this build's version will be `no_version`:
```bash
➜ ./bazel --version
bazel no_version
```

So you'll need to use flag `--overrideBazelVersion`. Also, Xcode version changed too already, so the full command for me was:

```bash
python3 build-system/Make/Make.py \
    --overrideXcodeVersion --overrideBazelVersion \
    --bazel="$HOME/bazel-arm/bazel" \
    --cacheDir="$HOME/telegram-bazel-cache" \
    generateProject \
    --bazel_x86_64="$HOME/bazel-dist/bazel"\
    --configurationPath="$HOME/telegram-configuration" \
    --disableExtensions \
    --disableProvisioningProfiles
```

Also note that `--bazel` uses new arm version, but `--bazel_x86_64` is still that *old* x86 v3.7.0

And this time simulator can be run!

**Comment by ali-fareed** [comment]
I would recommend to build Bazel in release mode by adding `-c opt`:

```
~/bazel-dist-4.0.0/bazel build --cpu=darwin_arm64 -c opt //src:bazel
```

**Comment by bohlool** [comment]
I have M1 Macbook and I'm trying to build this project using instructions that is provided here but I'm getting following error.

<img width="1440" alt="Screen Shot 2021-04-14 at 6 56 56 PM" src="https://user-images.githubusercontent.com/3276539/114727470-783c5b80-9d53-11eb-93ed-b5bc24d19be1.png">

Any help is appreciated.

**Comment by ali-fareed** [comment]
@bohlool Please open a new issue.
