### ISSUE TITLE
We need tutorial for build telegram

### ISSUE THREAD

**Issue by lexuanquynh** [TelegramMessenger/Telegram-iOS#469]
I think the readme file is lack of information for build this project. I think we need tutorial for build it. thank you.

**Comment by ali-fareed** [comment]
With which step are you having issues?

**Comment by lexuanquynh** [comment]
@ali-fareed thank for your reply. I having issues:
when I use command line in the build-system/Make forder:
`python3 Make.py \
    --bazel="$HOME/bazel-dist/bazel" \
    --cacheDir="$HOME/telegram-bazel-cache" \
    build \
    --configurationPath="$HOME/telegram-configuration" \
    --buildNumber=100001 \
    --configuration=release_universal`
I get errors:
`FileNotFoundError: [Errno 2] No such file or directory: '/Users/xuanquynhle/Telegram-iOS/build-system/Make/versions.json'`

**Comment by ali-fareed** [comment]
You need to run `Make.py` within `/Users/xuanquynhle/Telegram-iOS`.

**Comment by lexuanquynh** [comment]
@ali-fareed  thank for your support. But I get new error:
`Could not parse the Xcode version from /Library/Developer/CommandLineTools/../Info.plist`
I was doing something wrong? Does provisioning have a problem?

**Comment by lexuanquynh** [comment]
@ali-fareed  I use:
`sudo xcode-select -s /Applications/Xcode.app`
But I get error:
`Required Xcode version is 12.3, but 12.4 is reported by 'xcode-select -p'`

**Comment by ali-fareed** [comment]
Here's the relevant section in readme: https://github.com/TelegramMessenger/Telegram-iOS#tips

**Comment by lexuanquynh** [comment]
@ali-fareed thank you very  much. 
I give a the script for someone who needs it. 
`python3 build-system/Make/Make.py \
--overrideXcodeVersion \
    --bazel="$HOME/bazel-dist/bazel" \
    --cacheDir="$HOME/telegram-bazel-cache" \
    generateProject \
    --configurationPath="$HOME/telegram-configuration" \
    --disableExtensions`

**Comment by horak** [comment]
I cannot for the life of me figure out how to run this either, despite your instructions...

Here's what I'm trying —
```bash
python3 build-system/Make/Make.py \
    --overrideXcodeVersion  \
    --bazel="$HOME/bazel-dist/bazel" \
    --cacheDir="$HOME/telegram-bazel-cache" \
    generateProject \
    --configurationPath="$HOME/telegram-configuration" \
    --disableProvisioningProfiles
```

And here's my output:
```bash
Could not parse the Xcode version from /Library/Developer/CommandLineTools/../Info.plist
```

<img width="629" alt="Screen Shot 2021-02-09 at 12 20 23 PM" src="https://user-images.githubusercontent.com/1111424/107408902-31bb4e00-6ad1-11eb-82c0-69afa757402b.png">

What am I doing wrong?

**Comment by ali-fareed** [comment]
Run `sudo xcode-select -s /Applications/Xcode.app/Contents/Developer`

**Comment by horak** [comment]
Thanks so much @ali-fareed, that did the trick.

**Comment by lexuanquynh** [comment]
<img width="1399" alt="Screen Shot 2021-07-01 at 0 13 22" src="https://user-images.githubusercontent.com/17588791/124003456-eb2fa700-da11-11eb-887b-2a0c9679b4bb.png">
I think the last source code on this repos cannot build.
I have to checkout the previous source code.

**Comment by Kylmakalle** [comment]
CI Run fine for 7.8.2 as well https://github.com/TelegramMessenger/Telegram-iOS/runs/2952059308

**Comment by Pikdays** [comment]
> I cannot for the life of me figure out how to run this either, despite your instructions...
> 
> Here's what I'm trying —
> 
> ```shell
> python3 build-system/Make/Make.py \
>     --overrideXcodeVersion  \
>     --bazel="$HOME/bazel-dist/bazel" \
>     --cacheDir="$HOME/telegram-bazel-cache" \
>     generateProject \
>     --configurationPath="$HOME/telegram-configuration" \
>     --disableProvisioningProfiles
> ```
> 
> And here's my output:
> 
> ```shell
> Could not parse the Xcode version from /Library/Developer/CommandLineTools/../Info.plist
> ```
> 
> <img alt="Screen Shot 2021-02-09 at 12 20 23 PM" width="629" src="https://user-images.githubusercontent.com/1111424/107408902-31bb4e00-6ad1-11eb-82c0-69afa757402b.png">
> 
> What am I doing wrong?



pikdays@PikdaysMacBook-Pro Telegram-iOS % python3 build-system/Make/Make.py \
    --overrideXcodeVersion  \
    --bazel="$HOME/bazel-dist/bazel" \
    --cacheDir="$HOME/telegram-bazel-cache" \
    generateProject \
    --configurationPath="$HOME/telegram-configuration" \
    --disableProvisioningProfiles

Overriding the required Xcode version 12.4 with 12.5.1 as reported by 'xcode-select -p'
No matching processes belonging to you were found
INFO: Analyzed target //:tulsi (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //:tulsi up-to-date:
  bazel-bin/tulsi.zip
INFO: Elapsed time: 0.121s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
[Syslog] Tulsi CLI: version 0.20210120.88
[Syslog] Create project: Telegram
[Syslog] Fetching bazel path info
[Info] Running /Users/pikdays/Telegram-iOS/build-input/gen/project/bazel info '--override_repository=tulsi=/Users/pikdays/Library/Application Support/Tulsi/0.20210120.88/Bazel'
[Syslog] ** Completed bazel_get_package_path in 0.1048s
[Syslog] ** Completed get_package_path in 0.1057s
[Syslog] Fetching rules for packages ["Telegram"]
[Info] Running /Users/pikdays/Telegram-iOS/build-input/gen/project/bazel --max_idle_secs=60 query '--override_repository=tulsi=/Users/pikdays/Library/Application Support/Tulsi/0.20210120.88/Bazel' --announce_rc --noimplicit_deps --order_output=no --noshow_loading_progress --noshow_progress 'kind(rule, Telegram:all)' --output xml
[Syslog] ** Completed bazel_query_fetch_rules in 0.1025s
[Info] Bazel command info:
/Users/pikdays/Telegram-iOS/build-input/gen/project/bazel --max_idle_secs=60 query '--override_repository=tulsi=/Users/pikdays/Library/Application Support/Tulsi/0.20210120.88/Bazel' --announce_rc --noimplicit_deps --order_output=no --noshow_loading_progress --noshow_progress 'kind(rule, Telegram:all)' --output xml
Exited with code 7

INFO: Options provided by the client:
  Inherited 'common' options: --isatty=0 --terminal_columns=80
ERROR: no such package '@build_configuration//': No WORKSPACE file found in /private/var/tmp/_bazel_pikdays/c07dc2d226f40ecf8ae3c44f800e3e93/external/build_configuration

[Error] Failed to retrieve information about the Bazel workspace. This usually means that the contents of a BUILD file are incorrect or flags are missing. Read the message log carefully for details. ERROR: no such package '@build_configuration//': No WORKSPACE file found in /private/var/tmp/_bazel_pikdays/c07dc2d226f40ecf8ae3c44f800e3e93/external/build_configuration
[Syslog] ** Completed fetch_rules in 0.1037s
Failed to identify any valid build targets.
Traceback (most recent call last):
  File "/Users/pikdays/Telegram-iOS/build-system/Make/Make.py", line 613, in <module>
    generate_project(arguments=args)
  File "/Users/pikdays/Telegram-iOS/build-system/Make/Make.py", line 385, in generate_project
    generate(
  File "/Users/pikdays/Telegram-iOS/build-system/Make/ProjectGeneration.py", line 87, in generate
    call_executable([
  File "/Users/pikdays/Telegram-iOS/build-system/Make/BuildEnvironment.py", line 60, in call_executable
    subprocess.check_call(resolved_arguments, env=resolved_env)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/pikdays/Telegram-iOS/build-input/gen/project/Tulsi.app/Contents/MacOS/Tulsi', '--', '--verbose', '--create-tulsiproj', 'Telegram', '--workspaceroot', './', '--bazel', '/Users/pikdays/Telegram-iOS/build-input/gen/project/bazel', '--outputfolder', '/Users/pikdays/Telegram-iOS/build-input/gen/project', '--target', 'Telegram:Telegram', '--build-options', '--override_repository=build_configuration=/Users/pikdays/telegram-configuration --//Telegram:disableProvisioningProfiles']' returned non-zero exit status 24.
pikdays@PikdaysMacBook-Pro Telegram-iOS %

**Comment by shivanraptor** [comment]
What are the contents of the `/Library/Developer/CommandLineTools/../Info.plist`?
