### ISSUE TITLE
Forwarded messages reveal the name of the person you’re forwarding from

### ISSUE THREAD

**Issue by guidedways** [TelegramMessenger/Telegram-iOS#470]
This is a serious breach of privacy. If the other user has not turned off the setting (on by default), your forwarded messages reveal the identity of the person you're forwarding from. There is merit in never wanting to do this. You want it to remain anonymous. Please fix this.

**Comment by ali-fareed** [comment]
As this behavior is not specific to Telegram for iOS the issue should be filed at https://bugs.telegram.org
