### ISSUE TITLE
Can not build 7.4.1

### ISSUE THREAD

**Issue by d3nzZ3L** [TelegramMessenger/Telegram-iOS#472]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
Invoking build script by:
`python3 build-system/Make/Make.py     --bazel="$HOME/bazel-dist/bazel"     --cacheDir="$HOME/telegram-bazel-cache"     build     --configurationPath="$HOME/telegram-configuration"     --buildNumber=100001     --configuration=release_universal`

### Expected Behavior
Expecting successful build

### Actual Behavior
Occurs strange errors in AppDelegate source file

In 7.3.1 version all sources builds fine and this trouble occurs in 7.4.1 version

### Steps to Reproduce
1. Invoke build **python3 build-system/Make/Make.py** as in README.md
2. Errors occurring when compiling TelegramUI module

### Screenshots and Videos 
<img width="1169" alt="image" src="https://user-images.githubusercontent.com/21140562/106383120-1f585a80-63d5-11eb-8fd7-61f3c1282ca5.png">

<img width="1164" alt="image" src="https://user-images.githubusercontent.com/21140562/106383128-2b441c80-63d5-11eb-8b93-47f38aa441af.png">

<img width="1155" alt="image" src="https://user-images.githubusercontent.com/21140562/106383137-3434ee00-63d5-11eb-8d91-8a8e1b4847dd.png">

### Environment
**Device:** `iPhone12`

**iOS version**: `14.3`

**App version:** `7.4.1`

**Comment by ali-fareed** [comment]
Have you made any changes to the code?

**Comment by d3nzZ3L** [comment]
No, AppDelegate does not changed at all, code as like in official repo

**Comment by d3nzZ3L** [comment]
Found reason, thank you

**Comment by adilworth1038** [comment]
How can I get all my messages to expose successfully and redone load to my iPhone X
