### ISSUE TITLE
Termination Reason: Namespace RUNNINGBOARD, Code 0xdead10cc

### ISSUE THREAD

**Issue by alyfreym** [TelegramMessenger/Telegram-iOS#473]
Termination Reason: Namespace RUNNINGBOARD, Code 0xdead10cc.

This happens when the application has been in some time in background

**Comment by adilworth1038** [comment]
Do not terminate anything this is insane

**Comment by bigmouthstrks** [comment]
@alyfreym  Hey! please provide me more information about this issue, it happened on a simulator or physical device? What's the iOS version of the device running the issue? and everything else that might be helpful. Thank you!
