### ISSUE TITLE
ERROR: Unable to find an identity on the system matching the ones in external/build_configuration/provisioning/WatchExtension.mobileprovision

### ISSUE THREAD

**Issue by shivanraptor** [TelegramMessenger/Telegram-iOS#474]
in Telegram 7.3.1 & 7.4.1 release, I tried to compile following the latest README instructions to compile.

I copied the `telegram-configuration` folder from the source to the home folder, and modified the values in the `variables.bzl` (including changing the Bundle ID). I then created the Production Provisioning Profiles from Apple Developer > Certificates, Identifiers & Profiles according to the changed Bundle ID, and downloaded to `$HOME/telegram-configuration/provisioning/` folder. These provisioning profiles work in versions prior to version 7.3.1.

But when I issue the build command with the `configurationPath` set to `$HOME/telegram-configuration`, the build command fails saying the following:

> ERROR: Unable to find an identity on the system matching the ones in external/build_configuration/provisioning/WatchExtension.mobileprovision

The provisioning profile exists at `$HOME/telegram-configuration/provisioning/WatchExtension.mobileprovision` and is valid (since it is freshly created).

```
ERROR: /Users/adv/Documents/workspace/Xcode/xCodeProjects/Telegram_v7.4.1/Telegram-iOS/Telegram/BUILD:494:18: Processing and signing TelegramWatchExtension failed (Exit 1): process-and-sign-1202728910.sh failed: error executing command 
  (cd /private/var/tmp/_bazel_adv/45ef880466ea7fe75bfa8ae47cfb81f2/execroot/__main__ && \
  exec env - \
    APPLE_SDK_PLATFORM=WatchOS \
    APPLE_SDK_VERSION_OVERRIDE=7.2 \
    XCODE_VERSION_OVERRIDE=12.3.0.12C33 \
  bazel-out/applebin_watchos-watchos_armv7k-opt-ST-58153144368d/bin/Telegram/TelegramWatchExtension-intermediates/process-and-sign-1202728910.sh should_sign should_compress)
Execution platform: @local_config_platform//:host
ERROR: Unable to find an identity on the system matching the ones in external/build_configuration/provisioning/WatchExtension.mobileprovision
----------------
Note: The failure of target @build_bazel_rules_apple//tools/codesigningtool:codesigningtool (with exit code 1) may have been caused by the fact that it is running under Python 3 instead of Python 2. Examine the error to determine if that appears to be the problem. Since this target is built in the host configuration, the only way to change its version is to set --host_force_python=PY2, which affects the entire build.

If this error started occurring in Bazel 0.27 and later, it may be because the Python toolchain now enforces that targets analyzed as PY2 and PY3 run under a Python 2 and Python 3 interpreter, respectively. See https://github.com/bazelbuild/bazel/issues/7899 for more information.
----------------
Target //Telegram:Telegram failed to build
INFO: Elapsed time: 1537.308s, Critical Path: 702.96s
INFO: 7876 processes: 5064 remote cache hit, 1226 internal, 1586 local.
FAILED: Build did NOT complete successfully
```

What did I miss? Thanks in advance.

p.s. In the previous versions, I put the provisioning profiles in the `build-system/fake-codesigning/certs/`.

**Comment by shivanraptor** [comment]
Anyone can help?

**Comment by AnjeyNov** [comment]
@shivanraptor have you solve this problem? I meet the same one..

**Comment by YashGadle** [comment]
Can the author pls share a solution here? Or any other reason of closing this thread? @shivanraptor 
I am also facing exact issue.

**Comment by saniaxxx** [comment]
In my case the problem was in the certificate. To solve it revoke the certificate and create a new one via xcode

**Comment by YashGadle** [comment]
I see. For me the problem was that apple's authority "Apple Worldwide Developer Relations Intermediate Certificate", that issues these certificates had its own cert expired in Jan 2020. So we had to renew that as well
https://developer.apple.com/de/support/expiration/
