### ISSUE TITLE
Make project error 

### ISSUE THREAD

**Issue by zerxon** [TelegramMessenger/Telegram-iOS#476]
When I run:

```
python3 build-system/Make/Make.py \
    --bazel="$HOME/bazel-dist/bazel" \
    --cacheDir="$HOME/telegram-bazel-cache" \
    generateProject \
    --configurationPath="$HOME/telegram-configuration" \
    --disableExtensions
```

The terminal shows:
```Required Xcode version is 12.3, but 12.4 is reported by 'xcode-select -p'```

Can anyone help? Thanks a lot.

**Comment by zerxon** [comment]
My XCode version is 12.4

**Comment by ali-fareed** [comment]
Here is the relevant section from the readme: https://github.com/TelegramMessenger/Telegram-iOS#tips

**Comment by zerxon** [comment]
> Here is the relevant section from the readme: https://github.com/TelegramMessenger/Telegram-iOS#tips

Thanks a lot
