### ISSUE TITLE
IOS sharesheet missing

### ISSUE THREAD

**Issue by Altair-Bueno** [TelegramMessenger/Telegram-iOS#477]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
iOS sharesheet missing

### Expected Behavior
Using share button should let me share throughout telegam any media

### Actual Behavior
i can see whatsapp, signal, mail etc but no telegram

### Steps to Reproduce
1. share any link/photo using iOS share menu
2. look for telegram

### Screenshots and Videos 
![IMG_6061F2B8AC21-1](https://user-images.githubusercontent.com/67512202/107128005-9781bd00-68ba-11eb-824f-73d01166d589.jpeg)

### Environment
**Device:** `iPhone`

**iOS version**: `14.4`

**App version:** `7.4.2`

**Comment by Altair-Bueno** [comment]
Quick update: rebooted and now it shows up. Not sure is an iOS bug or telegram

**Comment by 60132189928** [comment]
Ok

**Comment by 60132189928** [comment]
@0132189928

**Comment by 60132189928** [comment]
#ChaAbdullah

**Comment by 60132189928** [comment]
t.me/ChaAbdullah
wa.me/+60132189928

**Comment by 60132189928** [comment]
0132189928 commented now
t.me/ChaAbdullah
wa.me/+60132189928

**Comment by laktyushin** [comment]
Not our bug. Rebooting device will help if encountered.
