### ISSUE TITLE
Extensions not built even without "--disableExtensions" flag set. 

### ISSUE THREAD

**Issue by horak** [TelegramMessenger/Telegram-iOS#483]
### Checklist
- [x ] I am reporting an issue in existing functionality that does not work as intended
- [x ] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
I've built the Xcode project successfully but am unable to use the Share Extension, despite not using the --disableExtensions flag in my build step.

### Expected Behavior
I tried sharing a photo to the Telegram app using the native Photos application.

### Actual Behavior
I received the following error upon tapping the Telegram app in the share sheet in the Photos app:
```
Unable to Share. There was an error while preparing to share. Please try again later.
```

### Steps to Reproduce
1. Build Xcode project using the following build command. Note the absence of the --disableExtension flag.
```
python3 build-system/Make/Make.py \
    --overrideXcodeVersion  \
    --bazel="$HOME/bazel-dist/bazel" \
    --cacheDir="$HOME/telegram-bazel-cache" \
    generateProject \
    --configurationPath="$HOME/telegram-configuration" \
    --disableProvisioningProfiles
```
2. I logged into my telegram account in the app.
3. I opened photos and tried sharing a file to the extension.
4. Then I saw the above error.

### Screenshots and Videos 
<img width="316" alt="Screen Shot 2021-02-10 at 5 31 23 PM" src="https://user-images.githubusercontent.com/1111424/107586785-3d3c7100-6bc6-11eb-9fe5-b9cf4bb3de64.png">

### Environment
**Device:** `iOS simulator 7th gen iOS 14.4`

**iOS version**: `13.X`

**App version:** Telegram 7.4.2 (19883)

### Questions
How do I go about getting this extension to build properly?

**Comment by ali-fareed** [comment]
Try running the same code in Simulator first.

**Comment by horak** [comment]
Unfortunately this is in the simulator! See Environment/ Device specs above. Thanks for your help @ali-fareed 👍

**Comment by ali-fareed** [comment]
Let's try resetting the simulator (`Device — Erase All Content and Settings...`).

**Comment by horak** [comment]
That unfortunately didn't change anything. But I'm running into a few confusing errors that might shed more light on this —

See here these `.appex` files in red:
<img width="498" alt="Screen Shot 2021-02-11 at 8 25 08 AM" src="https://user-images.githubusercontent.com/1111424/107649087-b4afe600-6c42-11eb-87c2-e32a481783e9.png">

**Comment by horak** [comment]
I'm also seeing this very long list of warnings Xcode is asking me to allow it to rectify. But I haven't changed anything except for the iOS Deployment Target value, from 9 -> 14.4.
<img width="1280" alt="Screen Shot 2021-02-11 at 12 59 53 PM" src="https://user-images.githubusercontent.com/1111424/107685200-5813f180-6c69-11eb-8cd0-57a161c4a479.png">

**Comment by ali-fareed** [comment]
Everything seems to work fine in a clean VM. Have you resolved the issue?

(These warnings are mostly irrelevant as Xcode is not used to build the project)

**Comment by horak** [comment]
Yes! The share sheet shows up for me now. Wiping the Simulator data did the trick.
