### ISSUE TITLE
Build 7.4.2 failed with default instructions 

### ISSUE THREAD

**Issue by zzmasoud** [TelegramMessenger/Telegram-iOS#485]
Build 7.4.2 failed, no modification except I changed Xcode version to _12.4_

- build script:
`python3 build-system/Make/Make.py \
    --bazel="$HOME/bazel-dist/bazel" \
    --cacheDir="$HOME/telegram-bazel-cache" \
    build \
    --configurationPath="$HOME/telegram-configuration" \
    --buildNumber=100001 \
    --configuration=release_universal`
    
    - logs:
![Screen Shot 2021-02-14 at 10 08 58 PM](https://user-images.githubusercontent.com/2379690/107885759-46ed0e00-6f11-11eb-974b-7f48ae10bc47.png)

![Screen Shot 2021-02-14 at 10 09 01 PM](https://user-images.githubusercontent.com/2379690/107885768-5409fd00-6f11-11eb-9f5b-05785985d3de.png)

 Thank you for your effort!

**Comment by zzmasoud** [comment]
@ali-fareed would you please take a look at it?

**Comment by SergeyKolokolnikov** [comment]
You can see more information during generating via tulsi gen

<img width="804" alt="Screen Shot 2021-02-15 at 1 40 40 PM" src="https://user-images.githubusercontent.com/7039183/107942301-b1df2900-6f93-11eb-972c-d1fce02a973c.png">

<img width="839" alt="Screen Shot 2021-02-15 at 1 40 59 PM" src="https://user-images.githubusercontent.com/7039183/107942307-b4da1980-6f93-11eb-9f58-51662cf2d6cb.png">

**Comment by zzmasoud** [comment]
> Telegram.tulsiproj

Thanks for your quick reply, I looked up in project and generated bazel directories but didn't find any  _build-input_ folder or _.tulsiproj_ file, any help?

**Comment by SergeyKolokolnikov** [comment]
try this steps
1. Clone repo and build project with default params. You get build-input folder and generated tulsi.
2. Modify files, assets, settings, profiles etc. Again build project via tulsi and you can see more information in log.

**Comment by ali-fareed** [comment]
You need to have the certificates that are referenced by your provisioning profiles installed locally.

**Comment by zzmasoud** [comment]
> You need to have the certificates that are referenced by your provisioning profiles installed locally.

is there any faster procedure to generate this profiles? idk maybe using fastlane?

**Comment by ali-fareed** [comment]
Yes, we are using fastlane internally. But if you're a solo developer it might be easier to do it once, manually.
