### ISSUE TITLE
Change Product Display Name (App name) and App Icons in v7.4.x?

### ISSUE THREAD

**Issue by shivanraptor** [TelegramMessenger/Telegram-iOS#492]
What is the correct way to change the Product Display Name (App name) and App Icons in v7.4.x? 

After I generate the Xcode project, the App Icons and `Info.plist` are not available for edit.

**Comment by ali-fareed** [comment]
Everything is set in the BUILD file. The icons section requires a bit of cleanup, but it's certainly possible to specify custom icons, see https://github.com/TelegramMessenger/Telegram-iOS/blob/master/Telegram/BUILD#L168

You may want to remove or customize the additional icons as well: https://github.com/TelegramMessenger/Telegram-iOS/blob/master/Telegram/BUILD#L1698

The user-facing app name is controlled by CFBundleDisplayName entries in plists:

https://github.com/TelegramMessenger/Telegram-iOS/blob/master/Telegram/BUILD#L444
https://github.com/TelegramMessenger/Telegram-iOS/blob/master/Telegram/BUILD#L1520
