### ISSUE TITLE
Calls not working from message

### ISSUE THREAD

**Issue by IgrovoyYT** [TelegramMessenger/Telegram-iOS#493]
If you click on your phone number in the dialog, you get the error "can't show url." Previously, there were no such problems, first seen in version 7.5

### Screenshots and Videos 
![image](https://user-images.githubusercontent.com/79647615/109165539-575c7e80-7784-11eb-8441-09e84c129d87.jpeg)

### Environment

**Device:** All devices

**iOS version**: all

**App version:** 7.5

**Comment by laktyushin** [comment]
Fixed in 7.5.1
