### ISSUE TITLE
Adding Firestore

### ISSUE THREAD

**Issue by vchernyshov** [TelegramMessenger/Telegram-iOS#495]
I want to add Firestore to Telegram v7.4.2
Xcode project generates correctly but build is failed.

This is gist with BUILD file and Xcode error log: https://gist.github.com/vchernyshov/87ce0227d89fa24b776a54ab2eb0de75

**Comment by ali-fareed** [comment]
BoringSSL is being linked twice.

**Comment by vchernyshov** [comment]
@ali-fareed I have removed barring-ssl from my build file, and now got another error:
https://gist.github.com/vchernyshov/ebcb1846eb435ecb04288bd106504e5e

**Comment by ali-fareed** [comment]
It seems you have removed the whole `BoringSSL-GRPC`. I would suggest rebuilding `GRPC` from source.

**Comment by vchernyshov** [comment]
Yep, I have removed Boring-SSL from Firestore as there's a version of boringssl in third-party folder of telegram

**Comment by vchernyshov** [comment]
@ali-fareed does Telegram have some special fork of boring ssl?

**Comment by ali-fareed** [comment]
Telegram uses standard BoringSSL as provided by Google. BoringSSL-GRPC, however, looks like a modified version of BoringSSL.

**Comment by vchernyshov** [comment]
Maybe there is some build option to avoid duplication of symbols?

**Comment by ali-fareed** [comment]
There is, you should rebuild the GRPC framework from source using the version of BoringSSL built into the app.

**Comment by vchernyshov** [comment]
Sounds like not the easiest tasks.
Why there were not such problems with BUCK?

**Comment by ali-fareed** [comment]
Telegram was using the regular OpenSSL, not BoringSSL before transitioning to Bazel.
