### ISSUE TITLE
Add Firestore

### ISSUE THREAD

**Issue by vchernyshov** [TelegramMessenger/Telegram-iOS#496]
I want to add Firestore to Telegram v7.4.2
I have manage to build Xcode project with new dependency but can't build the app.
This is the link to build file and error output: https://gist.github.com/vchernyshov/87ce0227d89fa24b776a54ab2eb0de75

Could anybody help with this?

**Comment by ali-fareed** [comment]
See https://github.com/TelegramMessenger/Telegram-iOS/issues/495
