### ISSUE TITLE
Build failed version 7.5.1

### ISSUE THREAD

**Issue by cunzhegao** [TelegramMessenger/Telegram-iOS#498]
### Checklist
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
Mac OS: 11.2 
Xcode: 12.4

When I tried to build project whether on terminal or Xcode, it always show the same error message indicating missing webrtc input files:

python3 build-system/Make/Make.py \
    --bazel="$HOME/bazel-dist/bazel" \
    --cacheDir="$HOME/telegram-bazel-cache" \
    build \
    --configurationPath="$HOME/telegram-configuration" \
    --buildNumber=100001 \
    --configuration=release_universal
TelegramBuild: running
/Users/gaocunzhe/bazel-dist/bazel build Telegram/Telegram --override_repository=build_configuration=/Users/gaocunzhe/telegram-configuration --announce_rc --features=swift.use_global_module_cache --verbose_failures --features=swift.skip_function_bodies_for_derived_files --jobs=16 --define=buildNumber=100001 --define=telegramVersion=7.5.1 --features=swift.split_derived_files_generation --disk_cache=/Users/gaocunzhe/telegram-bazel-cache -c opt --ios_multi_cpus=armv7,arm64 --watchos_cpus=armv7k,arm64_32 --apple_generate_dsym --output_groups=+dsyms --features=swift.opt_uses_wmo --features=swift.opt_uses_osize --swiftcopt=-num-threads --swiftcopt=0 --features=dead_strip --objc_enable_binary_stripping --apple_bitcode=watchos=embedded
INFO: Invocation ID: 89d3918c-8603-4dcc-a9f0-9895aa67d230
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=113
INFO: Reading rc options for 'build' from /Users/gaocunzhe/Developer/Telegram-iOS/.bazelrc:
  'build' options: --action_env=ZERO_AR_DATE=1 --apple_platform_type=ios --cxxopt=-std=c++14 --per_file_copt=third-party/webrtc/.*.cpp$,@-std=c++14 --per_file_copt=third-party/webrtc/.*.cc$,@-std=c++14 --per_file_copt=third-party/webrtc/.*.mm$,@-std=c++14 --features=debug_prefix_map_pwd_is_dot --features=swift.cacheable_swiftmodules --features=swift.debug_prefix_map --features=swift.enable_vfsoverlays --strategy=Genrule=standalone --spawn_strategy=standalone --strategy=SwiftCompile=standalone --define RULES_SWIFT_BUILD_DUMMY_WORKER=1
DEBUG: /private/var/tmp/_bazel_gaocunzhe/ba129248ded9df43bf95b0aa75e35425/external/bazel_tools/tools/osx/xcode_configure.bzl:89:14: Invoking xcodebuild failed, developer dir: /Applications/Xcode 10.app/Contents/Developer ,return code 138, stderr: , stdout: 
DEBUG: /private/var/tmp/_bazel_gaocunzhe/ba129248ded9df43bf95b0aa75e35425/external/build_bazel_rules_apple/apple/internal/partials/extension_safe_validation.bzl:42:22: The target //Telegram:ShareExtension is for an extension but its framework dependency //Telegram:TelegramUIFramework is not marked extension-safe. Specify 'extension_safe = 1' on the framework target. This will soon cause a build failure.
DEBUG: /private/var/tmp/_bazel_gaocunzhe/ba129248ded9df43bf95b0aa75e35425/external/build_bazel_rules_apple/apple/internal/partials/extension_safe_validation.bzl:42:22: The target //Telegram:NotificationContentExtension is for an extension but its framework dependency //Telegram:TelegramUIFramework is not marked extension-safe. Specify 'extension_safe = 1' on the framework target. This will soon cause a build failure.
DEBUG: /private/var/tmp/_bazel_gaocunzhe/ba129248ded9df43bf95b0aa75e35425/external/build_bazel_rules_apple/apple/internal/partials/extension_safe_validation.bzl:42:22: The target //Telegram:NotificationServiceExtension is for an extension but its framework dependency //Telegram:MtProtoKitFramework is not marked extension-safe. Specify 'extension_safe = 1' on the framework target. This will soon cause a build failure.
DEBUG: /private/var/tmp/_bazel_gaocunzhe/ba129248ded9df43bf95b0aa75e35425/external/build_bazel_rules_apple/apple/internal/partials/extension_safe_validation.bzl:42:22: The target //Telegram:NotificationServiceExtension is for an extension but its framework dependency //Telegram:SwiftSignalKitFramework is not marked extension-safe. Specify 'extension_safe = 1' on the framework target. This will soon cause a build failure.
DEBUG: /private/var/tmp/_bazel_gaocunzhe/ba129248ded9df43bf95b0aa75e35425/external/build_bazel_rules_apple/apple/internal/partials/extension_safe_validation.bzl:42:22: The target //Telegram:NotificationServiceExtension is for an extension but its framework dependency //Telegram:PostboxFramework is not marked extension-safe. Specify 'extension_safe = 1' on the framework target. This will soon cause a build failure.
DEBUG: /private/var/tmp/_bazel_gaocunzhe/ba129248ded9df43bf95b0aa75e35425/external/build_bazel_rules_apple/apple/internal/partials/extension_safe_validation.bzl:42:22: The target //Telegram:IntentsExtension is for an extension but its framework dependency //Telegram:SwiftSignalKitFramework is not marked extension-safe. Specify 'extension_safe = 1' on the framework target. This will soon cause a build failure.
DEBUG: /private/var/tmp/_bazel_gaocunzhe/ba129248ded9df43bf95b0aa75e35425/external/build_bazel_rules_apple/apple/internal/partials/extension_safe_validation.bzl:42:22: The target //Telegram:IntentsExtension is for an extension but its framework dependency //Telegram:PostboxFramework is not marked extension-safe. Specify 'extension_safe = 1' on the framework target. This will soon cause a build failure.
DEBUG: /private/var/tmp/_bazel_gaocunzhe/ba129248ded9df43bf95b0aa75e35425/external/build_bazel_rules_apple/apple/internal/partials/extension_safe_validation.bzl:42:22: The target //Telegram:IntentsExtension is for an extension but its framework dependency //Telegram:TelegramCoreFramework is not marked extension-safe. Specify 'extension_safe = 1' on the framework target. This will soon cause a build failure.
DEBUG: /private/var/tmp/_bazel_gaocunzhe/ba129248ded9df43bf95b0aa75e35425/external/build_bazel_rules_apple/apple/internal/partials/extension_safe_validation.bzl:42:22: The target //Telegram:IntentsExtension is for an extension but its framework dependency //Telegram:SyncCoreFramework is not marked extension-safe. Specify 'extension_safe = 1' on the framework target. This will soon cause a build failure.
DEBUG: /private/var/tmp/_bazel_gaocunzhe/ba129248ded9df43bf95b0aa75e35425/external/build_bazel_rules_apple/apple/internal/partials/extension_safe_validation.bzl:42:22: The target //Telegram:WidgetExtension is for an extension but its framework dependency //Telegram:SwiftSignalKitFramework is not marked extension-safe. Specify 'extension_safe = 1' on the framework target. This will soon cause a build failure.
DEBUG: /private/var/tmp/_bazel_gaocunzhe/ba129248ded9df43bf95b0aa75e35425/external/build_bazel_rules_apple/apple/internal/partials/extension_safe_validation.bzl:42:22: The target //Telegram:WidgetExtension is for an extension but its framework dependency //Telegram:PostboxFramework is not marked extension-safe. Specify 'extension_safe = 1' on the framework target. This will soon cause a build failure.
DEBUG: /private/var/tmp/_bazel_gaocunzhe/ba129248ded9df43bf95b0aa75e35425/external/build_bazel_rules_apple/apple/internal/partials/extension_safe_validation.bzl:42:22: The target //Telegram:WidgetExtension is for an extension but its framework dependency //Telegram:SyncCoreFramework is not marked extension-safe. Specify 'extension_safe = 1' on the framework target. This will soon cause a build failure.
DEBUG: /private/var/tmp/_bazel_gaocunzhe/ba129248ded9df43bf95b0aa75e35425/external/build_bazel_rules_apple/apple/internal/partials/extension_safe_validation.bzl:42:22: The target //Telegram:WidgetExtension is for an extension but its framework dependency //Telegram:TelegramCoreFramework is not marked extension-safe. Specify 'extension_safe = 1' on the framework target. This will soon cause a build failure.
INFO: Analyzed target //Telegram:Telegram (1 packages loaded, 3391 targets configured).
INFO: Found 1 target...
ERROR: /Users/gaocunzhe/Developer/Telegram-iOS/third-party/webrtc/BUILD:3549:13: Middleman _middlemen/webrtc-ObjcCppSemantics_build_arch_ios-armv7-min9.0-applebin_ios-ios_armv7-opt-ST-36ad1e8d6baf_with_suffix__objc_arc failed: missing input file '//third-party/webrtc:webrtc/api/adaptation/resource.h'
Target //Telegram:Telegram failed to build
ERROR: /Users/gaocunzhe/Developer/Telegram-iOS/third-party/webrtc/BUILD:3549:13 Middleman _middlemen/webrtc-ObjcCppSemantics_build_arch_ios-armv7-min9.0-applebin_ios-ios_armv7-opt-ST-36ad1e8d6baf_with_suffix__objc_arc failed: 1543 input file(s) do not exist
INFO: Elapsed time: 1.479s, Critical Path: 0.21s
INFO: 22 processes: 22 internal.
FAILED: Build did NOT complete successfully
Traceback (most recent call last):
  File "/Users/gaocunzhe/Developer/Telegram-iOS/build-system/Make/Make.py", line 577, in <module>
    build(arguments=args)
  File "/Users/gaocunzhe/Developer/Telegram-iOS/build-system/Make/Make.py", line 400, in build
    bazel_command_line.invoke_build()
  File "/Users/gaocunzhe/Developer/Telegram-iOS/build-system/Make/Make.py", line 295, in invoke_build
    call_executable(combined_arguments)
  File "/Users/gaocunzhe/Developer/Telegram-iOS/build-system/Make/BuildEnvironment.py", line 60, in call_executable
    subprocess.check_call(resolved_arguments, env=resolved_env)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/gaocunzhe/bazel-dist/bazel', 'build', 'Telegram/Telegram', '--override_repository=build_configuration=/Users/gaocunzhe/telegram-configuration', '--announce_rc', '--features=swift.use_global_module_cache', '--verbose_failures', '--features=swift.skip_function_bodies_for_derived_files', '--jobs=16', '--define=buildNumber=100001', '--define=telegramVersion=7.5.1', '--features=swift.split_derived_files_generation', '--disk_cache=/Users/gaocunzhe/telegram-bazel-cache', '-c', 'opt', '--ios_multi_cpus=armv7,arm64', '--watchos_cpus=armv7k,arm64_32', '--apple_generate_dsym', '--output_groups=+dsyms', '--features=swift.opt_uses_wmo', '--features=swift.opt_uses_osize', '--swiftcopt=-num-threads', '--swiftcopt=0', '--features=dead_strip', '--objc_enable_binary_stripping', '--apple_bitcode=watchos=embedded']' returned non-zero exit status 1.

Is there a way to fix this?

**Comment by ali-fareed** [comment]
Have you checked out all submodules?

**Comment by cunzhegao** [comment]
> Have you checked out all submodules?

I assume it's include in build script？ If I run build command in terminal, it will not throw this error. But if I generate a Xcode project and then tried to run on simulator, it will throw this error.

How could I check out all submodules after generated Xcode project?

**Comment by ali-fareed** [comment]
If you followed the build instructions in https://github.com/TelegramMessenger/Telegram-iOS#compilation-guide (specifically, ran `git clone` with `--recursive`), then submodules should have been checked out. Due to network issues this may fail. I would suggest to run `git submodule update` just to be sure.

Additionally, check that the files indeed exist: `ls third-party/webrtc/webrtc/api/adaptation/resource.h`

**Comment by cunzhegao** [comment]
re-clone the repo fix it. Thx.
