### ISSUE TITLE
Build did not complete successfully - version 7.5.1

### ISSUE THREAD

**Issue by sfilmak** [TelegramMessenger/Telegram-iOS#500]
### Checklist
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description

macOS: 11.2.2
Xcode: 12.4

I am trying to build an Xcode project without provisioning profiles (--disableProvisioningProfiles flag), but I am always getting an error.

---

**Logs:**

python3 build-system/Make/Make.py \
    --bazel="$HOME/bazel-dist/bazel" \
     --cacheDir="$HOME/telegram-bazel-cache" \
     build \
     --configurationPath="$HOME/telegram-configuration" \
     --buildNumber=100001 \
     --configuration=release_universal

TelegramBuild: running
/Users/grafneco/bazel-dist/bazel build Telegram/Telegram --override_repository=build_configuration=/Users/grafneco/telegram-configuration --announce_rc --features=swift.use_global_module_cache --verbose_failures --features=swift.skip_function_bodies_for_derived_files --jobs=4 --define=buildNumber=100001 --define=telegramVersion=7.5.1 --features=swift.split_derived_files_generation --disk_cache=/Users/grafneco/telegram-bazel-cache -c opt --ios_multi_cpus=armv7,arm64 --watchos_cpus=armv7k,arm64_32 --apple_generate_dsym --output_groups=+dsyms --features=swift.opt_uses_wmo --features=swift.opt_uses_osize --swiftcopt=-num-threads --swiftcopt=0 --features=dead_strip --objc_enable_binary_stripping --apple_bitcode=watchos=embedded
Starting local Bazel server and connecting to it...
INFO: Invocation ID: 37712617-0df3-4847-bffa-c956b7646fa7
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=80
INFO: Reading rc options for 'build' from /Users/grafneco/Desktop/TelegramiOS/Telegram-iOS/.bazelrc:
  'build' options: --action_env=ZERO_AR_DATE=1 --apple_platform_type=ios --cxxopt=-std=c++14 --per_file_copt=third-party/webrtc/.*.cpp$,@-std=c++14 --per_file_copt=third-party/webrtc/.*.cc$,@-std=c++14 --per_file_copt=third-party/webrtc/.*.mm$,@-std=c++14 --features=debug_prefix_map_pwd_is_dot --features=swift.cacheable_swiftmodules --features=swift.debug_prefix_map --features=swift.enable_vfsoverlays --strategy=Genrule=standalone --spawn_strategy=standalone --strategy=SwiftCompile=standalone --define RULES_SWIFT_BUILD_DUMMY_WORKER=1
ERROR: Error fetching repository: java.io.IOException: No WORKSPACE file found in /private/var/tmp/_bazel_grafneco/722148ba3622719baf614d78fb4e37d8/external/build_bazel_rules_apple
ERROR: no such package '@build_bazel_rules_apple//apple': No WORKSPACE file found in /private/var/tmp/_bazel_grafneco/722148ba3622719baf614d78fb4e37d8/external/build_bazel_rules_apple
INFO: Elapsed time: 7.393s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
Traceback (most recent call last):
  File "build-system/Make/Make.py", line 577, in <module>
    build(arguments=args)
  File "build-system/Make/Make.py", line 400, in build
    bazel_command_line.invoke_build()
  File "build-system/Make/Make.py", line 295, in invoke_build
    call_executable(combined_arguments)
  File "/Users/grafneco/Desktop/TelegramiOS/Telegram-iOS/build-system/Make/BuildEnvironment.py", line 60, in call_executable
    subprocess.check_call(resolved_arguments, env=resolved_env)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/grafneco/bazel-dist/bazel', 'build', 'Telegram/Telegram', '--override_repository=build_configuration=/Users/grafneco/telegram-configuration', '--announce_rc', '--features=swift.use_global_module_cache', '--verbose_failures', '--features=swift.skip_function_bodies_for_derived_files', '--jobs=4', '--define=buildNumber=100001', '--define=telegramVersion=7.5.1', '--features=swift.split_derived_files_generation', '--disk_cache=/Users/grafneco/telegram-bazel-cache', '-c', 'opt', '--ios_multi_cpus=armv7,arm64', '--watchos_cpus=armv7k,arm64_32', '--apple_generate_dsym', '--output_groups=+dsyms', '--features=swift.opt_uses_wmo', '--features=swift.opt_uses_osize', '--swiftcopt=-num-threads', '--swiftcopt=0', '--features=dead_strip', '--objc_enable_binary_stripping', '--apple_bitcode=watchos=embedded']' returned non-zero exit status 1.

**End of logs**

---

What could be a problem? And how can I fix it? Thanks in advance.

**Comment by ali-fareed** [comment]
Check that you have checked out the submodules: `git submodule update`

**Comment by sfilmak** [comment]
That worked - thank you

**Comment by cfcor** [comment]
How can I git submodule update?
