### ISSUE TITLE
relase-7.5 Run error!

### ISSUE THREAD

**Issue by cuteworld** [TelegramMessenger/Telegram-iOS#501]
Telegram-iOS/third-party/libvpx/BUILD:28:8: error: Executing genrule //third-party/libvpx:libvpx_build failed: (Exit 1): bash failed: error executing command 
Telegram-iOS/Telegram/BUILD:207:14 Compiling Swift module Telegram_Lib failed: (Exit 1): bash failed: error executing command 
Telegram-iOS/build-input/gen/project/Telegram.xcodeproj/.tulsi/Scripts/bazel_build.py:581: error: Bazel build failed with exit code 1. Please check the build log in Report Navigator (⌘9) for more information.

I successfully built the xcode project, but it failed to run. I don't know what error was reported in libvpx. Can you help me see why？

**Comment by ali-fareed** [comment]
You may need to install `yasm` for x86 builds (that is, iOS simulator on legacy hardware platforms).

If you have Homebrew installed, run `brew install yasm`

**Comment by cuteworld** [comment]
Thank you, I have solved the problem and successfully run version 7.5.

**Comment by cuteworld** [comment]
@ali-fareed 
I had already run the project successfully, but when I rebuilt the project today, an error occurred. But my bazel and telegram have not changed, and I tried again after deleting it, the same is the error. Can you help me solve this problem?

python3 build-system/Make/Make.py \
    --bazel="$HOME/bazel-dist/bazel" \
    --cacheDir="$HOME/telegram-bazel-cache" \
    generateProject \
    --configurationPath="$HOME/telegram-configuration" \
    --disableExtensions \
    --disableProvisioningProfiles
No matching processes belonging to you were found
INFO: Analyzed target //:tulsi (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //:tulsi up-to-date:
  bazel-bin/tulsi.zip
INFO: Elapsed time: 0.116s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
[Syslog] Tulsi CLI: version 0.20210120.88
[Syslog] Create project: Telegram
[Syslog] Fetching bazel path info
[Info] Running /usr/local/Cellar/bazel/4.0.0/bin/bazel info '--override_repository=tulsi=/Users/ruby1x/Library/Application Support/Tulsi/0.20210120.88/Bazel'
[Syslog] ** Completed bazel_get_package_path in 0.0890s
[Syslog] ** Completed get_package_path in 0.0900s
[Syslog] Fetching rules for packages ["Telegram"]
[Info] Running /usr/local/Cellar/bazel/4.0.0/bin/bazel --max_idle_secs=60 query '--override_repository=tulsi=/Users/ruby1x/Library/Application Support/Tulsi/0.20210120.88/Bazel' --announce_rc --noimplicit_deps --order_output=no --noshow_loading_progress --noshow_progress 'kind(rule, Telegram:all)' --output xml
[Syslog] ** Completed bazel_query_fetch_rules in 0.0695s
[Info] Bazel command info:
/usr/local/Cellar/bazel/4.0.0/bin/bazel --max_idle_secs=60 query '--override_repository=tulsi=/Users/ruby1x/Library/Application Support/Tulsi/0.20210120.88/Bazel' --announce_rc --noimplicit_deps --order_output=no --noshow_loading_progress --noshow_progress 'kind(rule, Telegram:all)' --output xml
Exited with code 7

INFO: Options provided by the client:
  Inherited 'common' options: --isatty=0 --terminal_columns=80
ERROR: error loading package 'Telegram': Unable to find package for @build_configuration//:variables.bzl: The repository '@build_configuration' could not be resolved.

[Error] Failed to retrieve information about the Bazel workspace. This usually means that the contents of a BUILD file are incorrect or flags are missing. Read the message log carefully for details. ERROR: error loading package 'Telegram': Unable to find package for @build_configuration//:variables.bzl: The repository '@build_configuration' could not be resolved.
[Syslog] ** Completed fetch_rules in 0.0708s
Failed to identify any valid build targets.
Traceback (most recent call last):
  File "/Users/ruby1x/Telegram-iOS/build-system/Make/Make.py", line 575, in <module>
    generate_project(arguments=args)
  File "/Users/ruby1x/Telegram-iOS/build-system/Make/Make.py", line 370, in generate_project
    generate(
  File "/Users/ruby1x/Telegram-iOS/build-system/Make/ProjectGeneration.py", line 86, in generate
    call_executable([
  File "/Users/ruby1x/Telegram-iOS/build-system/Make/BuildEnvironment.py", line 60, in call_executable
    subprocess.check_call(resolved_arguments, env=resolved_env)
  File "/usr/local/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/ruby1x/Telegram-iOS/build-input/gen/project/Tulsi.app/Contents/MacOS/Tulsi', '--', '--verbose', '--create-tulsiproj', 'Telegram', '--workspaceroot', './', '--bazel', '/Users/ruby1x/Telegram-iOS/build-input/gen/project/bazel', '--outputfolder', '/Users/ruby1x/Telegram-iOS/build-input/gen/project', '--target', 'Telegram:Telegram', '--build-options', '--override_repository=build_configuration=/Users/ruby1x/telegram-configuration --//Telegram:disableExtensions --//Telegram:disableProvisioningProfiles']' returned non-zero exit status 24.

**Comment by ali-fareed** [comment]
Check the contents of `$HOME/telegram-configuration`

**Comment by cuteworld** [comment]
Thank you, but I did not find any problems with $HOME/telegram-configuration. But after I tried to restart the computer, the build succeeded. I hope that friends who encounter the same problem as me in the future may find the reason.

**Comment by ali-fareed** [comment]
Right, there is an unresolved issue with Tulsi (the Xcode project generator) that may require a system reboot to work.
