### ISSUE TITLE
Provide a Catalyst build

### ISSUE THREAD

**Issue by iMonZ** [TelegramMessenger/Telegram-iOS#502]
My suggestion is that Telegram should provide a Catalyst build.
The Catalyst app would save money, so Telegram can focus on one App instead of two.
The Telegram Swift project wasn't updated either for a month.

And the features would be available immediately for macOS instead of waiting for someone making an update.

**Comment by ali-fareed** [comment]
Catalyst is only available on macOS 10.15 and later.

**Comment by iMonZ** [comment]
> Catalyst is only available on macOS 10.15 and later.

So?

please reopen this issue!

**Comment by ali-fareed** [comment]
The current macOS app supports versions back to 10.11.
