### ISSUE TITLE
Blank Screen when opening the app

### ISSUE THREAD

**Issue by StardustMetonymy** [TelegramMessenger/Telegram-iOS#505]
### Checklist

- [x] I am reporting an issue in existing functionality that does not work as intended

- [x] I've searched for existing [GitHub issues]

(https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
I load the app up and it gives me a blank screen. I have waited it out but it’s longer than ever before. I can access my account from the desktop version, however.

### Expected Behavior
It should open the app and load correctly in reasonable time.

### Actual Behavior
I open the app and it hangs on a blank screen forever. It seems to have a problem with loading in the information.

### Steps to Reproduce
1. Opening the app
2. Blank screen appears
3. Then repeat

### Screenshots and Videos
![BEFA5768-0C06-4C69-B792-0DB1C02A1369](https://user-images.githubusercontent.com/80840132/111491330-27b0ee80-8712-11eb-8a9f-e38754642f6f.png)

### Environment
**Device:** iPhone 6s

**iOS version**: 14.4

**App version:** 7.5.1

I’m new to this so forgive me for any incorrect information.

**Comment by moschlar** [comment]
Same here, iOS 14.4.1 on iPhone XR, App Version 7.6

**Comment by F4FBlack** [comment]
Same here too ^^
Device: iPhone 11pro Max
iOS version: 14.5
App version: 7.6

Only a reinstall works, but the Problem comes back again.

**Comment by gjcairo** [comment]
Experiencing same issue. iOS 14.4.2, iPhone 12 Pro, app version 7.6.1

Notifications arrive, but I get a white screen upon opening the app. I fixed it a couple of weeks ago by deleting the app and reinstalling, but the issue came back today.

**Comment by stefandanaita** [comment]
Same thing on iOS 14.4.2 and Telegram 7.6.1 😢

**Comment by Kylmakalle** [comment]
Pretty long-term issue that's finally reported.
Well, it also occurred in my Nicegram fork.
Notifications are still able to be received.
Log: https://pastebin.com/stAg018P


https://user-images.githubusercontent.com/24507532/113680614-b8ec0300-96c9-11eb-99fc-da2410892c5e.mp4

**Comment by ali-fareed** [comment]
Please check if the updated 7.6.2 fixes the issue.

**Comment by F4FBlack** [comment]
> Please check if the updated 7.6.2 fixes the issue.

I check it out, but the issue is still there.

**Comment by stefandanaita** [comment]
> Please check if the updated 7.6.2 fixes the issue.

I can confirm that 7.6.2 fixed the black screen issue.

**Comment by FirExpl** [comment]
Telegram 7.7. iPhone X, iOS 14.4.2. The black screen issue

**Comment by FirExpl** [comment]
OK, when the screen was black telegram has reduced cached files size from 66GB to ~3GB and after that it starts to work normally

**Comment by BenRacicot** [comment]
Should be repoened for continued issues on 
MacOS 10.15.7 (19H1030)
7.7 (215786) Stable

**Comment by mcgroarty** [comment]
It's not a fix for the bug, but sometimes I can restore the screen by holding the volume up and power buttons until the power off screen appears, then canceling.

**Comment by LSPBoy** [comment]
so did I, can you resovle?
