### ISSUE TITLE
Auto-delete is broken. TG keeps messages that are far older than set timer.

### ISSUE THREAD

**Issue by ubapsi** [TelegramMessenger/Telegram-iOS#507]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
Self-destruct seems to be broken since quite some time. I have found messages that date back to mid of February (at least 19th Feb). Interestingly, within the same chat, the messages for the other party are deleted accordingly. When holding down on a single message, the context menu will show "auto-deletes in 0:00".

### Expected Behavior
I hate these templates... 
The auto-delete timer should delete the messages.

### Actual Behavior
It does not delete the messages.

### Steps to Reproduce
1. Open a secret chat with a longer history and scroll back until a message appears that is older than set timer.

(not sure if this issue will also appear if you create a new chat, but with old existing ones it happens on all of the chats)

### Environment
**Device:** `iPhone SE`

**iOS version**: `13.2.3`

**App version:** `7.6` (and how are you supposed to find this information if it doesn't show in-app?)

**Comment by 8of** [comment]
This is still the case, for new secret chats with self-destruct timer as well.

Regular chats with self-destruct timer work fine. 

### Environment

Device: `iPhone 7`

iOS version: `14.4.2`

App version: `7.7`

**Comment by ubapsi** [comment]
Seems to be fixed in latest release. Can anyone confirm?
