### ISSUE TITLE
Can't share original HEIC assets from Photos

### ISSUE THREAD

**Issue by ultimate-deej** [TelegramMessenger/Telegram-iOS#510]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
When sharing a HEIC image from Photos ("File" share option), it is converted to JPEG. That does not happen when sharing from iCloud.

### Expected Behavior
The original image file gets shared.

### Actual Behavior
A JPEG image gets shared.

### Steps to Reproduce
1. Tap share button in a chat.
2. Choose "File", then "Photo or Video".
3. Tap on an image.
4. Make sure it's in HEIC format (displayed at the bottom of the screen)
5. Share the image.

### Environment
**Device:** `iPhone 12 Pro`

**iOS version**: `14.4.1`

**App version:** `7.6.1`

**Comment by laktyushin** [comment]
Added in 8.3
