### ISSUE TITLE
All secret chats disappeared after update

### ISSUE THREAD

**Issue by electro60** [TelegramMessenger/Telegram-iOS#514]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
I had an issue before this it was when I open telegram nothing but a blank screen ([This issue](https://github.com/TelegramMessenger/Telegram-iOS/issues/505) ), after the update first test crashed and the application closed suddenly second test all fixed but all secret chats DISAPPEARED, but I had noticed something the storage is the same before secret chats disappeared, another one when telegram calculating the size of cache the number of GBs of the cache is bigger from the chats it showed, the secret chats gone but the data is still there

### Expected Behavior
It should open and load normally

### Actual Behavior
Application opened but not loading the secret chats

### Steps to Reproduce
1. Opening the application 
2. No secret chats loading 
3. Repeat

### Environment
Device: iPhone X

iOS version: 14.4.2

App version: 7.6.2

Sorry for my English.

**Comment by ali-fareed** [comment]
Unfortunately, it is an expected behavior of the "black screen" fix. Hopefully, it's a onetime issue.
