### ISSUE TITLE
Building app error

### ISSUE THREAD

**Issue by aze20** [TelegramMessenger/Telegram-iOS#519]
https://core.telegram.org/reproducible-builds#step-7-building-the-app
I run the commands:
cd $HOME/telegram-ios BAZEL="$HOME/bazel/bazel" sh buildbox/build-telegram.sh verify
but log Error:
Base VM: "macos10_15_Xcode12_4"
Building on macOS
+ find . -type f -a -not -regex '\.' -a -not -regex '.*\./git' -a -not -regex '.*\./git/.*' -a -not -regex '\./bazel-bin' -a -not -regex '\./bazel-bin/.*' -a -not -regex '\./bazel-out' -a -not -regex '\./bazel-out/.*' -a -not -regex '\./bazel-testlogs' -a -not -regex '\./bazel-testlogs/.*' -a -not -regex '\./bazel-telegram-ios' -a -not -regex '\./bazel-telegram-ios/.*' -a -not -regex '\./buildbox' -a -not -regex '\./buildbox/.*' -a -not -regex '\./buck-out' -a -not -regex '\./buck-out/.*' -a -not -regex '\./\.buckd' -a -not -regex '\./\.buckd/.*' -a -not -regex '\./build' -a -not -regex '\./build/.*' -print0
+ tar cf buildbox/transient-data/source.tar --null -T -
+ PROCESS_ID=30764
+ '[' -z '' ']'
++ openssl rand -hex 10
+ VM_NAME=macos10_15_Xcode12_4-e8fe4a5938027b912b2b-build-telegram-30764
+ '[' macOS == linux ']'
+ '[' macOS == macOS ']'
+ '[' -z '' ']'
+ prlctl clone macos10_15_Xcode12_4 --linked --name macos10_15_Xcode12_4-e8fe4a5938027b912b2b-build-telegram-30764
buildbox/build-telegram.sh: line 158: prlctl: command not found

How should I solve this problem？ tks

**Comment by ali-fareed** [comment]
Do you have Parallels installed?

**Comment by aze20** [comment]
> Do you have Parallels installed?

Not yet. I'm looking for how to install it

**Comment by ali-fareed** [comment]
Then start with step 1: https://core.telegram.org/reproducible-builds#step-1-install-the-parallels-virtual-machine

**Comment by aze20** [comment]
> Do you have Parallels installed?

I probably know that the construction instructions on the official website are based on virtual machines, but I am using MacOS and I don’t need to install Parallels.
I am still confused about how to use BAZEL to build an app

**Comment by ali-fareed** [comment]
If you are not planning to perform verifiable builds, you can just follow the instruction in README.

**Comment by aze20** [comment]
I already know how to use BAZEL to build .ipa files, so close this Issues.   ：）

> If you are not planning to perform verifiable builds, you can just follow the instruction in README.
