### ISSUE TITLE
Command PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by m1faridi** [TelegramMessenger/Telegram-iOS#52]
/Users/mac-developer/Library/Developer/Xcode/DerivedData/Telegram-iOS-fmzjepjovidblogotojnsyqbcjlj/Build/Intermediates.noindex/FFMpeg.build/DebugFork-iphonesimulator/FFMpeg.build/Script-D04554C821BF0F5E007A6DD9.sh: line 17: /Users/mac-developer/Desktop/untitled: No such file or directory
Command PhaseScriptExecution failed with a nonzero exit code

**Comment by shivanraptor** [comment]
Clean Build Folder and retry.

**Comment by m1faridi** [comment]
> Clean Build Folder and retry.

The issue could not be fixed

**Comment by Omid-Kia** [comment]
I'm having the same issue. cleaning the build folder didn't help.

**Comment by ali-fareed** [comment]
Please see the updated build instructions in README.md.
