### ISSUE TITLE
Telegram Passport doesn't work

### ISSUE THREAD

**Issue by leiniercs** [TelegramMessenger/Telegram-iOS#524]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [X] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
I'm unable to interact with Telegram Passport service on Telegram for iOS (I'm able on Telegram Desktop and Telegram for Android)

### Expected Behavior
I expect the same behavior of Telegram Desktop and Telegram Android in which I can interact with Telegram Passport service.

### Actual Behavior
I interact with my bot, I press the 'Authorize' button so the I can start to interact with Telegram Passport window, but, it never opens.

### Steps to Reproduce
1. I interact with my bot, and open the web page that shows me the 'Authorize' button (https://reputacionbot.ccari.net/autorizar_dev.html)
2. I press the 'Authorize' button so Telegram Passport window can open
3. Telegram Passport window never opens

### Environment
**Device:** `iPhone`

**iOS version**: `14.1`

**App version:** `7.6.2`

**Comment by leiniercs** [comment]
I made tests with Google Chrome and Mozilla Firefox in order to discard a problem with Apple Safari, but, the behavior is the same: Telegram Passport window doesn't open in Telegram for iOS.

**Comment by leiniercs** [comment]
![image](https://user-images.githubusercontent.com/44554001/115461552-8d076c00-a1f7-11eb-8293-1b4c905bb598.png)

**Comment by leiniercs** [comment]
That screenshot was on Mozilla Firefox.

**Comment by Askadias** [comment]
Are there any estimations on making telegram passport working on iOS teleggram client?

**Comment by pulyaev** [comment]
iOS still not fixed.
Mac OS client has “generic error”, after auth button pressed
Official Android client don't have passport in 

only windows client works.

**Comment by TiiFuchs** [comment]
Stumbled upon this today... Still doesn't seem to work.
Would be nice if this would be fixed soon.

**Comment by christianbm1** [comment]
@leiniercs Did you end up solving the issue? Can you point me towards a possible solution? Thanks!

**Comment by leiniercs** [comment]
@christianbm1 Nope. I didn't make it work. As for now, I don't even have an iPhone.

**Comment by shizhu-ourpalm** [comment]
Is there any plan to fix this issue? thanks :)
