### ISSUE TITLE
ask for help 

### ISSUE THREAD

**Issue by LightStronger** [TelegramMessenger/Telegram-iOS#528]
flutter@flutterdeiMac ~ % cd Telegram-iOS 
flutter@flutterdeiMac Telegram-iOS % python3 build-system/Make/Make.py \
    --bazel="$HOME/bazel-dist/bazel" \
    --cacheDir="$HOME/telegram-bazel-cache" \
    generateProject \
    --configurationPath="$HOME/telegram-configuration" \
    --disableExtensions \
    --disableProvisioningProfiles
No matching processes belonging to you were found
Starting local Bazel server and connecting to it...
INFO: Analyzed target //:tulsi (46 packages loaded, 567 targets configured).
INFO: Found 1 target...
Target //:tulsi up-to-date:
  bazel-bin/tulsi.zip
INFO: Elapsed time: 20.930s, Critical Path: 0.41s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
[Syslog] Tulsi CLI: version 0.20210120.88
[Syslog] Create project: Telegram
[Syslog] Fetching bazel path info
[Info] Running /Users/flutter/Telegram-iOS/build-input/gen/project/bazel info '--override_repository=tulsi=/Users/flutter/Library/Application Support/Tulsi/0.20210120.88/Bazel'
[Syslog] ** Completed bazel_get_package_path in 6.7963s
[Syslog] ** Completed get_package_path in 6.7973s
[Syslog] Fetching rules for packages ["Telegram"]
[Info] Running /Users/flutter/Telegram-iOS/build-input/gen/project/bazel --max_idle_secs=60 query '--override_repository=tulsi=/Users/flutter/Library/Application Support/Tulsi/0.20210120.88/Bazel' --announce_rc --noimplicit_deps --order_output=no --noshow_loading_progress --noshow_progress 'kind(rule, Telegram:all)' --output xml
[Syslog] ** Completed bazel_query_fetch_rules in 0.9080s
[Syslog] ** Completed fetch_rules in 0.9294s
[Syslog] Create config: Telegram
[Syslog] Tulsi CLI: version 0.20210120.88
Generating project into '/Users/flutter/Telegram-iOS/build-input/gen/project' using:
	config at '/Users/flutter/Telegram-iOS/build-input/gen/project/Telegram.tulsiproj/Configs/Telegram.tulsigen'
	Bazel workspace at '/Users/flutter/Telegram-iOS'
	Bazel at '/Users/flutter/Telegram-iOS/build-input/gen/project/bazel'.
This may take a while.
[Syslog] Fetching bazel path info
[Info] Running /Users/flutter/Telegram-iOS/build-input/gen/project/bazel info '--override_repository=tulsi=/Users/flutter/Library/Application Support/Tulsi/0.20210120.88/Bazel'
[Syslog] ** Completed bazel_get_package_path in 0.1689s
[Syslog] ** Completed get_package_path in 0.1698s
[Info] Build Events JSON file at "/var/folders/p_/jv35_4ys6b15fc29j8x201gh0000gn/T/build_events_889.json"
[Syslog] Extracting info for 1 rules
[Info] Running /Users/flutter/Telegram-iOS/build-input/gen/project/bazel build --announce_rc --show_result=0 --noshow_loading_progress --noshow_progress --symlink_prefix=/ --override_repository=build_configuration=/Users/flutter/telegram-configuration --//Telegram:disableExtensions --//Telegram:disableProvisioningProfiles --override_repository=build_configuration=/Users/flutter/telegram-configuration --announce_rc --features=swift.use_global_module_cache --verbose_failures --features=swift.enable_batch_mode --swiftcopt=-j5 --define=buildNumber=10000 --define=telegramVersion=7.7 --disk_cache=/Users/flutter/telegram-bazel-cache --//Telegram:disableExtensions --apple_platform_type=ios --cpu=ios_x86_64 --watchos_cpus=i386 --announce_rc '--override_repository=tulsi=/Users/flutter/Library/Application Support/Tulsi/0.20210120.88/Bazel' --compilation_mode=dbg --define=apple.add_debugger_entitlement=1 --define=apple.propagate_embedded_extra_outputs=1 --define=apple.experimental.tree_artifact_outputs=1 --features=debug_prefix_map_pwd_is_dot --tool_tag=tulsi:generator --build_event_json_file=/var/folders/p_/jv35_4ys6b15fc29j8x201gh0000gn/T/build_events_889.json --noexperimental_build_event_json_file_path_conversion --noexpand_test_suites --features=-parse_headers --experimental_run_validations=0 --aspects @tulsi//:tulsi/tulsi_aspects.bzl%tulsi_sources_aspect --output_groups=tulsi_info,-_,-default //Telegram:Telegram
[Syslog] ** Completed bazel_extract_source_info in 6.4922s
[Syslog] ** Completed extract_source_info in 6.6093s
[Syslog] ** Completed gathering_sources_for_indexers in 1.2281s
[Syslog] ** Completed generating_indexers in 0.1966s
[Syslog] ** Completed generating_clean_target in 0.0054s
[Info] Running /usr/bin/xcrun swift --version
[Syslog] ** Completed extract_default_swift_version in 1.0159s
[Syslog] ** Completed generating_top_level_build_configs in 1.0179s
[Syslog] ** Completed generating_build_targets in 0.0004s
[Syslog] ** Completed patching_bazel_relative_references in 0.2924s
[Syslog] ** Completed patching_external_repository_references in 0.0000s
[Syslog] ** Completed updating_dbgshellcommands in 0.0036s
2021-04-29 10:08:23.467 Tulsi[889:9469] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Couldn't posix_spawn: error 8'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff31bd5627 __exceptionPreprocess + 250
	1   libobjc.A.dylib                     0x00007fff6aab15bf objc_exception_throw + 48
	2   Foundation                          0x00007fff34298ee1 -[NSConcreteTask launchWithDictionary:error:] + 4993
	3   Tulsi                               0x00000001054034b9 $s14TulsiGenerator012XcodeProjectB0C20executePythonProcess017_3D27909A8CA7F8C4l11BE25046CB74K1BLL_7onErrorySS_ys5Int32V_SStctF + 1385
	4   Tulsi                               0x00000001053f6753 $s14TulsiGenerator012XcodeProjectB0C20cleanCachedDsymPaths017_3D27909A8CA7F8C4m11BE25046CB74L1BLLyyF + 99
	5   Tulsi                               0x00000001053f66db $s14TulsiGenerator012XcodeProjectB0C05buildcD13WithMainGroup017_3D27909A8CA7F8C4m11BE25046CB74L1BLL_18stubInfoPlistPathsAC09GenerateddQ0AELLVAA8PBXGroupC_AA04StubqrS0VtKFyyXEfU8_ + 27
	6   Tulsi                               0x00000001053f35af $s14TulsiGenerator012XcodeProjectB0C05buildcD13WithMainGroup017_3D27909A8CA7F8C4m11BE25046CB74L1BLL_18stubInfoPlistPathsAC09GenerateddQ0AELLVAA8PBXGroupC_AA04StubqrS0VtKF13profileActionL__6actionySS_yyKXEtKF + 383
	7   Tulsi                               0x00000001053e3bed $s14TulsiGenerator012XcodeProjectB0C05buildcD13WithMainGroup017_3D27909A8CA7F8C4m11BE25046CB74L1BLL_18stubInfoPlistPathsAC09GenerateddQ0AELLVAA8PBXGroupC_AA04StubqrS0VtKF + 8637
	8   Tulsi                               0x00000001053e01fa $s14TulsiGenerator012XcodeProjectB0C08generatecD8InFoldery10Foundation3URLVAGKF + 3242
	9   Tulsi                               0x00000001053d9cbd $s14TulsiGenerator0a12XcodeProjectB0C08generatecD8InFoldery10Foundation3URLVAGKF + 237
	10  Tulsi                               0x000000010549a84b $s5Tulsi0A23GeneratorConfigDocumentC28generateXcodeProjectInFolder_04withbC016workspaceRootURL10messageLog20projectInfoExtractorAC16GenerationResultO10Foundation0M0V_0aB00abC0CAmA07MessageO8Protocol_pSgAN0agqR0CSgtFZ + 1579
	11  Tulsi                               0x000000010543769a $s5Tulsi29HeadlessXcodeProjectGeneratorV8generateyyKF + 10410
	12  Tulsi                               0x00000001054cfcd3 $s5Tulsi4main33_54889CDB73DF4DC25B8AC2F5AB42D120LLyyFyycfU_ + 771
	13  Tulsi                               0x00000001052f4de0 $sIeg_IeyB_TR + 48
	14  libdispatch.dylib                   0x00007fff6bbff6c4 _dispatch_call_block_and_release + 12
	15  libdispatch.dylib                   0x00007fff6bc00658 _dispatch_client_callout + 8
	16  libdispatch.dylib                   0x00007fff6bc05c44 _dispatch_lane_serial_drain + 597
	17  libdispatch.dylib                   0x00007fff6bc065d6 _dispatch_lane_invoke + 363
	18  libdispatch.dylib                   0x00007fff6bc0fc09 _dispatch_workloop_worker_thread + 596
	19  libsystem_pthread.dylib             0x00007fff6be5aa3d _pthread_wqthread + 290
	20  libsystem_pthread.dylib             0x00007fff6be59b77 start_wqthread + 15
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Traceback (most recent call last):
  File "build-system/Make/Make.py", line 560, in <module>
    generate_project(arguments=args)
  File "build-system/Make/Make.py", line 363, in generate_project
    generate(
  File "/Users/flutter/Telegram-iOS/build-system/Make/ProjectGeneration.py", line 118, in generate
    call_executable([
  File "/Users/flutter/Telegram-iOS/build-system/Make/BuildEnvironment.py", line 60, in call_executable
    subprocess.check_call(resolved_arguments, env=resolved_env)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/flutter/Telegram-iOS/build-input/gen/project/Tulsi.app/Contents/MacOS/Tulsi', '--', '--verbose', '--genconfig', '/Users/flutter/Telegram-iOS/build-input/gen/project/Telegram.tulsiproj:Telegram', '--bazel', '/Users/flutter/Telegram-iOS/build-input/gen/project/bazel', '--outputfolder', '/Users/flutter/Telegram-iOS/build-input/gen/project', '--no-open-xcode']' died with <Signals.SIGABRT: 6>.
flutter@flutterdeiMac Telegram-iOS % git branch
* master
flutter@flutterdeiMac Telegram-iOS % 

### Environment
MacOS 10.15.7
Xcode 12.4
Thanks

**Comment by gosgos11** [comment]
the same error, how to fix it?
