### ISSUE TITLE
generated xcode project build fail

### ISSUE THREAD

**Issue by xujingming666** [TelegramMessenger/Telegram-iOS#532]
### Checklist
- [ *] I am reporting an issue in existing functionality that does not work as intended
- [ *] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
generated xcode project build fail. It seems that the generated xcode project is not for armv7/arm64. 

python3 build-system/Make/Make.py --bazel="/Users/zaoguan001/bazel-dist/bazel" --cacheDir="/Users/zaoguan001/telegram-bazel-cache" generateProject --configurationPath="/Users/zaoguan001/telegram-configuration"  --disableExtensions --disableProvisioningProfiles

after running  command above,  cpu x86 is configured by default to generated xcode project. 

[Info] Running /Users/zaoguan001/h5_app/Telegram-iOS/build-input/gen/project/bazel build --announce_rc --show_result=0 --noshow_loading_progress --noshow_progress --symlink_prefix=/ --override_repository=build_configuration=/Users/zaoguan001/telegram-configuration --//Telegram:disableExtensions --//Telegram:disableProvisioningProfiles --override_repository=build_configuration=/Users/zaoguan001/telegram-configuration --announce_rc --features=swift.use_global_module_cache --verbose_failures --features=swift.enable_batch_mode --swiftcopt=-j3 --define=buildNumber=10000 --define=telegramVersion=7.7 --disk_cache=/Users/zaoguan001/telegram-bazel-cache --//Telegram:disableExtensions **--apple_platform_type=ios --cpu=ios_x86_64 --watchos_cpus=i386** --announce_rc '--override_repository=tulsi=/Users/zaoguan001/Library/Application Support/Tulsi/0.20210120.88/Bazel' --compilation_mode=dbg --define=apple.add_debugger_entitlement=1 --define=apple.propagate_embedded_extra_outputs=1 --define=apple.experimental.tree_artifact_outputs=1 --features=debug_prefix_map_pwd_is_dot --tool_tag=tulsi:generator --build_event_json_file=/var/folders/dl/m9wc2z6s6x9_3kctg6wkvdqw0000gn/T/build_events_31914.json --noexperimental_build_event_json_file_path_conversion --noexpand_test_suites --features=-parse_headers --experimental_run_validations=0 --aspects @tulsi//:tulsi/tulsi_aspects.bzl%tulsi_sources_aspect --output_groups=tulsi_info,-_,-default //Telegram:Telegram

How Can change the default setting to arm?

### Expected Behavior
generated xcode project build ok

### Actual Behavior

Showing All Messages
Telegram-iOS/third-party/libvpx/BUILD:28:8: Executing genrule //third-party/libvpx:libvpx_build failed: (Exit 1): bash failed: error executing command

### Environment
**Device:** `iPhone/iPad X`

**iOS version**: `13.X`

**App version:** `7.X`

**Comment by IcedOtaku** [comment]
have you tried this
`brew install yasm`

**Comment by xujingming666** [comment]
Thanks. It works.

**Comment by sysbol** [comment]
Hello, my problem is the same as yours. How can you solve it? Thank you #534
