### ISSUE TITLE
build 7.7 failed 

### ISSUE THREAD

**Issue by sysbol** [TelegramMessenger/Telegram-iOS#534]
Use the following instructions，Generate an Xcode project.

python3 build-system/Make/Make.py \
    --bazel="$HOME/bazel-dist/bazel" \
    --cacheDir="$HOME/telegram-bazel-cache" \
    generateProject \
    --configurationPath="$HOME/telegram-configuration" \
    --disableExtensions \
    --disableProvisioningProfiles

Use the simulator to run, there are four errors, such as screenshot
<img width="1556" alt="截屏2021-05-19 下午2 20 05" src="https://user-images.githubusercontent.com/6174835/118768604-ca701f80-b8b1-11eb-8feb-79d9a7aaacf9.png">

**Comment by sysbol** [comment]
It's finally working

**Comment by zeinali0** [comment]
Are you building project on M1 mac?

**Comment by cfcor** [comment]
@sysbol I met the same error, what did you do to fix it?
