### ISSUE TITLE
On the issue of building bazel paths

### ISSUE THREAD

**Issue by liuleiai1** [TelegramMessenger/Telegram-iOS#536]
Hello, I want to know how to change the path of bazel-dist so that it can be easily transplanted to others after the build is completed.If I put the path of bazel in the same path of the project, the build fails

![image](https://user-images.githubusercontent.com/34733405/118581375-193f8b80-b7c4-11eb-92e2-7b92f93d44f3.png)

**Comment by ali-fareed** [comment]
Please provide the build log with an error.
