### ISSUE TITLE
7.7 Build the app error

### ISSUE THREAD

**Issue by FranZhou** [TelegramMessenger/Telegram-iOS#537]
python3 build-system/Make/Make.py \
    --bazel="$HOME/bazel-dist/bazel" \
    --cacheDir="$HOME/telegram-bazel-cache" \
    build \
    --configurationPath="$HOME/telegram-configuration" \
    --buildNumber=100001 \
    --configuration=release_universal

TelegramBuild: running
/Users/Fran/bazel-dist/bazel build Telegram/Telegram --override_repository=build_configuration=/Users/Fran/telegram-configuration --announce_rc --features=swift.use_global_module_cache --verbose_failures --features=swift.skip_function_bodies_for_derived_files --jobs=4 --define=buildNumber=100001 --define=telegramVersion=7.7 --features=swift.split_derived_files_generation --disk_cache=/Users/Fran/telegram-bazel-cache -c opt --ios_multi_cpus=armv7,arm64 --watchos_cpus=armv7k,arm64_32 --apple_generate_dsym --output_groups=+dsyms --features=swift.opt_uses_wmo --features=swift.opt_uses_osize --swiftcopt=-num-threads --swiftcopt=0 --features=dead_strip --objc_enable_binary_stripping --apple_bitcode=watchos=embedded
INFO: Invocation ID: 4c1f1fa2-25c6-495b-8ec3-5a775461e1b3
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=80
INFO: Reading rc options for 'build' from /Users/Fran/Desktop/workplace/Telegram-iOS-master/.bazelrc:
  'build' options: --action_env=ZERO_AR_DATE=1 --apple_platform_type=ios --cxxopt=-std=c++14 --per_file_copt=third-party/webrtc/.*.cpp$,@-std=c++14 --per_file_copt=third-party/webrtc/.*.cc$,@-std=c++14 --per_file_copt=third-party/webrtc/.*.mm$,@-std=c++14 --features=debug_prefix_map_pwd_is_dot --features=swift.cacheable_swiftmodules --features=swift.debug_prefix_map --features=swift.enable_vfsoverlays --strategy=Genrule=standalone --spawn_strategy=standalone --strategy=SwiftCompile=standalone --define RULES_SWIFT_BUILD_DUMMY_WORKER=1
ERROR: Error fetching repository: java.io.IOException: No WORKSPACE file found in /private/var/tmp/_bazel_root/75c6d7880cb7c71e1b03cb7e4f0c724d/external/build_bazel_rules_apple
ERROR: no such package '@build_bazel_rules_apple//apple': No WORKSPACE file found in /private/var/tmp/_bazel_root/75c6d7880cb7c71e1b03cb7e4f0c724d/external/build_bazel_rules_apple
INFO: Elapsed time: 0.406s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
Traceback (most recent call last):
  File "build-system/Make/Make.py", line 562, in <module>
    build(arguments=args)
  File "build-system/Make/Make.py", line 392, in build
    bazel_command_line.invoke_build()
  File "build-system/Make/Make.py", line 294, in invoke_build
    call_executable(combined_arguments)
  File "/Users/Fran/Desktop/workplace/Telegram-iOS-master/build-system/Make/BuildEnvironment.py", line 60, in call_executable
    subprocess.check_call(resolved_arguments, env=resolved_env)
  File "/Users/Fran/anaconda3/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/Fran/bazel-dist/bazel', 'build', 'Telegram/Telegram', '--override_repository=build_configuration=/Users/Fran/telegram-configuration', '--announce_rc', '--features=swift.use_global_module_cache', '--verbose_failures', '--features=swift.skip_function_bodies_for_derived_files', '--jobs=4', '--define=buildNumber=100001', '--define=telegramVersion=7.7', '--features=swift.split_derived_files_generation', '--disk_cache=/Users/Fran/telegram-bazel-cache', '-c', 'opt', '--ios_multi_cpus=armv7,arm64', '--watchos_cpus=armv7k,arm64_32', '--apple_generate_dsym', '--output_groups=+dsyms', '--features=swift.opt_uses_wmo', '--features=swift.opt_uses_osize', '--swiftcopt=-num-threads', '--swiftcopt=0', '--features=dead_strip', '--objc_enable_binary_stripping', '--apple_bitcode=watchos=embedded']' returned non-zero exit status 1.

**Comment by sysbol** [comment]
What version of Xcode do you have
Can you run the simulator?

**Comment by FranZhou** [comment]
xcode 12.5
can run the simulator
can't run my iphone

**Comment by michaeleisel** [comment]
having the same problem

**Comment by ali-fareed** [comment]
Run `git submodule update --init`.
