### ISSUE TITLE
Change service

### ISSUE THREAD

**Issue by sysbol** [TelegramMessenger/Telegram-iOS#538]
In which configuration file to replace the server address, we want to put chat records on our own server

**Comment by ali-fareed** [comment]
Network.swift, `seedAddressList`.

**Comment by ldu1101** [comment]
> Network.swift, `seedAddressList`.

hello，i change server, but it not worked

<img width="1169" alt="image" src="https://user-images.githubusercontent.com/12520900/216903128-6ddb254d-4fd5-4556-a2d1-2f366540482f.png">

this is error log

[MTTcpConnection#7fa54cd0f1b0 disconnected from 35.78.243.112]
[MT] 2023-2-6 14:51:12.530 [MTContext has chosen a scheme for DC1: tcp://35.78.243.112:10443 (media: no, cdn: no, static: no, secret: (null)) (media: no)]
[MT] 2023-2-6 14:51:12.530 [MTProto#0x6000011e4340@0x6000016dc100 transport #0x600000eda760 connection state: connecting]
[MT] 2023-2-6 14:51:12.530 [MTTcpConnection#7fa54cc0cf30 connecting to 35.78.243.112:10443]
[MT] 2023-2-6 14:51:12.580 Connection time: 48.409939 ms, interface: Wifi
[MT] 2023-2-6 14:51:12.580 [MTProto#0x6000011e4340@0x6000016dc100 transport #0x600000eda760 connection state: connected]
[MT] 2023-2-6 14:51:12.581 [MTDatacenterAuthMessageService#0x6000018e6640 mtProto#0x6000011e4340 (media: false) mtProtoMessageTransaction scheme:tcp://35.78.243.112:10443 (media: no, cdn: no, static: no, secret: (null)) (media: no)]
[MT] 2023-2-6 14:51:12.628 [MTProto#0x6000011e4340@0x6000016dc100 [84] received res_pq nonce:{length = 16, bytes = 0x8659e2d575a2d743f6de87c2960bf416} serverNonce:{length = 16, bytes = 0x352f7ed99af2d7ae95690caab5547426} pq:{length = 8, bytes = 0x17ed48941a08f981} fingerprints:a9e071c1771060cd (7196931837980975813, 0/0)]
[MT] 2023-2-6 14:51:12.628 [MTDatacenterAuthMessageService#0x6000018e6640 couldn't find valid server public key]
[MT] 2023-2-6 14:51:12.629 [MTDatacenterAuthMessageService#0x6000018e6640 mtProto#0x6000011e4340 (media: false) mtProtoMessageTransaction scheme:tcp://35.78.243.112:10443 (media: no, cdn: no, static: no, secret: (null)) (media: no)]

can you help me?
