### ISSUE TITLE
Error after running the program

### ISSUE THREAD

**Issue by m1faridi** [TelegramMessenger/Telegram-iOS#54]
![Screen Shot 2019-05-30 at 7 16 19 AM](https://user-images.githubusercontent.com/7335680/58639222-6494c280-82ab-11e9-9014-143b0c0d2f66.png)

**Comment by shivanraptor** [comment]
which release are you working on?

**Comment by m1faridi** [comment]
telegram-ios-fork

**Comment by m1faridi** [comment]
fixed
[https://dev.tail0r.com/remove-telegram-channel-restriction/](url)

**Comment by shivanraptor** [comment]
this is not the solution to your issue.
