### ISSUE TITLE
Error when validating archive

### ISSUE THREAD

**Issue by bohlool** [TelegramMessenger/Telegram-iOS#542]
My app runs on devices and simulators. The app archives with no errors. After I archive my project and try to validate or submit to the app store I get the error: "The archive contains nothing that can be signed. Verify that your build process has compiled binaries and copied in bundled resources."

How do I fix this?

**Comment by ali-fareed** [comment]
Using Xcode for building distribution archives is not supported. Please follow README to generate a valid .ipa file.
