### ISSUE TITLE
telegram Build did NOT complete successfully

### ISSUE THREAD

**Issue by wwwaqu** [TelegramMessenger/Telegram-iOS#544]
### Checklist
- [ ] I am reporting an issue in existing functionality that does not work as intended
- [ ] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
According to the official documents:BAZEL="$HOME/bazel-dist/bazel" sh buildbox/build-telegram.sh verify

### Expected Behavior
telegram.ipa

### Actual Behavior
/Users/telegram/telegram-ios/Telegram/BUILD:527:18: Processing and signing TelegramWatchExtension failed: (Exit 1): process-and-sign-1202728910.sh failed: error executing command 
(cd /private/var/tmp/_bazel_telegram/6f1b77c1cc8a191cdd17347091e2ce74/execroot/__main__ && \
exec env - \
APPLE_SDK_PLATFORM=WatchOS \
APPLE_SDK_VERSION_OVERRIDE=7.2 \
XCODE_VERSION_OVERRIDE=12.4.0.12D4e \
bazel-out/applebin_watchos-watchos_armv7k-opt-ST-58153144368d/bin/Telegram/TelegramWatchExtension-intermediates/process-and-sign-1202728910.sh should_sign should_compress)
Execution platform: @local_config_platform//:host
ERROR: Unable to find an identity on the system matching the ones in external/build_configuration/provisioning/WatchExtension.mobileprovision
Target //Telegram:Telegram failed to buil

### Steps to Reproduce
1. BAZEL="$HOME/bazel-dist/bazel" sh buildbox/build-telegram.sh verify

### Environment
macOS Big sur11.3.1
Xcode 12.4
Telegram 7.6

**Comment by ali-fareed** [comment]
Have you set up a Parallels virtual machine as directed in the documentation?

**Comment by lbjhzj** [comment]
@wwwaqu have you solve this problem?  I meet the same one..

**Comment by lzdtech** [comment]
@wwwaqu have you solve this problem? I meet the same one..

**Comment by jingsongshen** [comment]
> have you solve this problem? I meet the same one..

@lzdtech have you solve this problem? I meet the same one..

**Comment by maque123** [comment]
@wwwaqu have you solve this problem? I meet the same one..

**Comment by maque123** [comment]
@jingsongshen  have you solve this problem? I meet the same one..

**Comment by maque123** [comment]
@wwwaqu @jingsongshen have you solve this problem? I meet the same one..
