### ISSUE TITLE
Build did NOT complete successfully(v7.7)?

### ISSUE THREAD

**Issue by liangshiyi** [TelegramMessenger/Telegram-iOS#547]
/Users/firefox/Desktop/Telegram-Swift/Telegram-iOS/third-party/libvpx/BUILD:28:8: Executing genrule //third-party/libvpx:libvpx_build failed: (Exit 1): bash failed: error executing command 
/Users/firefox/Desktop/Telegram-Swift/Telegram-iOS/Telegram/BUILD:207:14 Compiling Swift module Telegram_Lib failed: (Exit 1): bash failed: error executing command 

How to solve these two problems？

**Comment by ali-fareed** [comment]
As temporary workaround, install yasm via homebrew: `brew install yasm`. The issue is fixed in the upcoming update.

**Comment by liangshiyi** [comment]
I have installed it earlier, but the problem is still not solved. Does anything need to be done to make yasm work.

**Comment by cfcor** [comment]
> I have installed it earlier, but the problem is still not solved. Does anything need to be done to make yasm work.

I met the same error,did you sovle it?

**Comment by hecanlin** [comment]
> 

Hello, I also encountered the same problem, seek a solution, thank you

**Comment by cfcor** [comment]
Sorry, I have not solve the problem yet, I also seek a solution. Do you
solve this problem? My telegram is (+852)65694517 Jack Gates, for deep
cooperation, thanks.

čt 16. 12. 2021 v 15:58 odesílatel 贺灿林 ***@***.***> napsal:
