### ISSUE TITLE
After switching to telegram, socks5 proxy is unusable

### ISSUE THREAD

**Issue by kzhui125** [TelegramMessenger/Telegram-iOS#55]
I hear that Telegram X ios has been discontinued. So I uninstalled Telegram X iOS, and switched to Telegram app.

But I can’t use socks5 proxy now using Telegram app. It takes many seconds to connecting proxy every time When I open the Telegram app (the same as telegram mac app, but telegram-desktop mac app is fast to connect socks5 proxy) It’s very very very unusable now. When I used Telegram X for iOS, it takes less than 1 seconds connecting to socks5 proxy every time the app is opened.

**Comment by laktyushin** [comment]
Same as #63. Closing this one because the other has more info.
