### ISSUE TITLE
v7.7 issue

### ISSUE THREAD

**Issue by liangshiyi** [TelegramMessenger/Telegram-iOS#550]
### Compile environment
+ Python3.8
+ Xcode12.5
### Build the app
```
python3 build-system/Make/Make.py \
    --bazel="$HOME/bazel-dist/bazel" \
    --cacheDir="$HOME/telegram-bazel-cache" \
    build \
    --configurationPath="$HOME/telegram-configuration" \
    --buildNumber=100001 \
    --configuration=release_universal
```

##### ERROR: /Users/firefox/Desktop/Telegram-Swift/Telegram-iOS/Telegram/BUILD:1138:14 Compiling Swift module NotificationContentExtensionLib failed: (Exit 1): bash failed: error executing command 
-----------
### Generate an Xcode project
```
python3 build-system/Make/Make.py \
    --bazel="$HOME/bazel-dist/bazel" \
    --cacheDir="$HOME/telegram-bazel-cache" \
    generateProject \
    --configurationPath="$HOME/telegram-configuration" \
    --disableExtensions
```
/Users/firefox/Desktop/Telegram-Swift/Telegram-iOS/third-party/libvpx/BUILD:28:8: Executing genrule //third-party/libvpx:libvpx_build failed: (Exit 1): bash failed: error executing command 
/Users/firefox/Desktop/Telegram-Swift/Telegram-iOS/Telegram/BUILD:207:14 Compiling Swift module Telegram_Lib failed: (Exit 1): bash failed: error executing command 

bazel_build.py:579
if exit_code:
      _Fatal('Bazel build failed with exit code %d. Please check the build '
             'log in Report Navigator (⌘9) for more information.'
             % exit_code)
Bazel build failed with exit code 1. Please check the build log in Report Navigator (⌘9) for more information.

How to solve thes issue？

**Comment by hecanlin** [comment]
Hello, I also encountered the same problem, seek a solution, thank you
