### ISSUE TITLE
failed: class javax.net.ssl.SSLException Read timed out

### ISSUE THREAD

**Issue by slsyswift** [TelegramMessenger/Telegram-iOS#552]
swf@s-w-1 Telegram-iOS % python3 build-system/Make/Make.py \
    --bazel="$HOME/bazel-dist/bazel" \
    --cacheDir="$HOME/telegram-bazel-cache" \
    generateProject \
    --configurationPath="$HOME/telegram-configuration" \
    --disableExtensions

No matching processes belonging to you were found
Starting local Bazel server and connecting to it...
INFO: Repository build_bazel_rules_apple instantiated at:
  /Users/swf/Telegram-iOS/build-system/tulsi/WORKSPACE:3:13: in <toplevel>
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_swf/f73444c2e78cf9f55da2b32df51ead83/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
WARNING: Download from https://github.com/bazelbuild/rules_apple/releases/download/0.21.1/rules_apple.0.21.1.tar.gz failed: class javax.net.ssl.SSLException Read timed out
ERROR: An error occurred during the fetch of repository 'build_bazel_rules_apple':
   Traceback (most recent call last):
	File "/private/var/tmp/_bazel_swf/f73444c2e78cf9f55da2b32df51ead83/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/bazelbuild/rules_apple/releases/download/0.21.1/rules_apple.0.21.1.tar.gz] to /private/var/tmp/_bazel_swf/f73444c2e78cf9f55da2b32df51ead83/external/build_bazel_rules_apple/temp9233125245930759810/rules_apple.0.21.1.tar.gz: Read timed out
ERROR: Error fetching repository: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_swf/f73444c2e78cf9f55da2b32df51ead83/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/bazelbuild/rules_apple/releases/download/0.21.1/rules_apple.0.21.1.tar.gz] to /private/var/tmp/_bazel_swf/f73444c2e78cf9f55da2b32df51ead83/external/build_bazel_rules_apple/temp9233125245930759810/rules_apple.0.21.1.tar.gz: Read timed out
ERROR: no such package '@build_bazel_rules_apple//apple': java.io.IOException: Error downloading [https://github.com/bazelbuild/rules_apple/releases/download/0.21.1/rules_apple.0.21.1.tar.gz] to /private/var/tmp/_bazel_swf/f73444c2e78cf9f55da2b32df51ead83/external/build_bazel_rules_apple/temp9233125245930759810/rules_apple.0.21.1.tar.gz: Read timed out
INFO: Elapsed time: 181.223s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
Traceback (most recent call last):
  File "build-system/Make/Make.py", line 560, in <module>
    generate_project(arguments=args)
  File "build-system/Make/Make.py", line 363, in generate_project
    generate(
  File "/Users/swf/Telegram-iOS/build-system/Make/ProjectGeneration.py", line 37, in generate
    call_executable(tulsi_build_command)
  File "/Users/swf/Telegram-iOS/build-system/Make/BuildEnvironment.py", line 60, in call_executable
    subprocess.check_call(resolved_arguments, env=resolved_env)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/swf/bazel-dist/bazel', 'build', '//:tulsi', '--xcode_version=12.4', '--use_top_level_targets_for_symlinks', '--verbose_failures']' returned non-zero exit status 1.

**Comment by slsyswift** [comment]
How to solve thes issue？

**Comment by JoinSugar** [comment]
The same problem. Have you solved it?

**Comment by ali-fareed** [comment]
Try running `curl https://github.com/bazelbuild/rules_apple/releases/download/0.21.1/rules_apple.0.21.1.tar.gz` manually.
