### ISSUE TITLE
Adopt Communication Notifications in iOS 15

### ISSUE THREAD

**Issue by gracjankn** [TelegramMessenger/Telegram-iOS#556]
iOS 15 adds new notification types. One of them is Communication Notifications. They a big profile picture of the sender and a small app icon in the corner. This is different to standard notification which only display the icon.

The behavior is also different, because the user can select individual people that they want to see messages from when the device is in each given Focus mode (without allowing notifications from a specific app), they don't end up in the Notification Summary and they are read by default if Siri Announce Notifications feature is enabled on device.

For more details see [Apple Human Interface Guidelines on Notifications](https://developer.apple.com/design/human-interface-guidelines/ios/system-capabilities/notifications).

**Comment by thebluepotato** [comment]
Apparently has been implemented in Telegram version 8.2, released on Nov 3.

**Comment by thebluepotato** [comment]
The lack of communication and updates from the developers is quite problematic though. The repo is months behind the latest releases. Telegram is basically developed closed-source now, with Github being used sporadically to show code updates and collect user feedback. This is not open-source development...

**Comment by gracjankn** [comment]
> The lack of communication and updates from the developers is quite problematic though.

I agree, they should totally work on establishing a regular and open conversation with users and contributors. Anybody remember the watchOS app contest? It started in March. The [results for round 3](https://t.me/contest/271) were published on August 16th and since then nothing. We don't even know if it's the last round, let alone any information about how and when will the winning project be made into the official version of the app for the Apple Watch.

The watchOS version of the app it's a perfect example of what you pointed out. People have been complaining about it for years and rightfully so, because Telegram on the Apple Watch is awful on many levels. They finally announced a contest, but we still see overly long periods between the deadlines for submissions for a specific round and the announcing of winners, they aren't clear on whatever this is the last round, etc. In the summer a single developer frustrated with all the waiting created [Nanogram](https://apps.apple.com/us/app/nanogram-watch-messenger/id1574130405), which although lacking a few features, is much, much faster and more reliable and works without the iPhone.

If you're making an open-source project, you should act like it. The amount of appreciation I have for Telegram in general only deepens my frustration when something obvious needs to be done — like adopting this API which luckily happened or fixing the watchOS which doesn't seem to have an end — and we only receive silence from the other side.

**Comment by maurice-schleussinger** [comment]
> Apparently has been implemented in Telegram version 8.2, released on Nov 3.

You are talking about the official Telegram app as it is available in the App Store? Because I can find no mention of support for focus mode in Telegram in any of the release notes and as far as I can see the features isn't implemented as of now.

**Comment by kecinzer** [comment]
> > Apparently has been implemented in Telegram version 8.2, released on Nov 3.
> 
> You are talking about the official Telegram app as it is available in the App Store? Because I can find no mention of support for focus mode in Telegram in any of the release notes and as far as I can see the features isn't implemented as of now.

This issue is not about focus mode, but about notification icons.

**Comment by thebluepotato** [comment]
To clarify (and I think this is all linked to #665), Telegram _did_ implement Communication Notifications (hence the new notification design) but it seems the contact-identification part is not fully implemented. It seems the system is unable to associate the sender with a contact in the Contacts app. Even though the name is correct, I think the Telegram code (see TelegramsIntents.swift) does not include the phone number in the INSendMessageIntent it donates (or the Telegram ID is not associated with the Contact, I'm not sure). Therefore, iOS does recognise all Telegram notifications as chat messages, but doesn't "understand" that these are your contacts (it's thus treated more like Discord with unknown people than a messaging app).

**Comment by kecinzer** [comment]
So what is conclusion about focus mode? Will be supported?

**Comment by devasworski** [comment]
Support for focus is a absolute must! Can somebody please fix this?

**Comment by maurice-schleussinger** [comment]
For those who ask about Telegram supporting Focus mode: As was clarified above, this issue here (#556) is not about that. You could either create a new issue here on Github and see if there is a response, or use the platform Telegram provides for suggestions: https://bugs.telegram.org/?type=suggestions&sort=rate&query=focus.

**Comment by tStaiger** [comment]
Alright, created a new Issue for exactly that: https://github.com/TelegramMessenger/Telegram-iOS/issues/839
