### ISSUE TITLE
Navigation bar is transparent.

### ISSUE THREAD

**Issue by Thoufak** [TelegramMessenger/Telegram-iOS#557]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
The navigation bar in an opened dialog/chat/channel is transparent. I encountered this after updating to the latest version.

### Expected Behavior
The navigation bar is not trasparent. 

### Steps to Reproduce
1. Open a dialog/chat/channel.

### Screenshots and Videos 
https://user-images.githubusercontent.com/40132582/123461674-0eadb880-d5f2-11eb-80d4-aa0a90b4b3c0.MP4

### Environment
**Device:** `iPhone SE 2020`

**iOS version**: `13.4.1`

**App version:** `7.8 (21399)`

**Comment by ali-fareed** [comment]
Have you ever used the in-app Debug menu?

**Comment by Thoufak** [comment]
> Have you ever used the in-app Debug menu?

Yes, I have. Why?

**Comment by minsk21** [comment]
I have this problem too

**Comment by ali-fareed** [comment]
@Thoufak we don't provide support for any non-default configuration of the Debug menu settings.

**Comment by Thoufak** [comment]
> @Thoufak we don't provide support for any non-default configuration of the Debug menu settings.

Can I reset the configuration to default without reinstalling the app?

**Comment by minsk21** [comment]
Bug not fixed.
Telegram 7.8.1 (21429)

**Comment by minsk21** [comment]
> we don't provide support for any non-default configuration

A very convenient excuse not to work.

**Comment by minsk21** [comment]
> we don't provide support for any non-default configuration of the Debug menu
Used the Debug menu != change settings Debug menu.
Your position is very comfortable. Those who don't know about the debug menu don't know about GitHub. The error may not be corrected for formal reasons.
