### ISSUE TITLE
Not able to build the app on XCode 12.5

### ISSUE THREAD

**Issue by sreedeeppaul** [TelegramMessenger/Telegram-iOS#559]
When i try to generate the XCode project on my simulator using latest XCode (official)

python3 build-system/Make/Make.py \
    --bazel="$HOME/bazel-dist/bazel" \
    --cacheDir="$HOME/telegram-bazel-cache" \
    generateProject \
    --configurationPath="$HOME/telegram-configuration" \
    --disableExtensions

I get this error
Required Xcode version is 12.4, but 12.5 is reported by 'xcode-select -p'

**Comment by Pikdays** [comment]
pikdays@PikdaysMacBook-Pro Telegram-iOS % python3 build-system/Make/Make.py \
    --overrideXcodeVersion  \                                        
    --bazel="$HOME/bazel-dist/bazel" \
    --cacheDir="$HOME/telegram-bazel-cache" \
    generateProject \
    --configurationPath="$HOME/telegram-configuration" \
    --disableProvisioningProfiles
Overriding the required Xcode version 12.4 with 12.5.1 as reported by 'xcode-select -p'
No matching processes belonging to you were found
ERROR: Error fetching repository: java.io.IOException: No WORKSPACE file found in /private/var/tmp/_bazel_pikdays/c07dc2d226f40ecf8ae3c44f800e3e93/external/build_bazel_rules_apple
ERROR: no such package '@build_bazel_rules_apple//apple': No WORKSPACE file found in /private/var/tmp/_bazel_pikdays/c07dc2d226f40ecf8ae3c44f800e3e93/external/build_bazel_rules_apple
INFO: Elapsed time: 0.130s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
Traceback (most recent call last):
  File "/Users/pikdays/Telegram-iOS/build-system/Make/Make.py", line 613, in <module>
    generate_project(arguments=args)
  File "/Users/pikdays/Telegram-iOS/build-system/Make/Make.py", line 385, in generate_project
    generate(
  File "/Users/pikdays/Telegram-iOS/build-system/Make/ProjectGeneration.py", line 37, in generate
    call_executable(tulsi_build_command)
  File "/Users/pikdays/Telegram-iOS/build-system/Make/BuildEnvironment.py", line 60, in call_executable
    subprocess.check_call(resolved_arguments, env=resolved_env)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/pikdays/bazel-dist/bazel', 'build', '//:tulsi', '--xcode_version=12.5.1', '--use_top_level_targets_for_symlinks', '--verbose_failures']' returned non-zero exit status 1.
pikdays@PikdaysMacBook-Pro Telegram-iOS %

**Comment by paragdulam** [comment]
Go to versions.json file which is in the root folder of the Telegram-iOS folder post cloning and change the version to current installed version of Xcode.
