### ISSUE TITLE
Chat list animations and text input in rtl

### ISSUE THREAD

**Issue by immmdreza** [TelegramMessenger/Telegram-iOS#560]
### Checklist
- [ ✅] I am reporting an issue in existing functionality that does not work as intended
- [✅ ] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

# 1  Chat lists animations 
### Description
There is no animations on chat lists when changing order ( Reduce Motion is off )

### Expected Behavior
The newly updated chat should jump to the first smoothly 

### Actual Behavior
The newly updated chats replaced instantly 

# 2 Blinker text input pointer in RTL
### Description
text input pointer is on stickers menu button
when typing in RTL, it should be next to it.

### Screenshots and Videos 
https://user-images.githubusercontent.com/47322990/123545510-99ff8900-d76d-11eb-8e5c-f34328892e7a.mov

### Environment
**Device:** `iPhone/iPad X`

**iOS version**: `14.X`

**App version:** `7.8.1`

**Comment by ali-fareed** [comment]
Please split the issue into two separate entries as they are not related to each other.
