### ISSUE TITLE
Transparent Title Bar

### ISSUE THREAD

**Issue by pavlovcik** [TelegramMessenger/Telegram-iOS#565]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
Describe the issue that you are experiencing

On my iPhone X this is okay, but on my iPhone 12 Mini the title bar is transparent. The chat text collides. 

### Expected Behavior
Tell us what should happen

### Actual Behavior
Tell us what happens instead

### Steps to Reproduce
1. 
2. 
3. 

### Screenshots and Videos 

![image](https://user-images.githubusercontent.com/4975670/123561483-1eeaa280-d76e-11eb-95f7-1c8e099e8266.png)

![image](https://user-images.githubusercontent.com/4975670/123561566-ba7c1300-d76e-11eb-935a-c2eae3d4e127.png)

### Environment
**Device:** `iPhone/iPad X`

iPhone 12 Mini

**iOS version**: `13.X`

14.6

**App version:** `7.X`

7.8 (21399)

**Comment by minsk21** [comment]
#557

**Comment by pavlovcik** [comment]
It's "player embedding" causing this. 




![image](https://user-images.githubusercontent.com/4975670/123852947-80338280-d8e2-11eb-925b-2389ec75b793.png)

**Comment by Thoufak** [comment]
> It's "player embedding" causing this.
> 
> ![image](https://user-images.githubusercontent.com/4975670/123852947-80338280-d8e2-11eb-925b-2389ec75b793.png)

Thanks for telling this! It solved the issue for me too.
