### ISSUE TITLE
I need tutorial for custom new module

### ISSUE THREAD

**Issue by lexuanquynh** [TelegramMessenger/Telegram-iOS#566]
I create a my submodule, and I want to add into exist telegram source code. 
The forder is:
Telegram-iOS/submodules/QModule
contains:
- QViewController.xib
- QViewController.swift
My script in BUILD file is:

```python
load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library")

swift_library(
    name = "QModule",
    module_name = "QModule",
    srcs = glob([
	"Sources/**/*.swift",
   	"Sources/**/*.xib",
    ]),    
    visibility = [
        "//visibility:public",
    ],
)
```

When I run generate with script:

```python
python3 build-system/Make/Make.py \
    --bazel="$HOME/bazel-dist/bazel" \
    --cacheDir="$HOME/telegram-bazel-cache" \
    generateProject \
    --configurationPath="$HOME/telegram-configuration" \
    --disableExtensions \
    --disableProvisioningProfiles
```
It build success. But I can't find my module. What step am I missed?

**Comment by matt59631** [comment]
X

**Comment by ali-fareed** [comment]
How are you planning to use this module?

**Comment by lexuanquynh** [comment]
@ali-fareed I want add the UIViewcontroller into the Telegram Tabbar. I try to custom a new viewcontroller. I naively thought that adding was simply creating a directory in submodules, and writing Bazel scripts. It built successfully, but it's not contain in the Xcode project. What step was I missing? Can you help me?

**Comment by ali-fareed** [comment]
I'm afraid it would take a lot of effort to describe the general architecture of the app.

I would recommend reading https://hubo.dev/tags/#Telegram

**Comment by lexuanquynh** [comment]
@ali-fareed thank you very much. I think having this source code for research is the best thing a dev has.

**Comment by Kylmakalle** [comment]
> `.xib`

Unfrotunatelly you will not be able to use Storyboards due to [AsynkDisplayKit restrictions](https://github.com/facebookarchive/AsyncDisplayKit/issues/132) which is (partially) used in Telegram sources.


I've made some attempts to integrate some basic UIVeiwControllers and additional tab bar icons in app, but unfortunatelly whole project is based on custom ViewControllers (mostly based on AsynKDisplayKit stuff) and it requires a lot of work to adapt them (edges, colors, swipes, navigation and etc.)

So I assume it's relly better to integrate something based on AsyncDisplayKit

> **NB:** Check [this post ](https://hubo.dev/2020-06-14-source-code-walkthrough-of-telegram-ios-part-5/) as well to make sure that you have enough framework modules to create your Views.

**Comment by Kylmakalle** [comment]
>  But I can't find my module.

Try to declare your module as a dependency for other module (eg. submodules/TelegramUI/BUILD) or in main app file (Telegram-iOS/BUILD)

Also, take a look at [Nicegram example](https://github.com/nicegram/Telegram-iOS/blob/master/submodules/TelegramUI/BUILD#L42)

**Comment by lexuanquynh** [comment]
@Kylmakalle thank you very much. Can you give me your telegram or twitter?

**Comment by Kylmakalle** [comment]
Telegram Is the same as on github
