### ISSUE TITLE
Share image with caption from other apps via UIActivityViewController

### ISSUE THREAD

**Issue by Banck** [TelegramMessenger/Telegram-iOS#569]
Hello!
Currently, when share UIImage + String/URL via UIActivityViewController - telegram sends two messages: one with image and another one with text.
It will be cool, if tg could create one image message with caption in this case

**Comment by VetaLioSTV** [comment]
Actually is not a bug, but flow which was from design. It discussed many times here https://bugs.telegram.org/. Workaround -> Send image and than edit it with corresponding text(as result expected behaviour as one message with caption text)

**Comment by vfsoraki** [comment]
Since this is not yet closed, I'm gonna second this. I haven't read the bugs yet, but I also think it is better to use the text as caption instead of a second message.

**Comment by laktyushin** [comment]
Added in 8.4
