### ISSUE TITLE
No way to scroll down bot search results in inline mode

### ISSUE THREAD

**Issue by unintended** [TelegramMessenger/Telegram-iOS#57]
According to https://core.telegram.org/bots/api#inline-mode bots can reply with `next_offset ` field and a client must re-run search for a next page of the results. However it doesn't work in iOS client. 

You can check it via `@vid` bot (e.g. type `@vid test` and scroll down) and compare behavior from desktop/android versions: they will load next pages on scroll down, but the ios version will stay on the first page.

**Comment by laktyushin** [comment]
Fixed in 5.13
