### ISSUE TITLE
Неправильные картинки в поиске изображений. Баг с поиском изображений.

### ISSUE THREAD

**Issue by SuperWillow** [TelegramMessenger/Telegram-iOS#572]
### Checklist
- [ ] I am reporting an issue in existing functionality that does not work as intended
- [ ] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
Когда ищешь картинки по этим запросам, то находит не те изображения. Исправьте этот баг

### Expected Behavior
Если набрать запросы "Лунтик вечеринка", "бинг мультик","Растишка снежинки', то появляются неправильные картинки (смотрите скрины).

### Actual Behavior
Механизм поисковой системы "Microsoft Bing" ищет по картинкам' так как картинки неправильные.

### Steps to Reproduce
1. Зайди в Телеграмм, и нажми на скрепку
2. Нажми на кнопку с лупой
3. А теперь вбей эти запросы, и посмотри что будет с картинками.

### Screenshots and Videos 
Remove, if not applicable
![image](https://user-images.githubusercontent.com/87235362/125624193-d7388241-da33-4b12-a6aa-119eefbfb7ca.jpeg)![image](https://user-images.githubusercontent.com/87235362/125624283-694182be-17c5-4b82-8339-01bc9953b5e1.jpeg)![image](https://user-images.githubusercontent.com/87235362/125624319-c03b4843-785c-42fe-9b62-1bfb796281ac.jpeg)![image](https://user-images.githubusercontent.com/87235362/125624780-84c407de-8d05-4510-aded-fb6490b24b6f.jpeg)

### Environment
**Device:** `iPad (8-го поколения)`

**iOS version**: `14.4`

**App version:** `7.7`

**Comment by ali-fareed** [comment]
The issue does not seem to be iOS-specific, please file one at https://bugs.telegram.org
