### ISSUE TITLE
Can't build successfully？ why？ Why so many bugs！

### ISSUE THREAD

**Issue by Pikdays** [TelegramMessenger/Telegram-iOS#581]
macOS: 11.5
xcode: 12.5.1
run: terminal

error：

python3 build-system/Make/Make.py \
    --bazel="$HOME/bazel-dist/bazel" \
    --cacheDir="$HOME/telegram-bazel-cache" \
    generateProject \
    --configurationPath="$HOME/telegram-configuration" \
    --disableExtensions \
    --disableProvisioningProfiles

Required Xcode version is 12.4, but 12.5.1 is reported by 'xcode-select -p'
pikdays@PikdaysMacBook-Pro Telegram-iOS %

**Comment by ali-fareed** [comment]
Here is what I would recommend: https://www.youtube.com/watch?v=HIj8wU_rGIU
