### ISSUE TITLE
Remove Apply Pay capabilities in the App

### ISSUE THREAD

**Issue by shivanraptor** [TelegramMessenger/Telegram-iOS#582]
In Apple App Review process, it mentioned that they cannot verify the Apple Pay feature in Telegram Bot. 

1. Is there any way for the Apple Review team to test such a feature? So far the official Shop Bot (https://t.me/shopbot) and Donate Bot (https://t.me/TelegramDonate) cannot use Apple Pay.

OR

2. Is there any way to remove Apply Pay capabilities in the App?

Thanks.

**Comment by ali-fareed** [comment]
If you are submitting a forked application to the App Store, Apple Pay should be already disabled, see https://github.com/TelegramMessenger/Telegram-iOS/blob/master/Telegram/BUILD#L290

It may be that you accidentally enabled Apple Pay while configuring your app at developer.apple.com. In that case you can simply remove it and regenerated your provisioning profiles.

**Comment by shivanraptor** [comment]
Thanks! Apple didn't check Apply Pay feature until recently. Strange.

**Comment by Kylmakalle** [comment]
I've also faced this issue long time ago. Apple asked "If Apple Pay features are used in App". Reviewer were pretty fine with my answer that Apple Pay kit is just imported but not used in project.
Hope it will help you pass the review.
