### ISSUE TITLE
Bubbles animations don’t work

### ISSUE THREAD

**Issue by laralove143** [TelegramMessenger/Telegram-iOS#586]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
Message bubbles animations don’t work, the app behaves the same even if reduce motion is disabled

### Expected Behavior
The bubbles should move slightly on scroll

### Actual Behavior
The bubbles don’t move at all

### Steps to Reproduce
1. Scroll in a chat

### Environment
**Device:** `iPhone 12 mini, iPhone 6s`

**iOS version**: `14.7.1`

**App version:** `7.8.4`

**Comment by ariffnorhadi** [comment]
im facing this issue on 'iPhone XR' running iOS '14.7.1'

**Comment by ali-fareed** [comment]
Kinetic bubble animations have been removed.

**Comment by ariffnorhadi** [comment]
> Kinetic bubble animations have been removed.

this bug has been solved? what do u mean by removing it?

**Comment by ariffnorhadi** [comment]
> Kinetic bubble animations have been removed.

do u mean this feature has been completely removed?
