### ISSUE TITLE
Fork version of Telegram build SOMETIMES does not have Badge notification

### ISSUE THREAD

**Issue by shivanraptor** [TelegramMessenger/Telegram-iOS#588]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
**Fork** version of Telegram build **SOMETIMES** does not have Badge notification (the red ball over the app icon with the number of messages), just got banner notifications.

### Expected Behavior
When a new message is received, the Telegram app should have a Badge and banner notification. Double checked the Setting page has enabled Badge notification (see screenshots).

### Actual Behavior
When a new message is received, the Telegram app only got a banner notification. Some one-to-one conversations received a badge notification, but group conversations never receive a badge notification. 

For example, when I receive a notification of a new message, a banner notification is received but no badge number. When I open the Fork app and close the app (put it back in the background), the badge reflects the number of unread messages correctly. 

### Steps to Reproduce
1. A new message is received when the app is running in the background
2. A banner notification is received
3. Pressing the banner notification will go to the correct conversation.

### Screenshots and Videos 
![IMG_3099](https://user-images.githubusercontent.com/997890/127607696-94465c72-4405-4a3d-a1e8-1a7c767de7bf.PNG)
![IMG_3100](https://user-images.githubusercontent.com/997890/127607730-e9712e3d-c33e-426d-bc74-b7bc6dac8866.PNG)

### Environment
**Device:** `tested on iPhone Xr, also happen on all other device models`

**iOS version**: `14.6`

**App version:** `7.6 to 7.8.2`

**Comment by ali-fareed** [comment]
Badge updates currently depend on the ability to be woken up in background. This will have been resolved (one way or another) by the time iOS 15 is released.
