### ISSUE TITLE
Latest update (7.9) instant crash on iOS 10 device

### ISSUE THREAD

**Issue by VetaLioSTV** [TelegramMessenger/Telegram-iOS#589]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
After installing latest update 7.9 on iOS 10 device, you can no longer use app , since it crashes instantly after start.

### Expected Behavior
App should start and run

### Actual Behavior
App instantly crashes

### Steps to Reproduce
1. Install update 7.9
2. Open app
3. See instant crash

### Environment
**Device:** `iPhone 5c`

**iOS version**: `10.3.3`

**App version:** `7.9`

**Comment by hehua04** [comment]
+1 I meet this problem on my ios10.3 iPad .

**Comment by badigit** [comment]
Same iOS 9.3.6 - iPad 3, iPad 4 mini

**Comment by ali-fareed** [comment]
The issue was resolved immediately after receiving the first reports and the updated build is currently in review with Apple.

**Comment by akotelnikov** [comment]
I have reproduced this bug on ipad 3 (ios 9.3.6)

**Comment by hehua04** [comment]
Thank you!

From my iPad


在 2021年8月1日，21:32，ali-fareed ***@***.******@***.***>> 写道：


The issue was resolved immediately after receiving the first reports and the updated build is currently in review with Apple.

**Comment by VetaLioSTV** [comment]
> The issue was resolved immediately after receiving the first reports and the updated build is currently in review with Apple.

Lol, how then it went to production untested :| ? This is something not good, little bit upset about that moment...

**Comment by ali-fareed** [comment]
7.9.1 is now available on the App Store.

**Comment by VetaLioSTV** [comment]
#568 @ali-fareed could you check also ?

**Comment by akotelnikov** [comment]
@ali-fareed, Thank you, problem solved in 7.9.1 version, work properly 🚀

**Comment by hehua04** [comment]
OK.
