### ISSUE TITLE
Некорректная обработка текста с нижними подчеркиваниями (_)

### ISSUE THREAD

**Issue by Supermanoff** [TelegramMessenger/Telegram-iOS#59]
Привет!

При отправке сообщения кому-либо, в котором есть полосы из нескольких нижних подчеркиваний, клиент на iOS перемешивает весь текст.

Попробуйте отправить этот текст кому-то в чат из Telegram для iOS:

```
Привет

Раз

два

три

четыре
_________________________

пять

шесть

_________________________
```

Он превратиться в:

```
Привет
⠀
Раз
⠀
два
⠀
три
⠀
четыре
_____________________
Привет
⠀
Раз
⠀
_____________________
```

**Comment by laktyushin** [comment]
Fixed in 5.9.1
