### ISSUE TITLE
[Question] Generating fake codesigning

### ISSUE THREAD

**Issue by Kylmakalle** [TelegramMessenger/Telegram-iOS#590]
Hey. I'm curious how you managed to create fake codesigning certs and provision.
I've a fork and it requires some more capabilities for AppleWatch app, so provided fake-codesign fails on Github Actions CI

```
ERROR: Target "//Telegram:TelegramWatchExtension_entitlements" uses entitlements with a "com.apple.developer.associated-domains" key, but the profile does not support use of this key.
```

I assume you're creating real codesigning with fastlane and then invalidate certs on developer portal. 
Can you please share a script if possible?

Thanks in advance!

**Comment by ali-fareed** [comment]
https://dkimitsa.github.io/2018/01/04/ios-homemade-provision-profile/

Basically, generate real provisioning profiles via developer.apple.com, then replace certificate IDs and expiry dates to match your own (self-signed) certificate.
