### ISSUE TITLE
Unable to install "Telegram" in device,but in  simulator is normally

### ISSUE THREAD

**Issue by Dzhijian** [TelegramMessenger/Telegram-iOS#591]
First,I used this statement：
python3 build-system/Make/Make.py \
    --bazel="$HOME/bazel-dist/bazel" \
    --cacheDir="$HOME/telegram-bazel-cache" \
    generateProject \
    --configurationPath="$HOME/telegram-configuration"

and then I changed my own  provisioning profile

Unable to install "Telegram "when I install Xcode on the device, but it can run normally in the simulator, how can I install on the device?

I don't know what's wrong

Can you guys help me out here?

Details

Unable to install "Telegram"
Domain: com.apple.dt.MobileDeviceErrorDomain
Code: -402620395
--
A valid provisioning profile for this executable was not found.
Domain: com.apple.dt.MobileDeviceErrorDomain
Code: -402620395
User Info: {
    DVTRadarComponentKey = 487925;
    MobileDeviceErrorCode = "(0xE8008015)";
    "com.apple.dtdevicekit.stacktrace" = (
	0   DTDeviceKitBase                     0x0000000111b5fc8f DTDKCreateNSErrorFromAMDErrorCode + 220
	1   DTDeviceKitBase                     0x0000000111b9e241 __90-[DTDKMobileDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:]_block_invoke + 155
	2   DVTFoundation                       0x00000001088e764b DVTInvokeWithStrongOwnership + 71
	3   DTDeviceKitBase                     0x0000000111b9df82 -[DTDKMobileDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:] + 1440
	4   IDEiOSSupportCore                   0x0000000115d2ca10 __118-[DVTiOSDevice(DVTiPhoneApplicationInstallation) processAppInstallSet:appUninstallSet:installOptions:completionBlock:]_block_invoke.292 + 3513
	5   DVTFoundation                       0x0000000108a1617e __DVT_CALLING_CLIENT_BLOCK__ + 7
	6   DVTFoundation                       0x0000000108a17da0 __DVTDispatchAsync_block_invoke + 1191
	7   libdispatch.dylib                   0x00007ff817bc0308 _dispatch_call_block_and_release + 12
	8   libdispatch.dylib                   0x00007ff817bc1500 _dispatch_client_callout + 8
	9   libdispatch.dylib                   0x00007ff817bc7479 _dispatch_lane_serial_drain + 639
	10  libdispatch.dylib                   0x00007ff817bc7f27 _dispatch_lane_invoke + 366
	11  libdispatch.dylib                   0x00007ff817bd1d16 _dispatch_workloop_worker_thread + 758
	12  libsystem_pthread.dylib             0x00007ff817d6e132 _pthread_wqthread + 326
	13  libsystem_pthread.dylib             0x00007ff817d6d0bf start_wqthread + 15
);
}
--

System Information

macOS Version 12.0 (Build 21A5284e)
Xcode 12.4 (17801) (Build 12D4e)
Timestamp: 2021-08-02T00:38:56+08:00

**Comment by bzz445** [comment]
same problem
