### ISSUE TITLE
I can't compile IOS telegraph messenger

### ISSUE THREAD

**Issue by liuyu310** [TelegramMessenger/Telegram-iOS#596]
###Checklist
-[] I want to compile the telegraph IOS source code, but I can't continue
-[] I searched for existing [GitHub questions]（ https://github.com/telegrammessenger/Telegram-iOS/issues )
###Description
When I install the official document and run it to the fifth part, I export the Xcode document and open it. I run the project, report an error and prompt the linking telegraph / telegraph uiframework_ bin failed: (Exit 1): wrapped_ clang_ pp failed: error executing command
###Expected behavior
Projects that can operate normally
###Actual behavior
Linking Telegram/TelegramUIFramework_ bin failed: (Exit 1): wrapped_ clang_ pp failed: error executing command
###Copy steps
python3 build-system/Make/Make.py \
--bazel="$HOME/bazel-dist/bazel" \
--cacheDir="$HOME/telegram-bazel-cache" \
generateProject \
--configurationPath="$HOME/telegram-configuration" \
--disableExtensions
###Environment
**Device: * ` iPhone`
**IOS version * *: ` 13.1`
**Application version: * ` 7.8`

**Comment by demoker** [comment]
Same question!
Required Xcode version is 13.0, but 13.1 is reported by 'xcode-select -p'
