### ISSUE TITLE
Can any one show me the direction to disable pornographic channel restriction?

### ISSUE THREAD

**Issue by zj299792458** [TelegramMessenger/Telegram-iOS#6]
Since it's the source code it won't be affected by Apple Store guideline. So is there any tricks that can disable the channel restriction just like the Android app? 
I know there is a lot of detours that can get rid of it, such as using a web version, but I just simply hate Apple rules and I'm not planning on obeying it. I've already compile it on my phone with push certification setup, but I'm not a swift reader. 
I know it's possible because I've done it on Objective C version of Telegram already.
Appreciate any help.

**Comment by shivanraptor** [comment]
I know the way, but it's not the reason of having Telegram Swift version open-sourced. This won't help Telegram in any ways.

**Comment by zj299792458** [comment]
> I know the way, but it's not the reason of having Telegram Swift version open-sourced. This won't help Telegram in any ways.

Indeed, It's not the reason of having Telegram Swift version open-sourced, it's the consequence that open-source can have. To make this consequence happen, I appreciate any help. I don't know if it help Telegram, but I'm sure it will help me, without breaking any laws to the best of my knowledge. It will help other users who is seeking free software too.

**Comment by NightMachinary** [comment]
Just search the whole code base for “porn”? Using a tool like ag.
