### ISSUE TITLE
can’t see what voice massage someone replies to in night(black) theme

### ISSUE THREAD

**Issue by h1lary7** [TelegramMessenger/Telegram-iOS#605]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
when someone replies to your voice message you cant see what message someone replies to.

### Expected Behavior
the message will get lighter and you can see what massage someone replies to

### Actual Behavior
the program sends you to a place of message, but it doesn't show specific massage. i mean that massage doesn't become lighter. But it worked before one of updates of telegram.

### Steps to Reproduce
1. turn on black theme
2. send some voice massages
3. reply to one from another account
4. press "voice massage" in replied massage to and you can see that the current massage doesn't become lighter.

### Environment
**Device:** `iPhone 11`

**iOS version**: `14.6`

**App version:** `7.9.2`

**Comment by laktyushin** [comment]
Fixed in 8.4
