### ISSUE TITLE
can’t play any music in telegram on ios 15 .12 pro

### ISSUE THREAD

**Issue by Mohamadzhamedani** [TelegramMessenger/Telegram-iOS#614]
### Checklist
- [ ] I am reporting an issue in existing functionality that does not work as intended
- [ ] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
Describe the issue that you are experiencing

### Expected Behavior
Tell us what should happen

### Actual Behavior
Tell us what happens instead

### Steps to Reproduce
1. 
2. 
3. 

### Screenshots and Videos 
Remove, if not applicable

### Environment
**Device:** `iPhone/iPad X`

**iOS version**: `13.X`

**App version:** `7.X`

**Comment by Laiteux** [comment]
Same on iOS 15 with iPhone 11, device model doesn't seem to matter, issue seems linked to iOS 15 itself. Since upgrading, music files won't play anymore.

**Comment by Parsa2820** [comment]
Same here. It seems the music file itself isn't corrupted and can be played using other apps.

**Comment by ali-fareed** [comment]
Does the latest update fix the issue for you?

**Comment by Parsa2820** [comment]
> 
> 
> Does the latest update fix the issue for you?

Yes. This issue should be closed.
