### ISSUE TITLE
Request: folders tabs swipe

### ISSUE THREAD

**Issue by SPAHI4** [TelegramMessenger/Telegram-iOS#619]
If you have chats folders, you can navigate between them with tap. You can't swipe left or right becaus these actions are already assigned to archive/read/etc with individual chats. But you still can swipe on the bottom navigation bar. So I suggest to navigate between folders with swipe on the navigation bar, similar how it's implemented on the new safari.

**Comment by ali-fareed** [comment]
You can use swipe to navigate between folders by starting the swipe closer to the middle of the screen.
