### ISSUE TITLE
Not build project in XCode 13

### ISSUE THREAD

**Issue by thiti-y** [TelegramMessenger/Telegram-iOS#631]
I not build project in XCode 13, It got error following error below

![image](https://user-images.githubusercontent.com/7018802/137592624-bb715cd8-e3fc-430f-9b91-34022bef8f2c.png)

# Environment:

- Mac M1
- Xcode 13
- bazel 4.2.1

**Comment by ali-fareed** [comment]
Xcode 13 support will be introduced in the next app / source code update.

**Comment by thiti-y** [comment]
Awesome, thank you.

**Comment by Kylmakalle** [comment]
Xcode 13 is now supported

**Comment by cfcor** [comment]
I met the same error. Can anyone help me?

**Comment by yxx19950523** [comment]
Dude, did you fix that mistake
