### ISSUE TITLE
Add ability to “Like” a message

### ISSUE THREAD

**Issue by charles-hood** [TelegramMessenger/Telegram-iOS#638]
Enhancement Request: Make it so users can “Like” an individual message with a small emoji that displays on the message as a subscript. (See Apple iMessage and Facebook Messenger as examples of chat with this capability.)

**Comment by gracjankn** [comment]
This is a very good idea, but I prefer the implementation in Signal and Discord, because they allow you to pick any emoji as a reaction to a message.

**Comment by noahtallen** [comment]
I think this is covered here: https://bugs.telegram.org/c/23. I hear it may be in progress?

**Comment by laktyushin** [comment]
Added in 8.4
