### ISSUE TITLE
Support contact identifiers for notifications

### ISSUE THREAD

**Issue by Kamik423** [TelegramMessenger/Telegram-iOS#639]
iOS 15 brought focus modes to iOS where one can block all notifications except from whitelisted contacts. For this an app‘s notifications need to be connected to a contact card. Slack for example supports this. When sliding left on a notification and hitting [Options] one can connect the contact. Telegram however does not. Either all of my telegram notifications get blocked or none. There is no way to whitelist certain contacts in some focus modes.

Apple documents how to do this in their [Implementing Communication Notifications](https://developer.apple.com/documentation/usernotifications/implementing_communication_notifications) documentation page.

![IMG_3740](https://user-images.githubusercontent.com/16278233/139674421-e5078663-eafb-4f14-bf7f-f1b7ef8e1761.jpeg)

**Comment by thebluepotato** [comment]
Same as #556
Telegram should really adopt this as soon as possible as apparently many users enjoy configuring Focus modes.

**Comment by Kamik423** [comment]
Yes, the update today implemented this. Thanks Telegram :)
