### ISSUE TITLE
"🙉 " emoji doesn't have animation

### ISSUE THREAD

**Issue by fadziljusri** [TelegramMessenger/Telegram-iOS#649]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
"🙉 " emoji doesn't have animation as see-no-evil monkey

### Expected Behavior
Should have been animated

### Actual Behavior
Static emoji displayed without animation

### Steps to Reproduce
1. Choose "🙉 " and send to any chat

### Environment
**Device:** `iPhone 11`

**iOS version**: `15.0.2`

**App version:** `8.2.1`

**Comment by laktyushin** [comment]
Not a bug.
