### ISSUE TITLE
iOS missing messages (holes bug)

### ISSUE THREAD

**Issue by alfredonodo** [TelegramMessenger/Telegram-iOS#65]
Hi,
you should fix the holes bug as soon as possible. It is unacceptable for telegram a bug like this. You will never be able to replace other famous messaging apps with such problem.
Best Regards

**Comment by Kylmakalle** [comment]
Tap 10x times on settings icon and try to use Reset Holes option.

**Comment by alfredonodo** [comment]
> Tap 10x times on settings icon and try to use Reset Holes option.

This is a workaround, but it does not solve the problem. This bug is a very important to be solve to compete against other famous messaging apps. Please give it the maximum priority.

**Comment by Kylmakalle** [comment]
> Please give it the maximum priority.

I'm not a TG dev, you can try to ask in official twitter/support.

**Comment by alfredonodo** [comment]
> > Please give it the maximum priority.
> 
> I'm not a TG dev, you can try to ask in official twitter/support.

Ok, unfortunately I do not have any social network account.

**Comment by laktyushin** [comment]
All known missing messages issues have been fixed.
