### ISSUE TITLE
I have build the project,but it can't run successfully.

### ISSUE THREAD

**Issue by cfcor** [TelegramMessenger/Telegram-iOS#651]
I met this error.Can anyone help me solve it.

/Users/aj/Telegram-iOS/submodules/MediaPlayer/BUILD:3:14: Compiling Swift module UniversalMediaPlayer failed: (Exit 1): worker failed: error executing command 
/Users/aj/Telegram-iOS/submodules/MediaPlayer/Sources/MediaPlayer.swift:400:13: 'CMTimebaseCreateWithMasterClock(allocator:masterClock:timebaseOut:)' was deprecated in iOS 8.0: renamed to 'CMTimebaseCreateWithSourceClock(allocator:sourceClock:timebaseOut:)'
/Users/aj/Telegram-iOS/submodules/MediaPlayer/Sources/MediaPlayerAudioRenderer.swift:100:47: 'CMTimebaseCopyMaster' was deprecated in iOS 9.0: renamed to 'CMTimebaseCopySource(_:)'
/Users/aj/Telegram-iOS/submodules/MediaPlayer/Sources/MediaPlayerAudioRenderer.swift:104:29: 'CMTimebaseSetRateAndAnchorTime(_:rate:anchorTime:immediateMasterTime:)' is deprecated: renamed to 'CMTimebaseSetRateAndAnchorTime(_:rate:anchorTime:immediateSourceTime:)'
/Users/aj/Telegram-iOS/submodules/MediaPlayer/Sources/MediaPlayerAudioRenderer.swift:805:9: 'CMTimebaseCreateWithMasterClock(allocator:masterClock:timebaseOut:)' was deprecated in iOS 8.0: renamed to 'CMTimebaseCreateWithSourceClock(allocator:sourceClock:timebaseOut:)'
/Users/aj/Telegram-iOS/build-input/gen/project/Telegram.xcodeproj/.tulsi/Scripts/bazel_build.py:581:1: Bazel build failed with exit code 1. Please check the build log in Report Navigator (⌘9) for more information.
<img width="1440" alt="螢幕截圖 2021-11-11 上午8 05 29" src="https://user-images.githubusercontent.com/87554617/141213183-3ba9c026-d0d2-4a4d-9949-bfb9726676a7.png">

**Comment by cfcor** [comment]
@ali-fareed Would you please have a look about this error?

**Comment by ali-fareed** [comment]
Update to the latest commit.
