### ISSUE TITLE
Build Error.

### ISSUE THREAD

**Issue by crocodile305** [TelegramMessenger/Telegram-iOS#653]
I got this error when I would like to try to build the app.
But I can run successfully via simulator.

OS: macOS Big Sur version 11.6
Xcode :  13.0

![2021-11-12_21h46_48](https://user-images.githubusercontent.com/38894059/141477118-14c2c96c-263f-430f-a2c2-9ad0eb283de0.png)

**Comment by ali-fareed** [comment]
You need to generate your own provisioning profiles.

**Comment by crocodile305** [comment]
would you like to let me know how to generate my own provisioning profiles?
