### ISSUE TITLE
transfer data between two iPhone devices, it will lost all data.

### ISSUE THREAD

**Issue by visoon** [TelegramMessenger/Telegram-iOS#660]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
When transfer data between two iPhone devices, it lost all data when finished.
I don't know why it will happen, and where is the code in project ?

### Expected Behavior
Tell us what should happen

### Actual Behavior
Tell us what happens instead

### Steps to Reproduce
Follow the screenshot to do it.

### Screenshots and Videos 
![image](https://user-images.githubusercontent.com/10443089/142558736-4fbaa107-36f9-4ca6-af3c-e805ccb5000a.png)

### Environment
**Device:** `iPhone/iPad X`

**iOS version**: `13.X`

**App version:** `7.X`

**Comment by ali-fareed** [comment]
The data should only be synced when backing up to a Mac or a Windows PC.
