### ISSUE TITLE
Question regarding 'this channel.. violates Apple App Store Review Guidelines' messages

### ISSUE THREAD

**Issue by le-codechetif-blanc** [TelegramMessenger/Telegram-iOS#67]
Hi Peter,

I understand that there's a restriction in newer versions of the app that bans channels that Apple considers politically incorrect, which displays a message along the lines of "this channel couldn't be displayed on your device because it violates Apple App Store Review Guidelines, section 1.1.1." I see no record of this in the released source- am I missing something, or is the logic used to make this determination not publicly released?

Thanks,

**Comment by laktyushin** [comment]
It is handled server-side using existing mechanisms, no changes were required.
