### ISSUE TITLE
Build the app Error

### ISSUE THREAD

**Issue by hecanlin** [TelegramMessenger/Telegram-iOS#680]
I get an error when I execute the script:
python3 build-system/Make/Make.py \
    --bazel="$HOME/bazel-dist/bazel" \
    --cacheDir="$HOME/telegram-bazel-cache" \
    build \
    --configurationPath="$HOME/telegram-configuration" \
    --buildNumber=100001 \
    --configuration=release_universal

### Description
ERROR: /Users/a1234/Telegram-iOS/third-party/yasm/BUILD:3:8: Executing genrule //third-party/yasm:yasm [for host] failed: (Exit 1): bash failed: error executing command 
  (cd /private/var/tmp/_bazel_a1234/66b492e35ec9c352ae2b7edbdf1b235c/execroot/__main__ && \
  exec env - \
    PATH=/usr/bin:/bin:/usr/sbin:/sbin \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; 
set -x
    core_count="`sysctl -n hw.logicalcpu`"
    BUILD_DIR="bazel-out/host/bin/third-party/yasm/build"
    rm -rf "$BUILD_DIR"
    mkdir -p "$BUILD_DIR"

    CMAKE_DIR="$(pwd)/$BUILD_DIR/cmake"
    rm -rf "$CMAKE_DIR"
    mkdir -p "$CMAKE_DIR"
    tar -xf "external/cmake_tar_gz/file/downloaded" -C "$CMAKE_DIR"
    
    tar -xzf "third-party/yasm/yasm-1.3.0.tar.gz" --directory "$BUILD_DIR"
    pushd "$BUILD_DIR/yasm-1.3.0"
    mkdir build
    cd build
    PATH="$PATH:$CMAKE_DIR/cmake-3.19.2-macos-universal/CMake.app/Contents/bin" cmake .. -DYASM_BUILD_TESTS=OFF -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF
    make -j $core_count
    popd

    tar -cf "bazel-out/host/bin/third-party/yasm/yasm.tar" -C "$BUILD_DIR/yasm-1.3.0/build" .
')
Execution platform: @local_config_platform//:host
++ sysctl -n hw.logicalcpu
+ core_count=12
+ BUILD_DIR=bazel-out/host/bin/third-party/yasm/build
+ rm -rf bazel-out/host/bin/third-party/yasm/build
+ mkdir -p bazel-out/host/bin/third-party/yasm/build
++ pwd
+ CMAKE_DIR=/private/var/tmp/_bazel_a1234/66b492e35ec9c352ae2b7edbdf1b235c/execroot/__main__/bazel-out/host/bin/third-party/yasm/build/cmake
+ rm -rf /private/var/tmp/_bazel_a1234/66b492e35ec9c352ae2b7edbdf1b235c/execroot/__main__/bazel-out/host/bin/third-party/yasm/build/cmake
+ mkdir -p /private/var/tmp/_bazel_a1234/66b492e35ec9c352ae2b7edbdf1b235c/execroot/__main__/bazel-out/host/bin/third-party/yasm/build/cmake
+ tar -xf external/cmake_tar_gz/file/downloaded -C /private/var/tmp/_bazel_a1234/66b492e35ec9c352ae2b7edbdf1b235c/execroot/__main__/bazel-out/host/bin/third-party/yasm/build/cmake
+ tar -xzf third-party/yasm/yasm-1.3.0.tar.gz --directory bazel-out/host/bin/third-party/yasm/build
+ pushd bazel-out/host/bin/third-party/yasm/build/yasm-1.3.0
+ mkdir build
+ cd build
+ PATH=/usr/bin:/bin:/usr/sbin:/sbin:/private/var/tmp/_bazel_a1234/66b492e35ec9c352ae2b7edbdf1b235c/execroot/__main__/bazel-out/host/bin/third-party/yasm/build/cmake/cmake-3.19.2-macos-universal/CMake.app/Contents/bin
+ cmake .. -DYASM_BUILD_TESTS=OFF -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF
CMake Error at /private/var/tmp/_bazel_a1234/66b492e35ec9c352ae2b7edbdf1b235c/execroot/__main__/bazel-out/host/bin/third-party/yasm/build/cmake/cmake-3.19.2-macos-universal/CMake.app/Contents/share/cmake-3.19/Modules/CMakeTestCCompiler.cmake:66 (message):
  The C compiler

    "/Applications/Xcode 13.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /private/var/tmp/_bazel_a1234/66b492e35ec9c352ae2b7edbdf1b235c/execroot/__main__/bazel-out/host/bin/third-party/yasm/build/yasm-1.3.0/build/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/usr/bin/make cmTC_8f6d4/fast && /Applications/Xcode 13.1.app/Contents/Developer/usr/bin/make  -f CMakeFiles/cmTC_8f6d4.dir/build.make CMakeFiles/cmTC_8f6d4.dir/build
    make: /Applications/Xcode: No such file or directory
    make: *** [cmTC_8f6d4/fast] Error 1
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:1 (PROJECT)

/private/var/tmp/_bazel_a1234/66b492e35ec9c352ae2b7edbdf1b235c/execroot/__main__/bazel-out/host/bin/third-party/yasm/build/yasm-1.3.0 /private/var/tmp/_bazel_a1234/66b492e35ec9c352ae2b7edbdf1b235c/execroot/__main__
-- The C compiler identification is AppleClang 13.0.0.13000029
-- The CXX compiler identification is AppleClang 13.0.0.13000029
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Check for working C compiler: /Applications/Xcode 13.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode 13.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - broken
-- Configuring incomplete, errors occurred!
See also "/private/var/tmp/_bazel_a1234/66b492e35ec9c352ae2b7edbdf1b235c/execroot/__main__/bazel-out/host/bin/third-party/yasm/build/yasm-1.3.0/build/CMakeFiles/CMakeOutput.log".
See also "/private/var/tmp/_bazel_a1234/66b492e35ec9c352ae2b7edbdf1b235c/execroot/__main__/bazel-out/host/bin/third-party/yasm/build/yasm-1.3.0/build/CMakeFiles/CMakeError.log".
Target //Telegram:Telegram failed to build
INFO: Elapsed time: 19.476s, Critical Path: 18.85s
INFO: 264 processes: 119 internal, 145 local.
FAILED: Build did NOT complete successfully
Traceback (most recent call last):
  File "build-system/Make/Make.py", line 638, in <module>
    build(arguments=args)
  File "build-system/Make/Make.py", line 427, in build
    bazel_command_line.invoke_build()
  File "build-system/Make/Make.py", line 314, in invoke_build
    call_executable(combined_arguments)
  File "/Users/a1234/Telegram-iOS/build-system/Make/BuildEnvironment.py", line 60, in call_executable
    subprocess.check_call(resolved_arguments, env=resolved_env)
  File "/Applications/Xcode 13.1.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/a1234/bazel-dist/bazel', 'build', 'Telegram/Telegram', '--override_repository=build_configuration=/Users/a1234/telegram-configuration', '--announce_rc', '--features=swift.use_global_module_cache', '--verbose_failures', '--features=swift.skip_function_bodies_for_derived_files', '--jobs=12', '--define=buildNumber=100001', '--define=telegramVersion=8.3.1', '--features=swift.split_derived_files_generation', '--disk_cache=/Users/a1234/telegram-bazel-cache', '-c', 'opt', '--ios_multi_cpus=armv7,arm64', '--watchos_cpus=armv7k,arm64_32', '--apple_generate_dsym', '--output_groups=+dsyms', '--features=swift.opt_uses_wmo', '--features=swift.opt_uses_osize', '--swiftcopt=-num-threads', '--swiftcopt=0', '--features=dead_strip', '--objc_enable_binary_stripping', '--apple_bitcode=watchos=embedded']' returned non-zero exit status 1.
a1234@hecanlindeMacBook-Pro Telegram-iOS % python3 build-system/Make/Make.py \
    --bazel="$HOME/bazel-dist/bazel" \
    --cacheDir="$HOME/telegram-bazel-cache" \
    generateProject \
    --configurationPath="$HOME/telegram-configuration" \
    --disableExtensions \
    --disableProvisioningProfiles
Starting local Bazel server and connecting to it...
INFO: Analyzed target //:tulsi (48 packages loaded, 522 targets configured).

### Environment

**Xcode version**: `13.1`

**MacOS version:** `12.0.1`

**Comment by shivanraptor** [comment]
```
The C compiler
"/Applications/Xcode 13.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc"
is not able to compile a simple test program.
```

The error is self-explained. Re-install the Xcode.

**Comment by MacleChen** [comment]
Are you kidding me?

**Comment by MacleChen** [comment]
is this the solution?

**Comment by MacleChen** [comment]
Don't to do this, It doesn't work.
