### ISSUE TITLE
构建错误  

### ISSUE THREAD

**Issue by liude233** [TelegramMessenger/Telegram-iOS#687]
python3 build-system/Make/Make.py \
    --bazel="$HOME/bazel-dist/bazel" \
    --cacheDir="$HOME/telegram-bazel-cache" \
    build \
    --configurationPath="$HOME/telegram-configuration" \
    --buildNumber=100001 \
    --configuration=release_universal

ERROR: Error fetching repository: java.io.IOException: No WORKSPACE file found in /private/var/tmp/_bazel_liudeshan/115b7c8a368a2b62bc04999ae831e6af/external/build_bazel_rules_apple
ERROR: no such package '@build_bazel_rules_apple//apple': No WORKSPACE file found in /private/var/tmp/_bazel_liudeshan/115b7c8a368a2b62bc04999ae831e6af/external/build_bazel_rules_apple

INFO: Elapsed time: 0.276s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
Traceback (most recent call last):
  File "build-system/Make/Make.py", line 638, in <module>
    build(arguments=args)
  File "build-system/Make/Make.py", line 427, in build
    bazel_command_line.invoke_build()
  File "build-system/Make/Make.py", line 314, in invoke_build
    call_executable(combined_arguments)
  File "/Users/liudeshan/Telegram-iOS/build-system/Make/BuildEnvironment.py", line 60, in call_executable
    subprocess.check_call(resolved_arguments, env=resolved_env)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/liudeshan/bazel-dist/bazel', 'build', 'Telegram/Telegram', '--override_repository=build_configuration=/Users/liudeshan/telegram-configuration', '--announce_rc', '--features=swift.use_global_module_cache', '--verbose_failures', '--features=swift.skip_function_bodies_for_derived_files', '--jobs=8', '--define=buildNumber=100001', '--define=telegramVersion=8.3.1', '--features=swift.split_derived_files_generation', '--disk_cache=/Users/liudeshan/telegram-bazel-cache', '-c', 'opt', '--ios_multi_cpus=armv7,arm64', '--watchos_cpus=armv7k,arm64_32', '--apple_generate_dsym', '--output_groups=+dsyms', '--features=swift.opt_uses_wmo', '--features=swift.opt_uses_osize', '--swiftcopt=-num-threads', '--swiftcopt=0', '--features=dead_strip', '--objc_enable_binary_stripping', '--apple_bitcode=watchos=embedded']' returned non-zero exit status 1.

**Comment by shivanraptor** [comment]
English please.

**Comment by janeroseloving** [comment]
构建是不会出错的，把你的工程删掉重新来，执行这个命令clone
git clone --recursive -j8 https://github.com/TelegramMessenger/Telegram-iOS.git

碰到这类错误“ERROR: Error fetching repository: java.io.IOException”，就是submodule没download下来
执行：git submodule update --init --recursive

参考：https://stackoverflow.com/questions/10168449/git-update-submodules-recursively

**Comment by janeroseloving** [comment]
> English please.
help me this
https://github.com/TelegramMessenger/Telegram-iOS/issues/688
