### ISSUE TITLE
Error 2

### ISSUE THREAD

**Issue by lotus-lotus** [TelegramMessenger/Telegram-iOS#69]
![2DFF9DE2-CFE2-473E-8130-C8C0127B6F7E](https://user-images.githubusercontent.com/24632295/59507223-fd972080-8edc-11e9-8665-48b7d84b8f48.png)
_apiId and _apiHash Have a value

**Comment by m1faridi** [comment]
I have the same error

**Comment by Kylmakalle** [comment]
You must set App groups properly

https://github.com/peter-iakovlev/Telegram-iOS/blob/master/Telegram-iOS/AppDelegate.swift#L335-L338

**Comment by lotus-lotus** [comment]
但是只是模拟器测试,并没有程序组
That's why "Error 2" appears

As for Cydia Impactor - Free Apple Developer account doesn't support App groups

**Comment by SGmuwa** [comment]
> You must set App groups properly
> 
> https://github.com/peter-iakovlev/Telegram-iOS/blob/master/Telegram-iOS/AppDelegate.swift#L335-L338

Http error 404.

**Comment by Lxa333** [comment]
@XavierLost did u solve this problem? I have the same

**Comment by Roman7451** [comment]
![59507223-fd972080-8edc-11e9-8665-48b7d84b8f48](https://user-images.githubusercontent.com/108979378/178101404-320b2881-8343-4a81-94f4-aa249329c5b3.png)

Как Решить?

**Comment by Kylmakalle** [comment]
Updated answer on that. 
Error occures if main app does not have a permission to use it's App group.
https://github.com/TelegramMessenger/Telegram-iOS/blob/688bf1bd4f065572230ade7e22ff68c8c260221d/submodules/TelegramUI/Sources/AppDelegate.swift#L448-L451

So the declaration expects you have properly set up an App Group for Telegram app identifiers on your developer portal.
https://github.com/TelegramMessenger/Telegram-iOS/blob/688bf1bd4f065572230ade7e22ff68c8c260221d/submodules/TelegramUI/Sources/AppDelegate.swift#L411-L413

Example:
If you have an app bundle called `com.supercool.telegram-fork`, you need to create an App Group called `group.com.supercool.telegram-fork` here https://developer.apple.com/account/resources/identifiers/add/bundleId
<img width="922" alt="image" src="https://user-images.githubusercontent.com/24507532/178138711-54816160-f0d3-4fc1-83a2-54350ce494cf.png">


Then add it to your identifiers. AFAIK you will need to do this for any Telegram-releated identifier, cause app heavily relies on that type of communications between extensions.
<img width="951" alt="image" src="https://user-images.githubusercontent.com/24507532/178138761-4716e4fc-a674-4216-9251-860567c5ca4e.png">

Remember to apply your new provisioning.

**Comment by Roman7451** [comment]
![Screenshot_16](https://user-images.githubusercontent.com/108979378/178140032-eb7de86b-2e96-4cb2-9d6f-9ba495e3c04e.png)
You need a subscription for $ 99?

**Comment by Roman7451** [comment]
> Обновленный ответ на этот вопрос. Ошибка возникает, если у основного приложения нет разрешения на использование его группы приложений.
> 
> https://github.com/TelegramMessenger/Telegram-iOS/blob/688bf1bd4f065572230ade7e22ff68c8c260221d/submodules/TelegramUI/Sources/AppDelegate.swift#L448-L451
> 
> Таким образом, объявление ожидает, что вы правильно настроили группу приложений для идентификаторов приложений Telegram на вашем портале разработчика.
> 
> https://github.com/TelegramMessenger/Telegram-iOS/blob/688bf1bd4f065572230ade7e22ff68c8c260221d/submodules/TelegramUI/Sources/AppDelegate.swift#L411-L413
> 
> Пример: если у вас вызван пакет приложений`com.supercool.telegram-fork`, вам необходимо создать группу приложений с именем `group.com.supercool.telegram-fork`here https://developer.apple.com/account/resources/identifiers/add/bundleId <img alt="изображение" width="922" src="https://user-images.githubusercontent.com/24507532/178138711-54816160-f0d3-4fc1-83a2-54350ce494cf.png">
> 
> Затем добавьте его в свои идентификаторы. AFAIK вам нужно будет сделать это для любого идентификатора, связанного с Telegram, потому что приложение сильно зависит от этого типа связи между расширениями. <img alt="изображение" width="951" src="https://user-images.githubusercontent.com/24507532/178138761-4716e4fc-a674-4216-9251-860567c5ca4e.png">
> 
> Не забудьте применить новую подготовку.
![Screenshot_16](https://user-images.githubusercontent.com/108979378/178140452-ae7c3b63-2eda-4045-9731-aa3a891cd05f.png)
Do I need a subscription here?

**Comment by Kylmakalle** [comment]
App Groups are available only for paid developers accounts
