### ISSUE TITLE
Add option to disable quick reactions

### ISSUE THREAD

**Issue by dancojocaru2000** [TelegramMessenger/Telegram-iOS#696]
On old Telegram versions, double tapping opened the menu for the message. On iMessage as well, double tapping opens the reactions menu with a reply button.

Please add an option to disable quick reactions and revert to the old behavior.

**Comment by Laiteux** [comment]
Was about to post this. Please, give us an option to bring the double-click context menu back. It's as easy as adding a toggle in the "Quick reaction" setting tab

**Comment by Arcegis** [comment]
I third this.
We do not need this imposed feature.

**Comment by PavelAgurov** [comment]
+100. I also want to have option to disable it from personal chats. Now it's for each image (and even messages).

**Comment by ali-fareed** [comment]
A better place do discuss this would be at https://bugs.telegram.org/?type=suggestions

**Comment by dancojocaru2000** [comment]
Why? It's not exactly a suggestion, it's breaking a feature that was previously working, a regression.

**Comment by ali-fareed** [comment]
I understand that this may be seen as an issue, but the feature is working as expected. A public bug tracker entry would be more accessible to non-developers for discussion.

**Comment by dancojocaru2000** [comment]
> but the feature is working as expected

Working as expected by the developers or working as expected by everyone using Telegram before the update.

Frankly, I'm not exactly sure why a discussion is needed. The feature existed previously, so there's no need to prove that it's needed, and the user facing implementation to me would be adding a "none" option in the quick reactions setting that would bring back the old behavior, or at least disable quick reactions.

As it stands right now, muscle memory is making me like a lot of messages.

**Comment by ali-fareed** [comment]
> Working as expected by the developers

Exactly.

**Comment by Laiteux** [comment]
@dancojocaru2000 is right, muscle memory also makes everyone like a lot of messages by mistake. I think the fact that there's no option to disable quick reactions is indeed a regresssion, especially since I'm more willing to edit/delete/view seen receipts of a message than wanting to like it. There's a ton of features in the context menu which makes it way more favorable to be open rather than a reaction to be given

**Comment by dancojocaru2000** [comment]
> Exactly.

@ali-fareed Well, from a user perspective, even if the developers *deliberately* code a problem, it's still a problem.

**Comment by ryder203** [comment]
Quick reactions are just damn annoying. Telegram is oh so innovative. Gonna call it facegram now. It's a messenger, maybe quit making it a bad social media platform.

**Comment by azat11** [comment]
Would using older version of the app disable them?

**Comment by ali-fareed** [comment]
@azat11 It will, but older versions will be unable to display messages that use the new spoiler text feature.

**Comment by Silent-Hunter** [comment]
I would like to add my desire that this feature be togglable. Not just quick reactions, I want to disable reactions entirely, they make the context menu take slightly longer to open and it's jarring.

**Comment by EugeneAbramchuk** [comment]
Hey guys, please upvote https://bugs.telegram.org/c/12966

Hopefully this questionable feature is getting a toggle it deserves.

**Comment by kuanysho** [comment]
> On old Telegram versions, double tapping opened the menu for the message. On iMessage as well, double tapping opens the reactions menu with a reply button.
> 
> Please add an option to disable quick reactions and revert to the old behavior.

Not only in iOS, but in Android too please
