### ISSUE TITLE
Inline keyboard buttons cannot be clicked

### ISSUE THREAD

**Issue by fujiapple852** [TelegramMessenger/Telegram-iOS#697]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
Regression bug: as of the iOS update today (31st Dec 2021) some inline keyboard button presses do not work (clicking on them does not register any action nor trigger the button press animation).  

Issue observed when there are multiple (~4) rows on the keyboard.  The buttons in the first few rows work, the buttons in the lower rows do not work.  Adding several messages _after_ the inline keyboard seems to avoid the problem (i.e. when the inline keyboard is no longer at the bottom of the screen).

There is also a slight layout quirk when the buttons appear which I suspect may be related.  The buttons appear on the screen and then quickly move positions (similar to a html "reflow").  

Update: This occurs when _editing_ an existing inline keyboard such that the old and new keyboards have differing numbers of rows and buttons.  It is notable that the number of buttons that continue to work after the edit is the same as the number of buttons that existed before the edit (as can be seen in the video below).

Reinstalling the Telegram app has not resolved the problem.

### Steps to Reproduce

Observed in an existing Telegram app, should be easy to see in any app which uses multi-row inline keyboards.  I can craft a demo app if necessary.

### Environment
**Device:** `iPhone and iPad`

**iOS version**: `15.2`

**App version:** `8.4 (22704)`

**Comment by fujiapple852** [comment]
Here is a video of the behaviour.  In the video, after selecting "Menu 3" I then proceed to press "Back to Main Menu" followed by "Item 9" down through to "Item 5" and for each of these button presses nothing happens.  Finally I press "Item 4" which works. 

https://user-images.githubusercontent.com/36075719/147817026-b292993a-edb0-47b2-bb07-2ead9da8546a.mov

**Comment by fujiapple852** [comment]
Related bug report: https://bugs.telegram.org/c/12654

**Comment by giladwa** [comment]
This makes users very unhappy, please prioritize!

**Comment by laktyushin** [comment]
Fixed
