### ISSUE TITLE
will more language support？

### ISSUE THREAD

**Issue by evilstyle** [TelegramMessenger/Telegram-iOS#7]
for ex  Chinese？

**Comment by stefandesu** [comment]
Telegram [recently introduced a translation platform](https://telegram.org/blog/translations-iv2) for their apps, letting everyone contribute to the translations. [Chinese (Simplified)](https://translations.telegram.org/zh-hans/) seems to be ~86% done for iOS. You can use it right now by opening [this link](https://t.me/setlanguage/zh-hans-beta) on the device where you use Telegram.
![img_f2927e1a3da3-1](https://user-images.githubusercontent.com/3275148/52900698-2fcb9680-31f9-11e9-85f7-3a1f767963ac.jpeg)
