### ISSUE TITLE
App settings reset after reboot

### ISSUE THREAD

**Issue by ethylmorphine** [TelegramMessenger/Telegram-iOS#70]
iOS 12.3.1, iPhone 7, Telegram 5.7 (1726)

Telegram settings do not persist on reboot and reset every time my phone runs out of battery.

Steps to reproduce:
1. Use Telegram.
2. Wait until your phone completely discharged.
3. Plug it in, boot into the system.
4. Open the app and find out that you gotta set everything up again. And again. And again. Please, fix it ASAP because it’s really darn annoying.

**Comment by Neurotoxin001** [comment]
I can confirm that the problem exists. Faced with this yesterday.
