### ISSUE TITLE
The telegram toolbar overlaps with the iPadOS Status Bar on the iPad mini (6th Generation) on iPadOS 15.2

### ISSUE THREAD

**Issue by S0ulf3re** [TelegramMessenger/Telegram-iOS#705]
### Checklist
- [x ] I am reporting an issue in existing functionality that does not work as intended
- [x ] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
The Telegram toolbar seems to be overlapping with the status bar in iPadOS. 

### Expected Behavior
The toolbar should be moved down or should have some padding applied so that it doesn't overlap with the official status bar

### Steps to Reproduce
N/A because it seems to always happen. So it must be an issue with the way the UI is designed

### Screenshots and Videos 
![IMG_B7385F620755-1](https://user-images.githubusercontent.com/50301900/148679454-1fa17da4-bcc5-4bb1-9662-58532ab9f53a.jpeg)

### Environment
**Device:** iPad mini (6th Generation)

**iOS version**: `15.2`

**App version:** `8.4`

**Comment by pokurt** [comment]
same here on mine as well, on ipadOS 15.4

**Comment by Ekulok** [comment]
Same, mine is using iPadOS 15.4.1

**Comment by Bustycat** [comment]
I received my iPad mini 6 yesterday, updated it to iPadOS 15.5, and installed Telegram (8.7.1) immediately. The problem is still there.

**Comment by dantherussell** [comment]
Can confirm that this now appears to be fixed on latest stable version

**Comment by S0ulf3re** [comment]
Indeed it has
