### ISSUE TITLE
Не работает экспорт в телеграм анимированных стикеров iOS

### ISSUE THREAD

**Issue by stayf** [TelegramMessenger/Telegram-iOS#708]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
Критичный баг. Не экспортируются анимированные стикеры из стороннего приложения в телеграм, если приложение телеграмма не было запущенно ранее. На андроиде проблемы нет.

P.S. Описывал баг еще в октября в репозиторие библиотеки для экспорта стикеров. Но владелец репозитория игнорит https://github.com/TelegramMessenger/TelegramStickersImport/issues/8

### Expected Behavior
Анимированные стикеры должны экспортироваться в телеграм даже если приложение телеграмма не было запущенно ранее.

### Actual Behavior
Если экспортировать стикеры(анимированные) в телеграм из стороннего приложения, а мобильное приложение телеграма не было запущено ранее, то в телеграме невозможно произвести экспорт(отображается два меню с экспортом и при создании ссылки вечно крутится троббер).
При повторной попытке экспортировать при уже запущенном телеграме все работает корректно.

### Steps to Reproduce
1. Убедиться что мобильное приложение телеграмма не запущенно! А если запущенно, то убрать его из памяти.
2. Открыть стороннее приложение по созданию анимированных стикеров(например https://apps.apple.com/app/id1575123344). Создать стикер и экспортировать в телеграм. 
3. Попытаться создать набор из экспортируемых стикеров.

### Screenshots and Videos 
https://user-images.githubusercontent.com/1859216/149062955-bfce6dec-39c0-4c75-b776-84686442ae52.mp4

### Environment
**Device:** `iPhone SE(первое поколение)`

**iOS version**: `15.2`

**App version:** `8.4`

**Comment by stayf** [comment]
@laktyushin Исправлено частично. Версия 8.5.1 ios 15.3. Теперь отображается одно меню с экспортом. Но ссылка не создается.
https://user-images.githubusercontent.com/1859216/153139076-d4641994-7e1f-4bf7-9f21-128d90a353e6.MP4

**Comment by stayf** [comment]
@laktyushin Когда почините? Я жду фикса этого бага уже почти пол года. **Сценарий основной и критически важный**. Уже другие разрабы просят фикс https://github.com/TelegramMessenger/TelegramStickersImport/issues/9

**Comment by stayf** [comment]
Починили. Спасибо!

**Comment by osmontanov** [comment]
> Починили. Спасибо!

Добрый день, можете дать совет по экпорту анимированных стикеров в телеграм пожалуйста?, очень нужна помощь ))
