### ISSUE TITLE
New Release? Version 8.4?

### ISSUE THREAD

**Issue by Sle77en** [TelegramMessenger/Telegram-iOS#709]
It will be nice, if you could compile a new ipa with version 8.4. Version 7.9 is to old to run. I want to install a censorship-free version of the Telegram app. That's why I don't want the AppStore version.

**Comment by tomsilom** [comment]
Same Request from my side, please update the ipa to newest version

**Comment by Sle77en** [comment]
> The *.ipa files in Releases are exactly the same as those sent to the App Store.

Are you serious? Why don't you give experienced iOS users the opportunity to install the Telegram app uncensored themselves?

**Comment by tomsilom** [comment]
Dear Ali-Fareed, your answer can't be correct, as the ipa version you offer here on github is version Telegram 7.9.1 (21656)
But in app store it is 8.4
When I install the ipa from github and try to login I get error 40-6  Update app to login installed version 7.9.1
So the ipa at github is not the same as at app store
