### ISSUE TITLE
> The *.ipa files in Releases are exactly the same as those sent to the App Store.

### ISSUE THREAD

**Issue by rutra123** [TelegramMessenger/Telegram-iOS#713]
> The *.ipa files in Releases are exactly the same as those sent to the App Store.

Are you serious? Why don't you give experienced iOS users the opportunity to install the Telegram app uncensored themselves? 

__Originally posted by @Sle77en in https://github.com/TelegramMessenger/Telegram-iOS/issues/709#issuecomment-1021235046__

**Comment by ali-fareed** [comment]
Please refer to https://github.com/TelegramMessenger/Telegram-iOS/issues/712#issuecomment-1021241056
