### ISSUE TITLE
Some of video circles loses it's sound after a few seconds from the beginning.

### ISSUE THREAD

**Issue by 42lacksky** [TelegramMessenger/Telegram-iOS#715]
### Checklist
- [ x ] I am reporting an issue in existing functionality that does not work as intended
- [ x ] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
Video loses its sound almost immediately (from 2 to 4 seconds) after playback starts. Moreover, videos recorded immediately after the problematic one, are not likely to have reproduce the issue. The problem occurs in some reasonable amount of time (from an hour to the days). 

Me and my friends are encountering it since 03.06.2021.

### Expected Behavior
Circle video should play from the beginning till the end with no sound loss.

### Actual Behavior
Some of video circles loses it's sound after a few seconds from the beginning.

### Steps to Reproduce
Couldn't reproduce, it happens randomly. 

### Environment
**Device:** `iPhone 13 Pro Max`

**iOS version**: `15.3`

**App version:** `8.5.1`

**Comment by ShahaneMirzoyan** [comment]
I have experienced this issue, too. Seems like it can be older, here is a bug report back to May 2021 and Telegram iOS 7.7 (20729) –  https://bugs.telegram.org/c/5465

Could you please look it up?

**Comment by matthewstifler** [comment]
Very annoying if I say so myself!

**Comment by laktyushin** [comment]
We would appreciate more detailed steps to reproduce the issue.

**Comment by laktyushin** [comment]
It seems to be working fine, no more reports came in the last months. Let's mark it as closed.
