### ISSUE TITLE
Some animations on the chat interface disappear

### ISSUE THREAD

**Issue by SeaIceNX** [TelegramMessenger/Telegram-iOS#716]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
Slide the screen up and down.

### Expected Behavior
Message scrolls, and each message will have a separate linear animation.

### Actual Behavior
The message scrolls, but the interval remains unchanged.

### Steps to Reproduce
always

### Environment
**Device:** `iPhone Xs`

**iOS version**: `15.3`

**App version:** `8.5.1`

**Comment by laktyushin** [comment]
Intended.

**Comment by SeaIceNX** [comment]
Which version did this start with?

**Comment by SeaIceNX** [comment]
> Intended.



> Intended.

Which version did this start with?
