### ISSUE TITLE
Just curious, which IDE the develop team use?

### ISSUE THREAD

**Issue by cnSchwarzer** [TelegramMessenger/Telegram-iOS#729]
I think this repository is only be able to build with Xcode. I don't think the generated project can be efficiently developed only using Xcode. 
Or this repository is only for build propose?

**Comment by tmandalo** [comment]
it can be buid with cli and ide isn't that important, they can code in vim, it's up to developer

**Comment by ali-fareed** [comment]
It is Xcode.
