### ISSUE TITLE
Cannot build the IPA / generate project at the second time

### ISSUE THREAD

**Issue by shivanraptor** [TelegramMessenger/Telegram-iOS#733]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
Cannot run the command twice, errors are reported.

### Expected Behavior
The command that runs on the second time should be okay to run twice without a problem.

### Actual Behavior
But errors are shown when generating the project:
```
ERROR: /Users/adv/Documents/workspace/Xcode/xCodeProjects/telegram/release-8.6/build-system/tulsi/src/TulsiGenerator/BUILD:30:14: output 'src/TulsiGenerator/tulsi_generator_lib_objs/BazelAspectInfoExtractor.swift.partial_swiftmodule' was not created
ERROR: /Users/adv/Documents/workspace/Xcode/xCodeProjects/telegram/release-8.6/build-system/tulsi/src/TulsiGenerator/BUILD:30:14: output 'src/TulsiGenerator/tulsi_generator_lib_objs/BazelBuildEvents.swift.partial_swiftmodule' was not created
ERROR: /Users/adv/Documents/workspace/Xcode/xCodeProjects/telegram/release-8.6/build-system/tulsi/src/TulsiGenerator/BUILD:30:14: output 'src/TulsiGenerator/tulsi_generator_lib_objs/BazelBuildSettings.swift.partial_swiftmodule' was not created
ERROR: /Users/adv/Documents/workspace/Xcode/xCodeProjects/telegram/release-8.6/build-system/tulsi/src/TulsiGenerator/BUILD:30:14: output 'src/TulsiGenerator/tulsi_generator_lib_objs/BazelBuildSettingsFeatures.swift.partial_swiftmodule' was not created
```
The command for generating the project is:
```
python3 build-system/Make/Make.py --overrideXcodeVersion --bazel="$HOME/.bazel/bin/bazel" --cacheDir="$HOME/telegram-bazel-cache" generateProject --configurationPath="$HOME/telegram-configuration"
```

as well as building the IPA:
```
# Configuration: 7a639284f44c6fde4dc0fc40202af18202445c8ba36f019aeb934b9494b5c62f
# Execution platform: @local_config_platform//:host
submodules/SSignalKit/SSignalKit/Source/SSignalKit/SQueueLocalObject.m:32:16: error: variable 'value' set but not used [-Werror,-Wunused-but-set-variable]
    __block id value = self->valueRef;
               ^
1 error generated.
Error in child process '/usr/bin/xcrun'. 1
Target //Telegram:Telegram failed to build
INFO: Elapsed time: 18.683s, Critical Path: 1.79s
INFO: 570 processes: 266 disk cache hit, 292 internal, 12 local.
FAILED: Build did NOT complete successfully
```
The command for building the IPA is:
```
python3 build-system/Make/Make.py --overrideXcodeVersion --bazel="$HOME/.bazel/bin/bazel" --cacheDir="$HOME/telegram-bazel-cache" build --configurationPath="$HOME/telegram-configuration" --buildNumber=11062 --configuration=release_universal
```

I didn't change anything and I tried to clean the project with this command before I run `generateProject` and `build`:
```
python3 build-system/Make/Make.py --overrideXcodeVersion --bazel="$HOME/.bazel/bin/bazel" --cacheDir="$HOME/telegram-bazel-cache" clean
```

### Steps to Reproduce
1. Build the App for the first time using the command above. No problem, IPA is generated.
2. Run the same command for the second time. Failed
3. Tried to clean the project and re-run the build app command, failed as well.
4. Same for generating the project.

### Environment
**macOS version**: `12.2.1`
**App version:** `8.6`
**Xcode version:** `13.3`
**Bazel version:** `5.0.0`

**Comment by shivanraptor** [comment]
You mean downgrading to Xcode 13.2.1? Let me try.

**Comment by shivanraptor** [comment]
Using Xcode 13.2.1 (by switching to this version via `sudo xcode-select --switch`, the build is successful again (p.s. still using Xcode 13.3's Command Line Tools). Probably need some Xcode 13.3 workarounds in the future.

**Comment by ali-fareed** [comment]
I was unable to build the app using Xcode 13.3. Looks like there are some issues with Bazel swift rules and with the swift compiler itself.

**Comment by liujia1993** [comment]
Can you help me

The command for building the IPA is:
`python3 build-system/Make/Make.py --overrideXcodeVersion --bazel="$HOME/bazel-dist/bazel" --cacheDir="$HOME/telegram-bazel-cache" build --configurationPath="$HOME/telegram-configuration" --buildNumber=2300 --configuration=release_universal`

But errors are shown when generating the project:
`ERROR: /Users/da/Telegram-iOS/Telegram/BUILD:1509:14: ProcessEntitlementsFiles Telegram/IntentsExtension_entitlements.entitlements failed: (Exit 1): plisttool failed: error executing command 
  (cd /private/var/tmp/_bazel_da/90132f016756581685f8aa3261cd2681/execroot/__main__ && \
  exec env - \
    APPLE_SDK_PLATFORM=iPhoneOS \
    APPLE_SDK_VERSION_OVERRIDE=15.2 \
    XCODE_VERSION_OVERRIDE=13.2.1.13C100 \
  bazel-out/darwin-opt-exec-2B5CBBC6-ST-8bd7c7db9774/bin/external/build_bazel_rules_apple/tools/plisttool/plisttool bazel-out/applebin_ios-ios_armv7-opt-ST-2b171abadebf/bin/Telegram/entitlements/IntentsExtensionplisttool-control)
# Configuration: a1da070f8e70f8e9c50feff6caf7157881963e865209bcd35277ef599567031c
# Execution platform: @local_config_platform//:host
ERROR: In target "//Telegram:IntentsExtension"; the bundle_id ("com.cloud.telegram.chat.SiriIntents") did not match the id in the entitlements ("com.cloud.telegram.chat.siri").
Target //Telegram:Telegram failed to build
INFO: Elapsed time: 6402.817s, Critical Path: 4397.32s
INFO: 9273 processes: 20 disk cache hit, 1241 internal, 8012 local.
FAILED: Build did NOT complete successfully
`
Environment
macOS version: 12.4
App version: 8.7
Xcode version: 13.2.1
Bazel version: 5.1.0

**Comment by ali-fareed** [comment]
I believe this line is self-explanatory:

> ERROR: In target "//Telegram:IntentsExtension"; the bundle_id ("com.cloud.telegram.chat.SiriIntents") did not match the id in the entitlements ("com.cloud.telegram.chat.siri").

**Comment by liujia1993** [comment]
I only know Telegram.mobileprovision how to configure

How do you configure these files：
`BroadcastUpload.mobileprovision
Intents.mobileprovision
NotificationContent.mobileprovision
NotificationService.mobileprovision
Share.mobileprovision
WatchApp.mobileprovision
WatchExtension.mobileprovision
Widget.mobileprovision`
