### ISSUE TITLE
No build the app and generate an Xcode project

### ISSUE THREAD

**Issue by igrssv** [TelegramMessenger/Telegram-iOS#737]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
I perform all the actions according to the instructions and at the time of the application reset I get an error.
Tried several times already, but 52 minutes of waiting did not give a result.
Used this script to reset:
`python3 build-system/Make/Make.py \
    --cacheDir="$HOME/telegram-bazel-cache" \
    build \
    --configurationPath="$HOME/telegram-configuration" \
    --buildNumber=100001 \
    --configuration=release_universal`

I also tried to immediately build the xCode project using this script:
`python3 build-system/Make/Make.py \
    --cacheDir="$HOME/telegram-bazel-cache" \
    generateProject \
    --configurationPath="$HOME/telegram-configuration" \
    --disableExtensions`
"

### Expected Behavior
Build the app and generate an Xcode project

### Actual Behavior
When trying to build the application, this error occurs:
`ERROR: /Users/igrssv/Telegram-iOS/Telegram/BUILD:661:18: Processing and signing TelegramWatchExtension failed: (Exit 1): process-and-sign--1805968442.sh failed: error executing command 
  (cd /private/var/tmp/_bazel_igrssv/1f1e5561112ee2d6dda59d0dec86d1fc/execroot/__main__ && \
  exec env - \
    APPLE_SDK_PLATFORM=WatchOS \
    APPLE_SDK_VERSION_OVERRIDE=8.3 \
    XCODE_VERSION_OVERRIDE=13.2.1.13C100 \
  bazel-out/applebin_watchos-watchos_armv7k-opt-ST-7e2263d114c4/bin/Telegram/TelegramWatchExtension-intermediates/process-and-sign--1805968442.sh should_sign should_compress)
Configuration: f1421a38ab02ac4b4c98d3bc6970bb1a7be287fa721ecc9652d6b85ad81ebf7d
 Execution platform: @local_config_platform//:host
ERROR: Unable to find an identity on the system matching the ones in external/build_configuration/provisioning/WatchExtension.mobileprovision
Target //Telegram:Telegram failed to build
INFO: Elapsed time: 3155.224s, Critical Path: 2822.09s
INFO: 9308 processes: 34 disk cache hit, 1231 internal, 8043 local.
FAILED: Build did NOT complete successfully
Traceback (most recent call last):
  File "/Users/igrssv/Telegram-iOS/build-system/Make/Make.py", line 648, in <module>
    build(bazel=bazel_path, arguments=args)
  File "/Users/igrssv/Telegram-iOS/build-system/Make/Make.py", line 430, in build
    bazel_command_line.invoke_build()
  File "/Users/igrssv/Telegram-iOS/build-system/Make/Make.py", line 317, in invoke_build
    call_executable(combined_arguments)
  File "/Users/igrssv/Telegram-iOS/build-system/Make/BuildEnvironment.py", line 60, in call_executable
    subprocess.check_call(resolved_arguments, env=resolved_env)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/igrssv/Telegram-iOS/build-input/bazel-5.0.0-darwin-arm64', 'build', 'Telegram/Telegram', '--override_repository=build_configuration=/Users/igrssv/telegram-configuration', '--announce_rc', '--features=swift.use_global_module_cache', '--verbose_failures', '--features=swift.skip_function_bodies_for_derived_files', '--jobs=8', '--define=buildNumber=100001', '--define=telegramVersion=8.6', '--features=swift.split_derived_files_generation', '--disk_cache=/Users/igrssv/telegram-bazel-cache', '-c', 'opt', '--ios_multi_cpus=armv7,arm64', '--watchos_cpus=armv7k,arm64_32', '--apple_generate_dsym', '--output_groups=+dsyms', '--features=swift.opt_uses_wmo', '--features=swift.opt_uses_osize', '--swiftcopt=-num-threads', '--swiftcopt=0', '--features=dead_strip', '--objc_enable_binary_stripping', '--apple_bitcode=watchos=embedded']' returned non-zero exit status 1.`

When trying to build a project in xCode, the following error occurs:

`FAILED: Build did NOT complete successfully
Traceback (most recent call last):
  File "/Users/igrssv/Telegram-iOS/build-system/Make/Make.py", line 646, in <module>
    generate_project(bazel=bazel_path, arguments=args)
  File "/Users/igrssv/Telegram-iOS/build-system/Make/Make.py", line 396, in generate_project
    generate(
  File "/Users/igrssv/Telegram-iOS/build-system/Make/ProjectGeneration.py", line 45, in generate
    call_executable(tulsi_build_command)
  File "/Users/igrssv/Telegram-iOS/build-system/Make/BuildEnvironment.py", line 60, in call_executable
    subprocess.check_call(resolved_arguments, env=resolved_env)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/igrssv/.bazel/bin/bazel', 'build', '//:tulsi', '--macos_cpus=arm64', '--xcode_version=13.2.1', '--use_top_level_targets_for_symlinks', '--verbose_failures']' returned non-zero exit status 1.
igrssv@Air-Igor Telegram-iOS % 
`

### Environment
**App version:** `8.6`
**Bazel version:** `5.0.0`
**xCode version:** `13.2.1`
**MacOS version: ** `12.1`

**Comment by zhangxu0302** [comment]
You can try dropping the Xcode version down to 13.2.1

**Comment by shivanraptor** [comment]
You did not replace the provisioning profiles in the configuration folder with the ones you generated on Apple Developer Portal, or the profiles are expired.

**Comment by xiaoshuojie1019** [comment]
> 

I've replaced the provisioning profiles in the configuration folder ，but t still report the above error

**Comment by visoon** [comment]
make sure your bezel version is over 5.0.0, then try again.

**Comment by visoon** [comment]
replace the tulsi with official version.

**Comment by Wangbinbin123** [comment]
> replace the tulsi with official version.

how do it?

**Comment by liujia1993** [comment]
I have the same problem. Have you solved it yet?

**Comment by dangkhoasdc** [comment]
I got the same issue after upgrading Xcode 14.0. To fix the issue, I update `build_bazel_rules_apple` as following:
```bazel
http_archive(
    name = "build_bazel_rules_apple",
    sha256 = "90e3b5e8ff942be134e64a83499974203ea64797fd620eddeb71b3a8e1bff681",
    url = "https://github.com/bazelbuild/rules_apple/releases/download/1.1.2/rules_apple.1.1.2.tar.gz",
    patches = [
        # Bypass checking ios unit test runner when building MP ios applications.
        "@//third_party:build_bazel_rules_apple_bypass_test_runner_check.diff"
    ],
    patch_args = [
        "-p1",
    ],
)
```

**Comment by tboxSol** [comment]
Anyone managed to solve it?
