### ISSUE TITLE
Global account renaming instead of local person renaming

### ISSUE THREAD

**Issue by yahorbarkouski** [TelegramMessenger/Telegram-iOS#739]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
Describe the issue that you are experiencing
Backstory: I added my mom's account to my telegram app for a while, then logged out from it and noticed that globally my account name had changed to the name I signed on my mom's telegram. The same thing happened when I created my second telegram account and tried to rename my first account from the second account - my GLOBAL name changed to my local name from the second account, and this is reproduced even if I log out of my second account from my phone and do this chain again.

### Expected Behavior
My global name should only be changed from the account that has that name

### Actual Behavior
Instead, I can change the global name of one account from another account that was once tied to the same Telegram app. I don't want my name globally to look like "my son" as I signed my mom's 😄 

### Steps to Reproduce
1. Log in to the second account from the same device
2. Change the name of the first account from the second device
3. Wait a while

### Environment
**Device:** `iPhone/iPad X`

**iOS version**: `13.X`

**App version:** `7.X`

**Comment by shivanraptor** [comment]
I can't repeat this behavior. Which app version are you using?

**Comment by yahorbarkouski** [comment]
Still reproducing in 8.7.1.229827 Stable
