### ISSUE TITLE
Notifications problems

### ISSUE THREAD

**Issue by Neurotoxin001** [TelegramMessenger/Telegram-iOS#74]
Telegram iOS 5.7
iOS 12.3.1

1. I can't hide this popup with disabled notifications:
![image](https://user-images.githubusercontent.com/39812401/59898437-6e689c00-93f9-11e9-8678-71b164e7d718.png)

2. Telegram uses too much background time and it's eats too much battery (I have some big public chats, but disabled all background updating in iOS settings and disabled all notifications in Telegram/iOS settings too):
![image](https://user-images.githubusercontent.com/39812401/59898486-ae2f8380-93f9-11e9-9d24-755b88536e07.png)

**Comment by Kylmakalle** [comment]
Tg aggressively fetches updates in background, refreshing bage number, chats and etc.

Probably, using multiple accounts and setting one that have less chats before exit could help

**Comment by stefandesu** [comment]
I recently posted about the battery issue on Reddit and someone confirmed my suspicion there as well. I'm wondering whether I can completely disable background fetching in a fork and use that. I'll try to find out but if someone has an idea how to do that, I'd be very grateful.

**Comment by Kylmakalle** [comment]
@stefandesu background fetching is somehow bugged and don't work in forks
You can check out [Nicegram](https://t.me/nicegramapp)

**Comment by stefandesu** [comment]
> @stefandesu background fetching is somehow bugged and don't work in forks
> You can check out [Nicegram](https://t.me/nicegramapp)

I mean if background fetching doesn't work in forks, that's exactly what I want, isn't it? 

Thanks for the tip about Nicegram, I'll try it out.

**Comment by Neurotoxin001** [comment]
Version 5.8.1 still eats battery and I still can't remove this notification popup, nothing changed.

**Comment by shivanraptor** [comment]
Version 5.8.1 ? The latest release is 5.8.

**Comment by Neurotoxin001** [comment]
> Version 5.8.1 ? The latest release is 5.8.

https://apps.apple.com/us/app/telegram-messenger/id686449807

> Version 5.8.1

**Comment by shivanraptor** [comment]
> > Version 5.8.1 ? The latest release is 5.8.
> 
> https://apps.apple.com/us/app/telegram-messenger/id686449807
> 
> > Version 5.8.1

Seems you're not talking about this repository. Please be reminded that the issue list is about this Github repo / releases.

**Comment by Neurotoxin001** [comment]
> Seems you're not talking about this repository. Please be reminded that the issue list is about this Github repo / releases.

1. This repo about iOS app and don't matter where is it released
2. https://github.com/peter-iakovlev/Telegram-iOS/releases - here is already 5.8.1

**Comment by shivanraptor** [comment]
But from the time you asked, v5.8.1 hasn't released yet. Anyways, the notification in Fork is always a problem. Either incorrect, no badge count, or excessive use of battery by the background task. We shall look for a solution together.

**Comment by Neurotoxin001** [comment]
Still can't remove notification popup on 5.9. Battery seems fine now, but need to look more time.

**Comment by Neurotoxin001** [comment]
![image](https://user-images.githubusercontent.com/39812401/60821890-1a0d3c80-a1ad-11e9-8afd-2de1924984df.png)

Ain't funny anymore.

**Comment by shivanraptor** [comment]
The badge count problem comes back on `release-5.9`. Even with valid APNS certificate uploaded to Telegram Core, the badge count doesn't appear.

**Comment by Neurotoxin001** [comment]
Still can't hide notification popup if they are disabled even in 5.10.

**Comment by Neurotoxin001** [comment]
> Still can't hide notification popup if they are disabled even in 5.10.

5.12.2 here and still no fix.

**Comment by Neurotoxin001** [comment]
> Still can't hide notification popup if they are disabled even in 5.10.

Not fixed in 5.13

**Comment by Neurotoxin001** [comment]
> Still can't hide notification popup if they are disabled even in 5.10.

Not fixed in 5.14

**Comment by Neurotoxin001** [comment]
> Still can't hide notification popup if they are disabled even in 5.10.

6.2.1 still not fixed.

**Comment by Neurotoxin001** [comment]
> Still can't hide notification popup if they are disabled even in 5.10.

7.2.1 not fixed
