### ISSUE TITLE
Compile time errors with LegacyComponents

### ISSUE THREAD

**Issue by NaruFGT** [TelegramMessenger/Telegram-iOS#743]
I've been trying to build Telegram-iOS for a week now and I've silenced a few warnings regarding unused variables in submodules MtProtoKit, SSignalKit, and UIKitRUntimeUtils by modifying the Bazel `BUILD` files with `-Wno-error=unused-but-set-parameter` in the `copts`.
I've unfortunately run into an issue with `submodules/LegacyComponents/Sources/ActionStage.mm` in `isExecutingActorsWithGenericPath`
```
submodules/LegacyComponents/Sources/ActionStage.mm:479:16: error: cannot initialize return object of type 'bool' with an rvalue of type 'nullptr_t'
        return nil;
```

For context, I cloned the repo
`git clone --recursive -j8 git@github.com:TelegramMessenger/Telegram-iOS.git`
I edited `variables.bzl`
```
NaruFGT@censored:~/Documents/Telegram-iOS $ cat $HOME/telegram-configuration/variables.bzl                                                    

telegram_bundle_id = "censored"
telegram_api_id = "censored"
telegram_api_hash = "censored"
telegram_team_id = "censored"
telegram_app_center_id = "0"
telegram_is_internal_build = "true"
telegram_is_appstore_build = "false"
telegram_appstore_id = "0"
telegram_app_specific_url_scheme = "tg"
telegram_aps_environment = "production"
telegram_enable_siri = True
telegram_enable_icloud = True
telegram_enable_watch = True
```

Not that it's relevant yet but I created the configuration profiles in `$HOME/telegram-configuration/profiles/`

I then ran the build script with
`python3 build-system/Make/Make.py --cacheDir="$HOME/telegram-bazel-cache" --bazel="/usr/local/bin/bazel" --overrideBazelVersion --overrideXcodeVersion build --configurationPath="$HOME/telegram-configuration" --buildNumber=100001 --configuration=release_arm64`

From what I can tell ActionStage is third party code from [coderyi](https://github.com/coderyi/ActionStage) and I don't see any issues or PR on that repository. 
I'm surprised that code that hasn't been modified in 5 years is giving me compile time errors  so I suspect it's a recent change to the iOS SDK?

[build-output.TXT](https://github.com/TelegramMessenger/Telegram-iOS/files/8367774/build-output.TXT)

**Comment by shivanraptor** [comment]
Reading from your source code, the problem is, you used **Xcode 13.3** to build the source code. This version is known as unable to build the source code. Try using Xcode 13.2.1.

See #733 as well.

**Comment by lexuanquynh** [comment]
To use Tulsi, clone this repository and run build_and_run.sh. By default this will install the Tulsi.app inside $HOME/Applications. Additionally, following options are available:

-b: Bazel binary that Tulsi should use to build and install the app (Default is bazel)
-d: The folder where to install the Tulsi app into (Default is $HOME/Applications)
-x: The Xcode version Tulsi should be built for (Default is 13.2.1)

**Comment by NaruFGT** [comment]
Thanks @shivanraptor!
I did end up switching to Xcode 13.2.1 to play with the build.
It looks like there has been progress since #733 so I imagine these issues will be resolved soon (and I'll be glad to not have a second Xcode.app take up my precious disk space.)
I do think that these legacy components need to be reviewed, the method that failed to build `isExecutingActorsWithGenericPath` appears to be dead code.
```
NaruFGT@censored:~/Documents/Telegram-iOS $ git grep isExecutingActorsWithGenericPath
submodules/LegacyComponents/PublicHeaders/LegacyComponents/ActionStage.h:55:- (bool)isExecutingActorsWithGenericPath:(NSString *)genericPath;
submodules/LegacyComponents/Sources/ActionStage.mm:473:- (bool)isExecutingActorsWithGenericPath:(NSString *)genericPath
```
If I have time next week I'll be digging more into the ActionStage submodule to see how much of it is still used in the current release.

**Comment by NaruFGT** [comment]
@lexuanquynh I appreciate the response. 
I'm not familiar with Bazel or the related components so I'm excited to look into these tools.
