### ISSUE TITLE
I can't generate an Xcode project

### ISSUE THREAD

**Issue by jalalimehdi** [TelegramMessenger/Telegram-iOS#749]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
I perform all the actions according to the instructions but I can't  generate an Xcode project.

### Expected Behavior
generate an Xcode project

### Actual Behavior
 1-(without sudo) when generating the project with this command :
```
python3 build-system/Make/Make.py \
    --cacheDir="$HOME/telegram-bazel-cache" \
    generateProject \
    --configurationPath="$HOME/telegram-configuration" \
    --disableExtensions
```
this error is shown

`Process: Tulsi [41408] Path: /Users/USER/Documents/*/Tulsi.app/Contents/MacOS/Tulsi Identifier: com.google.Tulsi Version: 0.20210318.88 (0.20210318.88) Code Type: X86-64 (Native) Parent Process: Python [41384] Responsible: Terminal [3231] Crashed Thread: 0 Dispatch queue: com.google.Tulsi.xcodeProjectGenerator`

```
Application Specific Information: *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: \'Couldn't posix_spawn: error 2' terminating with uncaught exception of type NSException abort() called
```

```
subprocess.CalledProcessError: Command '['/Users/jalalimehdi/Documents/REPOS_TG/Telegram-iOS/build-input/gen/project/Tulsi.app/Contents/MacOS/Tulsi', '--', '--verbose', '--genconfig', '/Users/jalalimehdi/Documents/REPOS_TG/Telegram-iOS/build-input/gen/project/Telegram.tulsiproj:Telegram', '--bazel', '/Users/jalalimehdi/Documents/REPOS_TG/Telegram-iOS/build-input/gen/project/bazel', '--outputfolder', '/Users/jalalimehdi/Documents/REPOS_TG/Telegram-iOS/build-input/gen/project', '--no-open-xcode']' died with <Signals.SIGABRT: 6>. 


```
 2-(with sudo) when generating the project with this command :
```
sudo python3 build-system/Make/Make.py \
    --cacheDir="$HOME/telegram-bazel-cache" \
    generateProject \
    --configurationPath="$HOME/telegram-configuration" \
    --disableExtensions
```
these lines are show in my terminal
```
No matching processes were found
INFO: Analyzed target //:tulsi (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //:tulsi up-to-date:
  bazel-bin/tulsi.zip
INFO: Elapsed time: 0.174s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
[Syslog] Tulsi CLI: version 0.20210318.88
[Syslog] Create project: Telegram
```
after
I don't see any change in my terminal
my terminal is not respond the display on my screen is stop at an unusual place like this screen shot.

### Screenshots and Videos 
Also, here's a screenshot: 

<img width="665" alt="Screen Shot 2022-04-07 at 5 49 11 PM" src="https://user-images.githubusercontent.com/4976108/162211195-40c4e6b5-fe0f-46fd-8c58-8f45dad94d39.png">

### Steps to Reproduce
1. Build the app (I succeeded to build the app)
2. Generate an Xcode project (Faild)

### Environment
**App version: ** `8.6`

**Bazel version: ** `5.1.0`

**xCode version: ** `13.2.1`

**MacOS version: ** `12.3.1`

**Comment by sherlockmm** [comment]
upgrade Tulsi version and replace

**Comment by jalalimehdi** [comment]
Hi @sherlockmm  thanks for your assistance.
upgrade Tulsi version to Tulsi 0.20220209.427587075  , 0.20220209.88
unfortunately I couldn't generate an Xcode project.
these lines are show in my terminal

```
jalalimehdi@jalalimehdis-iMac Telegram-iOS % sudo python3 build-system/Make/Make.py \   
    --bazel="$HOME/bazel-dist/bazel" \
    --cacheDir="$HOME/telegram-bazel-cache" \
    generateProject \
    --configurationPath="$HOME/telegram-configuration" \
    --disableExtensions\
    --disableProvisioningProfiles
No matching processes were found
INFO: Analyzed target //:tulsi (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //:tulsi up-to-date:
  bazel-bin/tulsi.zip
INFO: Elapsed time: 0.148s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
[Syslog] Tulsi CLI: version 0.20220209.88
[Syslog] Create project: Telegram
```

 I don't see any change in my terminal.

**Comment by sherlockmm** [comment]
1.  Please read the README
2. `python3 build-system/Make/Make.py --bazel="$HOME/bazel-dist/bazel"  clean`
3. upgrade Tulsi version and replace --> cd /build-system---> replace  Tulsi
4. update 'version.json'

**Comment by gosgos11** [comment]
I met the same error:

**App version: ** 8.6.1

**Bazel version: ** 5.1.0/5.0.0

**xCode version: ** 13.2.1

**MacOS version: ** 12.3.1

2022-05-18 18:33:27.599 Tulsi[58597:665722] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Couldn't posix_spawn: error 2'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007ff80641e1e3 __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007ff80617ec13 objc_exception_throw + 48
	2   Foundation                          0x00007ff807273095 -[NSConcreteTask launchWithDictionary:error:] + 5081
	3   Tulsi                               0x000000010e2bbf5f $s14TulsiGenerator012XcodeProjectB0C20executePythonProcess017_3D27909A8CA7F8C4l11BE25046CB74K1BLL_7onErrorySS_ys5Int32V_SStctF + 1119xa
	4   Tulsi                               0x000000010e2b0580 $s14TulsiGenerator012XcodeProjectB0C20cleanCachedDsymPaths017_3D27909A8CA7F8C4m11BE25046CB74L1BLLyyF + 80
	5   Tulsi                               0x000000010e2b051b $s14TulsiGenerator012XcodeProjectB0C05buildcD13WithMainGroup017_3D27909A8CA7F8C4m11BE25046CB74L1BLL_18stubInfoPlistPathsAC09GenerateddQ0AELLVAA8PBXGroupC_AA04StubqrS0VtKFyyXEfU8_ + 27
	6   Tulsi                               0x000000010e2ad9d7 $s14TulsiGenerator012XcodeProjectB0C05buildcD13WithMainGroup017_3D27909A8CA7F8C4m11BE25046CB74L1BLL_18stubInfoPlistPathsAC09GenerateddQ0AELLVAA8PBXGroupC_AA04StubqrS0VtKF13profileActionL__6actionySS_yyKXEtKF + 343
	7   Tulsi                               0x000000010e2a1030 $s14TulsiGenerator012XcodeProjectB0C05buildcD13WithMainGroup017_3D27909A8CA7F8C4m11BE25046CB74L1BLL_18stubInfoPlistPathsAC09GenerateddQ0AELLVAA8PBXGroupC_AA04StubqrS0VtKF + 7488
	8   Tulsi                               0x000000010e29d9c5 $s14TulsiGenerator012XcodeProjectB0C08generatecD8InFoldery10Foundation3URLVAGKF + 2917
	9   Tulsi                               0x000000010e29821b $s14TulsiGenerator0a12XcodeProjectB0C08generatecD8InFoldery10Foundation3URLVAGKF + 219
	10  Tulsi                               0x000000010e33a577 $s5Tulsi0A23GeneratorConfigDocumentC28generateXcodeProjectInFolder_04withbC016workspaceRootURL10messageLog20projectInfoExtractorAC16GenerationResultO10Foundation0M0V_0aB00abC0CAmA07MessageO8Protocol_pSgAN0agqR0CSgtFZ + 1383
	11  Tulsi                               0x000000010e2e7c53 $s5Tulsi29HeadlessXcodeProjectGeneratorV8generateyyKF + 8851
	12  Tulsi                               0x000000010e3662f4 $s5Tulsi4main33_54889CDB73DF4DC25B8AC2F5AB42D120LLyyFyycfU_ + 612
	13  Tulsi                               0x000000010e1d3c88 $sIeg_IeyB_TR + 40
	14  libdispatch.dylib                   0x00007ff8061200cc _dispatch_call_block_and_release + 12
	15  libdispatch.dylib                   0x00007ff806121317 _dispatch_client_callout + 8
	16  libdispatch.dylib                   0x00007ff806127317 _dispatch_lane_serial_drain + 672
	17  libdispatch.dylib                   0x00007ff806127dfd _dispatch_lane_invoke + 366
	18  libdispatch.dylib                   0x00007ff806131eee _dispatch_workloop_worker_thread + 753
	19  libsystem_pthread.dylib             0x00007ff8062d8fd0 _pthread_wqthread + 326
	20  libsystem_pthread.dylib             0x00007ff8062d7f57 start_wqthread + 15
)
libc++abi: terminating with uncaught exception of type NSException
Traceback (most recent call last):
  File "build-system/Make/Make.py", line 646, in <module>
    generate_project(bazel=bazel_path, arguments=args)
  File "build-system/Make/Make.py", line 396, in generate_project
    generate(
  File "/build-system/Make/ProjectGeneration.py", line 130, in generate
    call_executable([
  File "/build-system/Make/BuildEnvironment.py", line 60, in call_executable
    subprocess.check_call(resolved_arguments, env=resolved_env)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['build-input/gen/project/Tulsi.app/Contents/MacOS/Tulsi', '--', '--verbose', '--genconfig', '/build-input/gen/project/Telegram.tulsiproj:Telegram', '--bazel', '/build-input/gen/project/bazel', '--outputfolder', '/build-input/gen/project', '--no-open-xcode']' died with <Signals.SIGABRT: 6>.

**Comment by bzz445** [comment]
> 1. Please read the README
> 
>     2. `python3 build-system/Make/Make.py --bazel="$HOME/bazel-dist/bazel"  clean`
> 
>     3. upgrade Tulsi version and replace --> cd /build-system---> replace  Tulsi
> 
>     4. update 'version.json'

Thank you. It works for me. I just cloned and replaced build-system/tulsi

**Comment by ldu1101** [comment]
> > 1. Please read the README
> >    
> >    2. `python3 build-system/Make/Make.py --bazel="$HOME/bazel-dist/bazel"  clean`
> >    3. upgrade Tulsi version and replace --> cd /build-system---> replace  Tulsi
> >    4. update 'version.json'
> 
> Thank you. It works for me. I just cloned and replaced build-system/tulsi

How to upgrade Tulsi version？help me

**Comment by bzz445** [comment]
@ldu1101 clean `build-system/tulsi` folder and clone https://github.com/bazelbuild/tulsi to `build-system/tulsi`

**Comment by ldu1101** [comment]
> @ldu1101 clean `build-system/tulsi` folder and clone https://github.com/bazelbuild/tulsi to `build-system/tulsi`

Thank you, brother. I followed this operation once, but reported another error. The file could not be downloaded. I tried to download it manually, but every time I re-execute the command, the downloaded file will be cleared. Have you encountered this problem
![Uploading 22.png…]()
