### ISSUE TITLE
CarPlay integration

### ISSUE THREAD

**Issue by Supereg** [TelegramMessenger/Telegram-iOS#75]
Hello there, 

I hope this is the right place to ask this question. I wonder if there are any plans or ambitions to add CarPlay support into the Telegram iOS app. I know that Apple is verifies every app trying to support CarPlay but I think the Telegram messenger should be big enough to get in contact with Apple about that. As Telegram sees itself way ahead of the competition, this is the one spot Telegram lacks behind and making the operation of Telegram in car pretty annoying/impossible.
Am I missing any information?

Thanks and keep up the good work.

Best regards
Andi

**Comment by shivanraptor** [comment]
What do you expect the functionality of the Telegram CarPlay app? It's much more convenient to use Telegram with a phone (coz keyboard input is a problem with CarPlay). 

p.s. CarPlay apps support 2 main categories: Playable contents (`com.apple.developer.playable-content`) (e.g. audio, video, etc.) and Navigations (`com.apple.developer.carplay-maps`) (e.g. Maps).

**Comment by ethylmorphine** [comment]
Telegram has awesome audio playback capabilities. CarPlay might be used just for that. Or for audio messages and phone calls. I guess, it will be way more useful than animated cherry sticker that shakes its ass.

**Comment by Supereg** [comment]
> What do you expect the functionality of the Telegram CarPlay app? It's much more convenient to use Telegram with a phone (coz keyboard input is a problem with CarPlay).

Yes, but this gets trick and illegal pretty quick when driving.

I was thinking about just letting Siri read out the unread messages and reply with Siri by dictating (just like in iMessage and WhatsApp). Of course the fancy stuff like voice messages and the fancy stuff like @ethylmorphine mentioned it could be added too.
But for the start, Basic reading and dictating functionality would be awesome.

**Comment by godzillante** [comment]
It might be just like WhatsApp integration, at least initially. It's really boring having 99% of my conversations on Telegram and not being able to use it in the car.

**Comment by ikrasnoselskikh** [comment]
But sending voice messages should be a really good feature.
I would use this feature every day on the way to my work￼.

**Comment by vladsamoy** [comment]
It looks like it's in Beta-mode right now.

**Comment by Supereg** [comment]
Anyway to access the beta? I'm not really informed about the Telegram development workflow

**Comment by vladsamoy** [comment]
> Anyway to access the beta? I'm not really informed about the Telegram development workflow

Found it here https://www.reddit.com/r/CarPlay/comments/ck8o1t/telegram_got_carplay_support_on_the_latest_beta/

**Comment by Supereg** [comment]
Seems to be removed again from the latest beta though 🤔

**Comment by vladsamoy** [comment]
> Seems to be removed again from the latest beta though 🤔

Hi. Check out the latest version. CarPlay support goes to the prod
![9C69A71E-1805-40C1-BCEF-73781D016FF6](https://user-images.githubusercontent.com/48059203/69011231-19618f80-0971-11ea-8dcc-ed0eb9c0ab24.png)

**Comment by Supereg** [comment]
CarPlay seems to have arrived, closing

**Comment by kathampy** [comment]
@Supereg CarPlay doesn’t work when tapping the Telegram icon. It just says there was an error and quits. If I tap a message notification, it successfully reads the content and lets me reply. After replying it again says there was an error and quits, but the reply is sent.

**Comment by vladasbarisas** [comment]
Same issue here, but I can’t even reply to messages.
