### ISSUE TITLE
Horizontal sticker pack scrolling randomly breaks since 8.7

### ISSUE THREAD

**Issue by bviktor** [TelegramMessenger/Telegram-iOS#755]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description

When trying to scroll through sticker packs, scrolling randomly fails since 8.7 update.

### Expected Behavior

I expect scrolling to work.

### Actual Behavior

Scrolling randomly doesn't work.

### Steps to Reproduce

1. Enter random chat
2. Select stickers in the input bar
3. Swipe sticker pack list to the left. 1st swipe works, consecutive swipes randomly don't. Sometimes you have to wait until sticker pack icons are minimized again, sometimes you don't.

This happens more often when swiping to the left (i.e. scrolling forward). If it happens when swiping to the right (scrolling backwards towards the 1st sticker pack), the unresponsiveness can even cause Telegram to exit the current convo and go back to the chat list. \*

(\* Normally, going back to chat list only happens if I'm swiping from the left edge of the screen OR I'm scrolled all the way to the first sticker, but with this glitch it can also happen if I'm in the middle of the sticker list and I'm only touching the right half of the screen.)

### Environment
**Device:** `iPhone 12`

**iOS version**: `15.4.1`

**App version:** `8.7`

**Comment by bviktor** [comment]
Additionally, until the sticker pack icons minimize, you can't even select them, no matter how many times you tap on them. It'll only activate the sticker pack once the icons are minimized again.

**Comment by mathiswolff** [comment]
This makes stickers completly unusable if you use more than 10 sticker packs. Surly we can't be the only ones noticing this?

**Comment by shebubu** [comment]
Yes, I'm experiencing the same issue. The sticker packs are unusable because of this bug, and are getting on my nerves.

**Comment by uFNet1** [comment]
Actually, for now, you can try scrolling them by swiping over the names of the sticker packs. Also I’ve experienced same glitch in the past, and as far as I remember they couldn’t fix it in few updates.

**Comment by TeoNikolov** [comment]
I've been having the same for a while. Interestingly, I just tried to reproduce the issue and I noticed that on my phone (iPhone 12) if I scroll through the pack in the *bottom half* of the enlarged stickers, then it works. That is, scrolling in the area where the minimized stickers are, and not the message box above them. Curious to know if it's the same for others.

**Comment by breengles** [comment]
> I've been having the same for a while. Interestingly, I just tried to reproduce the issue and I noticed that on my phone (iPhone 12) if I scroll through the pack in the _bottom half_ of the enlarged stickers, then it works. That is, scrolling in the area where the minimized stickers are, and not the message box above them. Curious to know if it's the same for others.

Can confirm it.
No premium until fixed, dear telegram engineers :///

**Comment by HologramDK** [comment]
I can verify that I have had this issue for a couple of weeks now.
Furthermore, with the latest update (8.8.1, I believe), I can now only select the first 5 sticker sets on my horizontal list.
Tapping any sticker set after that just scrolls the vertical sticker selection box below that to the top.

**Comment by bviktor** [comment]
Actually some recent update made this even WORSE, if you can believe that.

Now I can't select the sticker packs even if I wait for them to minimize in size.

In other words the sticker bar is not utterly. completely unusable. You have no other choice but to scroll through all your friggin' stickers.

**Comment by HologramDK** [comment]
> Now I can't select the sticker packs even if I wait for them to minimize in size.

Is your situation the same as mine, where, for whatever reason, you can select the first 5, but none after that?

**Comment by bviktor** [comment]
Lol, now I checked: to me, it works on the first 11 stickers.

Why that number - I have no clue.

Tapping on anything after that, it makes the sticker panel scroll to the top.

WTAF...

**Comment by uFNet1** [comment]
> Lol, now I checked: to me, it works on the first 11 stickers.
> 
> Why that number - I have no clue.
> 
> Tapping on anything after that, it makes the sticker panel scroll to the top.
> 
> WTAF...

I have the same issue, but in my situation it’s first 4 stickerpacks, and then just like yours.

**Comment by TeoNikolov** [comment]
Lol, I thought I was mad, but I also started experiencing this somewhat recently (like 2-3 weeks ago). First time it was around the 11th sticker (not sure which number). Yesterday it was flat out 2-3 packs and that's it. I had to resort to using desktop in a conversation as the experience was just ruined.

I hope this gets revisited soon.

**Comment by Fuzzy-Paws** [comment]
I am having the same problem. iOS 15.5 on an iPhone 13 Pro Max, if it matters, and it's been going on for a while. The broader issue of the wonky scrolling and not being able to tap until after the icons reminimized has been happening for a few months. The more specific issue of not even being able to tap on the pack icons at all without it jumping back to the start of the packs has been going on for a couple weeks. I can reliably tap on the first six packs and anything after six jumps to the start of the packs, even if it is scrolled all the way to the start and I have the first seven icons on screen I can't actually jump to the seventh one.

**Comment by bradmajewski** [comment]
Same issue. Tapping the first 6 packs work as expected. All other packs scroll back to the top of the stickers.

**Comment by rafaelpivatto** [comment]
Same issue here, I'm using iPhone XS on latest iOS

**Comment by bilalyaylak** [comment]
Similar issue, cannot click any sticker pack to scroll to that pack

**Comment by bviktor** [comment]
Guys I don't wanna rush to conclusions but at first glance it seems they actually fixed this with the 8.8.3 release that came down just now. Can others please check too?

**Comment by GrizzlyBearDev** [comment]
> Guys I don't wanna rush to conclusions but at first glance it seems they actually fixed this with the 8.8.3 release that came down just now. Can others please check too?

@bviktor  Just updated and tested and it seems like it's fixed.

**Comment by TeoNikolov** [comment]
Indeed, the issues seem to be fixed. I can scroll and select a sticker pack, and the stickers will scroll to the correct position. In addition, the top side of the enlarged sticker strip is working, and can be used to select stickers.

**Comment by bviktor** [comment]
Awesome, thanks a bunch, guys. Closing the issue, thank you Telegram devs for fixing this!
