### ISSUE TITLE
Release 8.7.1 contains invalid reference to tgcalls repository

### ISSUE THREAD

**Issue by G-200** [TelegramMessenger/Telegram-iOS#756]
Here:
https://github.com/TelegramMessenger/Telegram-iOS/tree/release-8.7.1/submodules/TgVoipWebrtc
It references tgcalls repository:
https://github.com/TelegramMessenger/tgcalls/tree/3ce2c38805ea5af7a05b8fe93a26becaf9e76bd3
Which leads nowhere. Probably tgcalls updates were not uploaded.

**Comment by huangboju** [comment]
+1, 
I had the same problem

**Comment by mostafa-v** [comment]
problem is again happening with version 9.1.0
