### ISSUE TITLE
Dice emoji isn't interactive when send from the ReplyMarkup

### ISSUE THREAD

**Issue by peteroid** [TelegramMessenger/Telegram-iOS#766]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
When we send an emoji (🎲, 🎰, ⚽️, 🎯, 🎳 etc) which supports Dice feature, we expect that will become an interactive emoji. This is okay on Android phone and Telegram Lite on MacOS. However, on iOS, the emoji that sent from the ReplyMarkup will be a text-only emoji instead of the interactive version. 

This is a screenshot taken from the latest version of Telegram on Apps Store
![photo_2022-05-10_16-40-11](https://user-images.githubusercontent.com/12689188/167575864-587f1377-0f30-4d59-bfff-aa0b8994fc6b.jpg)

I also noticed someone asked a similar question on [StackOverflow](https://stackoverflow.com/questions/70189753/roll-the-dice-problem-in-replykeyboardmarkup-of-telegram-bot).

### Expected Behavior
The emoji should be interactive even it's sent from the ReplyMarkup.

### Actual Behavior
The emoji sent from the ReplyMarkup will be a text-only emoji.

### Steps to Reproduce
1. Prepare a bot with ReplyMarkup which contains any of the Dice emoji (🎲, 🎰, ⚽️, 🎯, 🎳 etc)
2. Send the emoji by clicking on the button of the ReplyMarkup
3. The emoji will be a text-only emoji

### Screenshots and Videos 

https://user-images.githubusercontent.com/12689188/167577414-fa89301c-ac42-46f0-9bd5-d6baaaa857a5.mov

### Environment
**Device:** `iPhone SE`

**iOS version**: `14.7.1`

**App version:** `8.7.1`

**Comment by duremika** [comment]
+1

**Comment by laktyushin** [comment]
Fixed in 9.4.2
