### ISSUE TITLE
iOS webrtc

### ISSUE THREAD

**Issue by liuxingyubm** [TelegramMessenger/Telegram-iOS#775]
Is the webrTC version in my Telegramee-ios project too old，Import into my project various WEBRTC error，I chose c++11 or c++14 or c++17, webrtc source code is always a mess of errors。I can not modify the source code, how do I set my Xcode, but I do not know how to set the specific, please give me your advice。
<img width="848" alt="2AFA11D8-9CF3-45E6-8AED-1B0753520249" src="https://user-images.githubusercontent.com/100563041/167977950-a05032be-539d-47e6-af31-58dacf6e90e5.png">

**Comment by ali-fareed** [comment]
Please follow the official build guide in README.md

**Comment by azamjalali** [comment]
Hi ali, i want to record voice and video call in telgram-ios,  I got success in recording local video using AVCaputureSession. Now, in order record remote video, first I need to get remote video frames/buffer from RTCVideoRenderer(i know one method like renderFrame( RTCVideoFrame *)frame in this class, which renders frame, but how to get that frame). Do you help in this, how can I get frames from renderer?

Note: In android, they provided VideoSink method so we can get the frames, but no such class in iOS.
