### ISSUE TITLE
[Feature Request] Disable Notifications for Reactions

### ISSUE THREAD

**Issue by eugeneradionov** [TelegramMessenger/Telegram-iOS#778]
Pleas add an option to disable notifications for emoji reactions in chats

**Comment by Hulkmaster** [comment]
not intent to spam, but i just made a comment in one of the channels and for 15mins i received "reactions spam", had to delete comment because its bizarre

**Comment by Kasbr305** [comment]
amazing😁

**Comment by flleeppyy** [comment]
bump, should be made an option to disable for ALL platforms, not just iOS

**Comment by noripcord** [comment]
PLEASE add this. Even Whatsapp has this. Very necessary.

**Comment by Steve2811** [comment]
Are there any news? Thanks!

**Comment by ali-fareed** [comment]
The feature is implemented in 10.10.
