### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by cfcor** [TelegramMessenger/Telegram-iOS#783]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
When I build the project, but I met the error.
<img width="584" alt="Screen Shot 2022-06-06 at 23 15 47" src="https://user-images.githubusercontent.com/87554617/172288177-6f092d4b-b24f-4548-98ce-3a15a282c269.png">

### Actual Behavior
here is the detail information: 
adeiMac:Telegram-iOS imacroot$ sudo python3 build-system/Make/Make.py \
>     --cacheDir="$HOME/telegram-bazel-cache" \
>     generateProject \
>     --configurationPath="$HOME/telegram-configuration" \
>     --disableExtensions
Password:
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0Warning: Failed to create the file 
Warning: /Users/imacroot/Documents/telegram/Telegram-iOS/build-input/bazel-5.1.
Warning: 0-x86_64: No such file or directory
100     9  100     9    0     0      5      0  0:00:01  0:00:01 --:--:--     5
curl: (23) Failed writing body (0 != 9)
Traceback (most recent call last):
  File "/Users/imacroot/Documents/telegram/Telegram-iOS/build-system/Make/Make.py", line 718, in <module>
    bazel_path = locate_bazel(base_path=os.getcwd())
  File "/Users/imacroot/Documents/telegram/Telegram-iOS/build-system/Make/BazelLocation.py", line 17, in locate_bazel
    call_executable([
  File "/Users/imacroot/Documents/telegram/Telegram-iOS/build-system/Make/BuildEnvironment.py", line 60, in call_executable
    subprocess.check_call(resolved_arguments, env=resolved_env)
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/curl', '-L', 'https://github.com/bazelbuild/bazel/releases/download/5.1.0/bazel-5.1.0-x86_64', '--output', '/Users/imacroot/Documents/telegram/Telegram-iOS/build-input/bazel-5.1.0-x86_64']' returned non-zero exit status 23.

### Environment

**xcode version**: `13.1`
**macos**: '11.4'

**Comment by cfcor** [comment]
@ali-fareed, Can you help me with this problem? thank you!

**Comment by eduhcano** [comment]
It looks that there are some problems with last commit, check the first answer here:
https://stackoverflow.com/questions/71530539/why-is-there-no-build-api-of-the-telegram-ios-app

**Comment by cfcor** [comment]
> Best solution I found is install Bazel and use that custom Bazel installation as it's explained here, but with version 5.1.0
> https://swiftobc.com/repo/TelegramMessenger-Telegram-iOS-swift-content

I just see the same issue, but I didn't find the solution.

**Comment by cfcor** [comment]
> Best solution I found is install Bazel and use that custom Bazel installation as it's explained here, but with version 5.1.0
> https://swiftobc.com/repo/TelegramMessenger-Telegram-iOS-swift-content

Thank you. I try to use bazel 5.1.0 and it works!

**Comment by cfcor** [comment]
I used bazel5.1.0, but I met another issue. Does this mean that python was not initialized successfully, what should I do?
<img width="584" alt="Screen Shot 2022-06-19 at 20 58 49" src="https://user-images.githubusercontent.com/87554617/174507870-833ddf6b-df00-4c07-a1f0-a1256d5ddae3.png">
----------------------here is detail information----------------------------------------------------------
Python path configuration:
  PYTHONHOME = '/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Applications/Wireshark.app/Contents/MacOS:/Users/runner/work/Python-iOS/Python-iOS/kivy-ios/dist/root/python3'
  PYTHONPATH = '/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Applications/Wireshark.app/Contents/MacOS:/Users/runner/work/Python-iOS/Python-iOS/kivy-ios/dist/root/python3'
  program name = '/Applications/Xcode.app/Contents/Developer/usr/bin/python3'
  isolated = 0
  environment = 1
  user site = 1
  import site = 1
  sys._base_executable = '/Applications/Xcode.app/Contents/Developer/usr/bin/python3'
  sys.base_prefix = '/usr/local/bin'
  sys.base_exec_prefix = '/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Applications/Wireshark.app/Contents/MacOS:/Users/runner/work/Python-iOS/Python-iOS/kivy-ios/dist/root/python3'
  sys.executable = '/Applications/Xcode.app/Contents/Developer/usr/bin/python3'
  sys.prefix = '/usr/local/bin'
  sys.exec_prefix = '/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Applications/Wireshark.app/Contents/MacOS:/Users/runner/work/Python-iOS/Python-iOS/kivy-ios/dist/root/python3'
  sys.path = [
    '/usr/local/bin',
    '/usr/bin',
    '/bin',
    '/usr/sbin',
    '/sbin',
    '/Library/Apple/usr/bin',
    '/Applications/Wireshark.app/Contents/MacOS',
    '/Users/runner/work/Python-iOS/Python-iOS/kivy-ios/dist/root/python3',
    '/usr/local/bin/lib/python38.zip',
    '/usr/local/bin/lib/python3.8',
    '/usr/bin',
    '/bin',
    '/usr/sbin',
    '/sbin',
    '/Library/Apple/usr/bin',
    '/Applications/Wireshark.app/Contents/MacOS',
    '/Users/runner/work/Python-iOS/Python-iOS/kivy-ios/dist/root/python3/lib/python3.8/lib-dynload',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x0000000110beee00 (most recent call first):
<no Python frame>

**Comment by cfcor** [comment]
<img width="584" alt="Screen Shot 2022-06-19 at 21 02 59" src="https://user-images.githubusercontent.com/87554617/174508259-db54c2d5-c59b-434c-b1c2-12437608e714.png">

**Comment by shivanraptor** [comment]
Read this: https://stackoverflow.com/questions/38132755/importerror-no-module-named-encodings

**Comment by ali-fareed** [comment]
Please check that you are able to build the latest master commit without modifications.

**Comment by shivanraptor** [comment]
You can use `Bazelisk` to install the Bazel, instead of letting the build script to download a Bazel version.
