### ISSUE TITLE
8.8.1 does not work in iOS 9.3.5

### ISSUE THREAD

**Issue by abcdenis** [TelegramMessenger/Telegram-iOS#795]
Hi,
I have ipad2 with iOS 9.3.5 (the last version for this model).
Tried to install and run Telegram from AppStore. It has version 8.8.1 and requires minumal iOS 9.0.
On tapping on app icon it starts with white screen then shows back main iOS screen.
If I do double click on home button then I could see Telegram App in device's memory and unload it (but restart has the same effect).
Could you check this please.

ipad has an SIM-card slot but does not have it inserted.
Main connection is Wi-Fi.

Thank you.

**Comment by MadDaimond** [comment]
iPhone 4s, iOS 9.3.5 - same problem.

**Comment by ali-fareed** [comment]
We'll be tracking this under https://github.com/TelegramMessenger/Telegram-iOS/issues/791.
