### ISSUE TITLE
telegram stop working on ipad 4 after updating the app

### ISSUE THREAD

**Issue by nizardho** [TelegramMessenger/Telegram-iOS#798]
I have ipad 4 with ios 10.3.3
it was working great until I saw a notification to update telegram then after that app crashed wont work.
Please fix that as soon as possible. we love and use your app everyday.
Much appreciated for your work.

**Comment by gdwaynewarner** [comment]
Not sure why this was marked as closed, because Telegram still isn't working on my iPad 4.

**Comment by ali-fareed** [comment]
iPad 4 is not supported by iOS 11, which is the minimum required version for Telegram.

**Comment by gdwaynewarner** [comment]
That's nice, but it doesn't change the fact that my iPad 4 won't run that
version of the iOS.

**Comment by ali-fareed** [comment]
And that makes this issue unfixable.
