### ISSUE TITLE
Missing translation 

### ISSUE THREAD

**Issue by plagoutte** [TelegramMessenger/Telegram-iOS#80]
Missing translation on the widget when doing a 3D-Touch on the app. 

![DB725475-ED2D-47F9-9E09-44236EC154D6](https://user-images.githubusercontent.com/13762047/60474101-5e11b600-9c70-11e9-93c5-206080e24f29.jpeg)

**Comment by shivanraptor** [comment]
You can always contribute to Telegram's translation here: https://translations.telegram.org/

**Comment by plagoutte** [comment]
Sorry for the inconvenience, I'll check that ;)
