### ISSUE TITLE
Error 2 Telegram

### ISSUE THREAD

**Issue by Roman7451** [TelegramMessenger/Telegram-iOS#802]
![59507223-fd972080-8edc-11e9-8665-48b7d84b8f48](https://user-images.githubusercontent.com/108979378/178101570-35975ea0-c618-4e30-b54d-2cc31435fe1f.png)

как исправить?

**Comment by ali-fareed** [comment]
See https://github.com/TelegramMessenger/Telegram-iOS/issues/69
