### ISSUE TITLE
Telegram Fork cannot pass through App Store Review

### ISSUE THREAD

**Issue by shivanraptor** [TelegramMessenger/Telegram-iOS#806]
The latest app store review rejected my app for the following reason:

**Guideline 5.1.1(v) - Data Collection and Storage**

We noticed that your app supports account creation but does not include an option to initiate account deletion. 

Apps that support account creation must also offer account deletion to give App Store users more control of the data they've shared while using your app.

---

I know the Telegram app does not have an account deletion in-app (only available in the My Telegram web portal), is there any chance that the app can add such an account deletion feature?

**Comment by ali-fareed** [comment]
It does, check out the latest update: https://github.com/TelegramMessenger/Telegram-iOS/commit/8112d11896c7d2a30187510ce0d8a8b4d630098f
