### ISSUE TITLE
Generating derived files for Swift module //submodules/ImportStickerPackUI:ImportStickerPackUI failed: (Exit 77): bash failed: error executing command 

### ISSUE THREAD

**Issue by TheDreamOfABillionGirls** [TelegramMessenger/Telegram-iOS#810]
python3 build-system/Make/Make.py \
--bazel="$HOME/bazel-dist/bazel" \
--cacheDir="$HOME/telegram-bazel-cache" \
generateProject \
--configurationPath="$HOME/telegram-configuration" \
--disableExtensions \
--disableProvisioningProfiles

### Description
ERROR: /Users/fangyangdebeiduofen/Desktop/BeethOven/Telegram/telegram-ios/submodules/ImportStickerPackUI/BUILD:3:14 Generating derived files for Swift module //submodules/ImportStickerPackUI:ImportStickerPackUI failed: (Exit 77): bash failed: error executing command 
  (cd /private/var/tmp/_bazel_fangyangdebeiduofen/282cac1fbb69cd148144ffe9fbacc750/execroot/__main__ && \
  exec env - \
    PATH=/usr/bin:/bin:/usr/sbin:/sbin \
    ZERO_AR_DATE=1 \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; 
    set -ex

    if [ "ios_arm64" == "ios_armv7" ]; then
        BUILD_ARCH="armv7"
    elif [ "ios_arm64" == "ios_arm64" ]; then
        BUILD_ARCH="arm64"
    elif [ "ios_arm64" == "ios_sim_arm64" ]; then
        BUILD_ARCH="sim_arm64"
    elif [ "ios_arm64" == "ios_x86_64" ]; then
        BUILD_ARCH="x86_64"
    else
        echo "Unsupported architecture ios_arm64"
    fi

    BUILD_DIR="bazel-out/ios-arm64-min9.0-applebin_ios-ios_arm64-opt-ST-b50fc8c042fb/bin/third-party/opus/build_${BUILD_ARCH}"
    rm -rf "$BUILD_DIR"
    mkdir -p "$BUILD_DIR"

    cp third-party/opus/build-opus-bazel.sh "$BUILD_DIR/"
    cp third-party/opus/opus-1.3.1.tar.gz "$BUILD_DIR/"

    mkdir -p "$BUILD_DIR/Public/opus"

    sh $BUILD_DIR/build-opus-bazel.sh $BUILD_ARCH "$BUILD_DIR" opus-1.3.1.tar.gz
    cp -f "$BUILD_DIR/built/include/opus/opus.h" "bazel-out/ios-arm64-min9.0-applebin_ios-ios_arm64-opt-ST-b50fc8c042fb/bin/third-party/opus/Public/opus/opus.h"
cp -f "$BUILD_DIR/built/include/opus/opus_defines.h" "bazel-out/ios-arm64-min9.0-applebin_ios-ios_arm64-opt-ST-b50fc8c042fb/bin/third-party/opus/Public/opus/opus_defines.h"
cp -f "$BUILD_DIR/built/include/opus/opus_multistream.h" "bazel-out/ios-arm64-min9.0-applebin_ios-ios_arm64-opt-ST-b50fc8c042fb/bin/third-party/opus/Public/opus/opus_multistream.h"
cp -f "$BUILD_DIR/built/include/opus/opus_projection.h" "bazel-out/ios-arm64-min9.0-applebin_ios-ios_arm64-opt-ST-b50fc8c042fb/bin/third-party/opus/Public/opus/opus_projection.h"
cp -f "$BUILD_DIR/built/include/opus/opus_types.h" "bazel-out/ios-arm64-min9.0-applebin_ios-ios_arm64-opt-ST-b50fc8c042fb/bin/third-party/opus/Public/opus/opus_types.h"
cp -f "$BUILD_DIR/built/lib/libopus.a" "bazel-out/ios-arm64-min9.0-applebin_ios-ios_arm64-opt-ST-b50fc8c042fb/bin/third-party/opus/Public/opus/lib/libopus.a"')
# Configuration: ebb7cc8ed3be1387f97a5f9e6e3c3d5c2ccb7d98517c2387fe0b86d212ef1821
# Execution platform: @local_config_platform//:host
INFO: Elapsed time: 46.489s, Critical Path: 16.22s
INFO: 559 processes: 144 disk cache hit, 89 internal, 326 local.
FAILED: Build did NOT complete successfully
Traceback (most recent call last):
  File "build-system/Make/Make.py", line 728, in <module>
    build(bazel=bazel_path, arguments=args)
  File "build-system/Make/Make.py", line 482, in build
    bazel_command_line.invoke_build()
  File "build-system/Make/Make.py", line 328, in invoke_build
    call_executable(combined_arguments)
  File "/Users/fangyangdebeiduofen/Desktop/BeethOven/Telegram/telegram-ios/build-system/Make/BuildEnvironment.py", line 60, in call_executable
    subprocess.check_call(resolved_arguments, env=resolved_env)
  File "/Applications/Xcode 2.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/fangyangdebeiduofen/bazel-dist/bazel', 'build', 'Telegram/Telegram', '--override_repository=build_configuration=/Users/fangyangdebeiduofen/telegram-configuration', '--announce_rc', '--verbose_failures', '--features=swift.skip_function_bodies_for_derived_files', '--jobs=12', '--define=buildNumber=100001', '--define=telegramVersion=8.7.1', '--features=swift.split_derived_files_generation', '--disk_cache=/Users/fangyangdebeiduofen/telegram-bazel-cache', '-c', 'opt', '--ios_multi_cpus=armv7,arm64', '--watchos_cpus=armv7k,arm64_32', '--apple_generate_dsym', '--output_groups=+dsyms', '--features=swift.opt_uses_wmo', '--features=swift.opt_uses_osize', '--swiftcopt=-num-threads', '--swiftcopt=0', '--features=dead_strip', '--objc_enable_binary_stripping', '--apple_bitcode=watchos=embedded']' returned non-zero exit status 1.

### Environment
**Mac OS** `11.6`

**iOS version**: `13.2.1`

**App version:** `8.7.1`

**Comment by ali-fareed** [comment]
It doesn't look like there is an exact error here, but I'd start with checking the available disk space.
