### ISSUE TITLE
Videos using VP9 codec not playing correctly

### ISSUE THREAD

**Issue by ivan-gorin** [TelegramMessenger/Telegram-iOS#811]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
Videos with VP9 codec in mp4 container don't display correctly in telegram for IOS, the audio plays but the video remains as a blurred preview. (Also, same video stream in webm container displays as a file)

### Expected Behavior
Both the video and audio play normally.

### Actual Behavior
Video doesn't play, only blurred static preview is shown.

### Steps to Reproduce
1. Get a video encoded with VP9 codec and in an mp4 container.
2. Send the video in telegram.
3. Try to play the video.

### Screenshots and Videos 
![01](https://user-images.githubusercontent.com/43433603/180100241-0326c449-46e5-4d2d-a50a-071be9c78216.jpg)
![02](https://user-images.githubusercontent.com/43433603/180100240-630ae371-b13c-40d9-83c5-b4e64a831533.jpg)

### Environment
**Device:** `iPhone 11`

**iOS version**: `15.5`

**App version:** `8.8.3`

**Comment by ali-fareed** [comment]
Unfortunately, hardware-accelerated VP9 playback is currently restricted to Apple-approved apps, and we could not receive the approval.
