### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by nanirocks125** [TelegramMessenger/Telegram-iOS#82]
**No such module 'SwiftSignalKit' in TelegramAudio Framework**

It is already present in the Linked Frameworks and Libraries
![Screenshot 2019-07-05 at 5 28 57 PM](https://user-images.githubusercontent.com/25024660/60721077-64db4a00-9f4a-11e9-841f-cf5602ca69d8.png)

**Comment by shivanraptor** [comment]
Duplicate of #76

**Comment by nanirocks125** [comment]
Thank you @shivanraptor 
Kindly update the Read.Me file ( Telegram-iOS-Fork to  Telegram-iOS-AppStoreLLC )

**Comment by shivanraptor** [comment]
You still need to use `Telegram-iOS-Fork` target.

**Comment by DukeHuang** [comment]
I used `Telegram-iOS-Fork` target, the same wrong with @nanirocks125 .Then I changed to the 
`Telegram-iOS-AppStroeLLC` target, success compile!

**Comment by XavierLost** [comment]
I changed to the Telegram-iOS-AppStroeLLC , prompt " The bundle identifier of the application could not be determined"

**Comment by RodPrestes** [comment]
It appears that PR #116 has been a little out of sync.
Tried applying its changes on latest master but had no luck building.
PR branch builds fine but lacks new features.
