### ISSUE TITLE
Documentation on forked builds to appstore / integration with existing backends

### ISSUE THREAD

**Issue by wweevv-johndpope** [TelegramMessenger/Telegram-iOS#822]
### Checklist
- [ x] I am reporting an issue in existing functionality that does not work as intended
- [x ] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
Describe the issue that you are experiencing

are there any steps / documentation for forked builds? 
Eg. in the app - there's a share icon - it links to https://t.me - is there any guidance on how to replace this?
do we need to build our own url shortener? 
Did any one integrate facebook with this code base? 
I can see there's 1000 forks - but I'm struggling to salvage any previous efforts.
how do you go about syncing accounts - back to other server? 
Is it possible via firebase? I can read code - but at this point - it's more of feasibility study I need to take on.

**Comment by ali-fareed** [comment]
There are no official guidelines, but you may want to check out Nicegram: https://github.com/nicegram/Nicegram-iOS/tree/nicegram-plus

**Comment by wweevv-johndpope** [comment]
Thanks Ali
