### ISSUE TITLE
After emoji update, the app crashes on sticker panel opening

### ISSUE THREAD

**Issue by ov7a** [TelegramMessenger/Telegram-iOS#824]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
App crashes when I'm trying to open sticker panel.

### Expected Behavior
Stickers/Gifs panel is shown.

### Actual Behavior
The app just crashes.

I can still send stickers from suggestions by emoji. 
I can open emoji panel by typing `:` and tapping a smiley icon.
I can navigate to gifs from emoji panel but not stickers.

### Steps to Reproduce
1. Open any chat
2. Tap sticker icon to open stickers.

Alternative:
1. Open any chat
2. Type `:` to show emoji (sticker icon changes to smiley icon)
3. Tap smiley icon to open emoji panel.
4. Tap sticker icon to switch to stickers.

### Environment
**Device:** `IPad mini 5`

**iOS version**: `12.4.1`

**App version:** `8.9.1`

**Comment by ov7a** [comment]
I'm also not sure if this is related or not, but the app also crashes when I click on any custom emoji set in emoji panel.

**Comment by ov7a** [comment]
Fixed in 9.0

**Comment by hesam4g** [comment]
Still I have the same problem. I am using iphone se2 with ios 16.0.2 and Telegram client version 9.0.2
