### ISSUE TITLE
clarification on why the texture / yoga ascollectionview and other classes were removed.

### ISSUE THREAD

**Issue by johndpope** [TelegramMessenger/Telegram-iOS#825]
I'm looking at the code base and can't understand why these classes were removed - is it solely on size / optimizations - or did the code lead to ui dead locks?

**Comment by johndpope** [comment]
<img width="1427" alt="Screen Shot 2022-08-27 at 7 23 29 pm" src="https://user-images.githubusercontent.com/289994/187024081-6e9e6a4e-0ba6-4bb0-a567-c3f216a000a8.png">

The asyndisplaykit had these initially - and they would help me to be more productive since I'm uikit seasoned.
What would be guidance in building uicollectionview like control if not?

**Comment by johndpope** [comment]
2bfec3d11d47ea93522dce1fb380bffff5b7e828

**Comment by ali-fareed** [comment]
This project has never used any of the ASDK/Texture features except for asynchronous rendering. The current plan is to remove the dependency completely as it is no longer useful.

**Comment by johndpope** [comment]
Cool - thanks Ali. I've been fighting another battle for last few days using firebase with this codebase - 
https://github.com/firebase/firebase-ios-sdk/issues/6115

had a tiny bit of success (I get xcode project to build - but won't compile) - but it sucks Google doesn't offer any official or unofficial support. I think I need to build out an ios framework - I have no idea.

**Comment by ali-fareed** [comment]
While not convenient, you can always unpack externally built artifacts into headers and static libraries. Example for a make-based dependency: https://github.com/TelegramMessenger/Telegram-iOS/blob/master/third-party/libvpx/BUILD
I don't think it would work with dynamic frameworks.

**Comment by johndpope** [comment]
I’m interested to help rip out asyncdisplaykit- it’s causing headaches and struggling to do some trivial things. I can upgrade it but as you mentioned - it’s to be killed.

**Comment by ali-fareed** [comment]
Which things are you struggling with?
