### ISSUE TITLE
Cannot mute/block group chat notifications from a specific user

### ISSUE THREAD

**Issue by sbosshardt** [TelegramMessenger/Telegram-iOS#831]
Telegram has "mute user" and "block user" features, but they are ineffective when a blocked/muted user is in the same group as you and sending messages to the group. In other words, a user that I block and mute still can cause my phone to ding a dozen times in a day.

I'm not sure whether I should classify this issue as a bug report or a feature request. On one hand, the block and mute features are working as designed. On the other hand, I can't think of a realistic use case of someone muting/blocking a user but still wanting notifications bugging them every time the user chats in a group.

Some users believe that copying/pasting identical messages across multiple groups is them doing a public service. For example, dumping a dozen random news article messages in the chat every day. It is even worse if you and a spammer user are members of multiple groups (e.g. if you share two groups, what would be a dozen daily dings becomes two dozen).

Spammers are able to damage the usefulness of groups by polluting them, while not technically violating a group's rules. And as the signal-to-noise ratio decreases, group members are forced to choose between enduring the user's spam, or disengaging from a group. The spam negatively impacts the community's purpose and focus. As more and more people leave or mute notifications from the group, the number of engaged users decreases and the group gradually spirals to oblivion.

Although group admins technically have the ability to ban a pesky user who hasn't violated any rules, doing so can backfire. It can cause a loss of goodwill. The banned user can complain to others, and there may even be a few people who actually like to see those messages and come to view the banned user as a martyr.

I suppose there is more than one way that this could be implemented. For starters, a user who I've blocked or muted at the account-level ought to not be able to generate group-level notifications. Like I said, I can't think of a good use case where receiving notifications from a muted/blocked user is desirable (but maybe someone else can). I would think that this could even be accomplished entirely client-side (i.e. no changes required to Telegram's API) but I could be wrong on this one.

Another possibility is to develop a feature that allows a group's members to mute/block chats of another member. This approach could be done without making modifications to the existing mute/block features, but would take more development effort (including implementing UI changes and probably Telegram API changes). For example, say there is User A and User B, and they are both in Group 1 and Group 2. User A could mute notifications of User B messaging Group 1. User A would still be notified if User B sends a direct message to User A, or if User B messages Group 2.

**Comment by InfriaAB** [comment]
I have the exact same problem. 

I am in a group with a chatty user and I don't mind reading their messages at a later time but I don't want notifications from them. When I muted them I expected that I would no longer receive notifications from their messages but still be able to read them later. 

As you noted I still get notifications even though the user is muted. To me this seems close to a bug, or the feature has not been thought through all the way.

**Comment by Livadas** [comment]
bump

**Comment by ali-fareed** [comment]
As this is a platform-wide suggestion, I would suggest filing an issue at bugs.telegram.org.
