### ISSUE TITLE
Geocoder - obsolete call  geocodeAddressDictionary submodules/Geocoding/Sources/Geocoding.swift

### ISSUE THREAD

**Issue by wweevv-johndpope** [TelegramMessenger/Telegram-iOS#832]
I've swept through code and got app to build with min target - ios 13
https://github.com/wweevv-johndpope/Telegram-iOS/tree/ios13

There's a tonne of errors - and frankly - it's crashing. still investigating my changes.
<img width="1296" alt="Screen Shot 2022-09-01 at 3 31 13 pm" src="https://user-images.githubusercontent.com/109928647/187838599-c8ce2445-d331-4eb1-afa3-8bd207f112ac.png">

There's some reference to this code - that needs fixing.

Geocoder - obsolete call  geocodeAddressDictionary submodules/Geocoding/Sources/Geocoding.swift

geocodeAddressDictionary

I'm working through codebase to make my app min target ios 13.

this line 
  geocoder.geocodeAddressDictionary(dictionary, completionHandler: { placemarks, _ in

no longer compiles - maybe we can pass this onto 

https://github.com/wweevv-johndpope/Telegram-iOS/commit/305829a060bcb89f809c8662924b784f6a1a1839#diff-adb7a8ac696b5d7f4d91daa2ed80c38d18426e1442e878fb9c892c0299683d25R21
```swift

- (void)geocodeAddressDictionary:(NSDictionary *)addressDictionary completionHandler:(CLGeocodeCompletionHandler)completionHandler API_DEPRECATED("Use -geocodePostalAddress:completionHandler:", macos(10.8, 10.13), ios(5.0, 11.0), watchos(1.0, 4.0));
- (void)geocodeAddressString:(NSString *)addressString completionHandler:(CLGeocodeCompletionHandler)completionHandler;
- (void)geocodeAddressString:(NSString *)addressString inRegion:(nullable CLRegion *)region completionHandler:(CLGeocodeCompletionHandler)completionHandler;
- (void)geocodeAddressString:(NSString *)addressString inRegion:(nullable CLRegion *)region preferredLocale:(nullable NSLocale *)locale completionHandler:(CLGeocodeCompletionHandler)completionHandler API_AVAILABLE(macos(10.13), ios(11.0), watchos(4.0), tvos(11.0));

- (void)cancelGeocode;

@end

@interface CLGeocoder (ContactsAdditions)
- (void)geocodePostalAddress:(CNPostalAddress *)postalAddress completionHandler:(CLGeocodeCompletionHandler)completionHandler API_AVAILABLE(ios(11.0), macos(10.13), watchos(4.0)) API_UNAVAILABLE(tvos);
- (void)geocodePostalAddress:(CNPostalAddress *)postalAddress preferredLocale:(nullable NSLocale *)locale completionHandler:(CLGeocodeCompletionHandler)completionHandler API_AVAILABLE(macos(10.13), ios(11.0), watchos(4.0)) API_UNAVAILABLE(tvos);
@end

NS_ASSUME_NONNULL_END
```

will need to get  dictionary across to CNPostalAddress

           let value = CNMutablePostalAddress()
            value.street = address.street1 + "\n" + address.street2
            value.state = address.state
            value.city = address.city
            value.country = address.country
            value.postalCode = address.postcode
            return CNLabeledValue<CNPostalAddress>(label: address.label, value: value)

**Comment by ali-fareed** [comment]
Fixed in 9.0.1.
