### ISSUE TITLE
Is there a reason why autolayout would not work with asyncdisplaykit?

### ISSUE THREAD

**Issue by johndpope** [TelegramMessenger/Telegram-iOS#834]
I have a branch working with uiview nested inside async root node - but when I try to use with snapkit - it blows up.

<img width="1429" alt="Screen Shot 2022-09-06 at 10 04 34 pm" src="https://user-images.githubusercontent.com/289994/188630703-37d487e9-9baf-4349-a747-bee3172ac50e.png">

![Uploading Screen Shot 2022-09-06 at 10.05.56 pm.png…]()
<img width="1349" alt="Screen Shot 2022-09-06 at 10 05 59 pm" src="https://user-images.githubusercontent.com/289994/188630876-fcefec7a-6886-460f-8cd9-793241490dba.png">

I think it's maybe a problem with xcframework - than any limitations of uikit...
https://github.com/supabase-community/gotrue-swift/issues/32

**Comment by ali-fareed** [comment]
I'd suggest trying to run the project with memory sanitizer enabled, maybe there is some memory corruption going on.

**Comment by wweevv-johndpope** [comment]
<img width="434" alt="Screen Shot 2022-09-12 at 6 07 40 pm" src="https://user-images.githubusercontent.com/109928647/189603903-8a098960-6385-4c75-981e-10590e792833.png">


I can't explain it - but when I copy the snapkit source code into the component directly - without importing 
**import snapkit**

then it works.
