### ISSUE TITLE
Unable to format (bold/italic/underlined/hidden) text in iOS16

### ISSUE THREAD

**Issue by choodique** [TelegramMessenger/Telegram-iOS#837]
### Checklist
- [X] I am reporting an issue in existing functionality that does not work as intended
- [X] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
After updating to iOS16 I can no longer format text in the menu after selecting text

### Expected Behavior
After selecting text in the menu that came up, you could select text formatting (bold, italic, etc.)

### Actual Behavior
After selecting text in the menu that appears, no items responsible for selecting formatting (bold, italic, etc.)

### Steps to Reproduce
1. Enter text
2. Select all or part of it
3. Scroll through the menu that appears and look for the button responsible for text formatting

### Screenshots and Videos 
![Screenshot](https://pbs.twimg.com/media/FcjEdFjWQAMd-Gg?format=jpg&name=small)

### Environment
**Device:** `iPhone`

**iOS version**: `16`

**App version:** `8.9.1 (23989)`

**Comment by stefanodriussi** [comment]
I confirm this. After iOS 16 update I cannot format text anymore, nor add spoiler

**Comment by ollegsey** [comment]
Confirm

**Comment by wmorgue** [comment]
Same for me 🐞

**Comment by httpiga** [comment]
Same here!

**Comment by JaviPege** [comment]
Not working

**Comment by aklar** [comment]
Same here. On a German language version of iOS 16. This also makes it impossible to use text links. 😌

**Comment by MAYDAYSOS** [comment]
Same here 🥲

**Comment by MrRabbit71** [comment]
Confirming

if I’ve known this I wouldn’t have updated to iOS 16

annoying as frack this bug

**Comment by liahsheep** [comment]
Until this is fixed, you may use the formatting symbols as a workaround. Like this:

```
**bold**
__italic__
~~strikethrough~~
||spoiler||
`monospaced`
```

**Comment by thanhhoangngoc** [comment]
Me too, waiting Telegram new version fixed that issue!

**Comment by shelbyKiraM** [comment]
> Until this is fixed, you may use the formatting symbols as a workaround. Like this:
> 
> ```
> **bold**
> __italic__
> ~~strikethrough~~
> ||spoiler||
> `monospaced`
> ```

Also, for multiline preformatted text, use three backticks on an empty line before & after. Which is difficult to type on en_US keyboard but we'll live.

**Comment by hestiaas** [comment]
does anyone know the formatting for adding links to specific words for now?

**Comment by Laiteux** [comment]
> does anyone know the formatting for adding links to specific words for now?

I would've guessed `[text](http://example.com)` considering it's just markdown, sadly that does not seem to work.

**Comment by shelbyKiraM** [comment]
> it's just markdown

It's obviously not a feature-complete version. It's more Markdown-*ish*. 😿 But Telegram is amazing *otherwise*, let's go!

**Comment by Genyus** [comment]
> does anyone know the formatting for adding links to specific words for now?

You can use [MarkdownBot](https://t.me/markdownbot) to generate links with Markdown syntax

**Comment by shelbyKiraM** [comment]
I thought you might be able to copy directly from e.g. CKEditor's HTML text editing area but apparently not. However you can go to the CKEdit chat example ([https://ckeditor.com/docs/ckeditor5/latest/examples/framework/chat-with-mentions.html](https://ckeditor.com/docs/ckeditor5/latest/examples/framework/chat-with-mentions.html) ) & send a message, then copy/paste the text of the sent message into a message on Telegram.

**Comment by ali-fareed** [comment]
Fixed in 9.0.1.

**Comment by masiNJ02** [comment]
Confirm. I’ve updated to 16.0.2 but still no change.

**Comment by ng8weji9vowdv** [comment]
@ali-fareed now there's no regular button... so how do i revert bold text, lol?

**Comment by ng8weji9vowdv** [comment]
@laktyushin
