### ISSUE TITLE
Implement contact-identification in the Communication-Notification

### ISSUE THREAD

**Issue by tStaiger** [TelegramMessenger/Telegram-iOS#839]
As per #556, the Communication Notification is already implemented. That's good so far. What's missing is the contact-identification part of the notifications. Implementing it would benefit user a lot. They could set a focus and select specific people. After setting it, only messages from selected people will be delivered as notification. The others will be delivered but silently distributed. To do this, each notification needs to set a contact identifier (https://developer.apple.com/documentation/sirikit/inperson/2138319-init parameter `contactIdentifier`). Currently, it's filled with `nil`. That means, that no contact is associated. (https://github.com/TelegramMessenger/Telegram-iOS/blob/master/Telegram/NotificationService/Sources/NotificationService.swift).

**Comment by devasworski** [comment]
This is a absolut must! It makes Telegram absolutely useless for iOS users, as no notifications arrive if a Focus is active...

**Comment by kecinzer** [comment]
+1 this is absolute must have :).

BTW. focus filters as in Fantastical - https://flexibits.com/blog/2022/09/ios-16-fantastical-3-7-and-cardhop-2-2-are-all-out-today/ will be also great!

**Comment by ali-fareed** [comment]
Fixed in 9.0.1.

**Comment by devasworski** [comment]
This is not fixed at all!!!!! @ali-fareed

**Comment by dreyks** [comment]
why not? works for me

are you sure the contact you've added to focus exceptions is linked to the telegram contact?

**Comment by alexschcom** [comment]
Hey @ali-fareed @dreyks -- is this also possible with bots? I have a bot that sends me status updates periodically and I'd like that to break through Focus modes / be marked time-sensitive...
