### ISSUE TITLE
Spacing between dynamic island and contact name is too small

### ISSUE THREAD

**Issue by abhinavk99** [TelegramMessenger/Telegram-iOS#841]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
There isn’t enough spacing between the dynamic island and the name of the contact or group on the iPhone 14 Pro.

### Expected Behavior
There should be enough spacing so that the contact name isn’t almost touching the dynamic island.

### Actual Behavior
There is almost no spacing so the top bar looks uneven.

### Steps to Reproduce
1. Open Telegram on iPhone 14 Pro or any iPhone with a dynamic island.
2. Click on a chat and look at the top bar.

### Screenshots and Videos 
![5B84F911-2CF4-4F5B-AAD2-890BFC6278E2](https://user-images.githubusercontent.com/24740091/190874088-838896f0-1d03-4189-b854-8defe4b76546.jpeg)

### Environment
**Device:** `iPhone 14 Pro`

**iOS version**: `16.0.1`

**App version:** `9.0`

**Comment by shelbyKiraM** [comment]
I have a 14 Pro Max as well but this is more a feature than a bug to me. More screen space for messages? Thank you very much! Yeah, when it's two lines it's close, but when it is only one it's a generous distance.

![327F2698-BF33-4F97-8396-E8E9BD2531E5](https://user-images.githubusercontent.com/202692/191073844-773db800-0acc-40e4-b3f4-03d9fa48425c.png)
![73A0056A-5919-443B-9355-89A6775605B1](https://user-images.githubusercontent.com/202692/191073874-27c7b9e2-6a3c-4860-a67e-2aaf9b0e6e80.png)

**Comment by laktyushin** [comment]
Fixed in 9.0.1
