### ISSUE TITLE
New arguments when generate project

### ISSUE THREAD

**Issue by d3nzZ3L** [TelegramMessenger/Telegram-iOS#849]
Hello guys, could you provide some information about  --gitCodesigningRepository --gitCodesigningType arguments in generateProject function and show examples maybe, i can't generate project because of this new args.
Thank you. 

I'm getting error:
`Make generateProject: error: one of the arguments --gitCodesigningRepository --codesigningInformationPath is required
`

**Comment by Alarikus** [comment]
@Ivan-Yushkov 
> How did you resolve this issue?

You can copy and paste the fake-code signing folder from the build-system to telegram-configuration, then use a command
`python3 build-system/Make/Make.py --cacheDir="$HOME/telegram-bazel-cache" generateProject --configurationPath="$HOME/telegram-configuration/development-configuration.json" --disableExtensions --disableProvisioningProfiles --codesigningInformationPath "$HOME/telegram-configuration/fake-codesigning"`
Make sure that development-configuration.json exist, and you can use the example in build-system/appstore-configuration.json

**Comment by Lytvynets** [comment]
After that I had a problem with the version of Xcode just recently updated.

**Required Xcode version is 14.0, but 14.0.1 is reported by 'xcode-select -p'**

Can someone tell me how to use the 'xcode-select -p' command correctly?

**Comment by oboje** [comment]
@Alarikus 
> "Could not find a valid aps-environment entitlement in the provided provisioning profiles"

**Comment by Lytvynets** [comment]
Maybe someone knows what to do about it?

_Required Xcode version is 14.0, but 14.0.1 is reported by 'xcode-select -p'_

**Comment by moruadd** [comment]
python3 build-system/Make/Make.py --overrideXcodeVersion build ... # Don't check the version of Xcode

**Comment by ibohonos** [comment]
> @Ivan-Yushkov
> 
> > How did you resolve this issue?
> 
> You can copy and paste the fake-code signing folder from the build-system to telegram-configuration, then use a command `python3 build-system/Make/Make.py --cacheDir="$HOME/telegram-bazel-cache" generateProject --configurationPath="$HOME/telegram-configuration/development-configuration.json" --disableExtensions --disableProvisioningProfiles --codesigningInformationPath "$HOME/telegram-configuration/fake-codesigning"` Make sure that development-configuration.json exist, and you can use the example in build-system/appstore-configuration.json

after this recommendation it's next error:
`Could not find a valid aps-environment entitlement in the provided provisioning profiles`
how fix it?

**Comment by mailes** [comment]
I got some errors:

1 warning generated.
ERROR: /Users/weixiaobin/Telegram-iOS/Telegram/BUILD:1747:14: Processing and signing NotificationServiceExtension failed: (Exit 1): process-and-sign-54436305.sh failed: error executing command 
  (cd /private/var/tmp/_bazel_Amy/40d386df50af74df78f36125cbf8ace6/execroot/__main__ && \
  exec env - \
    APPLE_SDK_PLATFORM=iPhoneOS \
    APPLE_SDK_VERSION_OVERRIDE=16.0 \
    XCODE_VERSION_OVERRIDE=14.0.1.14A400 \
  bazel-out/applebin_ios-ios_armv7-opt-ST-5b7531beec20/bin/Telegram/NotificationServiceExtension-intermediates/process-and-sign-54436305.sh should_sign should_compress)
# Configuration: 55ac85af467c0852b40b5a17ea9a235c3643b5e1e32c1946185f8d4a033b0896
# Execution platform: @local_config_platform//:host
ERROR: Unable to find an identity on the system matching the ones in external/build_configuration/provisioning/NotificationService.mobileprovision
Target //Telegram:Telegram failed to build
INFO: Elapsed time: 454.123s, Critical Path: 450.67s
INFO: 1321 processes: 34 internal, 1287 local.
FAILED: Build did NOT complete successfully
Traceback (most recent call last):
  File "build-system/Make/Make.py", line 958, in <module>
    build(bazel=bazel_path, arguments=args)
  File "build-system/Make/Make.py", line 566, in build
    bazel_command_line.invoke_build()
  File "build-system/Make/Make.py", line 341, in invoke_build
    call_executable(combined_arguments)
  File "/Users/weixiaobin/Telegram-iOS/build-system/Make/BuildEnvironment.py", line 81, in call_executable
    subprocess.check_call(resolved_arguments, env=resolved_env)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.

**Comment by ZhangJiFeng** [comment]
> > @Ivan-Yushkov
> > > How did you resolve this issue?
> > 
> > 
> > You can copy and paste the fake-code signing folder from the build-system to telegram-configuration, then use a command `python3 build-system/Make/Make.py --cacheDir="$HOME/telegram-bazel-cache" generateProject --configurationPath="$HOME/telegram-configuration/development-configuration.json" --disableExtensions --disableProvisioningProfiles --codesigningInformationPath "$HOME/telegram-configuration/fake-codesigning"` Make sure that development-configuration.json exist, and you can use the example in build-system/appstore-configuration.json
> 
> after this recommendation it's next error: `Could not find a valid aps-environment entitlement in the provided provisioning profiles` how fix it?
> 
> UPDATE:
> 
> this error was because I replaced the values in `"$HOME/telegram-configuration/development-configuration.json"` if you want to use `"$HOME/telegram-configuration/fake-codesigning"` - don't replace these values

can not work
