### ISSUE TITLE
app store review 4.3 issues

### ISSUE THREAD

**Issue by xsKk** [TelegramMessenger/Telegram-iOS#851]
### Checklist
- [ ] I am reporting an issue in existing functionality that does not work as intended
- [ ] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
Describe the issue that you are experiencing

### Expected Behavior
Tell us what should happen

### Actual Behavior
Tell us what happens instead

### Steps to Reproduce
1. 
2. 
3. 

### Screenshots and Videos 
Remove, if not applicable

### Environment
**Device:** `iPhone/iPad X`

**iOS version**: `13.X`

**App version:** `7.X`

**Comment by xsKk** [comment]
I have encountered the problem of ios listing review others, can you provide any help?

**Comment by shivanraptor** [comment]
You didn't provide any details, and it's definitely not a bug.

**Comment by xsKk** [comment]
> You didn't provide any details, and it's definitely not a bug.
I didn't find an efficient way to solve this problem.

**Comment by culturetown** [comment]
Hello， How do I fill in the test account provided for submitting to the app shop for review?
