### ISSUE TITLE
Stickers have stopped increasing

### ISSUE THREAD

**Issue by minsk21** [TelegramMessenger/Telegram-iOS#859]
Stickers have stopped increasing if you hold your finger on them

![image](https://user-images.githubusercontent.com/26014600/194713129-bb357150-ba25-4444-b789-e66c2660ffb4.jpeg)

Перестали увеличиваеться стикеры, если на них зажать палец
ver 9.0.1 (24185)

**Comment by 8717908737** [comment]
What to do

**Comment by utsavDave97** [comment]
seems like it is fixed in 9.0.2 could you please check it out in 9.0.2

**Comment by minsk21** [comment]
9.1.0 (24364) -- fixed
