### ISSUE TITLE
Upgrading MTProxy to be used by CloudFlare and other CDN

### ISSUE THREAD

**Issue by hiddify** [TelegramMessenger/Telegram-iOS#861]
FakeTLS proxy has an issue that we can not use it on behind of a CDN.

If telegram can upgrade his protocol to use a real TLS on behind a CDN it would be great.

We successfully use v2ray protocol however it would be great if we can use a builtin proxy.

**Comment by ali-fareed** [comment]
This looks like a major cross-client task, so it would be better to report it at https://bugs.telegram.org
