### ISSUE TITLE
 Processing and signing NotificationServiceExtension failed:

### ISSUE THREAD

**Issue by mailes** [TelegramMessenger/Telegram-iOS#869]
weixiaobindeMacBook-Pro:Telegram-iOS Amy$ python3 build-system/Make/Make.py \
>  --overrideXcodeVersion \
>  --bazel="$HOME/bazel-dist/bazel" \
>  --cacheDir="$HOME/telegram-bazel-cache" \
>  build \
>  --configurationPath="$HOME/telegram-configuration/development-configuration.json" \
>  --buildNumber=100001 \
>  --configuration=release_universal \
>  --codesigningInformationPath="$HOME/telegram-configuration/fake-codesigning"
Overriding the required Xcode version 14.0 with 14.0.1 as reported by 'xcode-select -p'
TelegramBuild: running
/Users/weixiaobin/bazel-dist/bazel build Telegram/Telegram --override_repository=build_configuration=/Users/weixiaobin/Telegram-iOS/build-input/configuration-repository --announce_rc --features=swift.use_global_module_cache --verbose_failures --experimental_remote_cache_async --features=swift.skip_function_bodies_for_derived_files --jobs=8 --define=buildNumber=100001 --define=telegramVersion=9.0.2 --features=swift.split_derived_files_generation --disk_cache=/Users/weixiaobin/telegram-bazel-cache -c opt --ios_multi_cpus=armv7,arm64 --watchos_cpus=arm64_32 --apple_generate_dsym --output_groups=+dsyms --features=swift.opt_uses_wmo --features=swift.opt_uses_osize --swiftcopt=-num-threads --swiftcopt=0 --features=dead_strip --objc_enable_binary_stripping --apple_bitcode=watchos=embedded
Starting local Bazel server and connecting to it...
INFO: Invocation ID: 72537f35-2a3e-4d14-ada3-36c8504e13d1
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=80
INFO: Reading rc options for 'build' from /Users/weixiaobin/Telegram-iOS/.bazelrc:
  'build' options: --action_env=ZERO_AR_DATE=1 --apple_platform_type=ios --cxxopt=-std=c++17 --per_file_copt=third-party/webrtc/.*.cpp$,@-std=c++17 --per_file_copt=third-party/webrtc/.*.cc$,@-std=c++17 --per_file_copt=third-party/webrtc/.*.mm$,@-std=c++17 --per_file_copt=submodules/LottieMeshSwift/LottieMeshBinding/Sources/.*.mm$,@-std=c++17 --swiftcopt=-whole-module-optimization --features=debug_prefix_map_pwd_is_dot --features=swift.cacheable_swiftmodules --features=swift.debug_prefix_map --features=swift.enable_vfsoverlays --strategy=Genrule=standalone --spawn_strategy=standalone --strategy=SwiftCompile=standalone --define RULES_SWIFT_BUILD_DUMMY_WORKER=1
INFO: Analyzed target //Telegram:Telegram (401 packages loaded, 21695 targets configured).
INFO: Found 1 target...
ERROR: /Users/weixiaobin/Telegram-iOS/Telegram/BUILD:1747:14: Processing and signing NotificationServiceExtension failed: (Exit 1): process-and-sign-54436305.sh failed: error executing command 
  (cd /private/var/tmp/_bazel_Amy/40d386df50af74df78f36125cbf8ace6/execroot/__main__ && \
  exec env - \
    APPLE_SDK_PLATFORM=iPhoneOS \
    APPLE_SDK_VERSION_OVERRIDE=16.0 \
    XCODE_VERSION_OVERRIDE=14.0.1.14A400 \
  bazel-out/applebin_ios-ios_armv7-opt-ST-5b7531beec20/bin/Telegram/NotificationServiceExtension-intermediates/process-and-sign-54436305.sh should_sign should_compress)
# Configuration: 55ac85af467c0852b40b5a17ea9a235c3643b5e1e32c1946185f8d4a033b0896
# Execution platform: @local_config_platform//:host
ERROR: Unable to find an identity on the system matching the ones in external/build_configuration/provisioning/NotificationService.mobileprovision
Target //Telegram:Telegram failed to build
INFO: Elapsed time: 46.678s, Critical Path: 16.67s
INFO: 9 processes: 9 internal.
FAILED: Build did NOT complete successfully
Traceback (most recent call last):
  File "build-system/Make/Make.py", line 958, in <module>
    build(bazel=bazel_path, arguments=args)
  File "build-system/Make/Make.py", line 566, in build
    bazel_command_line.invoke_build()
  File "build-system/Make/Make.py", line 341, in invoke_build
    call_executable(combined_arguments)
  File "/Users/weixiaobin/Telegram-iOS/build-system/Make/BuildEnvironment.py", line 81, in call_executable
    subprocess.check_call(resolved_arguments, env=resolved_env)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/weixiaobin/bazel-dist/bazel', 'build', 'Telegram/Telegram', '--override_repository=build_configuration=/Users/weixiaobin/Telegram-iOS/build-input/configuration-repository', '--announce_rc', '--features=swift.use_global_module_cache', '--verbose_failures', '--experimental_remote_cache_async', '--features=swift.skip_function_bodies_for_derived_files', '--jobs=8', '--define=buildNumber=100001', '--define=telegramVersion=9.0.2', '--features=swift.split_derived_files_generation', '--disk_cache=/Users/weixiaobin/telegram-bazel-cache', '-c', 'opt', '--ios_multi_cpus=armv7,arm64', '--watchos_cpus=arm64_32', '--apple_generate_dsym', '--output_groups=+dsyms', '--features=swift.opt_uses_wmo', '--features=swift.opt_uses_osize', '--swiftcopt=-num-threads', '--swiftcopt=0', '--features=dead_strip', '--objc_enable_binary_stripping', '--apple_bitcode=watchos=embedded']' returned non-zero exit status 1.

**Comment by mailes** [comment]
please help me. thx

**Comment by ali-fareed** [comment]
You are trying to build the app for deployment on an actual device using empty code signing certificates.
