### ISSUE TITLE
GIF's is autoplays even if it's disabled

### ISSUE THREAD

**Issue by Neurotoxin001** [TelegramMessenger/Telegram-iOS#87]
Telegram iOS 5.9
iOS 12.3.1

1. Disable autoplay for GIF's in settings
2. Send any gif to any chat
3. GIF will autoplay

If you have disabled auto-download for GIF's and someone is send you GIF:
1. Download that GIF
2. Go away from this chat
3. Go back to this chat
4. GIF is autoplaying

**Comment by shivanraptor** [comment]
I can't repeat this problem in v5.9. If I set GIF autoplay to disable. The GIF is still stopped no matter how many times I leave and go back to the chat.

**Comment by Neurotoxin001** [comment]
> I can't repeat this problem in v5.9. If I set GIF autoplay to disable. The GIF is still stopped no matter how many times I leave and go back to the chat.

Try to save GIF to your account.

**Comment by laktyushin** [comment]
Fixed in 5.10 release.
