### ISSUE TITLE
Persian is not displayed correctly

### ISSUE THREAD

**Issue by AtaReversei** [TelegramMessenger/Telegram-iOS#871]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
Persian characters are not decoded correctly sometimes and the text is displayed as unknown characters (square with a question mark inside of it) but English text displays correctly at the same time.
This said behavior happens sometimes and then after a while it automatically returns to the normal state.
Simply said: most of the times everything works correctly but sometimes Persian is not rendered.

### Expected Behavior
Persian text should display correctly.

### Actual Behavior
Persian text displays as unknown characters once in a while.

### Steps to Reproduce
unfortunately I don't know what causes this problem.

### Screenshots and Videos 
![photo_2022-10-24_20-05-47](https://user-images.githubusercontent.com/76823888/197849940-049f5322-13e2-4c79-a9c0-e6bc4509a61c.jpg)

### Environment
**Device:** `iPhone xs`

**iOS version**: `15.7`

**App version:** `8.9`

**Comment by ali-fareed** [comment]
This issue should have been fixed in 9.0.
