### ISSUE TITLE
I cannot run the iOS project on the real machine. The simulator runs successfully, and I can successfully compile the IPA file.

### ISSUE THREAD

**Issue by mailes** [TelegramMessenger/Telegram-iOS#877]
According to the guidance file, I successfully compiled the IPA file and generated the Xcode project file that can run normally on the simulator. But when I tried to run the real machine, I checked Automatically manage signing and configured Capability, but still prompted me with the following error:

Unable to install "Telegram"
Domain: com.apple.dt.MobileDeviceErrorDomain
Code: -402620395
User Info: {
    DVTErrorCreationDateKey = "2022-10-28 01:50:37 +0000";
    IDERunOperationFailingWorker = IDEInstalliPhoneLauncher;
}
A valid provisioning profile for this executable was not found.
Domain: com.apple.dt.MobileDeviceErrorDomain
--
//----

I have configured all the signatures and certificates that can be configured, but they still cannot be compiled on the real machine. I don't know where the problem occurs, and whether there are some things I have missed. Please help me, thank you.

{
    "app": "9.0.2",
    "bazel": "5.3.1",
    "xcode": "14.0.1"
}

// -----

![Simulator Screen Shot - iPhone 14 - 2022-10-28 at 09 52 24](https://user-images.githubusercontent.com/2554806/198456455-cc895242-5acc-444e-b3a2-7aa07a57c5d4.png)

![WX20221028-095733@2x](https://user-images.githubusercontent.com/2554806/198456495-1a609fd2-883b-4c34-a4c5-2502cf7d4b48.png)
![WX20221028-095747@2x](https://user-images.githubusercontent.com/2554806/198456536-ffeb1650-bed6-4df4-8ea5-2db429eafb70.png)
![WX20221028-095810@2x](https://user-images.githubusercontent.com/2554806/198456580-436af017-118c-4778-bbed-8fb45399277b.png)

**Comment by mailes** [comment]
Error screenshot

![WX20221028-100924@2x](https://user-images.githubusercontent.com/2554806/198459214-1f442b52-2e00-41d8-84e5-0d17f383f757.png)

**Comment by mailes** [comment]
I used the following command to generate the project file:

python3 build-system/Make/Make.py \
 --overrideXcodeVersion \
 --cacheDir="$HOME/telegram-bazel-cache" \
 --bazel="$HOME/bazel-dist/bazel" \
 generateProject \
 --configurationPath="$HOME/telegram-configuration-development/development-configuration.json" \
 --disableExtensions \
 --codesigningInformationPath="$HOME/telegram-configuration-development/fake-codesigning"

or

python3 build-system/Make/Make.py \
 --overrideXcodeVersion \
 --cacheDir="$HOME/telegram-bazel-cache" \
 --bazel="$HOME/bazel-dist/bazel" \
 generateProject \
 --configurationPath="$HOME/telegram-configuration-development/development-configuration.json" \
 --codesigningInformationPath="$HOME/telegram-configuration-development/fake-codesigning"

**Comment by mailes** [comment]
It's strange that I deleted the project and cloned it again. All the previous certificate files have not changed. Then I rebuilt. I succeeded. I generated the iOS project file. I succeeded. Then I ran the project directly. Without checking any certificate settings, it can run on the real machine. This project does not need to set certificates in xcode. All the project settings are set in/Users/xxx/Program iOS/Program/BUILD, the build file.

**Comment by xionghx** [comment]
> Error screenshot
> 
> ![WX20221028-100924@2x](https://user-images.githubusercontent.com/2554806/198459214-1f442b52-2e00-41d8-84e5-0d17f383f757.png)

I would like to ask you how to configure your certificate, looking forward to your reply!

**Comment by dfang** [comment]
> > Error screenshot
> > ![WX20221028-100924@2x](https://user-images.githubusercontent.com/2554806/198459214-1f442b52-2e00-41d8-84e5-0d17f383f757.png)
> 
> I would like to ask you how to configure your certificate, looking forward to your reply!

i also got this error: "A valid provisioning profile for this executable was not found"

did you fix it?
