### ISSUE TITLE
Switching accounts causes the status bar to disappear.

### ISSUE THREAD

**Issue by Benno1308** [TelegramMessenger/Telegram-iOS#885]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
When switching between two accounts by pressing and holding on the profile picture in the bottom bar the iOS status bar disappears. This does not happen when using the account list in the settings. Bar is missing even when closing and reopening Telegram, only killing the app in the background and then restarting it fixes it. Another way to fix it is by pressing and holding the account selector again in the bugged state, and then instead of switching just tapping anywhere else to cancle the switch.
My best guess is that the status bar gets hidden for the blur effect while the switch list is open, and its not getting restored when the account gets switched.

### Expected Behavior
I expect to change the account, even with holding down on the account selector, without having the bar disappear.

### Actual Behavior
Currently switching the account by holding down the account selector and selecting a different account causes the top iOS status bar to disappear.

### Steps to Reproduce
1. Add two Telegram accounts
2. Press and hold the account selector in the bottom right
3. Select the second account
4. Notice the status bar is now gone

### Screenshots and Videos 
Before switching the account:
![Before](https://i.imgur.com/yacRNk5.png)

After switching the account, notice the clock, cellular, wifi and battery indicators are gone:
![After](https://i.imgur.com/8xYiIDp.png)

### Environment
**Device:** `iPhone 13 Pro Max`

**iOS version**: `16.0.2, not jailbroken`

**App version:** `9.0.2 (24217)`

**Comment by Skyfail** [comment]
Experiencing the same issue on iPhone 14 Pro Max. Very inconvenient.

**Comment by laktyushin** [comment]
Fixed in 9.1
