### ISSUE TITLE
Visual bug when scheduling messages

### ISSUE THREAD

**Issue by Neurotoxin001** [TelegramMessenger/Telegram-iOS#892]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
Describe the issue that you are experiencing

### Expected Behavior
Schedule button is not block the schedule timer

### Actual Behavior
Schedule button is blocking the schedule timer

### Steps to Reproduce
1. Schedule message
2. Click on time
3. The window with time will be blocked

### Screenshots and Videos 

https://user-images.githubusercontent.com/39812401/200302454-8616a159-f808-423e-b237-b37259b5de1b.mp4

### Environment
**Device:** `iPhone XR`

**iOS version**: `16.1`

**App version:** `9.1.0`

**Comment by laktyushin** [comment]
Fixed in 9.5
