### ISSUE TITLE
bug: Notification still shows on mobile after being seen on desktop

### ISSUE THREAD

**Issue by IoanaStanescu** [TelegramMessenger/Telegram-iOS#90]
Tg version: 5.9.1
IOS: 12.3.1

In the last 2 telegram versions, when receiving notifications on my phone and view the messages on my laptop, the notifications and the message count badge are still visible on my phone, they only disappear after opening telegram.

**Comment by shivanraptor** [comment]
which Telegram Desktop version are you using? btw, v5.9.1 hasn't released source at this moment.

**Comment by IoanaStanescu** [comment]
@shivanraptor I'm using `Telegram Desktop 1.7 Store` on `MacOS 10.14.5`

**Comment by shivanraptor** [comment]
I'm using Telegram 4.2.2.135543 (old Desktop client) on macOS 10.14.5, the badge count seems normal for me. Try terminating other old active sessions.

**Comment by laktyushin** [comment]
It was a server-side issue, everything should be fine now.
