### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by MrGuoZiHao** [TelegramMessenger/Telegram-iOS#905]
python3 build-system/Make/Make.py \--overrideBazelVersion \
    --bazel="$HOME/bazel-dist/bazel" \
    --cacheDir="$HOME/telegram-bazel-cache" \
    build \
    --configurationPath="$HOME/telegram-configuration" \
    --buildNumber=100001 \
    --configuration=release_universal

### Checklist
- [✅ ] I am reporting an issue in existing functionality that does not work as intended
- [ ✅] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

INFO: Invocation ID: d61cdfd7-1f94-4e35-b90e-bfac6f2ce9dd
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=80
INFO: Reading rc options for 'build' from /Users/guozihao/teamgram-ios/.bazelrc:
  'build' options: --action_env=ZERO_AR_DATE=1 --apple_platform_type=ios --cxxopt=-std=c++14 --per_file_copt=third-party/webrtc/.*.cpp$,@-std=c++14 --per_file_copt=third-party/webrtc/.*.cc$,@-std=c++14 --per_file_copt=third-party/webrtc/.*.mm$,@-std=c++14 --per_file_copt=submodules/LottieMeshSwift/LottieMeshBinding/Sources/.*.mm$,@-std=c++14 --swiftcopt=-whole-module-optimization --features=debug_prefix_map_pwd_is_dot --features=swift.cacheable_swiftmodules --features=swift.debug_prefix_map --features=swift.enable_vfsoverlays --strategy=Genrule=standalone --spawn_strategy=standalone --strategy=SwiftCompile=standalone --define RULES_SWIFT_BUILD_DUMMY_WORKER=1
INFO: Analyzed target //Telegram:Telegram (369 packages loaded, 21838 targets configured).
INFO: Found 1 target...
INFO: From Compiling third-party/ZipArchive/Sources/minizip/mz_strm_zlib.c:
third-party/ZipArchive/Sources/minizip/mz_strm_zlib.c:145:14: warning: variable 'total_in' set but not used [-Wunused-but-set-variable]
    uint32_t total_in = 0;
             ^
1 warning generated.
INFO: From Compiling third-party/ZipArchive/Sources/SSZipArchive.m:
third-party/ZipArchive/Sources/SSZipArchive.m:360:18: warning: variable 'isDirectory' set but not used [-Wunused-but-set-variable]
            BOOL isDirectory = NO;
                 ^
third-party/ZipArchive/Sources/SSZipArchive.m:309:14: warning: variable 'unzippingError' set but not used [-Wunused-but-set-variable]
    NSError *unzippingError;
             ^
third-party/ZipArchive/Sources/SSZipArchive.m:472:18: warning: variable 'isDirectory' set but not used [-Wunused-but-set-variable]
            BOOL isDirectory = NO;
                 ^
third-party/ZipArchive/Sources/SSZipArchive.m:597:14: warning: variable 'retErr' set but not used [-Wunused-but-set-variable]
    NSError *retErr = nil;
             ^
4 warnings generated.
ERROR: /Users/guozihao/teamgram-ios/third-party/yasm/BUILD:3:8: Executing genrule //third-party/yasm:yasm [for host] failed: (Exit 1): bash failed: error executing command 
  (cd /private/var/tmp/_bazel_guozihao/cffe0672cebfecf2266d14083cef5e70/execroot/__main__ && \
  exec env - \
    PATH=/usr/bin:/bin:/usr/sbin:/sbin \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; 
set -x
    core_count="`sysctl -n hw.logicalcpu`"
    BUILD_DIR="bazel-out/host/bin/third-party/yasm/build"
    rm -rf "$BUILD_DIR"
    mkdir -p "$BUILD_DIR"

    CMAKE_DIR="$(pwd)/$BUILD_DIR/cmake"
    rm -rf "$CMAKE_DIR"
    mkdir -p "$CMAKE_DIR"
    tar -xf "external/cmake_tar_gz/file/downloaded" -C "$CMAKE_DIR"
    
    tar -xzf "third-party/yasm/yasm-1.3.0.tar.gz" --directory "$BUILD_DIR"
    pushd "$BUILD_DIR/yasm-1.3.0"
    mkdir build
    cd build
    PATH="$PATH:$CMAKE_DIR/cmake-3.19.2-macos-universal/CMake.app/Contents/bin" cmake .. -DYASM_BUILD_TESTS=OFF -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF
    make -j $core_count
    popd

    tar -cf "bazel-out/host/bin/third-party/yasm/yasm.tar" -C "$BUILD_DIR/yasm-1.3.0/build" .
')
# Configuration: 0bd5fe4086c257b857bd1f2b65d911e00c80e669b05802c5c78fc7299295c27a
# Execution platform: @local_config_platform//:host
++ sysctl -n hw.logicalcpu
+ core_count=8
+ BUILD_DIR=bazel-out/host/bin/third-party/yasm/build
+ rm -rf bazel-out/host/bin/third-party/yasm/build
+ mkdir -p bazel-out/host/bin/third-party/yasm/build
++ pwd
+ CMAKE_DIR=/private/var/tmp/_bazel_guozihao/cffe0672cebfecf2266d14083cef5e70/execroot/__main__/bazel-out/host/bin/third-party/yasm/build/cmake
+ rm -rf /private/var/tmp/_bazel_guozihao/cffe0672cebfecf2266d14083cef5e70/execroot/__main__/bazel-out/host/bin/third-party/yasm/build/cmake
+ mkdir -p /private/var/tmp/_bazel_guozihao/cffe0672cebfecf2266d14083cef5e70/execroot/__main__/bazel-out/host/bin/third-party/yasm/build/cmake
+ tar -xf external/cmake_tar_gz/file/downloaded -C /private/var/tmp/_bazel_guozihao/cffe0672cebfecf2266d14083cef5e70/execroot/__main__/bazel-out/host/bin/third-party/yasm/build/cmake
+ tar -xzf third-party/yasm/yasm-1.3.0.tar.gz --directory bazel-out/host/bin/third-party/yasm/build
+ pushd bazel-out/host/bin/third-party/yasm/build/yasm-1.3.0
+ mkdir build
+ cd build
+ PATH=/usr/bin:/bin:/usr/sbin:/sbin:/private/var/tmp/_bazel_guozihao/cffe0672cebfecf2266d14083cef5e70/execroot/__main__/bazel-out/host/bin/third-party/yasm/build/cmake/cmake-3.19.2-macos-universal/CMake.app/Contents/bin
+ cmake .. -DYASM_BUILD_TESTS=OFF -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF
CMake Deprecation Warning at CMakeLists.txt:2 (CMAKE_MINIMUM_REQUIRED):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

CMake Error at ConfigureChecks.cmake:39 (MESSAGE):
  Could not find Python executable
Call Stack (most recent call first):
  CMakeLists.txt:36 (INCLUDE)

/private/var/tmp/_bazel_guozihao/cffe0672cebfecf2266d14083cef5e70/execroot/__main__/bazel-out/host/bin/third-party/yasm/build/yasm-1.3.0 /private/var/tmp/_bazel_guozihao/cffe0672cebfecf2266d14083cef5e70/execroot/__main__
-- The C compiler identification is AppleClang 13.1.6.13160021
-- The CXX compiler identification is AppleClang 13.1.6.13160021
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for locale.h
-- Looking for locale.h - found
-- Looking for libgen.h
-- Looking for libgen.h - found
-- Looking for unistd.h
-- Looking for unistd.h - found
-- Looking for direct.h
-- Looking for direct.h - not found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for abort
-- Looking for abort - found
-- Looking for getcwd
-- Looking for getcwd - found
-- Looking for toascii
-- Looking for toascii - found
-- Looking for dlopen in dl
-- Looking for dlopen in dl - found
-- Could NOT find PythonInterp (missing: PYTHON_EXECUTABLE) 
-- Configuring incomplete, errors occurred!
See also "/private/var/tmp/_bazel_guozihao/cffe0672cebfecf2266d14083cef5e70/execroot/__main__/bazel-out/host/bin/third-party/yasm/build/yasm-1.3.0/build/CMakeFiles/CMakeOutput.log".
See also "/private/var/tmp/_bazel_guozihao/cffe0672cebfecf2266d14083cef5e70/execroot/__main__/bazel-out/host/bin/third-party/yasm/build/yasm-1.3.0/build/CMakeFiles/CMakeError.log".
Target //Telegram:Telegram failed to build
ERROR: /Users/guozihao/teamgram-ios/Telegram/BUILD:1073:14 Linking Telegram/TelegramUIFramework_bin_unstripped failed: (Exit 1): bash failed: error executing command 
  (cd /private/var/tmp/_bazel_guozihao/cffe0672cebfecf2266d14083cef5e70/execroot/__main__ && \
  exec env - \
    PATH=/usr/bin:/bin:/usr/sbin:/sbin \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; 
set -x
    core_count="`sysctl -n hw.logicalcpu`"
    BUILD_DIR="bazel-out/host/bin/third-party/yasm/build"
    rm -rf "$BUILD_DIR"
    mkdir -p "$BUILD_DIR"

    CMAKE_DIR="$(pwd)/$BUILD_DIR/cmake"
    rm -rf "$CMAKE_DIR"
    mkdir -p "$CMAKE_DIR"
    tar -xf "external/cmake_tar_gz/file/downloaded" -C "$CMAKE_DIR"
    
    tar -xzf "third-party/yasm/yasm-1.3.0.tar.gz" --directory "$BUILD_DIR"
    pushd "$BUILD_DIR/yasm-1.3.0"
    mkdir build
    cd build
    PATH="$PATH:$CMAKE_DIR/cmake-3.19.2-macos-universal/CMake.app/Contents/bin" cmake .. -DYASM_BUILD_TESTS=OFF -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF
    make -j $core_count
    popd

    tar -cf "bazel-out/host/bin/third-party/yasm/yasm.tar" -C "$BUILD_DIR/yasm-1.3.0/build" .
')
# Configuration: 0bd5fe4086c257b857bd1f2b65d911e00c80e669b05802c5c78fc7299295c27a
# Execution platform: @local_config_platform//:host
INFO: Elapsed time: 62.160s, Critical Path: 24.55s
INFO: 116 processes: 16 internal, 100 local.
FAILED: Build did NOT complete successfully
Traceback (most recent call last):
  File "build-system/Make/Make.py", line 728, in <module>
    build(bazel=bazel_path, arguments=args)
  File "build-system/Make/Make.py", line 482, in build
    bazel_command_line.invoke_build()
  File "build-system/Make/Make.py", line 328, in invoke_build
    call_executable(combined_arguments)
  File "/Users/guozihao/teamgram-ios/build-system/Make/BuildEnvironment.py", line 60, in call_executable
    subprocess.check_call(resolved_arguments, env=resolved_env)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/guozihao/bazel-dist/bazel', 'build', 'Telegram/Telegram', '--override_repository=build_configuration=/Users/guozihao/telegram-configuration', '--announce_rc', '--verbose_failures', '--features=swift.skip_function_bodies_for_derived_files', '--jobs=8', '--define=buildNumber=100001', '--define=telegramVersion=1.1.3', '--features=swift.split_derived_files_generation', '--disk_cache=/Users/guozihao/telegram-bazel-cache', '-c', 'opt', '--ios_multi_cpus=armv7,arm64', '--watchos_cpus=armv7k,arm64_32', '--apple_generate_dsym', '--output_groups=+dsyms', '--features=swift.opt_uses_wmo', '--features=swift.opt_uses_osize', '--swiftcopt=-num-threads', '--swiftcopt=0', '--features=dead_strip', '--objc_enable_binary_stripping', '--apple_bitcode=watchos=embedded']' returned non-zero exit status 1.

### Environment
**Xcode** `13.4.1`

**bazel**: `5.3.1`

**App version:** `8.7.1`

**Comment by tboxSol** [comment]
@MrGuoZiHao  can you tell us what was the fix?
