### ISSUE TITLE
Ventura OS - mac + xcode 13.4 = BROKEN / xcode 14.1 won't compile.

### ISSUE THREAD

**Issue by wweevv-johndpope** [TelegramMessenger/Telegram-iOS#907]
<img width="198" alt="Screenshot 2022-11-18 at 3 47 42 pm" src="https://user-images.githubusercontent.com/109928647/202627187-822474d4-2210-42ae-a085-ba60dbc05257.png">
<img width="703" alt="Screenshot 2022-11-18 at 3 40 29 pm" src="https://user-images.githubusercontent.com/109928647/202627191-1fb2fef3-e2fd-4845-af2f-8e0a1b1a4f26.png">
<img width="383" alt="Screenshot 2022-11-18 at 3 40 01 pm" src="https://user-images.githubusercontent.com/109928647/202627196-7efaceb3-13c3-4938-9a99-ed9641114df4.png">

I can bypass apple check
https://stackoverflow.com/questions/74192400/how-to-use-xcode-13-in-mac-os-ventura

but I hit a snag here 
```shell

 python3 build-system/Make/Make.py \
    --cacheDir="$HOME/telegram-bazel-cache" \
    generateProject \
    --configurationPath="$HOME/telegram-configuration" \
    --disableExtensions \
    --disableProvisioningProfiles
No matching processes belonging to you were found
DEBUG: /private/var/tmp/_bazel_johndpope/0e434b6d62f27b03b80d39b702400d2a/external/bazel_tools/tools/osx/xcode_configure.bzl:243:14: No default Xcode version is set with 'xcode-select'; picking ':version14_1_0_14B47b'
ERROR: /private/var/tmp/_bazel_johndpope/0e434b6d62f27b03b80d39b702400d2a/external/local_config_xcode/BUILD:12:13: in xcode_config rule @local_config_xcode//:host_xcodes: --xcode_version=13.4.1 specified, but '13.4.1' is not an available Xcode version. available versions: [14.1.0.14B47b]. If you believe you have '13.4.1' installed, try running "bazel shutdown", and then re-run your command.
ERROR: /private/var/tmp/_bazel_johndpope/0e434b6d62f27b03b80d39b702400d2a/external/local_config_xcode/BUILD:12:13: Analysis of target '@local_config_xcode//:host_xcodes' failed
ERROR: Analysis of target '//:tulsi' failed; build aborted:
INFO: Elapsed time: 0.141s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
Traceback (most recent call last):
  File "build-system/Make/Make.py", line 726, in <module>
    generate_project(bazel=bazel_path, arguments=args)
  File "build-system/Make/Make.py", line 455, in generate_project
    target_name=target_name
  File "/Users/johndpope/Documents/gitWorkspace/Telegram-iOS/build-system/Make/ProjectGeneration.py", line 46, in generate
    call_executable(tulsi_build_command)
  File "/Users/johndpope/Documents/gitWorkspace/Telegram-iOS/build-system/Make/BuildEnvironment.py", line 60, in call_executable
    subprocess.check_call(resolved_arguments, env=resolved_env)
  File "/Users/johndpope/opt/miniconda3/envs/spleeter/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/johndpope/Documents/gitWorkspace/Telegram-iOS/build-input/bazel-5.1.0-darwin-x86_64', 'build', '//:tulsi', '--xcode_version=13.4.1', '--use_top_level_targets_for_symlinks', '--verbose_failures', '--swiftcopt=-whole-module-optimization']' returned non-zero exit status 1.
```

<img width="1269" alt="Screenshot 2022-11-18 at 4 30 13 pm" src="https://user-images.githubusercontent.com/109928647/202627752-ff1b2853-1f0d-440c-a2cf-41fdbeb420d9.png">

**Comment by wweevv-johndpope** [comment]
:( https://support.apple.com/en-us/HT208891

**Comment by wweevv-johndpope** [comment]
UPDATE

v

ueuing Tulsi build...
<*> Parsing options completed in 0.062 ms
Traceback (most recent call last):
  File "/Users/johndpope/Documents/gitWorkspace/wweevv-ios/build-input/gen/project/Telegram.xcodeproj/.tulsi/Scripts/bazel_build.py", line 1861, in <module>
    _exit_code = main(sys.argv)
  File "/Users/johndpope/Documents/gitWorkspace/wweevv-ios/build-input/gen/project/Telegram.xcodeproj/.tulsi/Scripts/bazel_build.py", line 1848, in main
    return BazelBuildBridge(build_settings).Run(argv)
  File "/Users/johndpope/Documents/gitWorkspace/wweevv-ios/build-input/gen/project/Telegram.xcodeproj/.tulsi/Scripts/bazel_build.py", line 564, in Run
    self.bazel_bin_path = os.path.abspath(parser.bazel_bin_path)
  File "/Applications/Xcode-13.4.1.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/posixpath.py", line 379, in abspath
    cwd = os.getcwd()
PermissionError: [Errno 1] Operation not permitted
Command /bin/sh failed with exit code 1


<img width="1170" alt="Screenshot 2022-12-27 at 9 30 57 am" src="https://user-images.githubusercontent.com/109928647/209597210-64e07393-961d-4bb3-9ff1-8a7d941f38ca.png">
<img width="492" alt="Screenshot 2022-12-27 at 9 30 47 am" src="https://user-images.githubusercontent.com/109928647/209597218-982bea5b-05b1-4e4c-941b-d174edc4b471.png">
<img width="295" alt="Screenshot 2022-12-27 at 9 30 44 am" src="https://user-images.githubusercontent.com/109928647/209597221-300ca44b-08ef-423b-86c1-8428809ac476.png">

**Comment by jeudesprits** [comment]
@ali-fareed It's the same problem in macOS Sonoma. Unfortunately, the script above doesn't work anymore. bazel shutdown does not help either.
