### ISSUE TITLE
Media files in chat blinking and bouncing across the screen

### ISSUE THREAD

**Issue by VladyslavBelov** [TelegramMessenger/Telegram-iOS#920]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
A large amount of media files in chat blinking and bouncing across the screen which makes it impossible to view the content normally. I have to use search by media for correct view media in chats.

### Expected Behavior
During scrolling the channel or direct chat with a grouped photo or video files, messages scrolls normally and the user can scroll up and down without any problem.

### Actual Behavior
When I opened a chat with a large amount of media files in one moment chat started blinking, bouncing and even automatically scrolling.

### Steps to Reproduce
1. Open the chat with many grouped media files, e.x. 5+ messages by 10 files(video and photo).
2. Start scrolling chat up 
3. In one moment, during scrolling chat started blinking and bouncing

### Screenshots and Videos 
https://user-images.githubusercontent.com/111646802/204289316-4c5bea1f-07c4-4297-a939-8505af9384e9.MP4

### Environment
**Device:** `iPhone XR and iPhone 13.`

**iOS version**: `16.1`

**App version:** `9.1.1(24496)`

**Comment by robsonsobral** [comment]
The same happening on environment:

Device: iPhone 8 Plus
iOS version: 15.4.1
App version: 9.1.1 (24496)

**Comment by ali-fareed** [comment]
Please check whether it is resolved in 9.2.

**Comment by robsonsobral** [comment]
The version 9.2.0 is working fine! Thank you!
