### ISSUE TITLE
[Feature Request] Favorite group message and Message Reactions

### ISSUE THREAD

**Issue by DevopsDood** [TelegramMessenger/Telegram-iOS#93]
There are two **very** common things people use on other platforms. Message favoriting in group so a user can reference it later more easily and reactions to messages. I'd really like to be able to just thumbs up a message in a group rather than say "cool" and not have to notify the other users in the group. I also have some favorite messages I want to save but am unable to.

**Comment by shivanraptor** [comment]
You can always forward your favorite messages to "Saved Messages".

**Comment by themotu** [comment]
Of course this can be done. But how does that help me keep it in context with the conversation in the group I did that from? Also how would I keep track of my more interesting saved messages? And how does this help with message reactions?

**Comment by michaelmarion** [comment]
I'd love to have message reactions! Hoping to bump this issue up to the top for a bit more visibility.

**Comment by samuelpetrosyan** [comment]
Any news on this topic??

**Comment by laktyushin** [comment]
Added in 8.4
