### ISSUE TITLE
In-app black screen

### ISSUE THREAD

**Issue by mikhailfluffy** [TelegramMessenger/Telegram-iOS#930]
Hello, there!

I can't sign IPA file from Releases by Apple certificate
After sign and install I've got a black screen in app
What I can do? It's required to setup app with XCode? Or have a variables how to do it without MacOS?

**Comment by L-Jay** [comment]
same issues，can you resolve？

**Comment by ali-fareed** [comment]
Application files in the Release section are not suitable for installation.

**Comment by df1228** [comment]
> Application files in the Release section are not suitable for installation.

Then how to build one suitable for installation in CI, both resign or sideload are acceptable.

**Comment by LSPBoy** [comment]
can you solve it?
