### ISSUE TITLE
Do this repository need more collaborators?

### ISSUE THREAD

**Issue by xjrcode** [TelegramMessenger/Telegram-iOS#932]
The [last released version](https://github.com/TelegramMessenger/Telegram-iOS/releases) is 8.9 but the [App Store version](https://apps.apple.com/app/telegram-messenger/id686449807) is 9.2

There are 18 pull requests and more than 340 issues, but there are commits every week. 

The iPad version still does not work properly and the support for WatchOS dropped with no news. 

It seems the focus now is generate content for get more money / TON but there is no intention of do a better platform. 

Do you need more support for manage all this stuff?

**Comment by ali-fareed** [comment]
The latest source code is always available after each public release at https://github.com/TelegramMessenger/Telegram-iOS/tags

The community is always welcome to contribute.
