### ISSUE TITLE
Support for custom tones?

### ISSUE THREAD

**Issue by pmkary** [TelegramMessenger/Telegram-iOS#94]
Thanks a lot for the amazing app.

Can we have support for custom notification tones? Like being able to access the custom text notification tones on the os or being able to set a file as the tone? It’ll make the feel of telegram very awesome

**Comment by laktyushin** [comment]
Apple does not allow to set user-provided sounds for push notifications. If we want to play a custom sound it must be included in the app bundle first (as we already do for the available tones).

**Comment by Mr-ph422** [comment]
Hey iOS-Telegram team,
i want to ask at this point again for supporting custom tones.
I had a closer look on the singal messanger code and they did it with connecting the iOS local storrage to the app. Maybe you can do this on the same way (There I had to put my sound file into the local storrage/Downloads/Signal-sounds folder).

It would be greate when you can make this possible :)

BR Christian

**Comment by GatoPresto** [comment]
In iOS I can sync my own ringtones via iTunes or buy something in store. It would be great if you just have simple solution like "use system text tone"

**Comment by pouyakary** [comment]
So happy to see this is implemented! Thanks a lot Telegram team 😘❤️👯‍♀️
