### ISSUE TITLE
Can't build the app following the directions in the readme

### ISSUE THREAD

**Issue by michaeleisel** [TelegramMessenger/Telegram-iOS#941]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
When I run the command in the readme under "It is possible to generate a project...", this one:
```
python3 build-system/Make/Make.py \
    --cacheDir="$HOME/telegram-bazel-cache" \
    generateProject \
    --configurationPath="$HOME/telegram-configuration" \
    --disableExtensions \
    --disableProvisioningProfiles
```

I get the error, `Make generateProject: error: one of the arguments --gitCodesigningRepository --codesigningInformationPath --noCodesigning is required`. When I add `--noCodesigning=1` to satisfy this, I get a new error, `IsADirectoryError: [Errno 21] Is a directory: '/Users/meisel/telegram-configuration'`. It appears that it expects that to be the path to a JSON file, not a directory. How can I fix this? Should the readme be updated?

### Environment
**Device:** ARM mac

**App version:** latest master, f24c1ea6bb46c

**Comment by emlnv** [comment]
I have same problem

**Comment by PankiHoy** [comment]
+

**Comment by csc-EricWu** [comment]
me too

**Comment by DajuanM** [comment]
I got the same problem, how should i solve this problem?

**Comment by wweevv-johndpope** [comment]
try this 
python3 build-system/Make/Make.py \
    --cacheDir="$HOME/telegram-bazel-cache" \
    generateProject \
    --configurationPath="$HOME/telegram-configuration" \
    --disableExtensions \
    --disableProvisioningProfiles  --noCodesigning true

**Comment by wweevv-johndpope** [comment]
related 
https://github.com/TelegramMessenger/Telegram-iOS/search?q=development-configuration.json&type=issues
https://github.com/TelegramMessenger/Telegram-iOS/issues/872

_... I copied the appstore-configuration.json in the build-system folder, then change the settings based on the old variables.bzl file. It works fine._

**Comment by wweevv-johndpope** [comment]
I still get all this 💩
<img width="1281" alt="Screenshot 2023-01-11 at 4 36 59 pm" src="https://user-images.githubusercontent.com/109928647/211726034-7060931f-9db9-4655-a387-efac1cf6e199.png">

**Comment by ali-fareed** [comment]
@michaeleisel The build instructions will be updated. @wweevv-johndpope is correct: you need to copy and edit `appstore-configuration.json`, and create a directory with provisioning profiles that follows the structure in `build-system/fake-codesigning`. After that, run `build` as usual with adjusted `--configurationPath` and `--codesigningInformationPath` parameters.

For future reference, the app is guaranteed to build with the arguments from the `verify_beta_testflight` stage in `.gitlab-ci.yml`.

**Comment by ali-fareed** [comment]
@wweevv-johndpope The deprecated API issues should be reproducible when building for x86-64 simulators only (e.g. iPhone 6, or when building using a non-Apple Silicon Mac). Everything else was updated for iOS 11 several months ago.

**Comment by johndpope** [comment]
I thought so. Thanks. My 2017 iMac quickly approaching vintage status.
