### ISSUE TITLE
Photo selection when creating a new channel cause an app crash

### ISSUE THREAD

**Issue by mostafa-v** [TelegramMessenger/Telegram-iOS#952]
### Checklist
- [ x] I am reporting an issue in existing functionality that does not work as intended
- [x ] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
When creating a Channel, if I choose a photo for the channel, Telegram will crash.

### Expected Behavior
Selected image should get loaded and showed in the image editor

### Actual Behavior
Telegram will crash after photo selection

### Steps to Reproduce
1. Tap on new message icon
2. Tap on create Channel
3. Select a photo for channel

### Environment
**Device:** `iPhone`

**iOS version**: `15, 16`

**App version:** `9.3`

**Comment by laktyushin** [comment]
Fixed in 9.4.3
