### ISSUE TITLE
How to modify the  PresentationStrings.mapping file?

### ISSUE THREAD

**Issue by twisturn** [TelegramMessenger/Telegram-iOS#96]
I want to add a string,How to modify the  PresentationStrings.mapping file?

**Comment by laktyushin** [comment]
You can edit Localizable.strings and then generate PresentationStrings.swift and PresentationStrings.mapping by running `sh tools/GenerateLocalization.sh` from the project root.

**Comment by twisturn** [comment]
Version 5.5 does not have GenerateLocalization.sh file, which cannot be used when I send GenerateLocalization.sh file to this version

**Comment by twisturn** [comment]
@laktyushin
