### ISSUE TITLE
Login through email ( missing functionality ) in latest client 9.3

### ISSUE THREAD

**Issue by VetaLioSTV** [TelegramMessenger/Telegram-iOS#963]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
Since on 16th september revealed an new [update of telegram ](https://telegram.org/blog/infinite-reactions-statuses/ru#uluchsheniya-pri-vhode-v-akkaunt) which introduced new functionality `Login through email` . I would be ultra happy to use it, but still isn't available on **9.3** client. It fully unclear how to use it/where it can be enabled(activated), since there is nothing described in update/docs/FAQ. So i assume its not impletented/visible for now as default ? Where i can find such setting(either how to force/enable that functionality, like 10x taps on settings menu and etc)?

### Expected Behavior
Login through email should be available at settings menu

### Actual Behavior
Isn't available at all

### Steps to Reproduce
1. Go to settings
2. Try to found such settings
3. It's not available

### Environment
**Device:** `iPhone 7 Plus`

**iOS version**: `16`

**App version:** `9.3`

**Comment by VetaLioSTV** [comment]
@ali-fareed please assist.

**Comment by ali-fareed** [comment]
Had the option been available before the latest update?

**Comment by VetaLioSTV** [comment]
@ali-fareed no, it didn't. Fully unclear how to activate and where i should setup it?

**Comment by ali-fareed** [comment]
E-mail login setup is initiated by the server. There is no way to manually trigger it from the UI.

**Comment by VetaLioSTV** [comment]
@ali-fareed there is no explanation about how to achieve it. Also, there is a lot of questions about it. So could you answer?

**Comment by ali-fareed** [comment]
I'm not aware of any specific set of actions that would result in enabling e-mail sign-in.

**Comment by VetaLioSTV** [comment]
@ali-fareed update which comes [yesyerday](https://telegram.org/blog/profile-pics-emoji-translations/ru#vhod-s-apple-i-google-id), so login through email is now disabled/not available anymore ?

**Comment by ali-fareed** [comment]
There have been no changes to the e-mail login functionality.

**Comment by ali-fareed** [comment]
Do you see the option in other apps (TDesktop etc.)?

**Comment by VetaLioSTV** [comment]
@ali-fareed its re-appeared again, but you need to some back-forward actions. Unfortunately it wasn't available at TDesktop and i dont know why, i even made issue for this [here ](https://web.archive.org/web/20230217191156/https://github.com/telegramdesktop/tdesktop/issues/25737)
