### ISSUE TITLE
Users' geolocation info is blocked on Telegram Webapps

### ISSUE THREAD

**Issue by truth7eeker** [TelegramMessenger/Telegram-iOS#964]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
The webpage opened from Telegram Webapp fails to return any data on `navigator.geolocation.getCurrentPosition()` method call, although GPS is enabled within the phone and location services are allowed for the Telegram app. The same webpage works fine when opened from the mobile browser and shows the expected behavior on any iOS version. It looks like older versions of iOS works better in webapps, and the issue is mainly related to the newer versions.

### Expected Behavior
Webapp gets geolocation info on JS's `navigator.geolocation.getCurrentPosition()` method call.

### Actual Behavior
Webapp fails to get geolocation info on JS's `navigator.geolocation.getCurrentPosition()` method call.

### Environment
**Device:** `iPhone 11/12/13/14`

**Comment by ali-fareed** [comment]
This should be reported to the relevant issue trackers.

**Comment by jekeam** [comment]
> Об этом следует сообщить соответствующим трекерам проблем.

what needs to be done? please explain in more detail?

**Comment by jekeam** [comment]
> This should be reported to the relevant issue trackers.

How to ask a question correctly? can you explain in more detail?
