### ISSUE TITLE
[Privacy] Share extension activity is always logged to file which then can be accessed

### ISSUE THREAD

**Issue by G-200** [TelegramMessenger/Telegram-iOS#965]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
Share extension activity is always logged to file. Here is why:

https://github.com/TelegramMessenger/Telegram-iOS/blob/6a495f84c6bef56b554526218b26795fc0e15488/submodules/TelegramUI/Sources/ShareExtensionContext.swift#L261

Logs contain big amount of data about what was shared, to which chats, etc.
This seems like a privacy issue.
If someone gets access to the device, they always can see all sharing history of the user along with bunch of other data saved in debugging logs. And users can do nothing to stop it.
Besides log files cannot be deleted. Only option is to reinstall the app.

### Expected Behavior
By default logging should be disabled. Here the setting should be used instead of hardcoded value.
Also it would be good if there was option to clear logs in debugging menu.

### Actual Behavior
Share extension always write debugging logs to file, ignoring the settings.

### Steps to Reproduce
1. Share anything from any app to Telegram, for example share web page from Safari to any Telegram chat
2. Open debugging menu
3. Choose "Send Share Logs (Up to 40 MB)"
4. Open resulting file and observe too many private data saved there for no good reason.

### Environment
**Device:** `iPhone/iPad X`

**iOS version**: `16.2`

**App version:** `9.3.2` (bug exists since 7.4.1)

**Comment by ali-fareed** [comment]
Thank you for the report. The fix is going to be available in the next release.
The condition was not restored after debugging the Share extension locally.

**Comment by ali-fareed** [comment]
Thank you, the fix will be available in the next bug fix update. For reference, the initialization should look like:

```swift
do {
    let semaphore = DispatchSemaphore(value: 0)
    var loggingSettings = LoggingSettings.defaultSettings
    if buildConfig.isInternalBuild {
        loggingSettings = LoggingSettings(logToFile: true, logToConsole: false, redactSensitiveData: true)
    }
    let _ = (accountManager.transaction { transaction -> LoggingSettings? in
        if let value = transaction.getSharedData(SharedDataKeys.loggingSettings)?.get(LoggingSettings.self) {
            return value
        } else {
            return nil
        }
    }).start(next: { value in
        if let value {
            loggingSettings = value
        }
        semaphore.signal()
    })
    semaphore.wait()
    
    Logger.shared.logToFile = loggingSettings.logToFile
    Logger.shared.logToConsole = loggingSettings.logToConsole
    Logger.shared.redactSensitiveData = loggingSettings.redactSensitiveData
}
```

**Comment by ali-fareed** [comment]
https://github.com/TelegramMessenger/Telegram-iOS/blob/333011a6a649c7f6afea162d5eb1bef8bc178310/submodules/TelegramUI/Components/ShareExtensionContext/Sources/ShareExtensionContext.swift#L270C2-L270C2
