### ISSUE TITLE
Create xcode item block

### ISSUE THREAD

**Issue by ldu1101** [TelegramMessenger/Telegram-iOS#967]
### Description
Execute the following command

 python3 build-system/Make/Make.py \
    --overrideXcodeVersion \
    --cacheDir="$HOME/telegram-bazel-cache" \
    generateProject \
    --configurationPath="$HOME/telegram-configuration/development-configuration.json"  \
    --codesigningInformationPath "$HOME/telegram-configuration/fake-codesigning" \
    --disableExtensions \
    --disableProvisioningProfiles

### Happened Behavior

Stuck in this step, it hasn't changed for a long time

Starting local Bazel server and connecting to it...
INFO: Analyzed target //:tulsi (72 packages loaded, 1205 targets configured).
INFO: Found 1 target...
Target //:tulsi up-to-date:
  bazel-bin/tulsi.zip
INFO: Elapsed time: 11.328s, Critical Path: 0.47s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
[Syslog] Tulsi CLI: version 0.20220209.88
[Syslog] Create project: Telegram

### Environment

{
    "app": "9.3",
    "bazel": "5.3.1",
    "xcode": "14.2"
}

**Comment by niufuwei** [comment]
Hello，Excuse me, have you solved it? I also have this problem @ali-fareed @ldu1101
