### ISSUE TITLE
Packaging error Processing and signing IntentsExtension failed

### ISSUE THREAD

**Issue by ldu1101** [TelegramMessenger/Telegram-iOS#968]
### Description
Use the following command to package

python3 build-system/Make/Make.py \
    --overrideXcodeVersion \
    --cacheDir="$HOME/telegram-bazel-cache" \
    build \
    --configurationPath="$HOME/telegram-configuration/development-configuration.json"  \
    --codesigningInformationPath "$HOME/telegram-configuration/fake-codesigning" \
    --buildNumber=100001 \
    --configuration=release_universal

### Actual Behavior

ERROR: /Users/zhongjing/Telegram-iOS/Telegram/BUILD:1582:14: Processing and signing IntentsExtension failed: (Exit 1): process-and-sign--622850460.sh failed: error executing command 
  (cd /private/var/tmp/_bazel_zhongjing/e75cad79b59f775ce4e0ce0f86686315/execroot/__main__ && \
  exec env - \
    APPLE_SDK_PLATFORM=iPhoneOS \
    APPLE_SDK_VERSION_OVERRIDE=16.2 \
    XCODE_VERSION_OVERRIDE=14.2.0.14C18 \
  bazel-out/applebin_ios-ios_armv7-opt-ST-5b7531beec20/bin/Telegram/IntentsExtension-intermediates/process-and-sign--622850460.sh should_sign should_compress)
# Configuration: d197f69d6dbac29e003785f365fe53da6be3b527d8f5a1cdede5b9b3d5cb6d4a
# Execution platform: @local_config_platform//:host
ERROR: Unable to find an identity on the system matching the ones in external/build_configuration/provisioning/Intents.mobileprovision
Target //Telegram:Telegram failed to build
INFO: Elapsed time: 3.151s, Critical Path: 1.43s
INFO: 4 processes: 4 internal.
FAILED: Build did NOT complete successfully

who can help me

### Environment

{
    "app": "9.3",
    "bazel": "5.3.1",
    "xcode": "14.2"
}

**Comment by ali-fareed** [comment]
You need to place your own provisioning profiles at `codesigningInformationPath`. The corresponding certificates must be installed and not be expired (this can be checked with `Keychain Access`).

**Comment by ldu1101** [comment]
> You need to place your own provisioning profiles at `codesigningInformationPath`. The corresponding certificates must be installed and not be expired (this can be checked with `Keychain Access`).

thanks, it works

**Comment by baiyidjp** [comment]
I also encountered this error, but I don't know how to do it at all, can you teach me how to do it ？
