### ISSUE TITLE
[Web Apps] "popup_closed" event contains incorrect payload

### ISSUE THREAD

**Issue by heyqbnk** [TelegramMessenger/Telegram-iOS#969]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
According to official `popup_closed` [documentation](https://core.telegram.org/api/bots/webapps#popup-closed), in case no button was clicked, we should receive empty object (`{}`), but not `null`.

### Expected Behavior
`popup_closed` event should contain `{}` payload in case, no button were clicked.

### Actual Behavior
`popup_closed` payload contains `null`.

### Steps to Reproduce
1. Open [Web Apps polygon bot](https://t.me/webapps_polygon_bot) ([source code](https://github.com/Telegram-Web-Apps/bridge-polygon))
2. Open developers tools (F12)
3. Call Web Apps method:
```typescript
bridge.postEvent('web_app_open_popup', {
    title: 'Title',
    message: 'Message',
    buttons: [{type: 'ok', id: 'ok'}]
})
```
4. Close popup by clicking outside or by clicking popup top right cross
5. See log in console:
```
[...] [Bridge] [processEvent] popup_closed null
```
It means, application received event `popup_closed` with payload presented as `null`.

### Environment
**Device:** `iPhone XR`

**iOS version**: `16.1.1`

**App version:** `9.3.2`

**Comment by laktyushin** [comment]
Fixed in 9.5
