### ISSUE TITLE
Second draft comment disappears while typing

### ISSUE THREAD

**Issue by vladislavromanov** [TelegramMessenger/Telegram-iOS#974]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
When I send a comment to a community post and then type a second comment afterwards, it gets erased at a random time.

### Expected Behavior
When I type a comment, it shouldn't disappear. 

### Actual Behavior
When I send a comment and type a new one, the text may disappear.

### Steps to Reproduce
1. Write a comment to the post in the channel
2. Start typing a second comment, loooong comment
3. After a while the text in the input field will disappear

### Screenshots and Videos 
https://user-images.githubusercontent.com/63917524/214852208-54aba48f-9b4b-465a-ae96-a764a4a7d071.MP4

### Environment
**Device:** `iPhone 12`

**iOS version**: `16.1.2`

**App version:** `9.3.2`

**Comment by ali-fareed** [comment]
Fixed in 9.4.
