### ISSUE TITLE
[Web Apps] `main_button_pressed` event is still being received when button is not active

### ISSUE THREAD

**Issue by heyqbnk** [TelegramMessenger/Telegram-iOS#977]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
You can find full issue information here:
https://github.com/Telegram-Web-Apps/twa/issues/3

### Environment
**Device:** `iPhone XR`

**iOS version**: `16.1.1`

**App version:** `9.3.2`

**Comment by laktyushin** [comment]
Fixed in 9.5
