### ISSUE TITLE
Where is the code related to the search box and the function of receiving pictures video?

### ISSUE THREAD

**Issue by skycloudly** [TelegramMessenger/Telegram-iOS#98]
Where is the code related to the search box and the function of receiving pictures video?I plan to recompile a telegram client without search box and picture video according to the source code.Please help me

**Comment by shivanraptor** [comment]
It's not difficult to trace the codes; please study the codes carefully.

**Comment by laktyushin** [comment]
Not an issue. Please study the code yourself, it's pretty straightforward.
