### ISSUE TITLE
Wishlist - Roadmap 2024 - deprecate SignalKit to use apple combine / min target ios 13

### ISSUE THREAD

**Issue by johndpope** [TelegramMessenger/Telegram-iOS#980]
I've been looking at the signal code for months and it no clearer to me. 
if we use apple's combine 
https://developer.apple.com/documentation/combine
would tidy up code base and streamline more esoteric operations making code more readable.

Thinking about starting a fork to throw out the signal stuff but would be good to get some buy in.

it maybe ok to continue with signal - but it needs more documentation. This codebase is only one I can find using it. 

@yankodimitrov - are you still alive? what do you think would be best path to migrate off signalkit?
https://github.com/yankodimitrov?tab=overview&from=2022-12-01&to=2022-12-31

<img width="372" alt="Screenshot 2023-01-28 at 8 43 42 am" src="https://user-images.githubusercontent.com/289994/215206250-0b489001-a56f-4ff2-ac33-dde54130791f.png">

as a stepping stone - it maybe possible to create similar interface around signalkit - then progressively phase out calls to use vanilla combine.

UPDATE

it seems like the objective-c stuff is only being used by legacy components.
<img width="231" alt="Screenshot 2023-01-28 at 8 50 51 am" src="https://user-images.githubusercontent.com/289994/215208627-6732e3cb-3e10-4b96-8dbd-23e18f116d1f.png">
<img width="228" alt="Screenshot 2023-01-28 at 8 50 46 am" src="https://user-images.githubusercontent.com/289994/215208632-9c2c7714-1125-4626-b7f1-f928fedf770d.png">
<img width="209" alt="Screenshot 2023-01-28 at 8 50 41 am" src="https://user-images.githubusercontent.com/289994/215208637-72c89da7-c5e6-44aa-956c-3214b6f6c5fd.png">
<img width="370" alt="Screenshot 2023-01-28 at 8 50 37 am" src="https://user-images.githubusercontent.com/289994/215208641-72fd9804-cafb-430b-b505-5b2b2fa6ed8c.png">
<img width="420" alt="Screenshot 2023-01-28 at 8 50 30 am" src="https://user-images.githubusercontent.com/289994/215208645-3f769255-4913-45fa-98d3-9f9d609dcdc1.png">
<img width="248" alt="Screenshot 2023-01-28 at 8 50 25 am" src="https://user-images.githubusercontent.com/289994/215208651-533eea64-636e-4d6d-a27d-9132d563ce68.png">
<img width="217" alt="Screenshot 2023-01-28 at 8 50 18 am" src="https://user-images.githubusercontent.com/289994/215208656-c69c725f-4ad9-4f87-98f0-472c643861de.png">
<img width="259" alt="Screenshot 2023-01-28 at 8 50 14 am" src="https://user-images.githubusercontent.com/289994/215208659-4a3e73e4-8ed2-43a1-8bc6-28dd016d25a9.png">
<img width="222" alt="Screenshot 2023-01-28 at 8 50 07 am" src="https://user-images.githubusercontent.com/289994/215208664-67fa873c-7fdc-4f69-8d9a-76add6894d21.png">
<img width="173" alt="Screenshot 2023-01-28 at 8 50 01 am" src="https://user-images.githubusercontent.com/289994/215208668-8150547f-739a-4d1e-95aa-25be8b56fbe3.png">
<img width="190" alt="Screenshot 2023-01-28 at 8 49 57 am" src="https://user-images.githubusercontent.com/289994/215208671-0a9e76e8-ec61-4d62-9289-8c7f30985cc8.png">
<img width="193" alt="Screenshot 2023-01-28 at 8 49 52 am" src="https://user-images.githubusercontent.com/289994/215208674-d76d561a-ab62-4d1d-b048-96d3d0c8fc13.png">
<img width="244" alt="Screenshot 2023-01-28 at 8 49 47 am" src="https://user-images.githubusercontent.com/289994/215208679-9c4e58ab-9943-411b-947b-d83795873fb0.png">
<img width="157" alt="Screenshot 2023-01-28 at 8 49 42 am" src="https://user-images.githubusercontent.com/289994/215208682-056e64ac-a233-4e70-9cbf-7b64e6dd3af7.png">

<img width="295" alt="Screenshot 2023-01-28 at 8 51 35 am" src="https://user-images.githubusercontent.com/289994/215208596-ba491278-3b31-4e7c-96c5-75a2bcc4d7f5.png">
<img width="311" alt="Screenshot 2023-01-28 at 8 51 20 am" src="https://user-images.githubusercontent.com/289994/215208607-75684ac4-2a7f-4a56-969e-1e0ba69bd40c.png">
<img width="243" alt="Screenshot 2023-01-28 at 8 51 15 am" src="https://user-images.githubusercontent.com/289994/215208612-96e26f5d-9fea-4c81-b574-5a2dc5456834.png">
<img width="295" alt="Screenshot 2023-01-28 at 8 51 07 am" src="https://user-images.githubusercontent.com/289994/215208617-950b2058-8f33-40df-9e45-d53a60f884b0.png">
<img width="228" alt="Screenshot 2023-01-28 at 8 50 56 am" src="https://user-images.githubusercontent.com/289994/215208622-d536aba5-d62f-48cc-8785-134e0e61b809.png">

<img width="377" alt="Screenshot 2023-01-28 at 8 46 51 am" src="https://user-images.githubusercontent.com/289994/215206776-ef14574c-c9d7-41c0-9cc0-38d332299aad.png">
<img width="226" alt="Screenshot 2023-01-28 at 8 51 31 am" src="https://user-images.githubusercontent.com/289994/215208600-bc040fad-0205-4921-83ef-822b5821db04.png">
<img width="143" alt="Screenshot 2023-01-28 at 8 51 26 am" src="https://user-images.githubusercontent.com/289994/215208603-fafb1736-29a9-4f1f-b6c5-6a64658970a0.png">

<img width="148" alt="Screenshot 2023-01-28 at 8 51 59 am" src="https://user-images.githubusercontent.com/289994/215208568-aaef7433-76b4-40de-abed-3f464773e493.png">
<img width="291" alt="Screenshot 2023-01-28 at 8 51 53 am" src="https://user-images.githubusercontent.com/289994/215208578-0e42e38d-64f7-497a-804a-19599d025a0a.png">
<img width="227" alt="Screenshot 2023-01-28 at 8 51 48 am" src="https://user-images.githubusercontent.com/289994/215208584-efcf6ad4-93c0-4b29-9651-4139fc2150a6.png">
<img width="252" alt="Screenshot 2023-01-28 at 8 51 41 am" src="https://user-images.githubusercontent.com/289994/215208591-4b595798-82b5-4464-97fb-9448b01a83d9.png">

**Comment by ali-fareed** [comment]
`Signal.swift`: 85 lines, the core of the Rx-like value stream processing
`Disposable.swift`: 233 lines, cancellation handling with various semantics
`Subscriber.swift`: 145 lines, thread-safe value stream management

It would be very difficult to do software engineering without having the capacity to comprehend 463 lines of code spread over 3 files.
