### ISSUE TITLE
Voice messages bits per sample could be optimized

### ISSUE THREAD

**Issue by the-spyke** [TelegramMessenger/Telegram-iOS#981]
I've sent a voice message from the iOS client and after looking into media info it turned out to be a 32-bit 48kHz audio. For comparison a CD is 16-bit 44.4kHz. 32-bit is used by recording studios for mastering.

So, by reducing bitrate to 16 bits you could halve voice messages size and their costs for you servers and network traffic without actual quality loss. In reality voice don't need even 16 bits of dynamic range (you physically can't shout that loud) and full 24kHz of frequency band too.

![image](https://user-images.githubusercontent.com/3014095/215267668-b4ba5b11-be15-4c45-a2c8-fa2662b2eb59.png)

**Comment by ali-fareed** [comment]
Telegram encodes voice messages at 30 kbit/s. Is there an issue with this setup?

**Comment by the-spyke** [comment]
@ali-fareed Bitrate itself doesn't tell the whole story. The results will be totally different if we try to compress into 30kbps a dynamic range of 32 bits or 8 bits. An analogy is compressing images of different resolutions into the same file size. If high-resolution looks fine, then such file size is an overkill for a smaller resolution image. 32-bit is an overkill for voice and could be huge infra cost savings. Zoom is also using 32kHz sampling rate, but this is debatable.

**Comment by ali-fareed** [comment]
Are you sure but depth has any relevance in Opus?

**Comment by ali-fareed** [comment]
Let's close this for now
