### ISSUE TITLE
I can't run generated Xcode project on simulator

### ISSUE THREAD

**Issue by mhmdshz** [TelegramMessenger/Telegram-iOS#986]
```
objc_library(
    name = "Main",
    srcs = [
        "Telegram-iOS/main.m"
    ],
)

```
Above bazel build config returns below error:
"Compiling Telegram/Telegram-iOS/main.m failed: (Aborted): wrapped_clang failed: error executing command"

mac OS: 10.15.7
Xcode: 12.4
Telegram: 9.3
bazel: 5.3.1

**Comment by ali-fareed** [comment]
Does it say anything else?

**Comment by johndpope** [comment]
make sure you init submodules

**Comment by mhmdshz** [comment]
Thanks Ali you could see build Errors, I guess second from clang :
![E1](https://user-images.githubusercontent.com/80888773/216531769-a4a95eac-9977-489b-9263-aa20bd1f31ec.JPG)

**Comment by mhmdshz** [comment]
John @johndpope  , How Could I check "init submodules"?

**Comment by johndpope** [comment]
Double check you followed the steps in readme 

here’s updated with latest json config
https://github.com/TelegramMessenger/Telegram-iOS/pull/955

When you git  clone  there’s some extra info you need to pass it’s in the readme.
It looks like you just created a bazel file ?
You need to run python3 to spit out Xcode project.

**Comment by ali-fareed** [comment]
The current source code is limited to Xcode 14.1.

**Comment by tboxSol** [comment]
@mhmdshz  did you manage to fix this? I'm getting the same problem
