### ISSUE TITLE
Observation on TelegramUIFramework size 425MB 

### ISSUE THREAD

**Issue by johndpope** [TelegramMessenger/Telegram-iOS#987]
<img width="1147" alt="Screenshot 2023-02-03 at 2 23 57 pm" src="https://user-images.githubusercontent.com/289994/216505212-28484676-52c8-4107-b69f-5445b1618a86.png">
<img width="774" alt="Screenshot 2023-02-03 at 2 23 48 pm" src="https://user-images.githubusercontent.com/289994/216505228-11de07b9-108f-4794-862e-d19e01094fd5.png">

Is there a way we could reduce this? 
Is there a way we can get clarity on what's bloating this? Is it images? or?

**Comment by ali-fareed** [comment]
It is code and debug symbols.
