### ISSUE TITLE
App crashing while opening

### ISSUE THREAD

**Issue by SH2282000** [TelegramMessenger/Telegram-iOS#989]
### Checklist
- [X] I am reporting an issue in existing functionality that does not work as intended
- [X] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
Describe the issue that you are experiencing
On the latest version of the app on an iPhone XS, the app is crashing while opening.

### Expected Behavior
Tell us what should happen
The app should open.

### Actual Behavior
Tell us what happens instead
The app crash

### Steps to Reproduce
1. Get an iPhone XS
2. OPEN THE APP
3. THATS IT

### Screenshots and Videos 
Remove, if not applicable
https://user-images.githubusercontent.com/16389789/216844608-21bb555f-4f5a-4ea1-98d7-2bb1cf5c28a0.MOV

### Environment
**Device:** `iPhone XS` "almost full"

**iOS version**: `15.6.1`

**App version:** `Latest`

**Comment by staypov** [comment]
> 
> 
> ### Checklist
> - [X] I am reporting an issue in existing functionality that does not work as intended
> - [X] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)
> 
> ### Description
> Describe the issue that you are experiencing
> On the latest version of the app on an iPhone XS, the app is crashing while opening.
> 
> ### Expected Behavior
> Tell us what should happen
> The app should open.
> 
> ### Actual Behavior
> Tell us what happens instead
> The app crash
> 
> ### Steps to Reproduce
> 1. Get an iPhone XS
> 2. OPEN THE APP
> 3. THATS IT
> 
> ### Screenshots and Videos 
> Remove, if not applicable
> https://user-images.githubusercontent.com/16389789/216844608-21bb555f-4f5a-4ea1-98d7-2bb1cf5c28a0.MOV
> 
> ### Environment
> **Device:** `iPhone XS` "almost full"
> 
> **iOS version**: `15.6.1`
> 
> **App version:** `Latest`
