### ISSUE TITLE
disconnect mine own server

### ISSUE THREAD

**Issue by ldu1101** [TelegramMessenger/Telegram-iOS#990]
### Description

<img width="1111" alt="image" src="https://user-images.githubusercontent.com/12520900/216900928-3d8bbd49-d291-41fa-90ef-2e92de660729.png">

I modified my server address according to this document, but after running, I was prompted that the server could not be linked

### Actual Behavior

I modify my server address

<img width="1131" alt="image" src="https://user-images.githubusercontent.com/12520900/216901808-7efc335a-7c5c-4e09-8fa0-661b0421dab5.png">

this is error log

[MT] 2023-2-6 14:19:48.039 [MTTcpConnection#7faa4fb05da0 connecting to 35.78.243.112:10443]
[MT] 2023-2-6 14:19:48.039 [MTProto#0x600000e455f0@0x60000094ee00 preparing reqPq nonce:{length = 16, bytes = 0xbef2160236cb4d4bea0040a0a7cb992c} (7196923745658544128/0)]
[MT] 2023-2-6 14:19:48.041 [MTProto#0x600000e455f0@0x60000094ee00 transport #0x600001140720 connection state: connecting]
[MT] 2023-2-6 14:19:48.096 Connection time: 55.426002 ms, interface: Wifi
[MT] 2023-2-6 14:19:48.097 [MTProto#0x600000e455f0@0x60000094ee00 transport #0x600001140720 connection state: connected]
[MT] 2023-2-6 14:19:48.097 [MTDatacenterAuthMessageService#0x60000070fa80 mtProto#0x600000e455f0 (media: false) mtProtoMessageTransaction scheme:tcp://35.78.243.112:10443 (media: no, cdn: no, static: no, secret: (null)) (media: no)]
2023-02-06 14:19:48.137814+0800 Telegram[71425:2534664] [Snapshotting] Snapshotting a view (0x7faa4fa19e60, _ASDisplayView) that has not been rendered at least once requires afterScreenUpdates:YES.
[MT] 2023-2-6 14:19:48.147 [MTProto#0x600000e455f0@0x60000094ee00 [84] received res_pq nonce:{length = 16, bytes = 0xbef2160236cb4d4bea0040a0a7cb992c} serverNonce:{length = 16, bytes = 0x0c458fd2b4391bf805acbc89de62223e} pq:{length = 8, bytes = 0x17ed48941a08f981} fingerprints:a9e071c1771060cd (7196923745752396837, 0/0)]
[MT] 2023-2-6 14:19:48.147 [MTDatacenterAuthMessageService#0x60000070fa80 couldn't find valid server public key]
[MT] 2023-2-6 14:19:48.148 [MTDatacenterAuthMessageService#0x60000070fa80 mtProto#0x600000e455f0 (media: false) mtProtoMessageTransaction scheme:tcp://35.78.243.112:10443 (media: no, cdn: no, static: no, secret: (null)) (media: no)]
[MT] 2023-2-6 14:19:48.148 [MTTcpConnection#7faa4fb05da0 disconnected from 35.78.243.112]
[MT] 2023-2-6 14:19:48.148 [MTProto#0x600000e455f0@0x60000094ee00 preparing reqPq nonce:{length = 16, bytes = 0x36f3cd8cd6e80584ba3f736a5f4778ea} (7196923746169477120/0)]
[MT] 2023-2-6 14:19:48.148 [MTContext has chosen a scheme for DC1: tcp://35.78.243.112:10443 (media: no, cdn: no, static: no, secret: (null)) (media: no)]

What should I do to connect to my server？

### Environment
**Device:** `iPhone Simulator`

**Xcode version**: `14.2`

**App version:** `9.3`

**Comment by ali-fareed** [comment]
You need to provide your own server public key (see `defaultPublicKeys` in `MTDatacenterAuthMessageService.m`).
