### ISSUE TITLE
I Can't generate Xcode project

### ISSUE THREAD

**Issue by mhmdshz** [TelegramMessenger/Telegram-iOS#992]
I did all steps like read me but when run this command:

```
sudo python3 build-system/Make/Make.py \
    --cacheDir="$HOME/telegram-bazel-cache" \
    generateProject \
    --configurationPath="$HOME/telegram-configuration/configuration.json"\
    --disableExtensions \
    --disableProvisioningProfiles\
     --noCodesigning ""
```
Seems it's infinite loop 

![infinate_loop](https://user-images.githubusercontent.com/80888773/217060229-589856b7-3cdc-4c19-a586-5a6749867a1b.JPG)

I think above problem is common and it's in another closed issue but when I try solutions nothing changed(common solution base other issues):
```
python3 build-system/Make/Make.py --bazel="$HOME/bazel-dist/bazel"  clean
upgrade Tulsi version and replace --> cd /build-system---> replace Tulsi
update 'version.json'
```

**Environment**
**App version: ** 9.4

**Bazel version: ** 5.3.1

**xCode version: ** 14.1

**MacOS version: ** 13.2

**Comment by ldu1101** [comment]
you can try reset computer, it works for me

**Comment by ali-fareed** [comment]
Usually this means Bazel server has stuck. Rebooting the device usually helps.
