### ISSUE TITLE
Custom keyboard is not shown if the regular keyboard is open

### ISSUE THREAD

**Issue by lokorel** [TelegramMessenger/Telegram-iOS#993]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
When bot send message with custom keyboard (ReplyKeyboardMarkup), this is not shown if the regular keyboard is open.
if the regular keyboard is hide, the custom keyboard will be shown

### Expected Behavior
The custom keyboard should always replace the regular

### Actual Behavior
if the regular keyboard is open, when bot send message with custom keyboard, the regular keyboard goes into a hidden state, but custom keyboard (ReplyKeyboardMarkup) is not shown

### Steps to Reproduce
1. open chat with bot and open regular keyboard
2. send request 
POST https://api.telegram.org/bot{TOKEN}/sendMessage

{"chat_id":{chat_id},"text":"hello friend","reply_markup":{"keyboard":[["A button"],["B button"]],"one_time_keyboard":false,"resize_keyboard":true}}

### Environment
**Device:** `iPhone XR`

**iOS version**: `14.5`

**App version:** `9.4.1`

**Comment by laktyushin** [comment]
Fixed in 9.4.3
