### ISSUE TITLE
Unable to install on simulator(The application's Info.plist does not contain a valid CFBundleVersion.)

### ISSUE THREAD

**Issue by mhmdshz** [TelegramMessenger/Telegram-iOS#994]
All steps done same Read.me but I have below error:
**"The application's Info.plist does not contain a valid CFBundleVersion."**
Identity info:

![i_install](https://user-images.githubusercontent.com/80888773/217844803-0e2c9428-6032-417b-8247-c98d563b2a5b.JPG)

**Comment by ali-fareed** [comment]
Have you performed any modifications to the project files?
