### ISSUE TITLE
Quick React in Secret Chat - works in Android, not in iOS

### ISSUE THREAD

**Issue by anontelegram** [TelegramMessenger/Telegram-iOS#997]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
quick react emojis do not work in telegram for iOS in secret chat. they work in regular chat.

### Expected Behavior
should recieve quick react emoji response from other telegram user in secret chat
should be able to sent quick react emojis

### Actual Behavior
opens up reply menu

### Steps to Reproduce
1. android user sends quick react message in secret chat. ios user does not see react emoji
2. attempt to double tap and no quick react emoji menu appears 

### Environment
**Device:** `iPhone 12 pro max`

**iOS version**: `16.3`

**App version:** `9.4.1`

**Comment by ali-fareed** [comment]
Secret chats don't support reactions at the moment.

**Comment by anontelegram** [comment]
> Secret chats don't support reactions at the moment.

Why are android users able to use this? I only ask because my friend attempts to do so to my messages which results in me missing notifications but they assume that I am seeing their replies

**Comment by ali-fareed** [comment]
It must be a bug in the android app. The current secret chat protocol does not include reactions.
